text = {
	["pistol"] = "Pistool",
	["smg"] = "SMG",
	["rifle"] = "Geweer",
	["heavy"] = "Zwaar",
	["grenade"] = "Granaat",
	["sniperrifle"] = "Scherpschuttersgeweer",
	["shotgun"] = "Shotgun",
	["ak47"] = { name = "AK-47", desc = "Krachtig en betrouwbaar: de AK-47 is één van de meest betrouwbare aanvalsgeweren in de wereld. Het is het meest dodelijk in korte, gecontroleerde schoten." },
	["aug"] = { name = "AUG", desc = "Krachtig en precies: de AUG met zijn vizier compenseert zijn lange herlaadtijden met een kleine spreiding en een hoge vuursnelheid." },
	["awp"] = { name = "AWP", desc = "Hoog risico met hoge beloningen: de beruchte AWP is te herkennen aan zijn kenmerkend één-schot-één-dode-beleid." },
	["deserteagle"] = { name = "Desert Eagle", desc = "Zo duur als dat het sterk is: de Desert Eagle is een iconisch pistool dat moeilijk te meesteren is, maar verrassend scherp schiet op lange afstanden." },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Dubbele Beretta's", desc = "Twee Beretta's met grote magazijnen tegelijk leegschieten doet je mikken geen goed en verhoogt herlaadtijden. Maar, aan de andere kant, je schiet met twee Beretta's met grote magazijnen tegelijk." },
	["elite"] = "Dual Berettas",
	["famas"] = { name = "FAMAS", desc = "Een goedkope optie voor de spelers zonder geld: de FAMAS vult de leegte tussen de duurdere geweren en de minder effectieve submachinegeweren." },
	["fiveseven"] = { name = "Five-SeveN", desc = "Zeer accuraat en pantser-doordringend: de Five-Seven is een langzame herlader die dat goed maakt met een gul 20-kogelsmagazijn en een kleine terugslag." },
	["flashbang"] = { name = "Flashbang", desc = "De niet-dodelijke flashbang-granaat verblindt tijdelijk iedereen die in zijn buurt staat. Dit maakt het perfect voor gesloten ruimtes. Zijn luide explosie maskeert ook tijdelijk het geluid van voetstappen." },
	["g3sg1"] = { name = "G3SG1", desc = "De dure G3SG1 maakt je aanzienlijk langzamer, maar compenseert dit met zijn hoge vuursnelheid ten opzichte van andere scherpschuttersgeweren." },
	["galilar"] = { name = "Galil AR", desc = "Een minder dure optie onder de terroristen-exclusieve geweren: de Galil AR is een uitstekend wapen in gemiddeld tot lange afstandsgevechten." },
	["glock18"] = { name = "Glock-18", desc = "De Glock 18 is een prima eerste-rondepistool die het best werkt tegen ongepantserde tegenstanders en heeft de mogelijkheid om drie kogels per keer af te schieten." },
	["he_grenade"] = { name = "HE-granaat", desc = "De zeer explosieve handgranaat deelt veel schade uit in gesloten, grote ruimtes. Dit maakt het perfect om tegenstanders in kamers op te ruimen." },
	["knife"] = { name = "Mes", desc = "Stil en altijd beschikbaar: je mes heeft een snelle, zwakke primaire aanval en een langzame, sterke secundaire aanval. Een aanval in de rug geeft de stille spelers een directe kill." },
	["knife_t"] = { name = "Mes", desc = "Stil en altijd beschikbaar: je mes heeft een snelle, zwakke primaire aanval en een langzame, sterke secundaire aanval. Een aanval in de rug geeft de stille spelers een directe kill." },
	["knife_gg"] = "Gouden mes",
	["m249"] = { name = "M249", desc = "Een sterke LMG voor open ruimtes: de M249 is de perfecte keuze voor spelers die een lage vuursnelheid willen inruilen voor verhoogde precisie en grote magazijnen." },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "Met een kleiner magazijn dan zijn luidere tegenhanger biedt de M4A1 met zijn demper stillere schoten met minder terugslag en hogere precisie." },
	["mac10"] = { name = "MAC-10", desc = "Eigenlijk een doos waar kogels uitkomen: de MAC-10 biedt een hoge vuursnelheid, maar is niet accuraat na een aantal schoten en heeft een grote terugslag." },
	["p90"] = { name = "P90", desc = "Snel te herkennen door zijn unieke ontwerp: de P90 is een geweldig wapen om te gebruiken tijdens het lopen dankzij zijn grote magazijn en lage terugslag." },
	["smoke_grenade"] = { name = "Rookbom", desc = "De rookgranaat creëert een middelgroot rookgordijn. Dit kan jouw team effectief verbergen voor snipers, of als handige afleiding dienen." },
	["ump45"] = { name = "UMP-45", desc = "Het verkeerd begrepen kind van de machinegeweer-familie: het kleine magazijn van de UMP45 is het enige nadeel van de anderzijds op veel manieren inzetbare korte-afstandsgeweer." },
	["xm1014"] = { name = "XM1014", desc = "De XM1014 is een zeer krachtige volautomatische shotgun die zijn forse prijs compenseert met zijn vermogen om in zeer korte tijd een kamer te vullen met lood." },
	["c4"] = { name = "C4-explosief", desc = "Stabiel en kan tegen de meeste fysieke stoten: dit geïmproviseerde plastic explosief heeft een explosiesnelheid van meer dan 8.000 meter per seconde." },
	["bizon"] = { name = "PP-Bizon", desc = "De Bizon doet weinig schade, maar biedt een uniek groot magazijn dat snel herlaadt." },
	["mag7"] = { name = "MAG-7", desc = "De CT-exclusieve Mag-7 levert een vernietigend aantal schade op korte afstand. Zijn herlaadtijd maakt het een geweldige tactische keuze." },
	["negev"] = { name = "Negev", desc = "De Negev is een beest dat de vijand op afstand kan houden met zijn nauwkeurige schoten, mits je genoeg tijd hebt om er de controle over te krijgen." },
	["sawedoff"] = { name = "Sawed-Off", desc = "De klassieke Sawed-Off is enorm krachtig in korteafstandsgevechten, maar met zijn lage precisie, hoge spreiding en lage vuursnelheid kun je er beter zeker van zijn dat waar je op schiet, dood is." },
	["tec9"] = { name = "Tec-9", desc = "Een ideaal pistool voor de terrorist die onderweg is. De Tec-9 is dodelijk in kleine ruimtes en heeft een magazijn met hoge capaciteit." },
	["taser"] = { name = "Zeus x27", desc = "Perfect voor korte-afstandshinderlagen en gesloten omgevingen: de x27 Zeus kan met één schot de vijand permanent neerhalen." },
	["molotov"] = { name = "Molotov", desc = "De Molotov is een krachtig en onvoorspelbaar middel om gebieden af te sluiten als deze op de grond terecht komt, dankzij zijn vuurzee die elke speler in zijn bereik schade toedoet." },
	["incgrenade"] = "Brandbom",
	["decoy"] = "Afleidingsgranaat",
	["hkp2000"] = { name = "P2000", desc = "Accuraat en te beheersen, de van Duitse oorsprong P2000 is een pistool uit de eerste ronde die het best werkt tegen tegenstanders zonder pantser." },
	["mp7"] = { name = "MP7", desc = "Op veel manieren inzetbaar, maar duur: de van Duitse makelaardij MP7 is de perfecte keuze voor korte-afstandsgevechten dankzij zijn hoge schade." },
	["mp5sd"] = { name = "MP5-SD", desc = "De iconische MP5, die vaak is nagemaakt maar nog nooit is geëvenaard, is misschien wel het meest veelzijdige en populaire machinepistool ter wereld. Dit is de SD-variant, inclusief geïntegreerde demper waardoor het al geweldige wapen nu ook nog eens muisstil is." },
	["mp9"] = { name = "MP9", desc = "Gemaakt in Zwitserland: de revolutionaire MP9 is een ergonomisch polymeren wapen veel gekozen door privé beveiligingsfirma's." },
	["nova"] = { name = "Nova", desc = "Het prijskaartje van de Nova is zo laag - het maakt het het perfecte wapen voor hinderlagen voor een team dat niet veel geld heeft." },
	["p250"] = { name = "P250", desc = "Een kleine terugslag met een hoge vuursnelheid: de P250 is een relatief goedkope keuze tegen gepantserde tegenstanders." },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "De SCAR-20 is een semi-automatisch scherpschuttersgeweer dat zijn hoge vuursnelheid en krachtige langeafstandsschade inruilt voor een langzame bewegingssnelheid en hoog prijskaartje." },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "Het SSG08-scherpschuttersgeweer, met zijn één schot per keer, doet weinig schade maar is zeer effectief voor zijn prijs, wat het een slimme keus maakt om vroeg in het spel te gebruiken." },
	["heavyassaultsuit"] = "Zwaar pantser",
	["assaultsuit"] = "Kevlar + helm",
	["kevlar"] = "Kevlar-vest",
	["defuser"] = "Demontagekit",
	["cutters"] = "Reddingskit",
	["revolver"] = { name = "R8-revolver", desc = "De R8-revolver levert een zeer nauwkeurig en krachtig schot dat ten koste gaat van een tragere trekker. Snel vuren door de hamer te gebruiken is waarschijnlijk de beste optie wanneer er van dichtbij geschoten moet worden." },
	["usp_silencer"] = { name = "USP-S", desc = "Een favoriet van spelers in Counter-Strike: Source: het USP-pistool met zijn te verwijderen demper schiet met minder terugslag en onderdrukt geluid dat ongewilde aandacht trekt." },
	["knifebayonet"] = { name = "Bajonet", desc = "Met een bijna onveranderd design sinds de Tweede Wereldoorlog is de bajonet nog steeds aanwezig in moderne, militaire strategieën. Bajonetaanvallen zijn nog steeds effectief zoals bewezen in de Tweede Golfoorlog en de oorlog in Afghanistan." },
	["knifeflip"] = { name = "Knipmes", desc = "Knipmessen hebben een kromgetrokken lemmet in Perzische stijl, met een scherpe punt. Hoewel de punt zelf fragiel is, is het mes in het algemeen verrassend duurzaam." },
	["knifegut"] = { name = "Ingewandenmes", desc = "Het meest kenmerkende van het ingewandenmes is de haak voor de ingewanden op de rug van het lemmet. Populair gemaakt als een hulpstuk voor het villen van beesten is deze ook effectief voor het snijden door vezelachtige dingen, zoals touw, riemen en gordels." },
	["knifecss"] = { name = "Klassiek mes", desc = "A classic of the Counter-Strike series, the edge of this knife is press-fit Stellite perfectly held in place due to its precise fit with the titanium on the blade's cheek and spine. The handle is fossilized mastodon ivory held in a carbon fibre pocket." },
	["knifem9"] = { name = "M9 Bajonet", desc = "Dit is de M-9 bajonet. Deze is eigenlijk bedoeld om op een geweer te plaatsen, maar kan ook prima gebruikt worden in korteafstandsgevechten." },
	["knifekaram"] = { name = "Karambit", desc = "Met zijn krom getrokken lemmet dat lijkt op een klauw van een tijger is de karambit ontwikkeld als onderdeel van de Zuidoost-Aziatische gevechtsdiscipline van de Silat. Dit type mes wordt normaal gebruikt met een omgekeerde greep, met de ringvinger op de wijsvinger." },
	["knifetactical"] = { name = "Jagersmes", desc = "Een mes ontworpen voor modern tactisch gebruik. Het blad is zeer geschikt voor een scala aan zowel gevecht- als utilitaire behoeften. De unieke tanto-punt zorgt voor maximale penetratie door zelfs de meeste extreme oppervlakken." },
	["knife_butterfly"] = { name = "Vlindermes", desc = "Dit is een op maat ontworpen vlindermes. Kenmerkend aan dit wapen is het vrijdraaiende blad dat razendsnel uitgeklapt kan worden, maar ingeklapt ook goed verborgen kan blijven. Hierdoor zijn vlindermessen in veel landen verboden." },
	["partypopper"] = "Partyknaller!",
	["knife_falchion_advanced"] = { name = "Falchion-mes", desc = "Als een modern eerbetoon aan het Fautsoenzwaard heeft dit clip-point-mes een gebogen lemmet." },
	["knife_push"] = { name = "Schaduwdolken", desc = "De stootdolk is ontworpen voor efficiënte brutaliteit, en het gebruik is net zo eenvoudig als het uitdelen van een paar klappen." },
	["knife_survival_bowie"] = { name = "Bowiemes", desc = "Dit Bowiemes met een getand lemmet werd gemaakt voor zwaar gebruik in wrede overlevingssituaties." },
	["healthshot"] = "Medische spuit",
	["tagrenade"] = "Tactische bewustzijnsgranaat",
	["exploding_barrel"] = "Exploderend vat",
	["snowball"] = "Sneeuwbal",
	["stompdamagekillstring"] = "heeft je schedel verpletterd",
	["dangerzone"] = "Danger Zone",
	["autosentry"] = "Automatische sentry",
	["fists"] = "Blote vuisten",
	["tablet"] = "Tablet",
	["breachcharge"] = "Doorbraakexplosief",
	["bumpmine"] = "Springmijn",
	["axe"] = { name = "Bijl", desc = "Heavy and always available, the axe has a sharp side and a dull side. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. How much wood would a woodchuck chuck?" },
	["hammer"] = { name = "Hamer", desc = "The hammer is available for fixing things and breaking things. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. If all you have is a hammer, everything looks like a nail." },
	["spanner"] = { name = "Moersleutel", desc = "A wrench is typically used to apply torque when turning objects, but you can hit anything with it for low-damage primary attack or throw it for a high-damage secondary attack. Bringing a wrench to a firefight is a recipe for screwing up." },
	["tripwirefire"] = "Vuurval",
	["knife_cord"] = { name = "Paracordmes", desc = "This fixed-blade survival knife is designed to withstand being used as both a weapon and a tool, such as for setting traps, hunting animals or cutting foliage. The handle is wrapped in a length of multi-purpose paracord." },
	["knife_canis"] = { name = "Overlevingsmes", desc = "This multi-purpose tactical knife features a serrated edge for ripping through coarse material like bone or fiber, plus a sharp gutting hook. The composite material handle is bolted to the blade with hex nuts." },
	["knife_ursus"] = { name = "Ursus-mes", desc = "Dit mes in tantō-stijl heeft een geslepen blad waar het handvat op gemonteerd is, inclusief tegengewicht. Geen gedoe, geen bewegende onderdelen - gewoon een betrouwbaar mes dat klaar is om gebruikt te worden." },
	["knife_gypsy_jackknife"] = { name = "Navaja", desc = "Dit mes met gemarmerd handvat verbergt een klein, maar wreed taps toelopend mes." },
	["knife_outdoor"] = { name = "Nomadenmes", desc = "This ergonomic tactical hunting lock-blade knife features composite handle inserts and a broad, sturdy blade, useful for cutting and prying apart material." },
	["knife_widowmaker"] = { name = "Talon-mes", desc = "Deze met ivoor bewerkte karambit is gekenmerkt door messing klinknagels en zaagtandranden, waardoor hij op de heenweg zal snijden en scheuren op de terugweg." },
	["knife_stiletto"] = { name = "Stiletto", desc = "Historically a focal point of contention and even regulation, this Italian-style stiletto switchblade knife features a spring-loaded blade that can be deployed almost instantly with the push of a release catch." },
	["knife_skeleton"] = { name = "Skelettenmes", desc = "This skeletonized-tang knife has been taped at the handle for improved grip. The hole allows a finger to be threaded through for stability and safety." },
	["firebomb"] = { name = "Brandbom", desc = "De brandbom is een krachtig en experimenteel wapen dat als het op de grond gegooid wordt een chemische reactie loslaat op hoge temperatuur en iedereen verbrandt die in zijn wijde pad staat." },
	["diversion"] = { name = "Afleidingsapparaat", desc = "When thrown, the diversion device will highlight sectors on tablets, creating the illusion of additional enemies." },
	["frag_grenade"] = { name = "Fragmentatiegranaat", desc = "The experimental fragmentation grenade can output extreme amounts of highly explosive damage in a wider area, making it ideal for both attacking and defensive strategies." },
	["shield"] = "Oproerschild",
	["zone_repulsor"] = { name = "Afweerapparaat", desc = "Prototype Radial Emission Particulate Shielding Device" },
	["cz75a"] = "Een volledig automatische variant van de CZ75, de CZ75-Auto is de ideale keuze om de rollen om te draaien en je tegenstanders wapen te verkrijgen. Maar met zeer weinig munitie wordt een sterke discipline vereist.",
	["m4a4"] = "Meer precies maar die minder schade doet dan de AK-47: de M4A4 is een volautomatisch geweer dat door vele CT's gekozen wordt.",
	["sg553"] = "De exclusief voor terroristen beschikbare SG553 is een prima alternatief voor de AK-47 met zijn vizier voor langeafstandsgevechten.",
	["decoy_grenade"] = "De afleidingsgranaat doet het geluid na van het meest krachtige wapen dat je bij je draagt - zo lijkt het alsof je genoeg rugdekking hebt.",
	["incindiary_grenade"] = "Als de brandbom gegooid wordt laat deze een chemische reactie los op hoge temperatuur die iedereen verbrandt die in zijn wijde pad staat.",
	["knife_ghost"] = { name = "Spectral Shiv", desc = "Spoken houden van spookmessen. Je moet oppassen wanneer ze er eentje te pakken krijgen! Ze steken je neer wanneer ze daar de kans voor krijgen. Het is alleen jammer dat ze een spook zijn en dat spookmessen mensen geen pijn kunnen doen..." },
	["survival_healthshot"] = "Herstelt een deel van je gezondheid en geeft je een korte snelheidsboost.",
	["survival_shield"] = "Een ballistisch oproerschild dat een groot deel schade kan blokkeren voordat het het begeeft.",
	["survival_parachute"] = "Kan worden ingezet bij het vallen om valschade te voorkomen.",
	["survival_c4"] = "Plaats het ergens op de map om een grote explosie te veroorzaken. Kan worden gebruikt om kluizen te openen.",
	["survival_exploremoney"] = "Geeft je extra geld voor elke sector die je verkent.",
	["sniper"] = "Sniper",
	["survival_taser"] = "Extremely short range weapon capable of killing in one shot. Can also be used to open weapon crates.",
	["survival_vesthelm"] = "Provides resistance to damage.",
	["survival_exojump"] = "Significantly increases jump height.",
	["survival_dronepilot"] = "Grants the ability to take control of drones. Use the tablet to select a drone to take over.",
	["survival_wavemoney"] = "Grants extra money for each danger zone expansion wave survived.",
}
