text = {
	["pistol"] = "Pistola",
	["smg"] = "Submetralhadora",
	["rifle"] = "Espingarda",
	["heavy"] = "Arma Pesada",
	["grenade"] = "Granada",
	["sniperrifle"] = "Espingarda Sniper",
	["sniper"] = "Sniper",
	["shotgun"] = "Caçadeira",
	["ak47"] = { name = "AK-47", desc = "Potente e fiável, a AK-47 é uma das espingardas de assalto mais populares do mundo. É mais mortífera ao disparar rajadas curtas e controladas de balas." },
	["aug"] = { name = "AUG", desc = "Potente e precisa, a AUG é uma espingarda de assalto com uma mira telescópica que, apesar de ter um tempo de carregamento longo, tem um ritmo elevado de disparo." },
	["awp"] = { name = "AWP", desc = "A célebre AWP é arriscada de se usar mas extremamente mortífera, sendo conhecida por causar uma morte instantânea com cada tiro certeiro." },
	["deserteagle"] = { name = "Desert Eagle", desc = "Tão cara como potente, a Desert Eagle é uma pistola icónica que, apesar de ser difícil de dominar, é surpreendentemente precisa a longas distâncias." },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Dual Berettas", desc = "Disparar duas Berettas ao mesmo tempo significa uma baixa precisão e um tempo de carregamento maior. Mas vendo por um lado positivo, estás a dar tiros com duas pistolas de uma só vez." },
	["elite"] = "Dual Berettas",
	["famas"] = { name = "FAMAS", desc = "Uma opção barata quando há pouco dinheiro, a FAMAS preenche eficazmente aquele vazio entre as espingardas mais caras e as submetralhadoras menos eficientes." },
	["fiveseven"] = { name = "Five-SeveN", desc = "Muito precisa e útil contra oponentes com colete e capacete, a Five-Seven é cara e lenta a carregar, mas possui 20 balas no carregador e baixo recuo." },
	["flashbang"] = { name = "Flashbang", desc = "A granada Flashbang não é letal mas cega temporariamente qualquer pessoa perto da sua explosão, tornando-a perfeita para \"limpar\" espaços fechados. A sua explosão ensurdecedora também omite temporariamente o som de passos." },
	["g3sg1"] = { name = "G3SG1", desc = "A G3SG1 é das armas mais caras do jogo e reduz consideravelmente a mobilidade do seu portador, mas tem um ritmo de disparo elevado comparado com as outras espingardas sniper." },
	["galilar"] = { name = "Galil AR", desc = "Tratando-se da opção mais económica entre as espingardas de assalto exclusivas da equipa Terrorista, a Galil AR é uma arma eficaz a médias e longas distâncias." },
	["glock18"] = { name = "Glock-18", desc = "A Glock 18 é uma das pistolas disponíveis na primeira ronda e é eficaz contra oponentes sem colete nem capacete, sendo capaz de disparar rajadas de três balas." },
	["he_grenade"] = { name = "Granada HE", desc = "A granada de fragmentação altamente explosiva causa imenso dano numa determinada área, o que a torna ideal para eliminar eficazmente hostis em espaços fechados." },
	["knife"] = { name = "Faca", desc = "Silenciosa e sempre disponível, a faca tem um ataque principal rápido de pouco dano, assim como um ataque secundário lento que causa muito dano. Uma facada nas costas causa uma morte instantânea." },
	["knife_t"] = { name = "Faca", desc = "Silenciosa e sempre disponível, a faca tem um ataque principal rápido de pouco dano, assim como um ataque secundário lento que causa muito dano. Uma facada nas costas causa uma morte instantânea." },
	["knife_gg"] = "Faca Dourada",
	["knife_ghost"] = { name = "Faca Espectral", desc = "Os fantasmas adoram facas-fantasma. Se eles acharem uma, tem cuidado! Eles vão tentar esfaquear-te assim que puderem. Se bem que eles são fantasmas e facas-fantasma não aleijam ninguém..." },
	["m249"] = { name = "M249", desc = "Tratando-se de uma potente metralhadora para espaços abertos, a M249 é a escolha perfeita para jogadores que não se importam com um ritmo de disparo lento e procuram uma maior precisão e muitas, mas mesmo muitas, balas." },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "A M4A1 com silenciador tem menos capacidade de carregador do que a M4A4, mas dá disparos menos barulhentos, tem um menor recuo e uma melhor precisão." },
	["mac10"] = { name = "MAC-10", desc = "A submetralhadora MAC-10 é praticamente uma caixa que cospe balas. Tem um elevado ritmo de disparo, mas tem uma precisão muito pobre e um recuo muito alto." },
	["p90"] = { name = "P90", desc = "Facilmente reconhecível pelo seu design \"bullpup\", a P90 é uma arma ótima para dar tiros enquanto andas devido ao seu carregador de capacidade elevada e por ser uma arma com pouco recuo." },
	["smoke_grenade"] = { name = "Granada de Fumo", desc = "A granada de fumo cria uma barreira de fumo numa determinada área. Pode esconder eficazmente os membros da tua equipa da mira dos snipers, ou até criar uma distração útil." },
	["ump45"] = { name = "UMP-45", desc = "Podendo ser considerada como uma filha incompreendida da família das submetralhadoras, a UMP45 é uma arma automática versátil e ótima a disparar em alvos próximos, porém o seu carregador tem relativamente poucas balas." },
	["xm1014"] = { name = "XM1014", desc = "A XM1014 é uma caçadeira automática potente que justifica o seu preço elevado com a capacidade de encher de chumbo rapidamente uma sala cheia de inimigos." },
	["c4"] = { name = "Explosivo C4", desc = "Estável e resistente à maioria dos impactos físicos, este explosivo de plástico improvisado tem uma velocidade de detonação de mais de 8 quilómetros por segundo quando ativado." },
	["bizon"] = { name = "PP-Bizon", desc = "A submetralhadora Bizon causa pouco dano, mas é única pelo seu enorme carregador e pode ser carregada rapidamente." },
	["mag7"] = { name = "MAG-7", desc = "A MAG-7 é uma arma exclusiva da equipa Contraterrorista e causa uma quantidade devastadora de dano a curtas distâncias. O facto de usar carregadores em vez de cartuchos como as outras caçadeiras torna-a numa ótima opção tática." },
	["negev"] = { name = "Negev", desc = "A Negev é uma metralhadora capaz de manter os inimigos à distância graças aos seus disparos supressivos e precisos, desde que disponhas do tempo necessário para controlá-la." },
	["sawedoff"] = { name = "Sawed-Off", desc = "Esta clássica caçadeira de cano serrado causa imenso dano a curtas distâncias, mas com a sua baixa precisão, elevada dispersão e ritmo lento dos disparos, é melhor que tenhas boa pontaria." },
	["tec9"] = { name = "Tec-9", desc = "A Tec-9 é uma pistola ideal para os Terroristas que se deslocam com frequência, sempre letal em combates a curtas distâncias e possui carregadores com um elevado número de balas." },
	["taser"] = { name = "Zeus x27", desc = "Perfeita para emboscadas de curto alcance e confrontos em espaços fechados, a Zeus x27 só dispara um tiro mas é capaz de matar um inimigo de uma só vez." },
	["molotov"] = { name = "Molotov", desc = "O Molotov é uma arma poderosa e impresivível que cria uma barreira de chamas ao ser atirada ao chão, causando dano a qualquer jogador na área." },
	["incgrenade"] = "Granada Incendiária",
	["decoy"] = "Granada de Distração",
	["hkp2000"] = { name = "P2000", desc = "Vinda da Alemanha, a P2000 é uma pistola precisa e controlável. É uma das pistolas disponíveis na primeira ronda e é eficaz contra oponentes sem colete nem capacete." },
	["mp7"] = { name = "MP7", desc = "Vinda da Alemanha, a submetralhadora MP7 é versátil, cara e a opção perfeita para causar imenso dano em curtas distâncias." },
	["mp5sd"] = { name = "MP5-SD", desc = "Muito imitada mas nunca igualada, a icónica MP5 é talvez a submetralhadora mais versátil e popular do mundo. Esta variante SD vem equipada com um silenciador integrado, o que deixa uma arma já formidável tão silenciosa como um sussurro." },
	["mp9"] = { name = "MP9", desc = "Produzida na Suíça, a submetralhadora MP9 é uma arma inovadora e ergonómica, muito usada por empresas de segurança privadas." },
	["nova"] = { name = "Nova", desc = "O preço relativamente baixo da Nova torna-a numa ótima arma de emboscada para uma equipa com pouco dinheiro." },
	["p250"] = { name = "P250", desc = "Sendo uma pistola de baixo recuo e uma frequência elevada de disparo, a P250 é uma opção relativamente económica contra oponentes de colete e capacete." },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "A SCAR-20 é uma espingarda sniper semi-automática que, apesar de ser cara e reduzir a mobilidade do seu portador, tem um ritmo elevado de disparo e causa uma elevada quantidade de dano a longas distâncias." },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "A SSG08 é uma espingarda sniper que causa relativamente pouco dano, mas o seu baixo preço torna-a numa escolha prudente em tiroteios de longas distâncias nas primeiras rondas." },
	["heavyassaultsuit"] = "Proteção Pesada",
	["assaultsuit"] = "Kevlar + Capacete",
	["kevlar"] = "Colete em Kevlar",
	["defuser"] = "Kit de Desativação",
	["cutters"] = "Kit de Resgate",
	["revolver"] = { name = "R8 Revolver", desc = "O revólver R8 dispara balas precisas e potentes, mas tens de manter o gatilho pressionado durante um curto período de tempo antes de cada disparo. Porém, é possível pressionar a parte de trás do revólver para poderes disparar rapidamente (usa o botão de disparo secundário para tal)." },
	["usp_silencer"] = { name = "USP-S", desc = "Sendo das armas mais populares do Counter-Strike Source, a Pistola USP com silenciador tem um menor recuo e chama menos atenção com os seus disparos." },
	["knifebayonet"] = { name = "Bayonet", desc = "Praticamente inalterada desde a Segunda Guerra Mundial, a baioneta ainda tem o seu devido lugar na estratégia militar moderna. O uso da baioneta tem continuado a ser eficaz em eventos relativamente recentes, como a Segunda Guerra do Golfo e a guerra no Afeganistão." },
	["knifeflip"] = { name = "Flip Knife", desc = "As facas retráteis têm uma lâmina curva ao estilo persa e de uma ponta afiada. Embora a própria ponta possa ser frágil, a estrutura geral das facas retráteis é surpreendentemente robusta." },
	["knifegut"] = { name = "Gut Knife", desc = "A característica mais notável deste tipo de facas é a forma de gancho na ponta da lâmina. Popular entre caçadores por ajudar a remover as entranhas de animais de caça, o gancho é também útil em cortar materiais fibrosos, como cordas, correias ou cintos de segurança facilmente." },
	["knifecss"] = { name = "Faca Clássica", desc = "Um clássico da série Counter-Strike, esta faca representa um equilíbrio harmonioso entre a estelite no fio da lâmina e o titânio no dorso e na superfície. O cabo é feito de marfim de mastodonte fossilizado, reforçado com fibra de carbono." },
	["knifem9"] = { name = "M9 Bayonet", desc = "A baioneta M-9, apesar de ser originalmente pensada para ser adaptada no cano de espingardas, é igualmente letal como arma corpo a corpo." },
	["knifekaram"] = { name = "Karambit", desc = "A karambit é uma faca vinda da Indonésia, cuja forma curva foi inspirada nas garras dos tigres, e faz parte da tradição das artes marciais de \"silat\" do Sudeste Asiático. A faca é tipicamente empunhada para baixo, com o dedo indicador no aro." },
	["knifetactical"] = { name = "Faca Huntsman", desc = "Uma faca concebida para operações táticas modernas, cuja lâmina é adequada tanto para combate como para fins utilitários. O gume distinto permite um nível máximo de penetração através da mais rígida das superfícies." },
	["knife_butterfly"] = { name = "Faca Butterfly", desc = "Esta é uma faca butterfly, também conhecida como faca borboleta. A característica que mais define esta arma é a abertura que permite à lâmina entrar ou sair da empunhadura livremente num eixo giratório. Devido a isto, as facas butterfly são ilegais em muitos países." },
	["partypopper"] = "Lançador de Confetes!",
	["knife_falchion_advanced"] = { name = "Faca Falchion", desc = "Uma homenagem moderna à espada falchion, esta lâmina côncava tem uma borda curva." },
	["knife_push"] = { name = "Shadow Daggers", desc = "Estas adagas, criadas para brutalidade eficiente, são tão simples de usar como dar um soco ou dois." },
	["knife_survival_bowie"] = { name = "Faca Bowie", desc = "Uma faca Bowie de lâmina parcialmente serrada, concebida para uso intensivo em situações de sobrevivência brutais." },
	["healthshot"] = "Injeção Médica",
	["tagrenade"] = "Granada de Deteção Tática",
	["exploding_barrel"] = "Barril Explosivo",
	["snowball"] = "Bola de neve",
	["stompdamagekillstring"] = "esmagou-te a cabeça",
	["dangerzone"] = "Zona de Perigo",
	["autosentry"] = "Sentinela Automática",
	["fists"] = "Punhos",
	["tablet"] = "Tablet",
	["breachcharge"] = "Carga de Demolição",
	["bumpmine"] = "Mina Repulsora",
	["axe"] = { name = "Machado", desc = "Pesado e sempre disponível, o machado tem um lado afiado e um lado rombo. O ataque principal é um golpe de pouco dano, enquanto o ataque secundário lança o machado para causar muito dano. Se achares um machado, é um bom achado." },
	["hammer"] = { name = "Martelo", desc = "Quando não é para consertar coisas, o martelo está disponível para as partir. O ataque principal é um golpe de pouco dano, enquanto o ataque secundário lança o martelo para causar muito dano. Se a única coisa que tens é um martelo, tudo se parece com um prego." },
	["spanner"] = { name = "Chave-Inglesa", desc = "Uma chave-inglesa é normalmente usada para aplicar torção ao virar objetos, mas podes usá-la para dar um golpe de pouco dano (ataque principal). Também podes atirá-la para causar muito dano (ataque secundário). Porém, não é a melhor ferramenta no meio de um tiroteio." },
	["tripwirefire"] = "Armadilha de fogo",
	["knife_cord"] = { name = "Faca Paracord", desc = "Esta faca de sobrevivência de lâmina fixa foi concebida para poder ser usada tanto como arma como ferramenta para, por exemplo, armar armadilhas, caçar animais ou cortar folhagem. O cabo está envolto em corda multiúsos." },
	["knife_canis"] = { name = "Faca de Sobrevivência", desc = "Esta faca multifuncional tem uma lâmina serrada pensada para lacerar materiais espessos como osso ou fibra, e uma ponta afiada em forma de gancho. O cabo de material compósito está aparafusado à lâmina com porcas hexagonais." },
	["knife_ursus"] = { name = "Faca Ursus", desc = "Esta faca de sobrevivência estilo tantō trata-se de um modelo integral com uma lâmina facetada e complementado com um punho de impacto. Sem complicações nem peças móveis - apenas uma faca confiável e sempre pronta para qualquer trabalho." },
	["knife_gypsy_jackknife"] = { name = "Faca Navaja", desc = "Esta navalha de punho de mármore e esmalte esconde uma lâmina pequena, porém cruelmente afiada." },
	["knife_outdoor"] = { name = "Faca Nomad", desc = "Esta faca de caça dobrável e ergonómica possui um cabo de material compósito e uma lâmina reforçada e larga, útil para cortar e separar materiais." },
	["knife_widowmaker"] = { name = "Faca Talon", desc = "Esta karambit com um punho de marfim possui rebites de latão e uma lâmina parcialmente serrada, para que corte quando entrar em contacto com o alvo e rasgue a carne quando sair." },
	["knife_stiletto"] = { name = "Faca Stiletto", desc = "Historicamente um alvo de polémica e até regulamentações, este estilete de estilo italiano possui uma lâmina retrátil por mola, que pode ser acionada quase instantaneamente ao pressionar um botão." },
	["knife_skeleton"] = { name = "Faca Skeleton", desc = "A empunhadura desta faca de espiga esqueletizada foi embrulhada em fita para que possa ser manuseada melhor. O orifício no centro permite que a faca seja segurada com um dedo de uma forma estável e segura." },
	["firebomb"] = { name = "Bomba Incendiária", desc = "A bomba incendiária é uma poderosa arma experimental que, quando atirada ao chão, cria chamas intensas capazes de causar queimaduras químicas a qualquer jogador na vasta área da explosão." },
	["diversion"] = { name = "Dispositivo de Distração", desc = "Quando lançado, o dispositivo de distração irá destacar sectores no mapa dos tablets de outros jogadores, criando a ilusão de que há outros inimigos por perto." },
	["frag_grenade"] = { name = "Granada de Fragmentação", desc = "A granada de fragmentação experimental pode causar grandes quantidades de dano altamente explosivo numa área maior, tornando-a ideal para estratégias tanto ofensivas como defensivas." },
	["shield"] = "Escudo Balístico",
	["zone_repulsor"] = { name = "Dispositivo de Repulsão", desc = "Protótipo de dispositivo de proteção contra emissões de partículas radiais" },
	["cz75a"] = "Uma variante totalmente automática da CZ75, a CZ75-Auto é a escolha ideal a curto prazo para dar a volta à partida e conseguir obter uma arma do inimigo. Mas com tão poucas munições no carregador, é preciso moderar os disparos.",
	["m4a4"] = "A M4A4 é a espingarda de assalto automática de eleição para qualquer Contraterrorista: é mais precisa do que a sua rival AK-47, porém causa relativamente menos dano.",
	["sg553"] = "A espingarda SG553 é exclusiva para a equipa Terrorista e é uma boa alternativa com mira telescópica à AK-47 para confrontos de longa distância.",
	["decoy_grenade"] = "Ao ser atirada, a granada de distração imita o som da arma mais potente que tens, criando a ilusão de que um maior número de oponentes está a caminho.",
	["incindiary_grenade"] = "Ao ser atirada, a granada incendiária causa uma reação química exotérmica capaz de queimar qualquer um na área da explosão.",
	["survival_taser"] = "Uma arma de alcance extremamente curto, capaz de matar com um só disparo. Pode sar usada para abrir caixas de armas.",
	["survival_healthshot"] = "Restaura uma porção da tua vida e concede-te um bónus breve de velocidade.",
	["survival_vesthelm"] = "Concede resistência a dano.",
	["survival_shield"] = "Um escudo balístico que pode bloquear uma grande quantidade de dano antes de ser destruído.",
	["survival_parachute"] = "Pode ser aberto enquanto estiveres a cair para impedir que sofras dano pela queda.",
	["survival_exojump"] = "Ajuda-te a saltar muito mais alto.",
	["survival_c4"] = "Arma este explosivo em qualquer lado para causares uma explosão enorme. Pode ser usado para abrir cofres.",
	["survival_dronepilot"] = "Permite-te assumir o controlo de drones. Usa o tablet para selecionares qual drone queres controlar.",
	["survival_exploremoney"] = "Dá-te mais dinheiro por cada hexágono explorado.",
	["survival_wavemoney"] = "Dá-te mais dinheiro por cada ronda de expansão da zona de perigo que sobreviveres.",
}
