csstring = {
	["cat_pistols"] = "手槍",
	["cat_heavy"] = "重型武器",
	["cat_smg"] = "衝鋒槍",
	["cat_rifles"] = "步槍",
	["cat_grenades"] = "手榴彈",
	["cat_gear"] = "裝備",

	["ak47"] = { name = "AK-47", desc = "威力強大且可靠，身為世界上最受青睞的突擊步槍之一的 AK-47 在收放得當的點放射擊之下最能彰顯其致命性。" },
	["aug"] = { name = "AUG", desc = "高威力和高準度， 配有瞄準鏡的AUG是款犧牲換彈速度換取穩定彈道以及射擊速率的突擊步槍。" },
	["awp"] = { name = "AWP", desc = "高風險高報酬的 AWP 因為它的招牌槍聲以及秉持的一槍斃命政策而落得惡名昭彰，但也因此大名鼎鼎。" },
	["deserteagle"] = { name = "Desert Eagle", desc = "身為經典款手槍的沙漠之鷹有著不失它定價尊嚴的高破壞力，雖然駕馭不易卻在遠距準確度這方面有著令人咋舌的出色表現。" },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Dual Berettas", desc = "雖然同時抓著兩把貝瑞塔手槍進行射擊意味著無法兼顧的較差準確度以及有兩個彈匣要換將更為耗時，不過論好處來說至少雙手所掌握的火力也會是兩倍。" },
	["elite"] = "Dual Berettas",
	["famas"] = { name = "FAMAS", desc = "FAMAS 有效的滿足了介於昂貴的步槍以及傷害較低的衝鋒槍之間的空缺，是款適合在手頭緊時購買的便宜選擇。" },
	["fiveseven"] = { name = "Five-SeveN", desc = "精準且具備穿甲能力，威力偏低的 Five-seveN 雖然得費好一會工夫才能撂倒敵人卻有著連續擊中目標所需的 20 發的高容量彈匣還有低後座力來供它好好表現。" },
	["flashbang"] = { name = "閃光彈", desc = "非致命性的閃光彈會暫時的使所有人失明，其震盪性爆炸範圍內，使得它完美驅趕密閉地區敵人。其巨大的爆炸聲，也暫時掩蓋了腳步聲。" },
	["g3sg1"] = { name = "G3SG1", desc = "昂貴的 G3SG1 雖會導致移動速度明顯下降卻有著射速較其它狙擊步槍高出許多這個優點來補足表現。" },
	["galilar"] = { name = "Galil AR", desc = "在恐怖份子限定的突擊步槍之中 Galil AR 是款耐用且也不會那麼昂貴的選擇。" },
	["glock18"] = { name = "Glock-18", desc = "Glock 18 是一把堪用且能成切換三點放射擊模式的手槍，在對手未著防彈衣的頭幾個回合中最為有效。" },
	["he_grenade"] = { name = "高爆手榴彈", desc = "高爆手榴彈能對一個廣闊的範圍造成殺傷，做為一個用於攻擊充滿敵人的空間來說是個十分理想的武器。" },
	["knife"] = { name = "軍刀", desc = "安靜且隨時可得，軍刀分別擁有高速低傷害的主要攻擊和高傷害低速的次要攻擊。背刺將可迅速且安靜地殺死敵人。" },
	["knife_t"] = { name = "軍刀", desc = "安靜且隨時可得，軍刀分別擁有高速低傷害的主要攻擊和高傷害低速的次要攻擊。背刺將可迅速且安靜地殺死敵人。" },
	["knife_gg"] = "黃金軍刀",
	["m249"] = { name = "M249", desc = "對於那些願意犧牲射速換取較高的準確度還有大彈鼓所帶來的高續航力的玩家來說 M249  將會是款強而有力且泛用的完美選擇。" },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "比起沒消音器的原版彈匣容量更小。消音版的 M4A1 槍聲更為小聲，並擁有較小的後座力與加強的精準度。" },
	["mac10"] = { name = "MAC-10", desc = "MAC-10 怎麼看都像個會噴子彈的鐵盒子，重點是還噴得很快令它有著高後座力和差勁的準確度。" },
	["p90"] = { name = "P90", desc = "因為其獨特的犢牛式設計，P90 難以與其它槍枝混淆，同時具備高彈匣容量和低後座力讓它成為一邊移動一邊開火的優秀選擇。" },
	["smoke_grenade"] = { name = "煙霧彈", desc = "煙霧彈能製造一定範圍的煙霧屏障。幫助您的隊友有效的躲藏於敵方狙擊手的狙擊鏡下，或是分散敵人的注意力。" },
	["ump45"] = { name = "UMP-45", desc = "UMP45 是款在衝鋒槍家族中飽受冷落的中庸選擇，若非因為彈匣容量這個唯一缺點的話不然還挺全能的。" },
	["xm1014"] = { name = "XM1014", desc = "威力強大的 XM1014 是款能夠將槍口所對準的地方迅速打成蜂窩而不負它高昂定價的全自動霰彈槍。" },
	["c4"] = { name = "C4 炸彈", desc = "穩定且能抵抗大多數物理衝擊，這個拼湊而成的塑膠炸藥在引爆時將掀起速度超過每秒 8,000 公尺的震波。" },
	["bizon"] = { name = "PP-Bizon", desc = "Bizon 衝鋒槍的傷害雖小卻具有能夠容納大量彈藥和迅速更換的彈鼓設計。" },
	["mag7"] = { name = "MAG-7", desc = "反恐小組限定的 Mag-7 在近距離能夠造成強力傷害。它也因為藉由可以迅速更換的彈匣供彈而成為一個很好的戰術性選擇。" },
	["negev"] = { name = "Negev", desc = "Negev 是一頭能準確撒出壓制火力的猛獸，但前提是使用者要有足夠時間馴服它的後座力。" },
	["sawedoff"] = { name = "Sawed-Off", desc = "這款相當典型的裁短式霰彈槍能在近距離造成強烈的傷害，但基於準度不佳、飄散程度大和射速偏慢的緣故使用時最好還是謹慎出手為妙。" },
	["tec9"] = { name = "Tec-9", desc = "Tec-9 是恐怖份子四處行動的理想手槍，在近距離戰鬥中非常致命並且有著持久火力。" },
	["taser"] = { name = "Zeus x27", desc = "對付突如其來或準備伏擊的敵人非常有用的單發武器 x27 Zeus 可以以單發癱瘓單一敵人。" },
	["molotov"] = { name = "莫洛托夫汽油彈", desc = "莫洛托夫汽油彈是一個強大且無法預知傷害的區域封鎖性武器，火焰在地上時，任何一名敵人皆會在半徑範圍內受傷。" },
	["incgrenade"] = "燃燒手榴彈",
	["decoy"] = "誘餌手榴彈",
	["hkp2000"] = { name = "P2000", desc = "準確且容易掌握，由德國工藝製成的 P2000 是把能夠在開局回合中有效對抗未著防彈衣的對手的利器。" },
	["mp7"] = { name = "MP7", desc = "出自德國工藝的 MP7 衝鋒槍雖然多才多藝是款用於近距離激烈戰鬥的完美選擇但卻不怎便宜。" },
	["mp5sd"] = { name = "MP5-SD", desc = "時而被模仿但從未被超越，MP5 或許是世上最通用也最受歡迎的衝鋒槍。其衍生型 SD 具有整體式消音器，使這把已令人敬畏的武器更加莊嚴。" },
	["mp9"] = { name = "MP9", desc = "出自瑞士，採用尖端科技的 MP9 衝鋒槍有著人體工學設計並由聚合材質打造而成，是私人保全行業的最愛。" },
	["nova"] = { name = "Nova", desc = "Nova 的超低價格讓它對資金不多的隊伍來說是一款非常優秀的近距埋伏武器。" },
	["p250"] = { name = "P250", desc = "具有低後座力還有高射速， P250 用於對付身穿護甲的對手時是款的價格宜人的選擇。" },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "以昂貴的價格以及笨重的移動速度作為代價， SCAR-20 是款有著高射速和高遠距離傷害的半自動狙擊步槍。" },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "SSG08 是款傷害普通且需要手動操作槍機的單發狙擊步槍，但有著非常好的性價比因此使它成為早期回合中遠距離狙擊的明智選擇。" },
	["heavyassaultsuit"] = "重型護甲",
	["assaultsuit"] = "防彈背心 + 頭盔",
	["kevlar"] = "克維拉防彈背心",
	["defuser"] = "拆彈包",
	["cutters"] = "救援包",
	["revolver"] = { name = "R8 Revolver", desc = "R8 Revolver 提供了高度精確且強力的彈藥，代價是扣扳機耗時極久。透過搧動擊鎚快速開火可能是在需要近距離交火時的最佳選擇。" },
	["usp_silencer"] = { name = "USP-S", desc = "從《絕對武力：次世代》深受玩家喜愛並轉移過來的消音版 USP 手槍。有著能隨時拆裝的消音器，給予較低的後座力並降低開火的音量。" },
	["knifebayonet"] = { name = "刺刀", desc = "從第二次世界大戰後就沒什麼變化的刺刀，在現代軍事上的戰略方面仍有一席之地。刺刀衝鋒在最近的第二次波斯灣戰爭與阿富汗戰爭仍然能發揮最佳功效。" },
	["knifeflip"] = { name = "折疊式軍刀", desc = "折疊式軍刀有著波斯風格的尖銳後彎刀片。雖然刀片的尖端比較容易破碎，但以整體折疊式軍刀的設計來看，仍出奇的耐用。" },
	["knifegut"] = { name = "穿腸刀", desc = "穿腸刀上最顯眼的特點莫過於刀背上的尖鉤。雖然鉤狀的鋒刃最初是為野外狩獵時剖開獵得物所設計的輔助工具，但它也能讓人既輕鬆又有效地去割開繩索、網子，或是安全帶這類織物。" },
	["knifecss"] = { name = "經典軍刀", desc = "A classic of the Counter-Strike series, the edge of this knife is press-fit Stellite perfectly held in place due to its precise fit with the titanium on the blade's cheek and spine. The handle is fossilized mastodon ivory held in a carbon fibre pocket." },
	["knifem9"] = { name = "M9 刺刀", desc = "這是把 M-9 刺刀。原來就是用來裝在步槍身上，使步槍同時也能用於近戰方面上。" },
	["knifekaram"] = { name = "爪刀", desc = "其彎曲的刀片就像老虎的尖爪，爪刀本身作為東南亞馬來武術的一部份開發的。這把刀通常都是以食指插在其指環上並反握使用。" },
	["knifetactical"] = { name = "獵刀", desc = "一把專為現代戰爭設計的刀，刀身無論是戰鬥抑或他用都相當適合。獨特的短刀式尖鋒足以刺穿最堅硬的表面。" },
	["knife_butterfly"] = { name = "蝴蝶刀", desc = "這是把客製化的折疊刀，俗稱蝴蝶刀。這種武器最獨特的便屬它那宛如扇葉、可以自在旋轉的刀身，方便迅速展開或收起。不過蝴蝶刀也因此在許多國家禁止使用。" },
	["partypopper"] = "派對拉炮！",
	["knife_falchion_advanced"] = { name = "彎刃匕首", desc = "透過現代的手法向彎刀致敬，這把上揚刀刃有著弧形邊緣。" },
	["knife_push"] = { name = "暗影匕首", desc = "為有效的暴行所設計，使用一把手刺就像揮個一兩拳一樣簡單。" },
	["knife_survival_bowie"] = { name = "布伊刀", desc = "這把一體成形、刀背有鋸齒的布伊刀是設計在嚴峻的生存環境中大量使用的。" },
	["healthshot"] = "醫療針",
	["tagrenade"] = "戰術感測手榴彈",
	["exploding_barrel"] = "爆炸桶",
	["snowball"] = "雪球",
	["stompdamagekillstring"] = "打碎你的頭骨",
	["dangerzone"] = "危險區域",
	["autosentry"] = "自動步哨槍",
	["fists"] = "徒手",
	["tablet"] = "平板電腦",
	["breachcharge"] = "爆破炸藥",
	["bumpmine"] = "彈跳地雷",
	["axe"] = { name = "斧頭", desc = "Heavy and always available, the axe has a sharp side and a dull side. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. How much wood would a woodchuck chuck?" },
	["hammer"] = { name = "鐵鎚", desc = "The hammer is available for fixing things and breaking things. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. If all you have is a hammer, everything looks like a nail." },
	["spanner"] = { name = "扳手", desc = "A wrench is typically used to apply torque when turning objects, but you can hit anything with it for low-damage primary attack or throw it for a high-damage secondary attack. Bringing a wrench to a firefight is a recipe for screwing up." },
	["knife_ursus"] = { name = "熊刀", desc = "This tanto-style survival knife features a faceted blade and full tang, complete with impact pommel. No fuss, no moving parts - just a reliable blade that's ready to work." },
	["knife_gypsy_jackknife"] = { name = "西班牙折刀", desc = "This marble-enamel-handled flip knife conceals a small but viciously tapered blade." },
	["firebomb"] = { name = "汽油彈", desc = "汽油彈是一種強力的實驗性武器，投擲到地面上時會爆出高溫火焰，以化學方式燒傷任何在擴散範圍內的玩家。" },
	["diversion"] = { name = "干擾裝置", desc = "在經過投擲後，干擾裝置將使其他平板標示出它的所在區域，製造出有人在那的假象。" },
	["frag_grenade"] = { name = "破片手榴彈", desc = "這種實驗性破片手榴彈可在一個更廣的區域產生極大量的高爆傷害，是個執行攻擊或防守策略的理想器具。" },
	["shield"] = { name = "鎮暴盾", desc = "設計來轉移或吸收子彈傷害的防護裝置，可以在裝備者面對各種口徑彈藥時提供保護。" },
	["zone_repulsor"] = { name = "斥力裝置", desc = "放射型顆粒物護盾原型裝置" },
	["cz75a"] = "CZ75-Auto 為 CZ75 手槍衍生出來的全自動型號，是一款短期內為了翻盤以取得您對手武器的理想選擇。但是由於配給的彈藥非常稀少，射手將需要一隻有著足夠定力的食指。",
	["m4a4"] = "M4A4 是反恐小組陣營中全自動突擊步槍的不二選擇，比照對手陣營的 AK-47 來說更為準確不過殺傷力較小。",
	["sg553"] = "恐怖份子限定的 SG553 搭載著瞄準鏡，是款較 AK-47 更適合用於遠距離交戰的優異選擇。",
	["decoy_grenade"] = "當拋出誘餌手榴彈，將會模擬您身上持有火力最強大武器的聲音，來製造出支援火力的假象。",
	["incindiary_grenade"] = "當丟出燃燒彈的時候，燃燒彈會釋放高溫化學反應能夠燃燒廣泛爆炸範圍內的敵人。",
	["survival_taser"] = "能夠一槍斃命但有效距離極短的武器。也能夠用來打開武器箱。",
	["survival_healthshot"] = "恢復您的部分生命值並提供片刻的移動速度激增。",
	["survival_vesthelm"] = "提供傷害抗性。",
	["survival_shield"] = "鎮暴盾在被摧毀前能抵擋大量傷害。",
	["survival_parachute"] = "能在半空中使用來防止使用者摔傷。",
	["survival_exojump"] = "大幅提升跳躍高度。",
	["survival_c4"] = "安裝在場上任何地方然後在倒數後產生大爆炸。可用來打開保險箱。",
	["survival_dronepilot"] = "讓使用者能夠接管無人機並進行操控。用平板選擇要接管的無人機。",
	["survival_exploremoney"] = "提升區域探索獎勵金額。",
	["survival_wavemoney"] = "提升危險區域存活獎勵金額。",
	["knife_ghost"] = { name = "Spectral Shiv", desc = "Ghosts love ghost knives. When they get their hands on one, look out! They'll try stab you first chance they get. Too bad they are a ghost and ghost knives can't hurt people...." },
	["tripwirefire"] = "TrapFire",
	["knife_cord"] = { name = "Paracord Knife", desc = "This fixed-blade survival knife is designed to withstand being used as both a weapon and a tool, such as for setting traps, hunting animals or cutting foliage. The handle is wrapped in a length of multi-purpose paracord." },
	["knife_canis"] = { name = "Survival Knife", desc = "This multi-purpose tactical knife features a serrated edge for ripping through coarse material like bone or fiber, plus a sharp gutting hook. The composite material handle is bolted to the blade with hex nuts." },
	["knife_outdoor"] = { name = "Nomad Knife", desc = "This ergonomic tactical hunting lock-blade knife features composite handle inserts and a broad, sturdy blade, useful for cutting and prying apart material." },
	["knife_widowmaker"] = { name = "Talon Knife", desc = "This ivory-handled karambit features brass rivets and saw-tooth ridges, so it cuts on the way in, and tears on the way out." },
	["knife_stiletto"] = { name = "Stiletto Knife", desc = "Historically a focal point of contention and even regulation, this Italian-style stiletto switchblade knife features a spring-loaded blade that can be deployed almost instantly with the push of a release catch." },
	["knife_skeleton"] = { name = "Skeleton Knife", desc = "This skeletonized-tang knife has been taped at the handle for improved grip. The hole allows a finger to be threaded through for stability and safety." },
}
