csstring = {
	["cat_pistols"] = "Pistoler",
	["cat_heavy"] = "Tungt",
	["cat_smg"] = "MP-er",
	["cat_rifles"] = "Rifler",
	["cat_grenades"] = "Granater",
	["cat_gear"] = "Utstyr",

	["pistol"] = "Pistol",
	["smg"] = "MP",
	["rifle"] = "Rifle",
	["heavy"] = "Tungt",
	["grenade"] = "Granat",
	["sniperrifle"] = "Skarpskytterrifle",
	["sniper"] = "Skarpskytter",
	["shotgun"] = "Hagle",
	["ak47"] = { name = "AK-47", desc = "AK-47 er kraftig og pålitelig, og den er en av verdens mest populære rifler. Den er mest dødelig i korte, kontrollerte skuddsalver." },
	["aug"] = { name = "AUG", desc = "AUG er en kraftig og nøyaktig rifle, som kompenserer for lang ladetid med lav spredning og høy skuddtakt." },
	["awp"] = { name = "AWP", desc = "Den berømte AWP har høy risiko og høy belønning, og den kan lett gjenkjennes ved dens signaturlyd og ett skudd, ett drap-policy." },
	["deserteagle"] = { name = "Desert Eagle", desc = "Desert Eagle er like dyr som den er kraftig, og den er en ikonisk pistol som er vanskelig å mestre, men overraskende nøyaktig på langt hold." },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Dual Berettas", desc = "Du får lavere treffsikkerhet og økt omladningstid av å avfyre to Berettaer med store magasin samtidig. På den lyse siden får du avfyre to Berettaer med store magasin samtidig." },
	["elite"] = "Dual Berettas",
	["famas"] = { name = "FAMAS", desc = "FAMAS er et billig alternativ for pengelense spillere, og den fyller fint nisjen mellom dyrere rifler og de mindre effektive maskinpistolene." },
	["fiveseven"] = { name = "Five-SeveN", desc = "Den dyre, tregt ladede Five-Seven-pistolen kompenserer med høy presisjon, panserbrytning, magasin med 20 patroner og en tilgivende rekyl." },
	["flashbang"] = { name = "Sjokkgranat", desc = "Den ikke-dødelige sjokkgranaten blender, midlertidig, alle innenfor dens virkningsradius, noe som gjør den perfekt for å rense ut lukkede områder. Dens høylytte eksplosjon gjemmer også lyden av fottrinn i en kortere periode." },
	["g3sg1"] = { name = "G3SG1", desc = "Den dyre G3SG1 reduserer bevegelseshastigheten betraktelig, men kompenserer med høyere skuddtakt enn andre skarpskytterrifler." },
	["galilar"] = { name = "Galil AR", desc = "Som et rimeligere alternativ blant terroristeksklusive automatgevær, er Galil AR et brukbart våpen i skuddvekslinger over middels til lang avstand." },
	["glock18"] = { name = "Glock-18", desc = "Glock 18 er anvendelig pistol i den første runden, som fungerer best mot motstandere uten verneutstyr, og den er i stand til å avfyre skuddsalver." },
	["he_grenade"] = { name = "Høyeksplosiv granat", desc = "Den høyeksplosive splintgranaten sprer høy skade gjennom et stort område, noe som gjør den ideell for å rense fiendtlige rom." },
	["knife"] = { name = "Kniv", desc = "Stille og alltid tilgjengelig. Kniven har et raskt hovedangrep som gjør lite skade, og et tregt sekundærangrep som gjør mye skade. Et bakholdsangrep gir stille spillere et umiddelbart drap." },
	["knife_t"] = { name = "Kniv", desc = "Stille og alltid tilgjengelig. Kniven har et raskt hovedangrep som gjør lite skade, og et tregt sekundærangrep som gjør mye skade. Et bakholdsangrep gir stille spillere et umiddelbart drap." },
	["knife_gg"] = "Gullkniv",
	["knife_ghost"] = { name = "Spøkelseskniv", desc = "Spøkelser elsker spøkelseskniver. Du bør passe deg om de får tak i en! De vil prøve å stikke deg ved første anledning. Synd de er et spøkelse og at spøkelseskniver ikke kan skade folk..." },
	["m249"] = { name = "M249", desc = "Som et sterkt, lett maskingevær for åpne flater, er M249 det perfekte valget for spillere som er villige til å bytte en treg skuddtakt mot økt presisjon og en høy ammunisjonskapasitet." },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "Med et mindre magasin enn sitt høylytte motstykke, gir den lyddempende M4A1 støysvake skudd med mindre rekyl og bedre nøyaktighet." },
	["mac10"] = { name = "MAC-10", desc = "Kort fortalt en eske som kuler kommer ut av. Maskinpistolen MAC-10 gir en høy skuddtakt i bytte mot lav nøyaktighet og mye rekyl." },
	["p90"] = { name = "P90", desc = "P90 er lett gjenkjennelig grunnet sitt unike bullpup-design og er et fantastisk våpen å skyte med i bevegelse grunnet høy magasinkapasitet og lav rekyl." },
	["smoke_grenade"] = { name = "Røykgranat", desc = "Røykgranaten skaper et mellomstort røykteppe. Den kan effektivt skjule laget ditt fra skarpskyttere, eller bare lage en nyttig distraksjon." },
	["ump45"] = { name = "UMP-45", desc = "UMP45 er det misforståtte mellomste barnet i maskinpistolfamilien. Det lille magasinet er det eneste negative med dette ellers meget anvendelige automatvåpenet for nærkamp." },
	["xm1014"] = { name = "XM1014", desc = "XM1014 er en kraftig, helautomatisk hagle som rettferdiggjør en stiv pris med evnen til å raskt male et rom med bly." },
	["c4"] = { name = "C4", desc = "Stabil og i stand til å motstå de fleste fysiske sjokk, har dette improviserte plastiske sprengstoffet en detonasjonshastighet på over 8000 meter per sekund når den antennes." },
	["bizon"] = { name = "PP-Bizon", desc = "Bizon-maskinpistolen er lite kraftig, men tilbyr et unikt designet tønnemagasin som lades raskt om." },
	["mag7"] = { name = "MAG-7", desc = "Den AT-eksklusive Mag-7 leverer en ødeleggende mengde skade på nært hold. Den raske, magasinbaserte lademekanismen gjør den til et godt taktisk valg." },
	["negev"] = { name = "Negev", desc = "Negev er et beist som kan holde fienden i sjakk med sin nøyaktige dekningsild, forutsatt at du har tid til å temme den." },
	["sawedoff"] = { name = "Sawed-Off", desc = "Den klassiske avsagde haglen gjør veldig stor skade på nært hold, men med sin lave nøyaktighet, store spredning og trege skuddtakt, bør du drepe det du treffer." },
	["tec9"] = { name = "Tec-9", desc = "Tec-9 er en utmerket pistol for terrorister på farten, og den er dødelig på kloss hold og har høy magasinkapasitet." },
	["taser"] = { name = "Zeus x27", desc = "Perfekt for nærkampangrep og kamper i innelukkede områder, med sitt ene skudd er Zeus x27 i stand til å ta ut en fiende på ett treff." },
	["molotov"] = { name = "Molotov", desc = "Molotovcocktailen er et kraftig og uforutsigbart områdenektende våpen som bryter ut i flammer når den blir kastet på bakken, og skader enhver spiller i dens radius." },
	["incgrenade"] = "Branngranat",
	["decoy"] = "Lokkegranat",
	["hkp2000"] = { name = "P2000", desc = "Den tysklagde P2000 er presis og kontrollerbar, og det er en anvendelig pistol i den første runden, da den fungerer best mot motstandere uten verneutstyr." },
	["mp7"] = { name = "MP7", desc = "Den tyskproduserte MP7-maskinpistolen er allsidig, men dyr, og den er det perfekte valget for intens nærkamp." },
	["mp5sd"] = { name = "MP5-SD", desc = "Ofte etterlignet, men ingen er i nærheten av originalen. Den ikoniske MP5-en er kanskje den mest allsidige og populære maskinpistolen i verden. Denne SD-varianten har en integrert lyddemper, noe som gjør et allerede formidabelt våpen helt stillegående." },
	["mp9"] = { name = "MP9", desc = "Den banebrytende MP9-maskinpistolen er produsert i Sveits og er et ergonomisk polymervåpen foretrukket av private sikkerhetsfirmaer." },
	["nova"] = { name = "Nova", desc = "Novaens lave prislapp gjør den til et flott bakholdangrepsvåpen for et pengefattig lag." },
	["p250"] = { name = "P250", desc = "P250 er et skytevåpen med lav rekyl og høy skuddtakt, som er et relativt billig valg mot motstandere med verneutstyr." },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "SCAR-20 er en semiautomatisk skarpskytterrifle som bytter en høy skuddtakt og langdistanseskade mot treg bevegelseshastighet og en stor prislapp." },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "SSG08 er et boltmekanisk, mindre kraftig, men veldig kostnadseffektivt skarpskyttergevær, noe som gjør det til et smart valg for langdistansekamper i begynnelsen av spillet." },
	["heavyassaultsuit"] = "Panserdrakt",
	["assaultsuit"] = "Vernevest + hjelm",
	["kevlar"] = "Vernevest",
	["defuser"] = "Desarmeringssett",
	["cutters"] = "Redningssett",
	["revolver"] = { name = "R8 Revolver", desc = "R8 Revolver leverer et veldig nøyaktig og kraftig skudd på bekostning av et langt avtrekk. Når det er nødvendig med ildkraft på kloss hold, kan det å skyte raskt med hånden på hanen være det beste alternativet." },
	["usp_silencer"] = { name = "USP-S", desc = "Som en tilhengerfavoritt fra Counter-Strike: Source, har den lyddempende USP-pistolen en avtakbar lyddemper som gir skuddene mindre rekyl mens den kveler oppmerksomhetsskapende støy." },
	["knifebayonet"] = { name = "Bajonett", desc = "I stor grad uendret siden andre verdenskrig, men bajonetten har fortsatt en plass i moderne militærstrategi. Bajonettangrep har vist seg effektive så nylig som i den andre Golfkrigen og krigen i Afghanistan." },
	["knifeflip"] = { name = "Foldekniv", desc = "Foldekniver har et persisk-stil tilbaketrekkende blad med et spisst punkt. Selv om selve punktet kan være skjørt, er selve designet overraskende holdbart." },
	["knifegut"] = { name = "Sløyekniv", desc = "Den mest merkbare funksjonen til en sløyekniv er sløyekroken på bladets rygg. Den ble i utgangspunktet populær som et hjelpemiddel til å sløye dyr i felten, men sløyekroken er også effektiv på å kutte gjennom fiberrike materialer slik som tau, stropper eller belter." },
	["knifecss"] = { name = "Klassisk kniv", desc = "Denne kniven er en klassiker i Counter-Strike-serien. Knivseggen er av stellitt, som holdes perfekt på plass gjennom presspasningen med titanet på knivbladets sidestykke og rygg. Skaftet er av fossilisert elfenben fra mastodont, som er omkranset av karbonfiber." },
	["knifem9"] = { name = "M9-bajonett", desc = "Dette er M-9-bajonetten. I utgangspunktet lagd for å monteres på en rifle, men den passer også bra til nærkamp." },
	["knifekaram"] = { name = "Karambit", desc = "Med sitt kurvede blad som kan minne om en tigers klo, ble karambit utviklet som en del av den sørøst-asiatiske kampdisiplinen silat. Kniven blir typisk brukt med et omvendt grep, med fingerringen på pekefingeren." },
	["knifetactical"] = { name = "Jegerkniv", desc = "En kniv designet for moderne, taktiske bruksområder. Bladet er godt egnet for en rekke kamp- og nytteformål. Den unike tanto-spissen gir maksimal penetrering gjennom selv de tøffeste overflater." },
	["knife_butterfly"] = { name = "Butterflykniv", desc = "Dette er en spesialbygd balisong, også kjent som en butterflykniv. Våpenets særtrekk er den viftelignende åpnemekanismen av et fritt dreibart knivblad, som tillater hurtig åpning eller lukking av kniven. På grunn av dette, er butterflykniven bannlyst i flere land." },
	["partypopper"] = "Konfettikanon!",
	["knife_falchion_advanced"] = { name = "Falchion-kniv", desc = "En moderne hyllest til et falchion-sverd, dette bladet har en buet kant." },
	["knife_push"] = { name = "Skyggedolker", desc = "Designet for effektiv brutalitet, å bruke en dolk er like enkelt som å slå et slag eller to." },
	["knife_survival_bowie"] = { name = "Bowiekniv", desc = "Denne bowiekniven med fulltange og sagtenner, er designet for hardt bruk i brutale overlevelsessituasjoner." },
	["healthshot"] = "Helsesprøyte",
	["tagrenade"] = "Taktisk bevissthetsgranat",
	["exploding_barrel"] = "Eksplosiv tønne",
	["snowball"] = "Snøball",
	["stompdamagekillstring"] = "knuste skallen din",
	["dangerzone"] = "Faresone",
	["autosentry"] = "Automatisk sensorvåpen",
	["fists"] = "Knyttnever",
	["tablet"] = "Nettbrett",
	["breachcharge"] = "Sprengladning",
	["bumpmine"] = "Sprettmine",
	["axe"] = { name = "Øks", desc = "Øksen har en skarp side og en butt side, og den er både tung og alltid for hånden. Sving den med hovedangrepet for lite skade, eller kast den med sekundærangrepet for mye skade. God dag mann, øksekast!" },
	["hammer"] = { name = "Hammer", desc = "Hammeren kan brukes både til å fikse ting og å knuse ting. Sving den med hovedangrepet for lite skade, eller kast den med sekundærangrepet for mye skade. Hvis en hammer er det eneste du har, ligner alt på en spiker." },
	["spanner"] = { name = "Skiftenøkkel", desc = "En skiftenøkkel brukes vanligvis til å skru på visse ting, men du kan også slå hva som helst med hovedangrepet for å gjøre lite skade, eller kaste den med sekundærangrepet for å gjøre mye skade. Hvis du tar med en skiftenøkkel til en skuddveksling, har du en skrue løs." },
	["tripwirefire"] = "Snubletråd",
	["knife_cord"] = { name = "Paracordkniv", desc = "Denne overlevelseskniven har et fast blad, og er designet for å tåle bruk som både et våpen og verktøy, slik som å sette opp feller, jakte på dyr eller kutte busker. Skaftet er pakket inn i universell paracord." },
	["knife_canis"] = { name = "Overlevelseskniv", desc = "Denne universelle taktiske kniven har en taggete kant, som kan rispe gjennom grovt materiale som bein eller fiber, samt en skarp krok. Skaftet er laget av komposittmateriale og er boltet til bladet med sekskantmuttere." },
	["knife_ursus"] = { name = "Ursus", desc = "Denne overlevelseskniven i tanto-stil har et fasettert blad og fulltange, komplett med fingervern. Intet tull, ingen bevegelige deler – bare et pålitelig blad som er klar til å jobbe." },
	["knife_gypsy_jackknife"] = { name = "Navaja", desc = "Denne foldekniven har et emaljert marmorskaft, og skjuler et lite men brutalt, avsmalnet blad." },
	["knife_outdoor"] = { name = "Nomadekniv", desc = "Denne ergonomiske, taktiske jaktkniven har et bredt og solid låseblad, som er nyttig til å skjære og lirke fra hverandre materiale. Skaftet er laget ulike deler av komposittmateriale." },
	["knife_widowmaker"] = { name = "Talon", desc = "Denne karambiten har et elfenbeinskaft med messingnagler og en rygg med sagtenner, så den skjærer på vei inn, og river på vei ut." },
	["knife_stiletto"] = { name = "Springkniv", desc = "Denne springkniven i italiensk stil har historisk sett vært omstridt og regulert, og har et fjærbelastet blad som kan sprette opp nesten umiddelbart med et enkelt trykk." },
	["knife_skeleton"] = { name = "Skeletonkniv", desc = "Denne kniven har en uthult knivtange og teip på skaftet for bedre grep. Man kan holde en finger i hullet for bedre stabilitet og sikkerhet." },
	["firebomb"] = { name = "Brannbombe", desc = "Brannbomben er et kraftig, eksperimentelt våpen som sprer ut flammer når den kastes på bakken, noe som brenner alle innenfor dens store spredningsradius." },
	["diversion"] = { name = "Avledningsutstyr", desc = "Når avledningsutstyret kastes, uthever det sektorer på nettbrett, noe som skaper illusjonen av at det finnes flere fiender." },
	["frag_grenade"] = { name = "Sprenggranat", desc = "Den eksperimentelle sprenggranaten kan gjøre ekstremt mye skade i et større område, noe som gjør den ideell for både offensive og defensive formål." },
	["shield"] = { name = "Politiskjold", desc = "Beskyttelsesutstyr designet for å avlede eller absorbere ballistisk skade og verne brukeren fra prosjektiler i en rekke kaliber." },
	["zone_repulsor"] = { name = "Skjermingsenhet", desc = "Prototype av en radial skjermingsenhet mot partikkelutslipp." },
	["cz75a"] = "Som en helautomatisk versjon av CZ75, er CZ75-Auto det ideelle kortsiktige valget for å snu kampen og ta motstanderens våpen. Men med lite ammunisjon i magasinet kreves det sterk avtrekkerdisiplin.",
	["m4a4"] = "Mer nøyaktig, men mindre kraftig enn sin motpart – AK47. M4A4 er den helautomatiske riflen som gjelder for AT-ene.",
	["sg553"] = "Den terroristeksklusive SG553 med sikte er et førsteklasses alternativ til en AK-47 for effektive kamper på langt hold.",
	["decoy_grenade"] = "Når kastet, etterligner lokkegranaten lyden av det kraftigste våpenet du bærer, og skaper illusjonen av at du har ekstra styrker med deg.",
	["incindiary_grenade"] = "Når branngranaten kastes, slipper den løs en kjemisk reaksjon med høy temperatur, som kan brenne alle innenfor dens store eksplosjonsradius.",
	["survival_taser"] = "Et våpen med ekstremt kort rekkevidde, som kan drepe med ett skudd. Kan også brukes til å åpne våpenkasser.",
	["survival_healthshot"] = "Gjenoppretter en del av helsen og gir deg en kort fartsøkning.",
	["survival_vesthelm"] = "Gir deg beskyttelse mot skade.",
	["survival_shield"] = "Et ballistisk politiskjold som kan blokkere store mengder skade før det ødelegges.",
	["survival_parachute"] = "Kan åpnes når du faller, for å forhindre fallskade.",
	["survival_exojump"] = "Øker hopphøyden betraktelig.",
	["survival_c4"] = "Plant hvor som helst på kartet og lag en stor eksplosjon. Kan brukes til å åpne pengeskap.",
	["survival_dronepilot"] = "Gir deg mulighet til å ta kontroll over droner. Bruk nettbrettet til å velge en drone du vil ta over.",
	["survival_exploremoney"] = "Gir deg ekstra penger for hver sekskant du utforsker.",
	["survival_wavemoney"] = "Gir deg ekstra penger hver gang du overlever en utvidelse av faresonen.",
}
