csstring = {
	["cat_pistols"] = "Pistolety",
	["cat_heavy"] = "Ciężkie",
	["cat_smg"] = "PM-y",
	["cat_rifles"] = "Karabiny",
	["cat_grenades"] = "Granaty",
	["cat_gear"] = "Sprzęt",

	["pistol"] = "Pistolet",
	["smg"] = "PM",
	["rifle"] = "Karabin",
	["heavy"] = "Broń ciężka",
	["grenade"] = "Granat",
	["sniperrifle"] = "Karabin snajperski",
	["sniper"] = "Karabin snajperski",
	["shotgun"] = "Strzelba",
	["ak47"] = { name = "AK-47", desc = "Potężny i niezawodny AK-47 to jeden z najbardziej rozpoznawalnych karabinów szturmowych na świecie. Jest najbardziej zabójczy, gdy strzela się krótkimi, kontrolowanymi seriami." },
	["aug"] = { name = "AUG", desc = "Celny i potężny karabin szturmowy AUG z lunetą rekompensuje długi czas przeładowania niskim rozrzutem i wysoką szybkostrzelnością." },
	["awp"] = { name = "AWP", desc = "Broń wysokiego ryzyka i wysokich zysków; okryty niesławą AWP to karabin snajperski rozpoznawalny dzięki swojej charakterystycznej polityce - jeden strzał, jeden trup." },
	["deserteagle"] = { name = "Desert Eagle", desc = "Równie drogi co potężny, Desert Eagle to pistolet-ikona, który ciężko opanować, ale jest zaskakująco celny na dalekim zasięgu." },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Dwie beretty", desc = "Strzelanie z dwóch pistoletów Beretta o pojemnych magazynkach jednocześnie zmniejszy celność i wydłuży czas przeładowania. Z drugiej strony da ci to szansę na postrzelanie z dwóch berett o pojemnych magazynkach naraz." },
	["elite"] = "Dwie beretty",
	["famas"] = { name = "FAMAS", desc = "Tańsza opcja dla graczy bez gotówki. FAMAS efektywnie wypełnia lukę między drogimi karabinami a mniej efektywnymi pistoletami maszynowymi." },
	["fiveseven"] = { name = "Five-SeveN", desc = "Celny i dobrze penetrujący pancerz Five-Seven to drogi, wolny w przeładowaniu pistolet, który nadrabia te wady 20-nabojowym magazynkiem i wybaczalnym odrzutem." },
	["flashbang"] = { name = "Granat błyskowo-hukowy", desc = "Nieśmiercionośny granat hukowy-błyskowy czasowo oślepia każdego w swym polu działania, co czyni go świetnym narzędziem do wykurzania wrogów z ciasnych pomieszczeń. Towarzyszy mu głośny wybuch, który również chwilowo sprawia, że dźwięki kroków są niesłyszalne." },
	["g3sg1"] = { name = "G3SG1", desc = "Kosztowny G3SG1 znacznie spowalnia posiadacza, ale nadrabia to szybkostrzelnością znacznie wyższą od tej w innych karabinach snajperskich." },
	["galilar"] = { name = "Galil AR", desc = "Tańsza opcja wśród trzech unikalnych dla terrorystów karabinów szturmowych - Galil AR to doborowa broń do starć na średnim i dalekim zasięgu." },
	["glock18"] = { name = "Glock-18", desc = "Glock 18 to dogodny pistolet w pierwszej rundzie, który działa najlepiej na nieopancerzonych przeciwnikach i pozwala strzelać serią 3 strzałów." },
	["he_grenade"] = { name = "Granat zaczepny", desc = "Ten zaczepny granat odłamkowy zadaje duże obrażenia na szerokim obszarze, czyniąc go idealnym narzędziem do czyszczenia pomieszczeń." },
	["knife"] = { name = "Nóż", desc = "Nóż jest bronią cichą i możliwą do użycia w każdej chwili. Atak podstawowy to szybkie i lekkie pchnięcie, natomiast atak drugorzędny to mocniejszy zamach, zadający większe obrażenia w starciu. Cios w plecy nagrodzi atakującego cichym i szybkim zabiciem przeciwnika." },
	["knife_t"] = { name = "Nóż", desc = "Nóż jest bronią cichą i możliwą do użycia w każdej chwili. Atak podstawowy to szybkie i lekkie pchnięcie, natomiast atak drugorzędny to mocniejszy zamach, zadający większe obrażenia w starciu. Cios w plecy nagrodzi atakującego cichym i szybkim zabiciem przeciwnika." },
	["knife_gg"] = "Złoty nóż",
	["knife_ghost"] = { name = "Widmowy majcher", desc = "Duchy kochają widmowe noże. Kiedy dostaną jakiś w swoje ręce, uważaj! Będą próbowały cię dźgnąć przy pierwszej okazji. Szkoda, że to tylko duchy, a ich noże nie mogą ranić ludzi..." },
	["m249"] = { name = "M249", desc = "Potężny na otwartych przestrzeniach CKM M249 to idealny wybór dla graczy, którzy skorzy są poświęcić niską szybkostrzelność dla zwiększonej celności i bardzo pojemnego magazynka." },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "Posiadający mniejszy magazynek niż jego niewytłumiony odpowiednik, karabin M4A1-S zapewnia cichsze strzały, mniejszy odrzut i lepszą celność." },
	["mac10"] = { name = "MAC-10", desc = "Praktycznie rzecz biorąc pudełko, z którego lecą kule - pistolet maszynowy MAC-10 szczyci się wysoką szybkostrzelnością, lecz jest również niecelny i ma duży rozrzut." },
	["p90"] = { name = "P90", desc = "Łatwo rozpoznawalna przez unikatowy układ bullpup, P90 to świetna broń do strzelania w ruchu, gdyż posiada bardzo pojemny magazynek i niski odrzut." },
	["smoke_grenade"] = { name = "Granat dymny", desc = "Granat dymny tworzy barierę dymną średniej wielkości. Idealnie nadaje się do ukrywania drużyny przed snajperami albo do odwrócenia uwagi nieprzyjaciela." },
	["ump45"] = { name = "UMP-45", desc = "Niezrozumiałe drugie dziecko w rodzinie pistoletów maszynowych - mały magazynek UMP45 to jedyna wada tej wszechstronnej broni do starć na krótkim zasięgu." },
	["xm1014"] = { name = "XM1014", desc = "XM1014 to potężna strzelba półautomatyczna, która swoją cenę rekompensuje możliwością szybkiego wypełnienia dowolnego pomieszczenia ołowiem." },
	["c4"] = { name = "Ładunek C4", desc = "Stabilny i odporny na większość uderzeń, ten improwizowany plastyczny materiał wybuchowy posiada prędkość detonacji ok. 8000 metrów na sekundę po odpaleniu." },
	["bizon"] = { name = "PP-Bizon", desc = "Pistolet maszynowy Bizon zadaje niewielkie obrażenia, ale posiada unikatowy, pojemny magazynek ślimakowy, który szybko się przeładowuje." },
	["mag7"] = { name = "MAG-7", desc = "Dostępna tylko dla antyterrorystów strzelba Mag-7 zadaje olbrzymie obrażenia z bliska. Magazynkowe przeładowywanie czyni ją świetną bronią taktyczną." },
	["negev"] = { name = "Negev", desc = "Negev to bestia, która potrafi przygwoździć przeciwników dzięki bardzo celnemu ogniowi zaporowemu, jeśli jesteś w stanie znaleźć chwilę czasu, by ją okiełznać." },
	["sawedoff"] = { name = "Obrzyn", desc = "Ten klasyczny obrzyn zadaje ciężkie obrażenia z bliska, jednakże dzięki niskiej celności, wysokiemu rozrzutowi i niskiej szybkostrzelności, lepiej upewnij się, że zabijesz to, w co strzelisz." },
	["tec9"] = { name = "Tec-9", desc = "Idealny pistolet dla terrorysty w ciągłym ruchu - Tec-9 oferuje zabójczą siłę ognia na krótki dystans oraz pojemny magazynek." },
	["taser"] = { name = "Zeus x27", desc = "Idealny do zastawiania pułapek z bliska i w starciach na zamkniętych przestrzeniach jednostrzałowy paralizator Zeus x27 potrafi obezwładnić wroga jednym strzałem." },
	["molotov"] = { name = "Koktajl Mołotowa", desc = "Koktajl Mołotowa to potężna i nieprzewidywalna broń blokująca, która wybucha po rzuceniu na ziemię i rani każdego gracza w swym polu rażenia." },
	["incgrenade"] = "Granat zapalający",
	["decoy"] = "Wabik",
	["hkp2000"] = { name = "P2000", desc = "Celny i łatwy w obsłudze niemiecki pistolet P2000 to dogodna broń w pierwszej rundzie, która działa najlepiej na nieopancerzonych przeciwnikach." },
	["mp7"] = { name = "MP7", desc = "Wszechstronny, ale kosztowny niemiecki pistolet maszynowy MP7 to idealny wybór dla walk na krótkim zasięgu." },
	["mp5sd"] = { name = "MP5-SD", desc = "Często kopiowany, lecz nigdy niezrównany kultowy MP5 jest prawdopodobnie najskuteczniejszym i najpopularniejszym pistoletem maszynowym na całym świecie. Ten wariant SD posiada wbudowany tłumik, czyniąc tym samym tę groźną broń cichuteńką niczym szept." },
	["mp9"] = { name = "MP9", desc = "Stworzony w Szwajcarii doborowy pistolet maszynowy MP9 to ergonomiczna broń polimerowa, ceniona przez prywatne firmy ochroniarskie." },
	["nova"] = { name = "Nova", desc = "Niewielka cena Novy czyni ją bronią dobrą do zasadzek dla drużyny bez wielkiej ilości gotówki." },
	["p250"] = { name = "P250", desc = "Broń o niskim odrzucie i wysokiej szybkostrzelności - P250 to dość tani sposób na pozbycie się opancerzonych wrogów." },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "SCAR-20 to półautomatyczny karabin snajperski, który jest bardzo szybkostrzelny i zadaje wysokie obrażenia na dalekim zasięgu, ale za to znacznie spowalnia posiadacza i trzeba się na niego wykosztować." },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "Powtarzalny karabin snajperski SSG08 nie zadaje wielkich obrażeń, ale posiada wysoki stosunek ceny do efektywności, co czyni go znakomitym karabinem wyborowym w kilku pierwszych rundach." },
	["heavyassaultsuit"] = "Ciężki pancerz",
	["assaultsuit"] = "Kamizelka + hełm",
	["kevlar"] = "Kamizelka kuloodporna",
	["defuser"] = "Zestaw do rozbrajania",
	["cutters"] = "Zestaw ratunkowy",
	["revolver"] = { name = "Rewolwer R8", desc = "Rewolwer R8 to bardzo celna broń, która zadaje ogromne obrażenia, ale kosztem długiego czasu pociągnięcia spustu. Szybkie strzelanie poprzez ręczne napinanie kurka może się okazać lepszym wyjściem, gdy wymagane jest dostarczenie pełnej mocy obalającej na krótkim dystansie." },
	["usp_silencer"] = { name = "USP-S", desc = "Ulubieniec graczy z Counter-Strike Source - pistolet USP posiada zdejmowalny tłumik, który wygłusza strzały i zmniejsza odrzut." },
	["knifebayonet"] = { name = "Bagnet", desc = "Broń, której konstrukcja i wygląd od czasów II wojny światowej się niewiele zmieniła - bagnet wciąż ma swoje miejsce we współczesnych strategiach militarnych. Szarże z bagnetami były efektywnie używane podczas II wojny w Zatoce Perskiej, a także wojny w Afganistanie." },
	["knifeflip"] = { name = "Nóż składany", desc = "Ten nóż składany posiada odgięte do tyłu ostrze w stylu perskim zakończone szpicem. Nawet jeśli ten szpic wygląda na łamliwy, to ogólna budowa noża wydaje się być zaskakująco trwała." },
	["knifegut"] = { name = "Nóż z hakiem", desc = "Najbardziej charakterystycznym atutem tego noża jest wystający hak umieszczony po tępej stronie ostrza. Początkowo używany do obdzierania upolowanej zwierzyny ze skóry, hak ten jest teraz także używany do bezproblemowego przecinania włóknistych materiałów, takich jak liny, sieci czy pasy bezpieczeństwa." },
	["knifecss"] = { name = "Klasyczny nóż", desc = "Krawędź tego klasycznego noża z serii Counter-Strike została wykonana ze stellitu, a precyzyjne połączenie wciskowe z tytanowym płazem oraz grzbietem sprawia, że te elementy są do siebie idealnie dopasowane. Rękojeść składa się ze skamieniałej kości słoniowej mastodonta otulonej włóknem węglowym." },
	["knifem9"] = { name = "Bagnet M9", desc = "Oto bagnet M-9. Z założenia miał być doczepiany do karabinów, ale spisuje się też w walce w przestrzeniach zamkniętych." },
	["knifekaram"] = { name = "Karambit", desc = "Karambit to nóż o ostrzu przypominającym pazur tygrysa. Został on stworzony jako część sztuki walki zwanej silat, popularnej w Azji Południowo-Wschodniej. Nóż ten charakteryzuje się odwróconą rękojeścią, z palcem wskazującym przełożonym przez otwór." },
	["knifetactical"] = { name = "Nóż myśliwski", desc = "Nóż zaprojektowany dla współczesnych zastosowań taktycznych, którego ostrze dobrze nadaje się dla potrzeb bojowych i utylitarnych. Unikalne zakończenie typu Tanto pozwala na maksymalną penetrację nawet przez najtwardsze rodzaje powierzchni." },
	["knife_butterfly"] = { name = "Nóż motylkowy", desc = "To wyjątkowo zaprojektowany balisong, szerzej znany jako nóż motylkowy. Broń charakteryzuje się swobodnie obracającym się ostrzem, które daje możliwość błyskawicznego rozłożenia i złożenia. Z tego właśnie powodu noże motylkowe są zakazane w wielu krajach." },
	["partypopper"] = "Wystrzałowe Konfetti!",
	["knife_falchion_advanced"] = { name = "Nóż falcjon", desc = "Współczesny hołd dla miecza falcjonu, to ostrze o mocnej końcówce posiada lekko zakrzywioną krawędź tnącą." },
	["knife_push"] = { name = "Sztylety Cienia", desc = "Zaprojektowane w celu efektywnego zadawania ran. Pchnięcie tymi sztyletami jest tak proste, jak uderzenie pięścią." },
	["knife_survival_bowie"] = { name = "Nóż Bowie", desc = "Ten nóż Bowie typu full-tang z grzbietem głowni wyposażonym w piłę jest stworzony do ciężkich zastosowań w brutalnych survivalowych sytuacjach." },
	["healthshot"] = "Zastrzyk wzmacniający",
	["tagrenade"] = "Granat taktyczny",
	["exploding_barrel"] = "Wybuchająca beczka",
	["snowball"] = "Śnieżka",
	["stompdamagekillstring"] = "miażdży twoją czaszkę",
	["dangerzone"] = "Strefa zagrożenia",
	["autosentry"] = "Działko strażnicze",
	["fists"] = "Pięści",
	["tablet"] = "Tablet",
	["breachcharge"] = "Ładunek wyważający",
	["bumpmine"] = "Mina skokowa",
	["axe"] = { name = "Toporek", desc = "Topór – ciężki i zawsze pod ręką – jest z jednej strony ostry, a z drugiej tępy. Użyj ataku podstawowego, by wykonać zamach i zadać mniejsze obrażenia lub – jako atak alternatywny – rzuć nim, by zadać dużo większe obrażenia. W końcu czego trzeba strzelcowi do zestrzelenia cietrzewia drzemiącego w dżdżysty dzień na drzewie?" },
	["hammer"] = { name = "Młotek", desc = "Młotek to narzędzie zarówno do naprawy, jak i niszczenia rzeczy. Użyj ataku podstawowego, by wykonać zamach i zadać mniejsze obrażenia lub – jako atak alternatywny – rzuć nim, by zadać dużo większe obrażenia. Kiedy twój jedyny sprzęt to młotek, to wszystko wygląda jak gwóźdź." },
	["spanner"] = { name = "Klucz", desc = "Klucz francuski zwykle stosuje się do wkręcania rzeczy, ale spokojnie możesz uderzyć nim kogo- lub cokolwiek chcesz. Użyj ataku podstawowego, by wykonać cios i zadać mniejsze obrażenia lub – jako atak alternatywny – rzuć nim, by zadać dużo większe obrażenia. Pamiętaj tylko, żeby nie przychodzić na strzelaninę z samym kluczem w ręku..." },
	["tripwirefire"] = "TrapFire",
	["knife_cord"] = { name = "Nóż paracord", desc = "Ten nieskładany nóż survivalowy został zaprojektowany, by sprostał zadaniu zarówno jako broń, jak i narzędzie do zastawiania pułapek, polowania na zwierzynę czy wycinania listowia. Rękojeść jest owinięta wielofunkcyjną linką spadochronową typu paracord." },
	["knife_canis"] = { name = "Nóż survivalowy", desc = "Ten wielozadaniowy nóż taktyczny posiada częściowo ząbkowane ostrze do rozrywania tworzyw pokroju kości i tkanek, a także ostry hak do patroszenia. Rękojeść z kompozytu została przykręcona do ostrza za pomocą śrub z sześciokątnym łbem." },
	["knife_ursus"] = { name = "Ursus", desc = "Ten nóż w stylu tanto wykorzystywany przez wielu adeptów sztuki przetrwania posiada fasetowane ostrze, pełny trzpień i lekko zakrzywioną głowicę. Zero bzdur i ruchomych części - po prostu niezawodne ostrze, które jest gotowe do pracy." },
	["knife_gypsy_jackknife"] = { name = "Navaja", desc = "Ten nóż składany z błyszczącą rękojeścią przypominającą marmur skrywa małe, lecz śmiertelne, smukłe ostrze." },
	["knife_outdoor"] = { name = "Nóż nomada", desc = "Ten ergonomiczny, taktyczny nóż myśliwski posiada dodatkowe elementy kompozytowe na rękojeści oraz szerokie ostrze o mocnej budowie, które przydaje się do rozcinania różnego rodzaju tworzyw." },
	["knife_widowmaker"] = { name = "Szpon", desc = "Ten karambit z rękojeścią z kości słoniowej posiada mosiężne nity i ostrze o ząbkowanym wykończeniu, które tnie, wchodząc i rozrywa, wychodząc." },
	["knife_stiletto"] = { name = "Sztylet", desc = "Na przestrzeni dziejów najważniejszy obiekt wielu zażartych sporów (i regulacji), ten sprężynowy nóż w stylu włoskiego sztyletu posiada ostrze mogące zostać niemal natychmiastowo rozłożone po naciśnięciu przycisku." },
	["knife_skeleton"] = { name = "Nóż szkieletowy", desc = "Ten nóż o szkieletowym trzpieniu został owinięty taśmą na rękojeści w celu uzyskania lepszej przyczepności. Otwór pozwala na włożenie palca dla zwiększenia stabilności i bezpieczeństwa." },
	["firebomb"] = { name = "Bomba zapalająca", desc = "Bomba zapalająca jest potężną eksperymentalną bronią, która po rzuceniu na ziemię wytwarza reakcję chemiczną o wysokiej temperaturze będącej w stanie spalić każdego w swym szerokim polu działania." },
	["diversion"] = { name = "Urządzenie dywersyjne", desc = "Urządzenie dywersyjne po rzuceniu oznaczy sektor na tablecie, tworząc iluzję większej liczby wrogów." },
	["frag_grenade"] = { name = "Granat odłamkowy", desc = "Wybuch tego eksperymentalnego granatu odłamkowego potrafi zadać poważne obrażenia na dużym obszarze. Dzięki temu idealnie nadaje się zarówno do działań ofensywnych, jak i defensywnych." },
	["shield"] = { name = "Tarcza balistyczna", desc = "Sprzęt ochronny służący do odbijania lub pochłaniania obrażeń balistycznych i chroniący noszącego przed pociskami różnego kalibru." },
	["zone_repulsor"] = { name = "Urządzenie rozpraszające", desc = "Prototypowe urządzenie chroniące przed promieniowaniem cząstek stałych" },
	["cz75a"] = "W pełni automatyczna wersja CZ75, najlepsza na krótkim dystansie, pozwala zmienić losy walki i zdobyć broń przeciwnika. Przy swoim małym magazynku wymaga jednak celnych strzałów i pilnowania liczby nabojów.",
	["m4a4"] = "Celniejszy, ale zadający mniej obrażeń, co swój odpowiednik - AK-47, M4A4 to najczęściej wybierany przez antyterrorystów automatyczny karabin szturmowy.",
	["sg553"] = "Dostępny wyłącznie dla terrorystów SG553 z lunetą to alternatywa dla AK-47 dzięki możliwości efektywnego rażenia na dalekim zasięgu.",
	["decoy_grenade"] = "Wabik po rzuceniu wytwarza dźwięk najsilniejszej broni, jaką obecnie posiadasz, tworząc iluzję dodatkowych posiłków.",
	["incindiary_grenade"] = "Granat zapalający po rzuceniu wytwarza reakcję chemiczną o wysokiej temperaturze, która jest w stanie spalić każdego w swym szerokim polu działania.",
	["survival_taser"] = "Broń o bardzo krótkim zasięgu, która może zabić jednym strzałem. Może być również używana do otwierania skrzyń z bronią.",
	["survival_healthshot"] = "Przywraca część twojego zdrowia i zapewnia chwilową premię do szybkości poruszania się.",
	["survival_vesthelm"] = "Zapewnia odporność na obrażenia.",
	["survival_shield"] = "Tarcza balistyczna, która przed zniszczeniem potrafi pochłonąć wiele obrażeń.",
	["survival_parachute"] = "Można otworzyć w trakcie spadania, aby uniknąć obrażeń od upadku.",
	["survival_exojump"] = "Znacznie zwiększają wysokość skoku.",
	["survival_c4"] = "Podłóż gdziekolwiek na mapie, aby spowodować dużą eksplozję. Może zostać użyty w celu otwarcia sejfów.",
	["survival_dronepilot"] = "Przyznaje możliwość przejęcia kontroli nad dronami. Użyj tabletu, by wybrać drona do przejęcia.",
	["survival_exploremoney"] = "Przyznaje dodatkowe pieniądze za każdy zbadany sektor.",
	["survival_wavemoney"] = "Przyznaje dodatkowe pieniądze za każdą przetrwaną falę rozszerzającej się strefy zagrożenia.",
}
