csstring = {
	["cat_pistols"] = "Pistoler",
	["cat_heavy"] = "Hagel- och kulsprutegevär",
	["cat_smg"] = "K-Pistar",
	["cat_rifles"] = "Gevär",
	["cat_grenades"] = "Granater",
	["cat_gear"] = "Utrustning",

	["pistol"] = "Pistol",
	["smg"] = "SMG",
	["rifle"] = "Gevär",
	["heavy"] = "Tungt",
	["grenade"] = "Granat",
	["sniperrifle"] = "Prickskyttegevär",
	["sniper"] = "Krypskytt",
	["shotgun"] = "Hagelgevär",
	["ak47"] = { name = "AK-47", desc = "Kraftfull och tillförlitlig. AK-47:an är en av de populäraste automatkarbinerna i världen. Den är som dödligast när den avfyrar korta och kontrollerade salvor." },
	["aug"] = { name = "AUG", desc = "Kraftfull och träffsäker, AUG automatkarbin med kikarsikte kompenserar sin långa omladdningstid med liten spridning och hög eldgivningshastighet." },
	["awp"] = { name = "AWP", desc = "Hög risk och hög utdelning, den ökända AWP känns igen av sin signaturrapport samt sin \"ett skott, en död\"-policy." },
	["deserteagle"] = { name = "Desert Eagle", desc = "Lika dyr som kraftfull. Desert Eagle är en ikonisk pistol som är svår att bemästra men förvånansvärt pricksäker på långa avstånd." },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Dual Berettas", desc = "Att avfyra två stycken Berettas samtidigt sänker precisionen och ökar omladdningstiden. På den ljusa sidan; du får skjuta två Berettas samtidigt." },
	["elite"] = "Dual Berettas",
	["famas"] = { name = "FAMAS", desc = "Ett billigt alternativ för fattiga spelare. FAMAS fyller effektivt nischen mellan dyrare gevär och mindre effektiva kulsprutor." },
	["fiveseven"] = { name = "Five-SeveN", desc = "Mycket träffsäker och pansarbrytande. Den dyra Five-Seven laddar om långsamt men kompenserar med ett generöst magasin på 20 rundor och förlåtande rekyl." },
	["flashbang"] = { name = "Chockgranat", desc = "Den icke-dödliga distraktionshandgranaten förblindar alla temporärt som befinner sig inom dess verkningsradie, vilket gör den perfekt för att rensa ut slutna områden. Dess högljudda explosion döljer också temporärt ljudet av fotsteg." },
	["g3sg1"] = { name = "G3SG1", desc = "Den dyra G3SG1 sänker förflyttningshastigheten märkbart men kompenserar med en eldgivningshastighet som är högre än de flesta andra prickskyttegevär." },
	["galilar"] = { name = "Galil AR", desc = "Ett mindre dyrt alternativ bland de terroristexklusiva automatkarbinerna. Galil AR är ett funktionsdugligt vapen i medel-långdistansstrid." },
	["glock18"] = { name = "Glock-18", desc = "Glock 18 är en funktionsduglig pistol som fungerar bäst mot opansrade fiender och kan avfyra tre-skottsalvor." },
	["he_grenade"] = { name = "Högexplosiv granat", desc = "Den högexplosiva splittergranaten gör stor skada i ett stort område, vilket gör den idealisk för att rensa fientliga rum." },
	["knife"] = { name = "Kniv", desc = "Kniven är tyst och alltid tillgänglig. Den har en snabb primär attack som gör lite skada och en långsam sekundär attack som gör hög skada. Rygghugg gör att tysta spelare kan döda sina fiender i ett enda slag." },
	["knife_t"] = { name = "Kniv", desc = "Tyst och alltid nära till hands. Kniven har en snabb svag attack och en andra långsammare attack som gör mer skada. För tysta spelare är ett enda hugg i fiendens rygg allt som behövs för att omedelbart döda honom." },
	["knife_gg"] = "Guldkniv",
	["knife_ghost"] = { name = "Spökkniv", desc = "Spöken älskar spökknivar. När de får tag på en, se upp! De kommer att försöka hugga dig direkt. Synd att de är spöken och att spökknivar inte kan skada folk..." },
	["m249"] = { name = "M249", desc = "En stark lätt kulspruta för öppna områden, M249 är det perfekta valet för spelare som är villiga att ha långsam eldgivningshastighet men bättre träffsäkerhet och större ammunitionskapacitet." },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "Den ljuddämpade M4A1 har ett mindre magasin än sin icke-dämpade motsvarighet, och levererar tystare skott med svagare rekyl och bättre träffsäkerhet." },
	["mac10"] = { name = "MAC-10", desc = "I praktiken en låda som sprutar kulor. MAC-10 SMG har hög eldgivningshastighet, men stor spridning och kraftig rekyl." },
	["p90"] = { name = "P90", desc = "P90 är lätt igenkännbar för sin unika bullpup-design, och är ett bra vapen att skjuta med under förflyttning tack vare svag rekyl och dess stora magasin." },
	["smoke_grenade"] = { name = "Rökgranat", desc = "Rökgranaten skapar en mediumstor rökridå. Den kan användas för att effektivt dölja ditt lag från krypskyttar, eller bara som distraktion." },
	["ump45"] = { name = "UMP-45", desc = "Det missförstådda mittenbarnet i kulsprutefamiljen. UMP45:s lilla magasin är den enda olägenheten i ett för övrigt mångsidigt automatvapen för närstrid." },
	["xm1014"] = { name = "XM1014", desc = "XM1014 är ett kraftfullt helautomatiskt hagelgevär som rättfärdigar sitt höga pris med förmågan att kunna måla ett rum med hagel snabbt." },
	["c4"] = { name = "C4", desc = "Stabil och resistent mot de flesta fysiska chocker, den här improviserade sprängdegen har en detonationshastighet på över 8 000 meter per sekund när den antänds." },
	["bizon"] = { name = "PP-Bizon", desc = "Bizon SMG gör lite skada, men har ett unikt designat trummagasin med hög kapacitet och kan laddas om fort." },
	["mag7"] = { name = "MAG-7", desc = "Den antiterroristexklusiva Mag-7 utdelar förödande skada vid närstrid. Dess snabba magasinomladdningar gör den till ett bra taktiskt val." },
	["negev"] = { name = "Negev", desc = "Negev är ett odjur som kan hålla fienden i schack med dess precisa nedhållande eldkraft, förutsatt att du har tid till att få kontroll på den." },
	["sawedoff"] = { name = "Sawed-Off", desc = "Det klassiska avsågade hagelgeväret gör väldigt mycket skada på nära håll, men med sin dåliga träffsäkerhet, stora spridning och långsamma eldgivningshastighet så är det bäst att du dödar det du träffar." },
	["tec9"] = { name = "Tec-9", desc = "En ideal pistol för terrorister på resande fot, Tec-9 är dödlig på nära håll och har hög magasinskapacitet." },
	["taser"] = { name = "Zeus x27", desc = "Perfekt på nära håll för bakhåll och möten i slutna utrymmen. x27 Zeus med enkelskott är kapabel till att oskadliggöra en fiende med en enda träff." },
	["molotov"] = { name = "Molotov", desc = "Molotov är ett kraftfullt och oförutsägbart områdesnekande vapen som fattar eld när det kastas på marken, vilket skadar spelare inom dess radie." },
	["incgrenade"] = "Brandgranat",
	["decoy"] = "Lockgranat",
	["hkp2000"] = { name = "P2000", desc = "Pricksäker och kontrollerbar. Den tysktillverkade P2000 är en funktionsduglig pistol som fungerar bäst mot opansrade fiender." },
	["mp7"] = { name = "MP7", desc = "Mångsidig men dyr. Den tysktillverkade MP7 SMG är det perfekta valet för närstrider." },
	["mp5sd"] = { name = "MP5-SD", desc = "Den har ofta imiterats men inget har kunnat mäta sig med den ikoniska MP5:an, som kanske är den mångsidigaste och populäraste kulsprutepistolen i världen. Denna SD-variant har en inbyggd ljuddämpare, vilket gör ett redan imponerande vapen knäpptyst." },
	["mp9"] = { name = "MP9", desc = "Tillverkad i Schweiz, den banbrytande MP9 SMG är ett ergonomisk polymervapen som föredras av privata säkerhetsföretag." },
	["nova"] = { name = "Nova", desc = "Novas låga pris gör den till ett bra bakhållsvapen för ett fattigt lag." },
	["p250"] = { name = "P250", desc = "Ett skjutvapen med svag rekyl och hög eldgivningshastighet. P250 är ett relativt billigt val mot bepansrade motståndare." },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "SCAR-20 är ett halvautomatiskt prickskyttegevär som har hög eldgivningshastighet och kraftfull långdistansskada, men ger trögare förflyttning och har en stor prislapp." },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "SSG08 är ett prickskyttegevär som utdelar låg skada men är mycket kostnadseffektivt, vilket gör den till ett smart val för tidiga långdistansstrider." },
	["heavyassaultsuit"] = "Tung attackdräkt",
	["assaultsuit"] = "Kevlar + hjälm",
	["kevlar"] = "Kevlarväst",
	["defuser"] = "Desarmeringskit",
	["cutters"] = "Räddningskit",
	["revolver"] = { name = "R8 Revolver", desc = "R8-revolvern levererar hög träffsäkerhet och kraftfulla skott till bekostnad av ett längre avtryckardrag. Att skjuta snabbt med handen på hanen kan vara det bästa alternativet när eldkraft på väldigt nära håll krävs." },
	["usp_silencer"] = { name = "USP-S", desc = "En favorit bland fansen i Counter Strike: Source, den ljuddämpade USP-pistolen har en borttagbar ljuddämpare som gör att skotten ger svagare rekyl och dämpar oönskat oljud." },
	["knifebayonet"] = { name = "Bajonett", desc = "Bajonettens design har förändrats relativt lite sedan andra världskriget, och har fortfarande en plats i modern militärstrategi. Bajonettanfall har fortsatt varit effektiva så sent som i Kuwaitkriget och kriget i Afghanistan." },
	["knifeflip"] = { name = "Fällkniv", desc = "Fällkniven ståtar med en bakåtsvept klinga i persisk stil med en spetsig udd. Medan udden i sig må vara ömtålig, är den allmänna utformningen av fällknivens design förvånansvärt hållbar." },
	["knifegut"] = { name = "Buköppnare", desc = "Det mest märkbara kännetecknet på en magkniv är magkroken på klingans rygg. Magkniven blev populär som ett hjälpmedel för att tömma villebråd, men är även effektiv på att enkelt skära igenom fibrigt material såsom rep, vävband eller säkerhetsbälten." },
	["knifecss"] = { name = "Klassisk kniv", desc = "En klassiker i Counter-Strike-serien. Eggen på denna kniv har friktionssvetsat Stellite som hålls på plats tack vare dess precisa passform med titanet på bladets rygg och sida. Handtaget är gjort av fossilerat mastodontelfenben som hålls i ett kolfiberhölje." },
	["knifem9"] = { name = "M9-bajonett", desc = "Det här är M-9-bajonetten. Ursprungligen avsedd för att sättas fast på ett gevär, men är också väl anpassad för närstrid." },
	["knifekaram"] = { name = "Karambit", desc = "Med sin böjda klinga som härmar en tigers klo, utvecklades karambiten som en del av den sydostasiatiska kampsportsdisciplinen silat. Kniven används oftast med ett omvänt grepp, med fingerringen på pekfingret." },
	["knifetactical"] = { name = "Huntsmankniv", desc = "En kniv designad för moderna taktiska syften vars blad är väl lämpat för ett urval av både stridsmässiga och praktiska behov. Den unika Tanto-spetsen tillåter maximal penetrering genom till och med den tuffaste av ytor." },
	["knife_butterfly"] = { name = "Butterflykniv", desc = "Det är är en egendesignad balisong, vanligen benämnd butterflykniv. Detta vapens definierande karaktärsdrag är den solfjäderlika öpnningen av ett fritt roterande blad, som tillåter snabb användning eller döljande. Som resultat av detta är butterflyknivar olagliga i många länder." },
	["partypopper"] = "Party Popper!",
	["knife_falchion_advanced"] = { name = "Falchionkniv", desc = "Detta blad har en böjd kant, och är en modern hyllning till falchionsvärdet." },
	["knife_push"] = { name = "Skuggdolkar", desc = "En knogdolk som designats för effektiv brutalitet är lika lätt att använda som att slåss för hand." },
	["knife_survival_bowie"] = { name = "Bowiekniv", desc = "Denna Bowiekniv är utformad för hårt bruk i brutala överlevnadssituationer." },
	["healthshot"] = "Hälsospruta",
	["tagrenade"] = "Taktisk medvetenhetsgranat",
	["exploding_barrel"] = "Explosiv tunna",
	["snowball"] = "Snöboll",
	["stompdamagekillstring"] = "krossade din skalle",
	["dangerzone"] = "Farozon",
	["autosentry"] = "Automatiskt vaktgevär",
	["fists"] = "Knytnävar",
	["tablet"] = "Platta",
	["breachcharge"] = "Sprängladdning",
	["bumpmine"] = "Studsmina",
	["axe"] = { name = "Yxa", desc = "Heavy and always available, the axe has a sharp side and a dull side. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. How much wood would a woodchuck chuck?" },
	["hammer"] = { name = "Hammare", desc = "The hammer is available for fixing things and breaking things. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. If all you have is a hammer, everything looks like a nail." },
	["spanner"] = { name = "Skiftnyckel", desc = "A wrench is typically used to apply torque when turning objects, but you can hit anything with it for low-damage primary attack or throw it for a high-damage secondary attack. Bringing a wrench to a firefight is a recipe for screwing up." },
	["tripwirefire"] = "Eldfälla",
	["knife_cord"] = { name = "Paracordkniv", desc = "Denna överlevnadskniv med ett fast blad är designad för att kunna användas som både ett vapen och ett verktyg, och kan användas till att göra fällor, jakt, eller att ta dig igenom snårig terräng. Skaftet är inlindat i en flerfunktionell paracord." },
	["knife_canis"] = { name = "Överlevnadskniv", desc = "Denna flerfunktionella taktiska kniv har en sågtandad egg för att såga igenom material som ben eller fiber, samt en buköppnare. Skaftet, som är gjort av ett kompositmaterial, har bultats fast med sexkantsmuttrar." },
	["knife_ursus"] = { name = "Ursuskniv", desc = "Denna tanto-liknande överlevnadskniv har ett fasetterat blad och full tånge, samt en pommel. Inget krångel, inga rörliga delar - endast ett pålitligt blad som är redo att arbeta." },
	["knife_gypsy_jackknife"] = { name = "Navajakniv", desc = "Denna fällkniv med ett emaljerat marmorhandtag döljer ett litet men illvilligt avsmalnande blad." },
	["knife_outdoor"] = { name = "Nomad-kniv", desc = "Denna ergonomiska taktiska jaktkniv har ett brett och stadigt blad som kan låsas fast i dess kompositskaft, och är användbar till att skära och bryta isär material." },
	["knife_widowmaker"] = { name = "Talonkniv", desc = "Denna karambit med ett elfenbenshandtag har mässingnitar och en sågtandad rygg, så den skär på vägen in, och sliter på vägen ut." },
	["knife_stiletto"] = { name = "Stilettkniv", desc = "Historiskt har stiletten varit omtvistad och reglerad, denna italienska stilettkniv har ett fjäderladdat blad som kan tas fram nästan omedelbart genom ett tryck på en spärr." },
	["knife_skeleton"] = { name = "Skeleton-kniv", desc = "Denna avskalade kniv med full tang har ett tejpinlindat skaft för att förbättra greppvänligheten. Ett finger kan träs igenom hålet för att göra kniven säkrare och stabilare." },
	["firebomb"] = { name = "Brandbomb", desc = "Brandbomben är ett kraftfullt experimentellt vapen som ger upphov till mycket varma flammor när den kastas mot marken, som bränner alla inom ett stort område." },
	["diversion"] = { name = "Diversionsapparat", desc = "När diversionsapparaten kastas mot en plats kommer den att lysa upp sektorer på plattor, vilket skapar illusionen att det finns fiender där." },
	["frag_grenade"] = { name = "Splittergranat", desc = "Den experimentella splittergranaten kan göra extremt mycket skada i ett större område, vilket gör den ideal för både offensiva och defensiva syften." },
	["shield"] = { name = "Kravallsköld", desc = "En skyddsanordning utformad för att avleda eller absorbera ballistisk skada och skydda bäraren från en rad projektilkalibrer." },
	["zone_repulsor"] = { name = "Avskärmningsenhet", desc = "Prototyp av en radial avskärmningsenhet mot partikelutsläpp" },
	["cz75a"] = "CZ75-Auto är en helautomatisk variant av CZ75-pistolen, och är det ideala valet för att snabbt kunna döda fienden och ta dennes vapen. Men med väldigt lite ammo i magasinet krävs också ett mer sparsamt användande av avtryckaren.",
	["m4a4"] = "Mer precis men mindre skadlig är sin motsvarighet AK-47. M4A4 är antiterroristernas val när det gäller helautomatiska automatkarbiner.",
	["sg553"] = "Den terroristexklusiva och kikarutrustade SG553 är ett effektivt alternativ till AK47:an för långdistansstrider.",
	["decoy_grenade"] = "När lockgranaten kastas härmar den ljudet av det mest kraftfulla vapnet du bär, vilket skapar illusionen av extra stödtrupper.",
	["incindiary_grenade"] = "När brandgranaten kastas, släpper den lös en kemisk reaktion med hög temperatur som kan bränna alla inom dess stora sprängradie.",
	["survival_taser"] = "Ett närstridsvapen som kan döda med ett skott. Kan även användas till att öppna vapenlådor.",
	["survival_healthshot"] = "Återställer en del av din hälsa och ger en tillfällig hastighetsökning.",
	["survival_vesthelm"] = "Ger skydd mot skada.",
	["survival_shield"] = "En kravallsköld som kan blockera en stor mängd skada innan den förstörs.",
	["survival_parachute"] = "Kan fällas ut när du faller för att förhindra fallskador.",
	["survival_exojump"] = "Ökar din hopphöjd avsevärt.",
	["survival_c4"] = "Placera den var som helst på banan för att orsaka en stor explosion. Kan användas till att öppna kassaskåp.",
	["survival_dronepilot"] = "Ger dig möjligheten att ta kontrollen över drönare. Använd plattan för att välja en drönare att ta över.",
	["survival_exploremoney"] = "Ger extra pengar för varje hexagon som utforskas.",
	["survival_wavemoney"] = "Ger extra pengar varje gång du överlever en farozonsvåg.",
}
