csstring = {
	["cat_pistols"] = "Pistoolit",
	["cat_heavy"] = "Raskaat",
	["cat_smg"] = "Konepistoolit",
	["cat_rifles"] = "Kiväärit",
	["cat_grenades"] = "Kranaatit",
	["cat_gear"] = "Varusteet",

	["ak47"] = { name = "AK-47", desc = "Voimakas ja aina yhtä luotettava AK-47 on eräs maailman suosituimpia rynnäkkökivääreitä. Se on tappavimmillaan pieniä, hallittuja tulipurskeita ammuttaessa." },
	["aug"] = { name = "AUG", desc = "AUG on tehokas ja tarkka kiikarirynnäkkökivääri, joka kompensoi pitkiä latausaikojaan tappavalla tarkkuudellaan ja suurella tulinopeudellaan." },
	["awp"] = { name = "AWP", desc = "Suuren riskin, mutta myös suuren palkkion antava, (surullisen)kuuluisa AWP on tunnistettavissa uniikista äänestään ja yksi osuma, yksi tappo -toimintaperiaatteestaan." },
	["deserteagle"] = { name = "Desert Eagle", desc = "Yhtä kallis kuin tehokaskin, Desert Eagle on ikoninen pistooli, joka on vaikea hallita, mutta on hyvinkin tarkka pitkällä matkalla." },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Tupla-Berettat", desc = "Kahdella isolippaisella Berettalla yhtä aikaa ampuminen vähentää tarkkuutta ja hidastaa lataamista. Mutta toisaalta pääset ampumaan kahdella isolippaisella Berettalla yhtä aikaa." },
	["elite"] = "Tupla-Berettat",
	["famas"] = { name = "FAMAS", desc = "FAMAS on kitupiikin halpa vaihtoehto, joka täyttää sopivan raon kalliimpien kiväärien ja tehottomien konepistoolien välillä." },
	["fiveseven"] = { name = "Five-SeveN", desc = "Tarkka ja panssarit läpäisevä Five-Seven on kallis, hitaasti lataava pistooli, jota on kompensoitu 20 panoksen lippaalla ja anteeksiantavalla potkaisulla." },
	["flashbang"] = { name = "Valokranaatti", desc = "Valokranaatti ei tapa, mutta sokaisee hetkellisesti jokaisen iskukantaman alueella olevan, ja on siksi täydellinen vihollisen savustamiseen ulos ahtaista paikoista. Sen kova räjähdys peittää hetkellisesti myös askelten äänet." },
	["g3sg1"] = { name = "G3SG1", desc = "Hintava G3SG1 hidastaa matkantekoasi huomattavasti, mutta ampuu paljon nopeammin kuin muut kiikarikiväärit." },
	["galilar"] = { name = "Galil AR", desc = "Halvempi vaihtoehto terroristien rynnäkkökiväärien joukossa, Galil AR on toimiva ase keskipitkästä pitkään matkaan." },
	["glock18"] = { name = "Glock-18", desc = "Glock 18 on hyödyllinen ensimmäisen kierroksen pistooli, joka pystyy ampumaan kolmen ammuksen sarjoja ja tehoaa parhaiten vihollisiin, joilla ei ole Kevlar-liiviä." },
	["he_grenade"] = { name = "HE-kranaatti", desc = "Voimakas sirpalekranaatti kylvää tuhoa laajalle alueelle, ja on täydellinen suljettujen tilojen tyhjentämiseen vihollisista." },
	["knife"] = { name = "Veitsi", desc = "Taisteluveitsi on hiljainen ja aina saatavilla. Sen tavallinen hyökkäys on nopea mutta heikko, vaihtoehtoinen hyökkäys tappavampi. Hiljaiset pelaajat saavat selkäänpuukottamalla välittömän tapon." },
	["knife_t"] = { name = "Veitsi", desc = "Taisteluveitsi on hiljainen ja aina saatavilla. Sen tavallinen hyökkäys on nopea mutta heikko, vaihtoehtoinen hyökkäys tappavampi. Hiljaiset pelaajat saavat selkäänpuukottamalla välittömän tapon." },
	["knife_gg"] = "Kultaveitsi",
	["knife_ghost"] = { name = "Aaveveitsi", desc = "Kummitukset rakastavat kummitusveitsiä. Ole valppaana, kun ne saavat käsiinsä sellaisen! Ne yrittävät puukottaa ensimmäisen tilaisuuden tultua. Harmi kyllä, ne ovat kummituksia, eikä kummitusveitsetkään pysty vahingoittamaan ihmisiä...." },
	["m249"] = { name = "M249", desc = "Tehokas ja avoimiin tiloihin soveltuva M249-konekivääri on täydellinen pelaajille, jotka haluavat lisää tarkkuutta ja suuremman ammusmäärän tulitusnopeuden kustannuksella." },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "Äänenvaimentimella varustettu M4A1 on pienilippaisempi ja hiljaisempi vaihtoehto, joka takaa tarkat laukaukset." },
	["mac10"] = { name = "MAC-10", desc = "MAC-10 on käytännössä laatikko, joka syytää luoteja, sillä se räiskii luoteja nopeaan tahtiin hyvin epätarkasti ja kovalla potkaisulla." },
	["p90"] = { name = "P90", desc = "P90 on helppo tunnistaa ainutlaatuisesta bullpup-mallistaan. Se sopii ison lippaansa ja vähäisen potkaisunsa vuoksi juostessa ampumiseen." },
	["smoke_grenade"] = { name = "Savukranaatti", desc = "Savukranaatti tuottaa keskikokoisen savuverhon. Sen avulla voit suojella tiimiäsi tehokkaasti tarkka-ampujilta, tai vaikka tehdä harhautuksia." },
	["ump45"] = { name = "UMP-45", desc = "UMP45 on konepistoolien keskivertoa. Sen pieni lipas on aseen ainoa huono puoli, muuten se on hyvin monipuolinen automaattiase lähitaisteluihin." },
	["xm1014"] = { name = "XM1014", desc = "XM1014 on tehokas täysautomaattihaulikko, jonka hintalappu takaa huoneen täynnä lyijyä hetkessä." },
	["c4"] = { name = "C4-räjähde", desc = "Tämä improvisoitu muoviräjähde on vakaa ja kestää useimmat fyysiset rasitukset, ja sytytettäessä sen räjähdysnopeus on yli 8 000 m/s." },
	["bizon"] = { name = "PP-Bizon", desc = "Bizon-konepistooli ei tarjoa suurta tulivoimaa, mutta siinä on ainutlaatuinen, tilava rumpulipas, joka lataa nopeasti." },
	["mag7"] = { name = "MAG-7", desc = "Erikoisjoukkojen Mag-7 takaa tappavan annoksen vahinkoa lähikantamalta. Sen nopea lipaslataus tekee siitä taktisen vaihtoehdon." },
	["negev"] = { name = "Negev", desc = "Negev pitää viholliset loitolla tarkalla tulituksellaan, kunhan sinulla on tarpeeksi aikaa saada se hallintaan." },
	["sawedoff"] = { name = "Katkaistu haulikko", desc = "Klassinen katkaistu haulikko tekee hurjan määrän vahinkoa lähietäisyydeltä, mutta kun ase on epätarkka, ampuu hitaasti ja levittää haulit ympäriinsä, niin ensimmäisen osuman on paras tappaa." },
	["tec9"] = { name = "Tec-9", desc = "Ihanteellinen pistooli liikkuvalle terroristille. Tec-9 on tappava läheltä ja sisältää isokapasiteettisen lippaan." },
	["taser"] = { name = "Zeus x27", desc = "Zeus x27 on täydellinen lähikantaman väijytyksiin ja suljettujen tilojen taisteluihin, sillä se voi lamauttaa vihollisen yhdellä osumalla." },
	["molotov"] = { name = "Polttopullo", desc = "Molotov on tehokas ja arvaamaton ase, joka leimahtaa liekkeihin osuessaan maahan ja vahingoittaa sen lähellä olevia pelaajia." },
	["incgrenade"] = "Palopommi",
	["decoy"] = "Harhautuskranaatti",
	["hkp2000"] = { name = "P2000", desc = "Tarkka ja hallittava saksalaisvalmisteinen P2000 on hyödyllinen ensimmäisen erän pistooli, joka toimii parhaiten suojattomia vihollisia vastaan." },
	["mp7"] = { name = "MP7", desc = "MP7 on monipuolinen ja kallis saksalainen konepistooli, joka on täydellinen lähitaistelutilanteissa." },
	["mp5sd"] = { name = "MP5-SD", desc = "MP5 on ikoninen konepistooli, jota on yritetty turhaan jäljitellä. Se on ehkä maailman monikäyttöisin ja suosituin konepistooli. Tästä versiosta löytyy integroitu äänenvaimennin, joka tekee mahtavasta aseesta kuiskaavan vaarallisen." },
	["mp9"] = { name = "MP9", desc = "Sveitsiläinen MP9 on ergonominen polymeerikonepistooli, joka on varsinkin yksityisten vartiointifirmojen suosiossa." },
	["nova"] = { name = "Nova", desc = "Novan erittäin halpa hinta tekee siitä hyvän väijytysaseen rutiköyhille." },
	["p250"] = { name = "P250", desc = "P250 on hyvin vähän potkaiseva ja nopeasti ampuva käsiase, joka on halpa ratkaisu panssaroituja vihollisia vastaan." },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "SCAR-20 on puoliautomaattinen kiikarikivääri, joka ampuu nopeasti ja tehokkaasti pitkällä matkalla. Vastapainoksi se hidastaa matkantekoasi ja maksaa rutosti." },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "SSG08-pulttilukkokivääri tekee vähäistä vahinkoa halpaan hintaan, joten se sopii hyvin alkuerien pitkän matkan tarkkuusammuntaan." },
	["heavyassaultsuit"] = "Raskas rynnäkköpuku",
	["assaultsuit"] = "Kevlar + kypärä",
	["kevlar"] = "Kevlar-liivi",
	["defuser"] = "Pomminpurkupakkaus",
	["cutters"] = "Pelastuspakkaus",
	["revolver"] = { name = "R8-revolveri", desc = "R8-revolveri on varsin tarkka ja voimakas, hitaan liipaisinvedon kustannuksella. Kun raakaa pysäytysvoimaa tarvitaan, nopea tulitus iskuria pyörittämällä on paras vaihtoehto." },
	["usp_silencer"] = { name = "USP-S", desc = "Vaimennettu USP-pistooli on pelaajien suosikki Counter-Strike: Sourcesta. Siihen kuuluu irrotettava vaimennin, joka pienentää rekyyliä sekä hiljentää huomiota herättävää ääntä." },
	["knifebayonet"] = { name = "Pistin", desc = "Pistin ei ole juuri muuttunut sitten toisen maailmansodan, mutta sillä on silti paikkansa nykypäivän taistelutaktiikoissa. Pistinrynnäköt ovat pysyneet tehokkaina viime aikoinakin, kuten Persianlahden ja Afganistanin sodissa." },
	["knifeflip"] = { name = "Taittoveitsi", desc = "Taittoveitsissä on persialaistyylinen kaareva terä, jossa on terävä kärki. Vaikka kärki itsessään saattaa olla särkyvä, taittoveitsi on yllättävän kestävä sen muotoilun vuoksi." },
	["knifegut"] = { name = "Metsästysveitsi", desc = "Metsästysveitsen huomattavin ominaisuus on sen koukku terän selkäpuolella. Alun perin se yleistyi metsästyssaaliiden käsittelyn apuvälineenä, mutta leikkaa helposti myös narua, verkkoa tai turvavyön." },
	["knifecss"] = { name = "Klassinen veitsi", desc = "Counter-Strike-sarjan klassikko. Puukon laita on puristettua stelliittiä, joka istuu täydellisesti muun terän titaaniin. Puukon kahva on fossilisoitunutta mastodontin luuta hiilikuitutupessa." },
	["knifem9"] = { name = "M9-pistin", desc = "M9-pistin suunniteltiin alun perin kiinnitettäväksi kivääriin, mutta toimii hyvin myös lähikontaktissa." },
	["knifekaram"] = { name = "Karambit", desc = "Karambit, jonka kaareva terä muistuttaa tiikerin kynttä, kehitettiin osana Kaakkois-Aasian silat-kamppailulajeja. Veistä pidetään yleensä terä alaspäin etusormen ollessa veitsen kahvassa olevassa sormiaukossa." },
	["knifetactical"] = { name = "Metsämiehen veitsi", desc = "Moderneihin, taktisiin käyttötarkoituksiin suunniteltu veitsi, jonka terä sopii mainiosti käytettäväksi sekä taistelussa että työkaluna. Ainutlaatuinen Tanto-terä läpäisee kovimmatkin pinnat tehokkaasti." },
	["knife_butterfly"] = { name = "Perhosveitsi", desc = "Tämä on mittatilauksena tehty balisong, joka tunnetaan yleisesti perhosveitsenä. Tämän aseen erityispiirteenä on sen vapaasti kääntyvän terän viuhkamainen avautuminen, joka sallii sen nopean käyttöönoton tai kätkemisen. Tämän seurauksena perhosveitset ovat laittomia monissa maissa." },
	["partypopper"] = "Paukkuserpentiini!",
	["knife_falchion_advanced"] = { name = "Falchion-veitsi", desc = "Nykyaikaisena kunnianosoituksena falchion-miekalle tässä terässä on kurvikas kärki." },
	["knife_push"] = { name = "Varjotikarit", desc = "Tehokas mutta brutaali nyrkkipuukko yhtä yksinkertainen kuin nyrkinisku naamaan." },
	["knife_survival_bowie"] = { name = "Bowie-puukko", desc = "Tämä täysruotorakenteinen, hammastettu Bowie-puukko on suunniteltu kovaan käyttöön brutaaleissa selviytymistilanteissa." },
	["healthshot"] = "Lääkepiikki",
	["tagrenade"] = "Taktinen tiedustelukranaatti",
	["exploding_barrel"] = "Räjähtävä tynnyri",
	["snowball"] = "Lumipallo",
	["stompdamagekillstring"] = "murskasi kallosi",
	["dangerzone"] = "Vaaravyöhyke",
	["autosentry"] = "Automatisoitu vartiotykki",
	["fists"] = "Nyrkit",
	["tablet"] = "Tabletti",
	["breachcharge"] = "Murtopanos",
	["bumpmine"] = "Pomppumiina",
	["axe"] = { name = "Kirves", desc = "Heavy and always available, the axe has a sharp side and a dull side. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. How much wood would a woodchuck chuck?" },
	["hammer"] = { name = "Vasara", desc = "The hammer is available for fixing things and breaking things. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. If all you have is a hammer, everything looks like a nail." },
	["spanner"] = { name = "Jakoavain", desc = "A wrench is typically used to apply torque when turning objects, but you can hit anything with it for low-damage primary attack or throw it for a high-damage secondary attack. Bringing a wrench to a firefight is a recipe for screwing up." },
	["tripwirefire"] = "Ansalanka",
	["knife_cord"] = { name = "Paracord-kahvainen kenttäpuukko", desc = "Tämä selviytymisveitsi on suunniteltu sekä aseeksi että työkaluksi, ja sillä voi asettaa ansoja, metsästää eläimiä ja raivata lehvistöä. Veitsen kahvaan on kiedottu monikäyttöinen paracord-naru." },
	["knife_canis"] = { name = "Selviytymisveitsi", desc = "Tässä monikäyttöisessä taktisessa puukkossa on terävä koukku sekä sahalaitainen reuna, jonka ansioista sillä voi repiä jämäkämpääkin materiaalia, kuten luita tai kuituja. Sen komposiittikahva on kiinnitetty terään tukevasti kuusiomuttereilla." },
	["knife_ursus"] = { name = "Karhuveitsi", desc = "Tässä tantō-tyylisessä selviytymisveitsessä on viistetty terä ja täysruoto, jotka on viimeistelty iskuponsilla. Ei hössötystä eikä liikkuvia osia - ainoastaan luotettava veitsi, joka on valmis töihin." },
	["knife_gypsy_jackknife"] = { name = "Linkkuveitsi", desc = "Marmorikiillekahvaisessa taittoveitsessä on pieni mutta vaarallinen ja kapea terä." },
	["knife_outdoor"] = { name = "Nomad-puukko", desc = "Tämä ergonominen metsästykseen tarkoitettu kääntöveitsi koostuu komposiittikahvasta sekä leveästä ja tukevasta terästä. Hyödyllinen leikkelyyn ja materiaalin repimiseen." },
	["knife_widowmaker"] = { name = "Kynsiveitsi", desc = "Tässä norsunluukahvaisessa karambit-veitsessä on messinkiniitit ja sahanteräselkä, minkä vuoksi se leikkaa mennessä ja repii tullessa." },
	["knife_stiletto"] = { name = "Stiletti", desc = "Historiassa eripuran ja säännöstelyn keskipisteenä olleessa italialaistyyppisessä stilettiveitsessä on jousitettu terä, jonka saa otettua esiin lähes välittömästi nappia painamalla." },
	["knife_skeleton"] = { name = "Skeleton-puukko", desc = "Skeleton-puukon kahva on teipattu, jotta siitä saa paremman otteen. Reikään voi pujottaa sormen, jolloin ote on vakaampi ja turvallisempi." },
	["firebomb"] = { name = "Polttopullo", desc = "Palopommi on voimakas kokeellinen ase. Heitettäessä se syttyy palamaan, vapauttaa suuren määrän lämpöä ja polttaa sen laajalla räjähdysalueella olevia." },
	["diversion"] = { name = "Harhautuslaite", desc = "Heitetty harhautuslaite korostaa tabletilla sektoreita, mikä luo harhan useammasta vihollisesta." },
	["frag_grenade"] = { name = "Sirpalekranaatti", desc = "Kokeellinen sirpalekranaatti voi aiheuttaa valtavan räjähdysvahingon laajalla alueella. Nämä ominaisuudet tekevät siitä ihanteellisen sekä hyökkäys- että puolustusstrategioille." },
	["shield"] = { name = "Mellakkakilpi", desc = "Suojavaruste, joka on suunniteltu vaimentamaan ja kääntämään ballistinen vahinko pois kohteesta sekä auttamaan suojaamaan kantajaansa ammussateelta." },
	["zone_repulsor"] = { name = "Repulsorilaite", desc = "Pienhiukkassäteilyn suojalaitteen prototyyppi" },
	["cz75a"] = "Täysin automaattinen versio CZ75:stä. CZ75-Auto on väliaikaiseen käyttöön, tilanteen kääntämiseen ja aseen ryöstämiseen viholliselta. Pienen lipaskokonsa takia vaatii käyttäjältään hyvää liipasinkuria.",
	["m4a4"] = "M4A4 on erikoisjoukkojen tarkempi, mutta heikompi vastine terroristien AK-47-rynnäkkökiväärille.",
	["sg553"] = "Terroristien yksinoikeutettu SG553 on kiikarilla varustettu vaihtoehto AK-47-rynnäkkökiväärille pitkän matkan taisteluihin.",
	["decoy_grenade"] = "Heitettäessä harhautuskranaatti toistaa tehokkaimman kantamasi aseen ääntä, luoden illuusion apujoukoista.",
	["incindiary_grenade"] = "Heitettäessä palopommin kemiallinen reaktio vapauttaa suuren määrän lämpöä, joka polttaa jokaista sen suurella räjädysalueella olevaa.",
	["survival_taser"] = "Erittäin lyhyen kantaman ase, jolla voi tappaa yhdellä laukauksella. Voidaan käyttää myös aselaatikoiden avaamiseen.",
	["survival_healthshot"] = "Palauttaa osan terveydestäsi ja tarjoaa lyhytkestoisen nopeuslisän.",
	["survival_vesthelm"] = "Antaa vahingonvastustusta.",
	["survival_shield"] = "Mellakkakilpi, joka torjuu paljon vahinkoa ennen tuhoutumistaan.",
	["survival_parachute"] = "Estää vahingoittumasta putoamisen yhteydessä.",
	["survival_exojump"] = "Lisää huomattavasti hypyn korkeutta.",
	["survival_c4"] = "Aseta mihin tahansa kartalla aiheuttamaan suuri räjähdys. Voidaan käyttää tallelokeroiden avaamiseen.",
	["survival_dronepilot"] = "Voit hallita lennokkeja tabletillasi. Valitse tabletilla hallintaan otettava lennokki.",
	["survival_exploremoney"] = "Antaa lisärahaa jokaisesta tutkitusta sektorista.",
	["survival_wavemoney"] = "Myöntää lisää rahaa jokaisesta selvitystä Vaaravyöhykkeen räjähdysaallosta.",
	
    ["glock_use"] = "• Tehokas lähietäisyydeltä, hyödytön kaukotaistelussa[br]• Sopii puoliskon ensimmäiseen erään[br]• Vaikeustaso: ★★</font>",
    ["hkp2000_use"] = "• Tarkka kaukoetäisyydeltä, räiskintäominaisuus lähitaistelussa[br]• Sopii puoliskon ensimmäiseen erään[br]• Vaikeustaso: ★★</font>",
    ["usp_silencer_use"] = "• Tarkka, hiljainen ja jokseenkin tappava[br]• Sopii puoliskon ensimmäiseen erään[br]• Vaikeustaso: ★★</font>",
    ["elite_use"] = "• Kaksi sarjatulipistoolia yhden hinnalla[br]• Sopii puoliskon ensimmäiseen erään[br]• Vaikeustaso: ★★</font>",
    ["p250_use"] = "• Suosittu vaikkakin vaatimaton vahinkolisä[br]• Sopii rahansäästöeriin[br]• Vaikeustaso: ★</font>",
    ["fiveseven_use"] = "• Voimallla, vauhdilla ja tarkkuudella on hintansa [br]• Sopii rahansäästöeriin [br]• Vaikeustaso: ★★</font>",
    ["cz75a_use"] = "• Tulivoiman ryöppy riisuu viholliset aseista[br]• Sopii rahansäästöeriin[br]• Vaikeustaso: ★★★★</font>",
    ["tec9_use"] = "• Helposti kannettava, tehokas sekä läheltä että kaukaa[br]• Sopii rahansäästöeriin[br]• Vaikeustaso: ★★★</font>",
    ["revolver_use"] = "• Aiheuttaa massiivista vahinkoa pienellä viiveellä[br]• Sopii rahansäästöeriin[br]• Vaikeustaso: ★★★★</font>",
    ["deagle_use"] = "• Pääosumat tappavat läheltä tai kaukaa[br]• Sopii rahansäästöeriin[br]• Vaikeustaso: ★★★★</font>",
    ["taser_use"] = "• Kertakäyttöinen yhdellä osumalla tappava lähiase[br]• Kokeile omalla vastuulla[br]• Vaikeustaso: ★★★★</font>",
    ["bizon_use"] = "• Luotisade lahtaa panssaria vailla olevat viholliset hetkessä[br]• Sopii puoliskon kolmeen ensimmäiseen erään[br]• Vaikeustaso: ★★</font>",
    ["mac10_use"] = "• Pommialueiden rynnäköihin soveltuva ase[br]• Sopii puoliskon kolmeen ensimmäiseen erään[br]• Vaikeustaso: ★</font>",
    ["mp9_use"] = "• Tulinopeus ja -voima hidastavat vihollisten hyökkäystä[br]• Sopii puoliskon kolmeen ensimmäiseen erään [br]• Vaikeustaso: ★</font>",
    ["mp7_use"] = "• Helppokäyttöinen ja luotettava keskietäisyydeltä[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★</font>",
    ["mp5sd_use"] = "• Helppokäyttöinen ja matalaprofiilinen keskipitkällä kantamalla[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★</font>",
    ["ump45_use"] = "• Hyvä panssarinläpäisykyky keskietäisyydellä[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★★</font>",
    ["p90_use"] = "• Loputon luotisade, jonka peittoavat vain kiväärit[br]• Sopii täysostoeriin[br]• Vaikeustaso: ★</font>",
    ["galilar_use"] = "• Halpa, mutta tehokas läpäisemään vihollisten panssareja[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★★</font>",
    ["famas_use"] = "• Halpa, mutta tehokas läpäisemään vihollisten panssareja[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★★</font>",
    ["ak47_use"] = "• Tarkka ja tappava klassikko[br]• Sopii täysostoeriin[br]• Vaikeustaso: ★★★★</font>",
    ["m4a1_use"] = "• Hyvä tarkkuus ja reilusti ammuksia[br]• Sopii täysostoeriin[br]• Vaikeustaso: ★★★</font>",
    ["m4a1_silencer_use"] = "• Tarkka, hiljainen eikä jätä valojuovia[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★★</font>",
    ["aug_use"] = "• Erityisen tarkka valinnaisen kiikaritähtäimen kera[br]• Sopii täysostoseriin[br]• Vaikeustaso: ★★★</font>",
    ["sg556_use"] = "• Tappava ase, joka on entistä vaarallisempi kiikaritähtäimen kera[br]• Sopii täysostoeriin[br]• Vaikeustaso: ★★★</font>",
    ["awp_use"] = "• Järisyttävän tehokas kokeneen tarkka-ampujan käsissä[br]• Sopii täysostoeriin[br]• Vaikeustaso: ★★★</font>",
    ["g3sg1_use"] = "• Automaattinen tarkkuuskivääri, jonka hyöty-laatusuhde riippuu tilanteesta[br]• Sopii vain erikoistilanteisiin[br]• Vaikeustaso: ★★★</font>",
    ["scar20_use"] = "• Vahva mutta riskaabeli työkalu tuliaseman turvaamiseen[br]• Sopii vain erikoistilanteisiin[br]• Vaikeustaso: ★★★</font>",
    ["ssg08_use"] = "• Kevyt ja vahva ase, jolla ammutaan kaukaa[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★★★</font>",
    ["mag7_use"] = "• Yllätä vihollinen, lataa ase ja toista sama kuvio![br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★</font>",
    ["nova_use"] = "• Monikäyttöinen haulikko lähitaisteluihin[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★</font>",
    ["sawedoff_use"] = "• Erittäin tehokas haulikko lähitaisteluihin[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★</font>",
    ["xm1014_use"] = "• Nopea ja tappava konetuliase[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★</font>",
    ["m249_use"] = "• Tätä ei sentään tarvitse ladata[br]• Sopii vain erikoistilanteisiin[br]• Vaikeustaso: ★★★</font>",
    ["negev_use"] = "• Äärimmäisen tarkka, sopii taustatuleen ja vihollisen hidastamiseen[br]• Sopii ostopakkoeriin[br]• Vaikeustaso: ★★★★</font>",
    ["hegrenade_use"] = "• Tee vahinkoa tai hankkiudu eroon savukranaattien savupilvistä[br]• Käytä varoen[br]• Vaikeustaso: ★★★</font>",
    ["flashbang_use"] = "• Sokaisee ja kuurouttaa lähellä olevat pelaajat[br]• Heitä ennen hyökkäystä[br]• Vaikeustaso: ★★★★</font>",
    ["smokegrenade_use"] = "• Luo suuren savupilven[br]• Heitä sabotoidaksesi vihollisten näkökenttää[br]• Vaikeustaso: ★★★</font>",
    ["decoy_use"] = "• Imitoi ampumisääniä[br]• Heitä aikaisessa vaiheessa hämätäksesi vihollisia[br]• Vaikeustaso: ★★★</font>",
    ["molotov_use"] = "• Häätää viholliset ulos piiloistaan tulella[br]• Heitä ennen pommialueelle hyökkäämistä[br]• Vaikeustaso: ★★★</font>",
    ["incgrenade_use"] = "• Hidastaa vihollisten hyökkäystä sytyttämällä alueen tuleen[br]• Heitä heti, kun olet pulassa[br]• Vaikeustaso: ★★★</font>",
    ["assaultsuit_use"] = "• Pysäyttää useimmat luodit[br]• Sopii täysosto- ja ostopakkoeriin [br]• Vaikeustaso: ★</font>",
    ["kevlar_use"] = "• Suojaa koko vartaloa päätä lukuun ottamatta[br]• Sopii puoliskon ensimmäiseen erään[br]• Vaikeustaso: ★</font>",
    ["defuser_use"] = "• Pura pommi kaksi kertaa nopeammin[br]• Osta pomminpurkupakkaus ja säästy posauksilta![br]• Vaikeustaso: ★</font>",
    ["cutters_use"] = "• Kanna panttivangit turvaan vauhdilla[br]• Sopii tilanteisiin, joissa rahaa on yllin kyllin[br]• Vaikeustaso: ★</font>",
}
