csstring = {
	["cat_pistols"] = "Pisztolyok",
	["cat_heavy"] = "Nehézfegyverek",
	["cat_smg"] = "Géppisztolyok",
	["cat_rifles"] = "Puskák",
	["cat_grenades"] = "Gránátok",
	["cat_gear"] = "Felszerelés",

	["pistol"] = "Pisztoly",
	["smg"] = "Géppisztoly",
	["rifle"] = "Puska",
	["heavy"] = "Nehézfegyver",
	["grenade"] = "Gránát",
	["sniperrifle"] = "Mesterlövész puska",
	["sniper"] = "Mesterlövész",
	["shotgun"] = "Sörétes puska",
	["ak47"] = { name = "AK-47", desc = "Az erős és megbízható AK-47 az egyik legnépszerűbb gépkarabély a világon. Rövid, célzott sorozattűz leadásakor a leghalálosabb." },
	["aug"] = { name = "AUG", desc = "Az erős és pontos AUG távcsöves gépkarabély hosszú újratöltési idejét kis szórásával és magas tűzgyorsaságával egyenlíti ki." },
	["awp"] = { name = "AWP", desc = "Magas kockázat és magas nyereség; a hírhedt AWP jellegzetes lövéshangjáról, és egy lövés, egy ölés szabályáról ismerhető fel." },
	["deserteagle"] = { name = "Desert Eagle", desc = "A legendás Desert Eagle pisztoly olyan erős, amilyen drága; nehéz a mesterévé válni, de meglepően pontos nagy távolságra." },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Dupla Beretta", desc = "Két nagy táras Berettával egyszerre lőve csökken a pontosság és nő az újratöltési idő. A jó hír viszont, hogy egyszerre két nagy táras Berettával fogsz lőni." },
	["elite"] = "Dupla Beretta",
	["famas"] = { name = "FAMAS", desc = "Olcsó lehetőség pénzszűkében levő játékosoknak; a FAMAS hatékonyan tölti ki a rést a drágább karabélyok és a kevésbé hatékony géppisztolyok között." },
	["fiveseven"] = { name = "Five-SeveN", desc = "A nagyon pontos és páncélátütő, borsos árú Five-Seven lassú újratöltésű, amit bőséges, 20 lőszeres tárral és megbocsátható visszarúgással egyenlít ki." },
	["flashbang"] = { name = "Villanógránát", desc = "A nem halálos villanógránát átmenetileg mindenkit elvakít a lökéshullám-területén belül, ami tökéletessé teszi elzárt területek kifüstöléséhez. Hangos robbanása időlegesen elfedi a lépések hangját is." },
	["g3sg1"] = { name = "G3SG1", desc = "A borsos árú G3SG1 jelentősen csökkenti a mozgási sebességet, de kiegyenlíti ezt a többi mesterlövész puskáénál nagyobb tűzgyorsasággal." },
	["galilar"] = { name = "Galil AR", desc = "Kevésbé drága lehetőségként a csak terroristáknak elérhető gépkarabélyok között a Galil AR használható fegyver közepes ás nagy távolságú harchoz." },
	["glock18"] = { name = "Glock-18", desc = "A Glock 18 használható első körös pisztoly, amely páncél nélküli ellenfelekkel szemben működik a legjobban, és háromlövéses sorozattűzre képes." },
	["he_grenade"] = { name = "Nagy robbanóerejű gránát", desc = "A nagy robbanóerejű repeszgránát nagy területen fejt ki rombolóhatást, ami ideálissá teszi ellenséges helyiségek megtisztítására." },
	["knife"] = { name = "Kés", desc = "A csendes és mindig kéznél lévő kés gyors, kis sebzésű első támadással és egy lassú, de magas sebzésű másodlagos támadással rendelkezik. A csendes játékosok hátbadöféssel azonnali ölést szerezhetnek." },
	["knife_t"] = { name = "Kés", desc = "A csendes és mindig kéznél lévő kés gyors, kis sebzésű első támadással és egy lassú, de magas sebzésű másodlagos támadással rendelkezik. A csendes játékosok hátbadöféssel azonnali ölést szerezhetnek." },
	["knife_gg"] = "Arany kés",
	["knife_ghost"] = { name = "Kísérteties bökő", desc = "A szellemek imádják a szellemkéseket. Vigyázz, amikor megkaparintanak egyet! Az első adandó alkalommal megpróbálnak leszúrni. Kár, hogy szellemek, és a szellemkések embernek nem árthatnak..." },
	["m249"] = { name = "M249", desc = "Az M249 erős, nyílt terepre szánt géppuska, mely tökéletes választás olyan játékosoknak, akik hajlandók elfogadni az alacsonyabb tűzgyorsaságot magasabb pontosságért és lőszerkapacitásért." },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "A némítatlan társánál kisebb tárral rendelkező hangtompítós M4A1 halkabb lövéseket biztosít kisebb visszarúgással és nagyobb pontossággal." },
	["mac10"] = { name = "MAC-10", desc = "A MAC-10 géppisztoly, mely lényegében egy doboz, amiből golyók jönnek ki, magas tűzgyorsasággal büszkélkedhet, cserébe viszont rossz a szórásképe és nagy a visszarúgása." },
	["p90"] = { name = "P90", desc = "A különleges hátsótáras felépítéséről könnyen felismerhető P90 nagyszerű fegyver mozgás közbeni tüzeléshez, nagy kapacitású tára és kis visszarúgása miatt." },
	["smoke_grenade"] = { name = "Füstgránát", desc = "A füstgránát közepes kiterjedésű álcafüst-felhőt hoz létre. Hatásosan rejtheti el csapatod orvlövészek elől, vagy lehet csupán hasznos figyelem-elterelés." },
	["ump45"] = { name = "UMP-45", desc = "A géppisztolyok családjának félreértett középső gyermekének, az UMP45-nek csak a kis tára az egyetlen hátránya, egyébként sokoldalú automata közelharcfegyver." },
	["xm1014"] = { name = "XM1014", desc = "Az XM1014 erős, teljes automata sörétes puska, ami azzal szolgál rá súlyosabb árcédulájára, hogy képes gyorsan ólommal beteríteni egy szobát." },
	["c4"] = { name = "C4 robbanóanyag", desc = "Ez a stabil és a legtöbb fizikai behatásnak ellenálló rögtönzött plasztik robbanóeszköz több mint 8000 m/s detonációs sebességgel rendelkezik." },
	["bizon"] = { name = "PP-Bizon", desc = "A Bizon géppisztoly kis sebzésű, de egyedülállóan kialakított dobtárral rendelkezik, amely gyors újratöltést eredményez." },
	["mag7"] = { name = "MAG-7", desc = "A T-E exkluzív Mag-7 pusztító mennyiségű sebzést ad közelre. Gyors, szekrénytár-megoldású újratöltése nagyszerű taktikai választássá teszi." },
	["negev"] = { name = "Negev", desc = "A Negev egy szörnyeteg, ami hajszálpontos zárótüzével sakkban tudja tartani az ellenséget, feltéve, ha van elég időd átvenni az irányítást a szóródás felett." },
	["sawedoff"] = { name = "Lefűrészelt csövű sörétes", desc = "A klasszikus lefűrészelt csövű sörétes nagyon súlyos sebzést okoz közelre, de alacsony pontossága, nagy szórása és alacsony tűzgyorsasága miatt jobb, ha meg is ölöd, amit eltaláltál." },
	["tec9"] = { name = "Tec-9", desc = "A mozgásban levő Terrorista ideális pisztolya, a Tec-9 közelre halálos, és nagy tárkapacitással rendelkezik." },
	["taser"] = { name = "Zeus x27", desc = "A közeli lesből támadásokhoz és zárt helyi találkozásokhoz tökéletes egylövetű x27 Zeus egy találattal képes magatehetetlenné tenni egy ellenséget." },
	["molotov"] = { name = "Molotov-koktél", desc = "A Molotov erős és kiszámíthatatlan terület-lezáró fegyver, mely eldobva lángba borítja a földet, megsebezve minden játékost a hatósugarában." },
	["incgrenade"] = "Gyújtógránát",
	["decoy"] = "Csaligránát",
	["hkp2000"] = { name = "P2000", desc = "A pontos és jól kezelhető német gyártású P2000 használható első körös pisztoly, mely páncélozatlan ellenfelek ellen működik a legjobban." },
	["mp7"] = { name = "MP7", desc = "A sokoldalú de drága német gyártású MP7 géppisztoly tökéletes választás a nagy hatású közelharcokban." },
	["mp5sd"] = { name = "MP5-SD", desc = "A gyakran, de mindig sikertelenül másolt ikonikus MP5 talán a világ legsokoldalúbb és legnépszerűbb géppisztolya. Az SD változat beépített hangtompítóval érkezik, egy már félelmetes fegyvert suttogóan csendessé téve." },
	["mp9"] = { name = "MP9", desc = "A Svájcban gyártott élvonalbeli MP9 géppisztoly egy ergonomikus polimer fegyver, amely a magán biztonsági cégek nagy kedvence." },
	["nova"] = { name = "Nova", desc = "A Nova potom árcédulája miatt nagyszerű rajtaütő fegyver egy pénzszűkében levő csapatnak." },
	["p250"] = { name = "P250", desc = "A kis visszarúgású és nagy tűzgyorsaságú P250 viszonylag olcsó választás páncélozott célok ellen." },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "A SCAR-20 félautomata mesterlövész puska, mely nagy tűzgyorsaságot és erős távolsági sebzést kínál lassú mozgásért és magas árért cserébe." },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "A forgó-tolózáras SSG08 kis sebzésű, de nagyon költséghatékony mesterlövész puska, így okos választás a korai körökben nagy távolságú lövészethez." },
	["heavyassaultsuit"] = "Nehéz támadóöltözék",
	["assaultsuit"] = "Mellény + sisak",
	["kevlar"] = "Golyóálló mellény",
	["defuser"] = "Hatástalanító készlet",
	["cutters"] = "Kimenekítő készlet",
	["revolver"] = { name = "R8 revolver", desc = "Az R8 revolver nagyon pontos és erős lövedéket juttat célba, hosszú ravaszút árán. A kakas kézi felhúzásával végrehajtott gyorstűz lehet a legjobb lehetőség, amikor közelre van szükség megállítóerőre." },
	["usp_silencer"] = { name = "USP-S", desc = "A Counter-Strike: Source közönség-kedvence, a hangtompítós USP pisztoly leszerelhető hangtompítóval rendelkezik, ami egyszerre csökkenti a lövés visszarúgását és nyomja el figyelemfelkeltő zaját." },
	["knifebayonet"] = { name = "Bajonett", desc = "A felépítésében a Második Világháború óta viszonylag változatlan bajonett máig megtartotta helyét a modern katonai stratégiában. A bajonettroham továbbra is hatékony, még olyan közelmúltbeli helyszíneken is, mint a Második Öböl-háború, vagy az Afganisztáni Háború." },
	["knifeflip"] = { name = "Összecsukható kés", desc = "Az összecsukható késnek perzsa stílusú, hegyes, hátrafelé ívelt pengéje van. Bár maga a hegy törékeny lehet, az összecsukható kés teljes felépítését tekintve meglepően erős." },
	["knifegut"] = { name = "Zsigerelőkés", desc = "A belezőkés legszembetűnőbb jellemzője a penge gerincén levő belezőkampó. Az eredetileg az elejtett vad helyben való megnyúzásához népszerűvé vált belezőkampó hatékony olyan szálas anyagok könnyű elvágásában is, mint a kötél, háló és biztonsági öv." },
	["knifecss"] = { name = "Klasszikus Kés", desc = "A Counter-Strike sorozat klasszikusa; a sajtolással illesztett stellit penge tökéletesen áll a helyén, precíz illesztésének köszönhetően a penge lapján és fokán levő titánnal. A markolat szénszálas foglalatba illesztett masztodoncsont." },
	["knifem9"] = { name = "M9 bajonett", desc = "Ez az M-9 bajonett. Eredetileg karabélyra rögzítésre szánták, de közelharcra is igen alkalmas." },
	["knifekaram"] = { name = "Karambit", desc = "Az ívelt pengéjével tigriskarmot utánzó karambitot a silat nevű délkelet-ázsiai harcművészeti ág részeként fejlesztették ki. A kést tipikusan fordított fogással használják, az ujjgyűrűt a mutatóujjra húzva." },
	["knifetactical"] = { name = "Vadászkés", desc = "Egy kés, melyet a modern, taktikai használatra terveztek, pengéje jól alkalmazható mind harci, mind utilitarista helyzetekben. Az egyedülálló Tanto penge lehetővé teszi a maximális áthatolást még a legkeményebb felületeken is." },
	["knife_butterfly"] = { name = "Pillangókés", desc = "Ez egy egyedi kialakítású balisong, ismertebb nevén pillangókés. E fegyver meghatározó jellemzője a legyezőszerűen kinyitható, szabadon forgó penge, ami gyors kinyitást és elrejtést tesz lehetővé. Ennek eredményeképp a pillangókés számos országban be van tiltva." },
	["partypopper"] = "Bulipuska!",
	["knife_falchion_advanced"] = { name = "Handzsárkés", desc = "Modern tisztelgés egy handzsár kard előtt; ennek a szúrópengének ívelt éle van." },
	["knife_push"] = { name = "Árnyéktőr", desc = "A hatékony brutalitásra tervezett döfőtőrt használni olyan egyszerű, mint bevinni egy-két ütést." },
	["knife_survival_bowie"] = { name = "Bowie kés", desc = "Ezt a teljes markolattüskés Bowie kést erős igénybevételre tervezték, kegyetlen túlélési helyzetekhez." },
	["healthshot"] = "Elsősegély-injekció",
	["tagrenade"] = "Taktikai felderítő gránát",
	["exploding_barrel"] = "Robbanó hordó",
	["snowball"] = "Hógolyó",
	["stompdamagekillstring"] = "bezúzta a koponyádat",
	["dangerzone"] = "Veszélyzóna",
	["autosentry"] = "Automata lövegtorony",
	["fists"] = "Puszta kéz",
	["tablet"] = "Táblagép",
	["breachcharge"] = "Rombolótöltet",
	["bumpmine"] = "Röptetőakna",
	["axe"] = { name = "Fejsze", desc = "A nehéz és mindig kéznél lévő fejszének van egy éles és egy tompa oldala. Lengesd meg egy alacsony sebzésű elsődleges támadáshoz vagy dobd el egy magas sebzésű másodlagos támadáshoz. Nagy fába vágtad a fejszédet." },
	["hammer"] = { name = "Kalapács", desc = "A kalapács mindig kéznél van dolgok megjavítására és összetörésére. Lengesd meg egy alacsony sebzésű elsődleges támadáshoz vagy dobd el egy magas sebzésű másodlagos támadáshoz. Ha csak kalapácsod van, egyszerre minden szögnek tűnik." },
	["spanner"] = { name = "Csavarkulcs", desc = "A csavarkulcsot jellemzően nyomaték kifejtésére használják tárgyak forgatásakor, de bármit megüthetsz vele egy alacsony sebzésű elsődleges támadáshoz vagy eldobhatod egy magas sebzésű másodlagos támadáshoz. Csavarkulccsal érkezni egy tűzharcba nem vall csavaros észjárásra." },
	["tripwirefire"] = "TrapFire",
	["knife_cord"] = { name = "Paracord kés", desc = "Ezt a fix pengéjű túlélőkést úgy tervezték, hogy kibírja a fegyverként és szerszámként való használatot is, így lehet vele csapdát készíteni, állatokra vadászni, vagy növényzetet vágni. A markolatára ejtőernyőzsinór van tekerve." },
	["knife_canis"] = { name = "Túlélőkés", desc = "Ennek a többfunkciós taktikai késnek fogazott éle van kemény anyagok, mint a csont vagy szövedékek átvágásához, plusz egy éles belezőhorga. A kompozit anyagú markolat hatlapfejű csavarokkal van a pengéhez rögzítve." },
	["knife_ursus"] = { name = "Ursus kés", desc = "Ez a tanto jellegű túlélőkés fazettás pengével és ütővégsúlyban végződő teljes markolattüskével rendelkezik. Semmi csicsa, semmi mozgó alkatrész, csak egy megbízható penge, ami munkára kész." },
	["knife_gypsy_jackknife"] = { name = "Navaja kés", desc = "Ez a márványlakk markolatú összecsukható kés egy kicsi, de gonoszul hegyes pengét rejt." },
	["knife_outdoor"] = { name = "Nomád kés", desc = "Ez az ergonomikus, becsukható pengéjű taktikai vadászkés kompozit markolatbetétekkel és széles, erős pengével rendelkezik, ami vágáshoz és tárgyak szétfeszítéséhez is hasznos." },
	["knife_widowmaker"] = { name = "Talon kés", desc = "Ez az elefántcsont markolatú karambit rézszegecsekkel és fűrészfogazással rendelkezik, így befelé menet vág, kifelé jövet pedig tép." },
	["knife_stiletto"] = { name = "Stiletto kés", desc = "Ennek a hosszú ideje viták, sőt, szabályozások tárgyát képező olasz stílusú stiletto rugós késnek olyan rugóval mozgatott pengéje van, ami szinte azonnal kiugratható egy kioldópöcök megnyomásával." },
	["knife_skeleton"] = { name = "Csontváz kés", desc = "Ennek a lecsupaszított markolattüskéjű késnek a markolatára szalagot tekertek a fogás javítására. A lyukba bele lehet dugni egy ujjat a stabilitás és biztonság növelésére." },
	["firebomb"] = { name = "Gyújtóbomba", desc = "A gyújtóbomba nagy hatású kísérleti fegyver, amely eldobva magas hőmérsékletű lánggal égő területet hoz létre, megégetve minden játékost nagy hatóterületén." },
	["diversion"] = { name = "Figyelemelterelő gránát", desc = "Eldobva a figyelemelterelő gránát további szektorokat emel ki a táblagépeken, további ellenségek illúzióját keltve." },
	["frag_grenade"] = { name = "Repeszgránát", desc = "A kísérleti repeszgránát nagyobb területen okoz rendkívüli mennyiségű robbanási sebzést, ami támadó és védekező taktikákhoz is ideálissá teszi." },
	["shield"] = { name = "Rohampajzs", desc = "Lövedékek eltérítésére vagy elnyelésére szolgáló védőeszköz, segít megvédeni a használóját különféle űrméretű lövedékektől." },
	["zone_repulsor"] = { name = "Visszaverő készülék", desc = "Körsugárzó részecskeárnyékoló készülék prototípus." },
	["cz75a"] = "A CZ-75-Auto, a CZ75 teljes automata változata az ideális rövidtávú választás a helyzet megfordítására és az ellenfeleid fegyvereinek megszerzésére. De mivel nagyon kevés lőszere van a tárban, erős lőszertakarékosságot követel.",
	["m4a4"] = "A pontosabb, de AK-47-es megfelelőjénél kevesebbet sebző M4A4 teljes automata gépkarabély a T-E-k választása.",
	["sg553"] = "A terrorista-exkluzív SG553 prémium távcsöves alternatíva az AK-47 helyett hatékony nagy távolságú harchoz.",
	["decoy_grenade"] = "A csaligránát eldobva a nálad levő legerősebb fegyver hangját utánozza, további támogató erők illúzióját keltve.",
	["incindiary_grenade"] = "A gyújtógránát eldobva magas hőmérsékletű vegyi reakciót idéz elő, mely képes mindenkit megégetni a hatásos sugarán belül.",
	["survival_taser"] = "Rendkívül rövid hatótávú, egy lövéssel ölésre képes fegyver. Fegyverládák kinyitására is használható.",
	["survival_healthshot"] = "Helyreállítja életerőd egy részét és rövid sebességnövekedést ad.",
	["survival_vesthelm"] = "Sebzéssel szembeni ellenállást ad.",
	["survival_shield"] = "Golyóálló rohampajzs, ami nagy mennyiségű sérülést képes blokkolni, mielőtt megsemmisül.",
	["survival_parachute"] = "Zuhanás közben kinyitható a földet érési sérülés megakadályozására.",
	["survival_exojump"] = "Jelentősen növeli az ugrási magasságot.",
	["survival_c4"] = "A pályán bárhol telepíthető nagy robbanás előidézésére. Használható széfek kinyitására.",
	["survival_dronepilot"] = "Lehetővé teszi a drónok fölötti irányítás átvételét. A táblagép használatával válassz eltérítendő drónt.",
	["survival_exploremoney"] = "Plusz pénzt ad minden felderített mező után.",
	["survival_wavemoney"] = "Plusz pénzt ad minden túlélt veszélyzóna-terjeszkedés után.",
}
