csstring = {
	["cat_pistols"] = "권총",
	["cat_heavy"] = "중화기",
	["cat_smg"] = "기관단총",
	["cat_rifles"] = "소총",
	["cat_grenades"] = "수류탄",
	["cat_gear"] = "장비",

	["ak47"] = { name = "AK-47", desc = "강력하고 믿을 수 있는 AK-47은 세계에서 가장 유명한 돌격소총 중 하나입니다. 제어된 점사를 할 때 가장 위력적인 소총입니다." },
	["aug"] = { name = "AUG", desc = "강력하고 정확한 AUG 조준경 부착식 돌격소총은 긴 재장전 시간을 높은 집탄율과 연사력으로 보완합니다." },
	["awp"] = { name = "AWP", desc = "위험할수록 큰 보상이 따르는 이 악명 높은 AWP는 단방에 적을 제압하는 방식이 특징인 것으로 널리 알려져 있습니다." },
	["deserteagle"] = { name = "데저트 이글", desc = "비싼 만큼 큰 위력을 지닌 유명한 권총인 데저트 이글은 익숙해지기 어렵지만 장거리에서도 놀라운 명중률을 지니고 있습니다." },
	["deagle"] = "데저트 이글",
	["elites"] = { name = "양손 베레타", desc = "고용량 탄창을 장착한 2정의 베레타 권총을 같이 사격할 경우 명중률이 떨어지고 재장전 시간이 늘어납니다. 좋은 점이라면 2정의 고용량 탄창을 지닌 베레타 권총을 한번에 사격하고 있다는 거죠." },
	["elite"] = "양손 베레타",
	["famas"] = { name = "파마스", desc = "돈이 없는 플레이어들을 위한 파마스 돌격소총은 값비싼 소총과 효율이 떨어지는 기관단총 사이의 무기라 할 수 있습니다." },
	["fiveseven"] = { name = "파이브 세븐", desc = "명중률이 뛰어나고 철갑탄을 사용하는 파이브 세븐은 비싸고 재장전 속도가 느리지만 20발의 대용량 탄창과 낮은 반동이 이를 보완해줍니다." },
	["flashbang"] = { name = "섬광탄", desc = "비살상무기인 섬광탄은 폭발 범위에 있던 사람들의 눈을 멀게 하여 폐쇄된 좁은 공간을 확보하는 데 유용하게 쓰이며 큰 폭발음을 이용해 발소리를 가릴 수도 있습니다." },
	["g3sg1"] = { name = "G3SG1", desc = "약간 비싼 G3SG1은 이동 속도를 상당히 감소시키는 대신 다른 저격소총에 비해 높은 연사력으로 이를 보완합니다." },
	["galilar"] = { name = "갈릴 돌격소총", desc = "테러리스트 전용 돌격소총 중 가격이 낮은 편인 갈릴 돌격소총은 중거리 전투는 물론 장거리 전투에도 쓸만한 무기입니다." },
	["glock18"] = { name = "글록 18", desc = "기본적으로 지급되는 글록 18은 방탄복을 착용하지 않은 적을 상대할 때 가장 좋은 권총으로, 3점사가 가능합니다." },
	["he_grenade"] = { name = "고폭 수류탄", desc = "이 고성능 세열수류탄은 넓은 지역에 큰 피해를 줄 수 있어 적이 점거한 공간을 확보하는 데 유용합니다." },
	["knife"] = { name = "칼", desc = "어떤 상황에서도 꺼낼 수 있는 칼은 빠르지만 작은 피해를 주는 방법과 느리지만 큰 피해를 주는 공격 방법이 있습니다. 후방에서 찌르면 적군을 한 번에 처치할 수 있습니다." },
	["knife_t"] = { name = "칼", desc = "어떤 상황에서도 꺼낼 수 있는 칼은 빠르지만 작은 피해를 주는 방법과 느리지만 큰 피해를 주는 공격 방법이 있습니다. 후방에서 찌르면 적군을 한 번에 처치할 수 있습니다." },
	["knife_gg"] = "황금 칼",
	["knife_ghost"] = { name = "유령 칼", desc = "Ghosts love ghost knives. When they get their hands on one, look out! They'll try stab you first chance they get. Too bad they are a ghost and ghost knives can't hurt people...." },
	["m249"] = { name = "M249", desc = "강력한 경기관총인 M249은 향상된 명중률과 높은 탄창 용량을 위해 낮은 연사력을 기꺼이 받아들일 플레이어들에게 완벽한 무기입니다." },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "소음기가 없는 유사 제품보다 탄창이 더 작은, 소음기 장비 M4A1은 낮은 반동과 높은 명중률을 조용한 사격음과 함께 제공합니다." },
	["mac10"] = { name = "MAC-10", desc = "총알이 나오는 상자라 할 수 있는 MAC-10 기관단총은 높은 연사력을 자랑하지만, 대신에 영 좋지 못한 집탄율과 높은 반동을 지녔습니다." },
	["p90"] = { name = "P90", desc = "특이한 불펍 설계로 알려진 P90는 낮은 반동과 대용량 탄창 덕에 이동 사격이 용이한 무기입니다." },
	["smoke_grenade"] = { name = "연막탄", desc = "연막탄은 중간 범위의 연막을 생성하여 적군 저격수에게서 아군을 숨기거나 적의 주의를 흩뜨릴 때 사용할 수 있습니다." },
	["ump45"] = { name = "UMP-45", desc = "기관단총계의 이단아인 UMP45는 작은 탄창만 아니었다면 효과적인 근접전 무기가 될 수 있었을 겁니다." },
	["xm1014"] = { name = "XM1014", desc = "XM1014는 강력한 자동 산탄총으로써 공간 전체를 빠르게 총알으로 도배할 수 있는 능력을 통해 높은 가격을 정당화합니다." },
	["c4"] = { name = "C4 폭탄", desc = "안정적이고 물리적 충격 내성을 지닌 이 급조 폭발물은 초당 8000마일의 연소 속도를 지녔습니다." },
	["bizon"] = { name = "PP 비존", desc = "비존 기관단총은 피해력이 낮지만 재장전이 빠른, 특수 제작한 고용량 드럼 탄창을 사용합니다." },
	["mag7"] = { name = "MAG-7", desc = "대테러부대 전용 Mag-7 산탄총은 근거리에서 매우 위력적입니다. 탄창 덕분에 가능한 재빠른 재장전은 이 총을 뛰어난 전술적 무기로 만들었습니다." },
	["negev"] = { name = "네게브", desc = "총알을 빠르게 분사할 수 있는 네게브는 높은 연사력과 큰 탄창을 지닌 대신 낮은 집탄율과 제어하기 힘든 반동이 단점입니다." },
	["sawedoff"] = { name = "소드오프", desc = "이 고전적인 소드오프 산탄총은 매우 위력적인 근거리 피해를 줄 수 있지만, 연사력, 명중률, 집탄율이 죄다 낮기 때문에 적을 죽이고 싶으면 잘 맞춰야 합니다." },
	["tec9"] = { name = "Tec-9", desc = "이동을 자주 하는 테러리스트 플레이어를 위한 권총인 Tec-9은 근접전에서 치명적이며 장탄수가 많습니다." },
	["taser"] = { name = "제우스 x27", desc = "근접 습격과 폐쇄된 공간에서의 교전에 완벽한 단발 무기인 제우스 x27은 한 방에 적을 쓰러뜨릴 수 있습니다." },
	["molotov"] = { name = "화염병", desc = "화염병은 예측하기 힘든 구역을 방어할 때 효과적인 무기로, 표면과 충돌 시 불타올라 화염 반경에 있는 플레이어들에게 피해를 줍니다." },
	["incgrenade"] = "소이탄",
	["decoy"] = "유인 수류탄",
	["hkp2000"] = { name = "P2000", desc = "정확하고 다루기 쉬운, 기본적으로 지급되는 독일제 P2000은 방탄복을 착용하지 않은 적을 상대할 때 가장 좋은 권총입니다." },
	["mp7"] = { name = "MP7", desc = "활용도가 뛰어나지만 비싼 독일제 MP7 기관단총은 강력하고 빠른 근접 전투에 적합한 총기입니다." },
	["mp5sd"] = { name = "MP5-SD", desc = "Often imitated but never equaled, the iconic MP5 is perhaps the most versatile and popular SMG in the world. This SD variant features an integrated silencer, making an already formidable weapon whisper-quiet." },
	["mp9"] = { name = "MP9", desc = "스위스제 최첨단 MP9 기관단총은 인체공학적 설계와 가벼운 중합체를 재료로 한 총기로 사설 보안 단체들이 애용합니다." },
	["nova"] = { name = "노바", desc = "노바의 땅을 치는 가격은 가난한 팀에서 이 총을 습격용 무기로 선택하는 이유입니다." },
	["p250"] = { name = "P250", desc = "높은 연사력과 낮은 반동을 지닌 P250는 방탄복을 착용한 적을 상대할 때 저렴하고 유용한 권총입니다." },
	["cz75"] = "CZ75 기관권총",
	["scar20"] = { name = "SCAR-20", desc = "SCAR-20는 반자동 저격소총으로써 높은 연사력과 장거리 피해를 주는 대신 이동속도를 크게 감소시키며 매우 비쌉니다." },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "SSG08는 수동식 노리쇠 방식으로, 위력이 낮지만 가격 대 성능비가 좋은 무기로써 초반 장거리 저격에 적합한 선택입니다." },
	["heavyassaultsuit"] = "강화 방탄복",
	["assaultsuit"] = "방탄복 + 방탄모",
	["kevlar"] = "케블라 방탄조끼",
	["defuser"] = "폭탄 해체 장비",
	["cutters"] = "구출 장비",
	["revolver"] = { name = "R8 리볼버", desc = "R8 리볼버는 방아쇠를 당겨 격발할 때까지의 시간이 긴 대신 적에게 매우 정확하고 강력한 한 방을 먹일 수 있습니다. 근접전을 벌일 경우에는 공이를 손으로 쳐서 연사하여 적을 저지하는 것이 좋습니다." },
	["usp_silencer"] = { name = "USP-S", desc = "카운터 스트라이크: 소스의 팬들이 좋아하는 USP 소음 권총은 반동을 낮춰주면서 적의 주위를 끄는 소리를 줄여주는 탈착식 소음기가 장착되어 있습니다." },
	["knifebayonet"] = { name = "총검", desc = "제2차 세계대전 이후로도 비교적 변한 게 없는 총검은 현대의 군사 전략에도 여전히 사용되며 착검 돌격이 포함된 전술은 과거부터 2차 걸프전과 아프가니스탄의 전쟁과 같은 최근의 경우에서도 그 효율성을 재차 입증했습니다." },
	["knifeflip"] = { name = "접이식 칼", desc = "스포츠용의 접이식 칼은 페르시아식으로 뒤로 젖혀진 칼날에 예리한 칼끝을 지녔습니다. 부서질 것만 같은 형태지만, 전반적으로 접이식 칼의 설계는 놀랄만큼 튼튼합니다." },
	["knifegut"] = { name = "갈고리 칼", desc = "갈고리 칼은 칼등에 갈고리 모양의 홈을 지닌 칼로 원래 사냥감의 내장을 제거하는 데 쓰이는 도구이며 갈고리는 밧줄, 가죽 그리고 안전벨트와 같은 섬유를 자르는 데에도 효율적입니다." },
	["knifecss"] = { name = "고전 칼", desc = "카운터 스트라이크 시리즈의 고전적인 칼로, 칼볼과 칼등에 있는 티타늄이 정밀하게 맞물리기 때문에 이 칼의 가장자리에 압입식 스텔라이트 합금이 완벽하게 제자리에 고정되어 있습니다. 손잡이는 탄소 섬유 주머니에 들어있는 화석화된 마스토돈 상아로 되어있습니다." },
	["knifem9"] = { name = "M9 총검", desc = "M-9 총검은 총기에 부착하기 위해 만들어진 칼로 근접 전투에 알맞는 무기입니다." },
	["knifekaram"] = { name = "카람빗", desc = "카람빗은 호랑이 발톱을 본따 만들어진 곡도로, 동남아시아의 전통무술 중 하나인 실라트의 일부로써 개발되었습니다. 이 칼은 보통 검지를 고리에 끼우고 거꾸로 쥔 상태에서 사용합니다." },
	["knifetactical"] = { name = "헌츠맨 칼", desc = "현대적 전술에 맞춤 제작된 단검으로서, 전투 및 실용적인 활용 모두에 걸맞습니다. 이 단검의 극단적인 날카로움은 매우 단단한 표면도 뚫을 수 있는 극대의 관통력을 제공합니다." },
	["knife_butterfly"] = { name = "버터플라이 칼", desc = "버터플라이 칼이라는 이름으로 더 널리 알려진 주문 제작된 발리송입니다. 이 칼은 부채꼴로 자유롭게 펼칠 수 있어 빠르게 접었다 펼칠 수 있다는 특징이 있습니다. 하지만 이 특징 때문에 많은 나라에서 이 칼은 불법으로 규정되고 있기도 합니다." },
	["partypopper"] = "축하용 폭죽!",
	["knife_falchion_advanced"] = { name = "파르치온 칼", desc = "파르치온 검을 닮은 칼로 곡선형의 날을 지니고 있습니다." },
	["knife_push"] = { name = "그림자 단검", desc = "효과적인 폭력성을 위해 설계되었으며, 단검을 찔러넣는 것은 주먹을 한두 번 내지르는 것처럼 쉽습니다." },
	["knife_survival_bowie"] = { name = "보위 칼", desc = "검체가 손잡이까지 이어지고 검등이 톱날처럼 된 보위 단검은 잔혹한 생존 환경에서 유용하게 쓰일 수 있도록 설계된 단검입니다." },
	["healthshot"] = "의료 주사",
	["tagrenade"] = "전략적 인식 수류탄",
	["exploding_barrel"] = "폭발하는 술통",
	["dangerzone"] = "위험지대",
	["tablet"] = "태블릿",
	["axe"] = { name = "도끼", desc = "Heavy and always available, the axe has a sharp side and a dull side. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. How much wood would a woodchuck chuck?" },
	["hammer"] = { name = "망치", desc = "The hammer is available for fixing things and breaking things. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. If all you have is a hammer, everything looks like a nail." },
	["knife_cord"] = { name = "파라코드 칼", desc = "칼날이 고정되어 있는 이 서바이벌 칼은 덫을 설치하거나 동물을 사냥할 때 또는 수풀을 해칠 때 사용할 수 있는 도구이자 무기로 활용할 수 있도록 설계되었습니다. 손잡이는 다용도 파라코드로 감겨 있습니다." },
	["knife_canis"] = { name = "서바이벌 칼", desc = "This multi-purpose tactical knife features a serrated edge for ripping through coarse material like bone or fiber, plus a sharp gutting hook. The composite material handle is bolted to the blade with hex nuts." },
	["knife_ursus"] = { name = "우르수스 칼", desc = "This tanto-style survival knife features a faceted blade and full tang, complete with impact pommel. No fuss, no moving parts - just a reliable blade that's ready to work." },
	["knife_gypsy_jackknife"] = { name = "나바하 칼", desc = "This marble-enamel-handled flip knife conceals a small but viciously tapered blade." },
	["knife_outdoor"] = { name = "유목민 칼", desc = "This ergonomic tactical hunting lock-blade knife features composite handle inserts and a broad, sturdy blade, useful for cutting and prying apart material." },
	["knife_widowmaker"] = { name = "탈론 칼", desc = "This ivory-handled karambit features brass rivets and saw-tooth ridges, so it cuts on the way in, and tears on the way out." },
	["knife_stiletto"] = { name = "스틸레토 칼", desc = "Historically a focal point of contention and even regulation, this Italian-style stiletto switchblade knife features a spring-loaded blade that can be deployed almost instantly with the push of a release catch." },
	["knife_skeleton"] = { name = "스켈레톤 칼", desc = "This skeletonized-tang knife has been taped at the handle for improved grip. The hole allows a finger to be threaded through for stability and safety." },
	["frag_grenade"] = { name = "수류탄", desc = "The experimental fragmentation grenade can output extreme amounts of highly explosive damage in a wider area, making it ideal for both attacking and defensive strategies." },
	["cz75a"] = "자동 사격이 가능하도록 개조된 CZ75 기관권총은 전세를 역전시키고 적의 무기를 탈취하기 위해 잠깐 쓰기 좋은 무기입니다. 허나 제공된 탄약이 매우 적기 때문에 조심스럽게 사격해야 할 것입니다.",
	["m4a4"] = "AK-47보다 명중률이 더 높지만 위력이 떨어지는 M4A4는 대테러부대에게 딱 맞는 완전 자동 돌격소총입니다.",
	["sg553"] = "테러리스트 전용 SG553는 고성능 조준경이 장착되어 있어 장거리에 효과적인, AK-47의 대용품이라 할 수 있습니다.",
	["decoy_grenade"] = "유인 수류탄은 투척자가 지니고 있던 가장 강력한 무기의 사격음을 발생시켜 마치 추가 지원 병력이 오는 것처럼 적을 속일 수 있습니다.",
	["incindiary_grenade"] = "소이탄은 폭발 시 넓은 폭발 반경에 있던 사람들을 태워버릴 고온의 화학 반응을 일으키는 물질을 내보냅니다.",
	["snowball"] = "Snowball",
	["stompdamagekillstring"] = "crushed your skull",
	["autosentry"] = "Automated Sentry",
	["fists"] = "Bare Hands",
	["breachcharge"] = "Breach Charge",
	["bumpmine"] = "Bump Mine",
	["spanner"] = { name = "Wrench", desc = "A wrench is typically used to apply torque when turning objects, but you can hit anything with it for low-damage primary attack or throw it for a high-damage secondary attack. Bringing a wrench to a firefight is a recipe for screwing up." },
	["tripwirefire"] = "TrapFire",
	["firebomb"] = { name = "Fire Bomb", desc = "The Fire Bomb is a powerful experimental weapon that bursts into high-temperature flames when thrown on the ground, chemically burning any player in its wide spread radius." },
	["diversion"] = { name = "Diversion Device", desc = "When thrown, the diversion device will highlight sectors on tablets, creating the illusion of additional enemies." },
	["shield"] = { name = "Riot Shield", desc = "A protection device designed to deflect or absorb ballistic damage and help protect the carrier from an array of projectile calibers." },
	["zone_repulsor"] = { name = "Repulsor Device", desc = "Prototype Radial Emission Particulate Shielding Device" },
	["survival_taser"] = "Extremely short range weapon capable of killing in one shot. Can also be used to open weapon crates.",
	["survival_healthshot"] = "Restores a portion of your health and provides a brief speed boost.",
	["survival_vesthelm"] = "Provides resistance to damage.",
	["survival_shield"] = "A ballistic riot shield which can block a large amount of damage before being destroyed.",
	["survival_parachute"] = "Can be deployed when falling to prevent fall damage.",
	["survival_exojump"] = "Significantly increases jump height.",
	["survival_c4"] = "Plant anywhere in the map to cause a large explosion. Can be used to open safes.",
	["survival_dronepilot"] = "Grants the ability to take control of drones. Use the tablet to select a drone to take over.",
	["survival_exploremoney"] = "Grants extra money for each hex explored.",
	["survival_wavemoney"] = "Grants extra money for each danger zone expansion wave survived.",
}
