csstring = {
	["cat_pistols"] = "ピストル",
	["cat_heavy"] = "重火器",
	["cat_smg"] = "サブマシンガン",
	["cat_rifles"] = "ライフル",
	["cat_grenades"] = "グレネード",
	["cat_gear"] = "装備",

	["pistol"] = "ピストル",
	["smg"] = "サブマシンガン",
	["rifle"] = "ライフル",
	["heavy"] = "重火器",
	["grenade"] = "グレネード",
	["sniperrifle"] = "スナイパーライフル",
	["sniper"] = "スナイパー",
	["shotgun"] = "ショットガン",
	["ak47"] = { name = "AK-47", desc = "強力で信頼性の高い AK-47は、世界で最も有名なアサルトライフルの1つ。近距離で制御された射撃を行うときに最も威力がある。" },
	["aug"] = { name = "AUG", desc = "強力で精度が良い AUG 照準器付きアサルトライフルは、長い再装填時間を高い集弾率と高い射撃速度で補完している。" },
	["awp"] = { name = "AWP", desc = "リスクが高いが報酬も大きい悪名高き AWP は、特徴的な発射音とワンショット・ワンキルのポリシーで知られている。" },
	["deserteagle"] = { name = "Desert Eagle", desc = "その強力さと比例して高価な Desert Eagle は、使いこなすのは困難でも、遠距離で驚くほどの正確さを誇る象徴的な拳銃。" },
	["deagle"] = "Desert Eagle",
	["elites"] = { name = "Dual Berettas", desc = "大容量の弾倉を装着した2丁のベレッタを一度に射撃すると、命中率が下がり、装填時間が伸びる。明るい面を挙げれば、大容量の弾倉を備えた2丁のベレッタを一度に撃てる。" },
	["elite"] = "Dual Berettas",
	["famas"] = { name = "FAMAS", desc = "金欠プレイヤーにとって安価な選択肢となる FAMAS は、より高価なライフルとより効果の弱い SMG の間の隙間を効果的に埋める。" },
	["fiveseven"] = { name = "Five-SeveN", desc = "精度が高く、徹甲弾を用いる高価な Five-Seven は装填速度が遅いが、20発の大容量弾倉と低反動で補う。" },
	["flashbang"] = { name = "フラッシュグレネード", desc = "非致死性のフラッシュ・グレネードは震盪性衝撃内の全員の視力を一時的に奪うため、屋内エリアを一掃するのに最適。大きい爆発音が足音も一時的に隠してくれる。" },
	["g3sg1"] = { name = "G3SG1", desc = "高価な G3SG1 は、大幅に移動速度を減少させるが、他のスナイパーライフルより高い射撃速度で埋め合わせている。" },
	["galilar"] = { name = "Galil AR", desc = "テロリスト専用アサルトライフルの中で比較的安価な選択肢である Galil AR は、中長距離戦闘で役立つ武器。" },
	["glock18"] = { name = "Glock-18", desc = "実用向きで単発の Glock 18 は、防弾ベストを着用していない敵を相手にする時に最も有効に働き、3点バーストで射撃することができる。" },
	["he_grenade"] = { name = "HE グレネード", desc = "HEフラググレネードは広範囲に大ダメージを与え、 敵のいる部屋を一掃するのに理想的に使える。" },
	["knife"] = { name = "ナイフ", desc = "静かで、いつでも使えるナイフには、高速だがダメージの少ない第一攻撃と、遅いがダメージの多い第二攻撃がある。バックスタブで静かに一撃必殺。" },
	["knife_t"] = { name = "ナイフ", desc = "静かでいつでも使用できるナイフには、素早くダメージの少ない第一攻撃と、遅くダメージの大きい第二攻撃がある。隠密行動中のプレイヤーは、バックスタブで敵を一撃で倒すことが可能。" },
	["knife_gg"] = "ゴールドナイフ",
	["knife_ghost"] = { name = "スペクトルシフ", desc = "ゴーストはゴーストナイフを好む。ゴーストが手にした時には気を付けろ！奴らは隙あらばで刺しに来るだろう。残念ながら、彼らは所詮ゴーストで、ゴーストナイフで人は傷つけられないが…." },
	["m249"] = { name = "M249", desc = "強力な開けた場所用の LMG である M249 は、射撃速度の遅さを引き換えにさらなる精度と高い弾倉容量を望むプレイヤーに最適な選択。" },
	["m4a1"] = "M4A4",
	["m4_silencer"] = "M4A1-S",
	["m4a1_silencer"] = { name = "M4A1-S", desc = "消音器を外した同等品よりも弾倉が小さい消音器付き M4A1 。反動が小さく、精度が高い上に発砲音が静かだ。" },
	["mac10"] = { name = "MAC-10", desc = "本質的には弾丸が出てくる箱である MAC-10 サブマシンガンは、高い射撃速度を誇るが、引き換えに集弾精度が低く、反動が激しい。" },
	["p90"] = { name = "P90", desc = "独自のブルパップデザインにより一目で見分けが付くP90は、 大容量マガジンと低リコイルにより移動時の射撃に優れた武器。" },
	["smoke_grenade"] = { name = "スモークグレネード", desc = "スモークグレネードは、中程度のエリアに煙の覆いを作り出す。狙撃手から効果的にチームを隠すことができ、あるいは有効に撹乱をすることも可能。" },
	["ump45"] = { name = "UMP-45", desc = "SMG 家族の誤解された中子である UMP45 は万能型の近接戦闘用オートマチックだが、少容量の弾倉だけが唯一の欠点。" },
	["xm1014"] = { name = "XM1014", desc = "強力なオートマチックショットガンである XM1014 は、高速に空間を鉛弾で埋め尽くす能力を持ってその高価な価格を正当化する。" },
	["c4"] = { name = "C4 Explosive", desc = "ほとんどの物理的衝撃に対する耐久性と安定性のあるこの即席プラスチック爆弾は、起爆時に秒間8,000メートル以上の爆轟速度を持つ。" },
	["bizon"] = { name = "PP-Bizon", desc = "Bizon サブマシンガンは威力こそ弱いものの、 素早くリロードできる独特な構造の大容量ドラムマガジンを備えている。" },
	["mag7"] = { name = "MAG-7", desc = "CT 専用の Mag-7 は近距離では圧倒的なダメージ量を誇る。素早い弾倉形式のリロードを誇る、素晴らしい戦術的選択。" },
	["negev"] = { name = "Negev", desc = "コントロールする時間の贅沢があれば、Negevはピンポイントの射撃で敵を寄せ付けない獣だ。" },
	["sawedoff"] = { name = "Sawed-Off", desc = "古典的な Sawed-Off は激しい近距離ダメージを与えるが、精度の低さや低い集弾性、射撃速度の低さを考慮し、狙いは必ず仕留めるようにした方がいい。" },
	["tec9"] = { name = "Tec-9", desc = "行動中のテロリストには理想の拳銃であるTec-9は近接戦における高い殺傷力と、多くの装弾数を持つ。" },
	["taser"] = { name = "Zeus x27", desc = "近距離の奇襲や密閉された場所での遭遇戦に持ってこいな 単発の Zeus　x27 は、一撃で敵を無力化することができる。" },
	["molotov"] = { name = "火炎瓶", desc = "火炎瓶は強力で、投げて地面に当たると炎上し、範囲内にいる全プレイヤーにダメージを与える予測できない領域拒否武器。" },
	["incgrenade"] = "焼夷グレネード",
	["decoy"] = "デコイグレネード",
	["hkp2000"] = { name = "P2000", desc = "正確で制御しやすいドイツ製の P2000。実用向きで単発の防弾ベストを着用していない敵を相手にする時に最も有効に働く拳銃だ。" },
	["mp7"] = { name = "MP7", desc = "万能だが高価なドイツ製の MP7 サブマシンガンは、激しい近接戦に最適な選択。" },
	["mp5sd"] = { name = "MP5-SD", desc = "多様な使い方のできる SMG で世界で最も人気が高く、象徴的な MP5としてよく模造の対象となるが本物には遠く及ばない。この SD の変種は統合されたサイレンサーを特徴とし、既に強力な武器に囁くような静謐さを追加。" },
	["mp9"] = { name = "MP9", desc = "スイスで製造された最先端の MP9 サブマシンガンは、民間警備会社が愛用する人間工学に基づいたポリマー製武器。" },
	["nova"] = { name = "Nova", desc = "Nova の最低レベルの価格は、それを資金に乏しいチームにとっての素晴らしい奇襲武器となる。" },
	["p250"] = { name = "P250", desc = "発射速度が高く低反動な銃火器である P250 は、防弾ベストを着用した敵を相手にする際に相対的に安価な選択。" },
	["cz75"] = "CZ75-Auto",
	["scar20"] = { name = "SCAR-20", desc = "セミオートマチックのスナイパーライフルである SCAR-20 は、高い射撃速度と強力な長距離ダメージの代わりに、移動速度が遅く、価格も高い。" },
	["sg556"] = "SG 553",
	["ssg08"] = { name = "SSG 08", desc = "ボルトアクションの SSG08 は、ダメージは低いが非常にコストパフォーマンスの高いスナイパーライフルで、初期のラウンドの長距離狙撃に向いた賢い選択。" },
	["heavyassaultsuit"] = "ヘビーアサルトスーツ",
	["assaultsuit"] = "ケブラー + ヘルメット",
	["kevlar"] = "ケブラーベスト",
	["defuser"] = "爆弾解除キット",
	["cutters"] = "救助キット",
	["revolver"] = { name = "R8 Revolver", desc = "R8 Revolver は、トリガーを引くのに時間がかかる代わりに、正確で強力な一撃を与えることができる。至近距離での致命的な一撃が必要なときには、ハンマーを手で弾くことによって連射が可能だ。" },
	["usp_silencer"] = { name = "USP-S", desc = "Counter-Strike Source のファンのお気に入りである消音器付き USP ピストルには、射撃時の反動を抑え、なおかつ注意を引いてしまう雑音を抑えることの出来る取り外し可能なサイレンサーがついている。" },
	["knifebayonet"] = { name = "銃剣", desc = "第ニ次世界大戦から比較的設計面で変更がなされていない銃剣は、現代の軍事戦略において今なお地位を確保している。銃剣突撃は、第二次湾岸戦争やアフガニスタン戦争ほど最近までその有効性を保ってきた。" },
	["knifeflip"] = { name = "折りたたみナイフ", desc = "Flip ナイフは鋭利な一点を持つペルシャ式の後ろに傾斜した刃を誇る。その点自体は脆いが、 Flip ナイフの全体の設計は驚くほど頑強だ。" },
	["knifegut"] = { name = "ガットナイフ", desc = "ガットナイフの最も注目に値する特徴は、刃の背の部分にあるガットフック。元来、狩猟で獲物の解体を補助するものとして普及したガットフックは、ロープや帯ひも、安全バンドのような、繊維状の素材を容易に切断するのにも効果を発揮する。" },
	["knifecss"] = { name = "クラシックナイフ", desc = "A classic of the Counter-Strike series, the edge of this knife is press-fit Stellite perfectly held in place due to its precise fit with the titanium on the blade's cheek and spine. The handle is fossilized mastodon ivory held in a carbon fibre pocket." },
	["knifem9"] = { name = "M9バヨネット", desc = "M-9 銃剣。もともとライフルに装着されることを想定された武器だが、接近戦にもよく適している。" },
	["knifekaram"] = { name = "カランビット", desc = "トラの爪を模倣した湾曲した刃を持つ Karambit は東南アジアのシラットの軍事訓練の一環として開発された。このナイフは概して逆手のグリップと、人差し指につける指輪を装備して使用される。" },
	["knifetactical"] = { name = "Huntsman ナイフ", desc = "現代での戦術的使用のために設計されたナイフであり、その刃は戦闘にも実用にも、どちらの需要にもぴったり。独特な短刀刃は最も硬い部分でさえ最大限に貫通する。" },
	["knife_butterfly"] = { name = "バタフライナイフ", desc = "一般的にはバタフライナイフとして知られているカスタム設計されたバリソン。決定的特徴であるファンに似た自由に回転する刃の取り出し方が、素早い展開や隠匿を可能にする。結果として、バタフライナイフは多くの国で非合法化されている。" },
	["partypopper"] = "パーティー・クラッカー！",
	["knife_falchion_advanced"] = { name = "Falchion ナイフ", desc = "このクリップポイントナイフは、ファルシオンへの現代的オマージュであり、湾曲したエッジを持つ。" },
	["knife_push"] = { name = "シャドウダガー", desc = "効率的な残虐行為用に設計されたプッシュダガーは、パンチするのと同じぐらい簡単使える。" },
	["knife_survival_bowie"] = { name = "ボウイナイフ", desc = "このフルタング Sawback Bowie ナイフは、過酷なサバイバル環境での酷使に耐えられるよう設計されている。" },
	["tagrenade"] = "タクティカルアウェアネスグレネード",
	["snowball"] = "Snowball",
	["dangerzone"] = "Danger Zone",
	["autosentry"] = "自動セントリーガン",
	["fists"] = "素手",
	["tablet"] = "タブレット",
	["breachcharge"] = "ブリーチングチャージ",
	["axe"] = { name = "斧", desc = "Heavy and always available, the axe has a sharp side and a dull side. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. How much wood would a woodchuck chuck?" },
	["hammer"] = { name = "ハンマー", desc = "The hammer is available for fixing things and breaking things. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. If all you have is a hammer, everything looks like a nail." },
	["spanner"] = { name = "レンチ", desc = "A wrench is typically used to apply torque when turning objects, but you can hit anything with it for low-damage primary attack or throw it for a high-damage secondary attack. Bringing a wrench to a firefight is a recipe for screwing up." },
	["tripwirefire"] = "トラップファイア",
	["knife_cord"] = { name = "パラコードナイフ", desc = "This fixed-blade survival knife is designed to withstand being used as both a weapon and a tool, such as for setting traps, hunting animals or cutting foliage. The handle is wrapped in a length of multi-purpose paracord." },
	["knife_canis"] = { name = "サバイバルナイフ", desc = "This multi-purpose tactical knife features a serrated edge for ripping through coarse material like bone or fiber, plus a sharp gutting hook. The composite material handle is bolted to the blade with hex nuts." },
	["knife_ursus"] = { name = "Ursus ナイフ", desc = "この短刀型のサバイバルナイフはファセット刃とフルタングに加え、耐衝撃用ポンメルを備え持つ。手間要らずで可動部分もなく、すぐに使える頼れるナイフだ。" },
	["knife_gypsy_jackknife"] = { name = "Navaja ナイフ", desc = "この大理石エナメルハンドルのフリップナイフは、小さいながらも凶悪な先細の刃を隠し持つ。" },
	["knife_widowmaker"] = { name = "Talon ナイフ", desc = "この象牙ハンドルのカランビットナイフは、真鍮のリベットと鋸歯の峰を持ち、突くと切り、抜くと裂く。" },
	["knife_stiletto"] = { name = "Stiletto ナイフ", desc = "歴史的に論争や規制の的となってきたイタリアンスタイルのスティレットのスイッチブレードナイフ。リリーススイッチを押すと瞬時に飛び出すバネ式の刃を併せ持つ。" },
	["knife_skeleton"] = { name = "スケルトンナイフ", desc = "This skeletonized-tang knife has been taped at the handle for improved grip. The hole allows a finger to be threaded through for stability and safety." },
	["firebomb"] = { name = "焼夷弾", desc = "焼夷弾は強力な実験的武器で、地面に投げられると爆発して高温の炎となり、広範囲に渡りあらゆるプレーヤーを化学的に燃やす。" },
	["diversion"] = { name = "陽動デバイス", desc = "陽動デバイスを使用すると、タブレット上のセクターを強調表示し、追加の敵の幻影を作り出す。" },
	["frag_grenade"] = { name = "破片手榴弾", desc = "実験的フラググレネードは、より広範囲で激しい爆発ダメージを大量に与えることができ、攻撃戦略と防御戦略の両方に理想的だ。" },
	["shield"] = { name = "ライオットシールド", desc = "A protection device designed to deflect or absorb ballistic damage and help protect the carrier from an array of projectile calibers." },
	["cz75a"] = "CZ75をフルオートマチックに改造したCZ75-Autoは、戦局をひっくり返し、相手の武器を奪うのに理想的な短期決戦用の選択だ。しかし、マガジンに装填されている弾薬が極めて少なく、正確な射撃が求められる。",
	["m4a4"] = "同等級の AK-47 より精度が高いがダメージが少ない M4A4 は、 CT の第一選択肢となるフルオートのアサルトライフル。",
	["sg553"] = "テロリスト専用の SG553 は、長距離での交戦に効果的な AK47 の高級なスコープ付き代替品。",
	["decoy_grenade"] = "デコイグレネードを投擲すると、携帯している中で最も強力な武器の音を再現し、さらなる増援の幻影を作り出す。",
	["incindiary_grenade"] = "焼夷手榴弾を投げると、広い爆破範囲内の全員を燃やしてしまうことができる高温の化学反応を発生させる。",
	["healthshot"] = "Medi-Shot",
	["exploding_barrel"] = "Exploding Barrel",
	["stompdamagekillstring"] = "crushed your skull",
	["bumpmine"] = "Bump Mine",
	["knife_outdoor"] = { name = "Nomad Knife", desc = "This ergonomic tactical hunting lock-blade knife features composite handle inserts and a broad, sturdy blade, useful for cutting and prying apart material." },
	["zone_repulsor"] = { name = "Repulsor Device", desc = "Prototype Radial Emission Particulate Shielding Device" },
	["survival_taser"] = "Extremely short range weapon capable of killing in one shot. Can also be used to open weapon crates.",
	["survival_healthshot"] = "Restores a portion of your health and provides a brief speed boost.",
	["survival_vesthelm"] = "Provides resistance to damage.",
	["survival_shield"] = "A ballistic riot shield which can block a large amount of damage before being destroyed.",
	["survival_parachute"] = "Can be deployed when falling to prevent fall damage.",
	["survival_exojump"] = "Significantly increases jump height.",
	["survival_c4"] = "Plant anywhere in the map to cause a large explosion. Can be used to open safes.",
	["survival_dronepilot"] = "Grants the ability to take control of drones. Use the tablet to select a drone to take over.",
	["survival_exploremoney"] = "Grants extra money for each hex explored.",
	["survival_wavemoney"] = "Grants extra money for each danger zone expansion wave survived.",
}
