csstring = { -- English
	["cat_pistols"] = "Pistols",
	["cat_heavy"] = "Heavy",
	["cat_smg"] = "SMGs",
	["cat_rifles"] = "Rifles",
	["cat_grenades"] = "Grenades",
	["cat_gear"] = "Gear",

    ["ak47"] = { name = "AK-47", desc = "Powerful and reliable, the AK-47 is one of the most popular assault rifles in the world. It is most deadly in short, controlled bursts of fire." },
    ["aug"] = { name = "AUG", desc = "Powerful and accurate, the AUG scoped assault rifle compensates for its long reload times with low spread and a high rate of fire." },
    ["awp"] = { name = "AWP", desc = "High risk and high reward, the infamous AWP is recognizable by its signature report and one-shot, one-kill policy." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "As expensive as it is powerful, the Desert Eagle is an iconic pistol that is difficult to master but surprisingly accurate at long range." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Dual Berettas", desc = "Firing two large-mag Berettas at once will lower accuracy and increase load times. On the bright side, you'll get to fire two large-mag Berettas at once." },
    ["elite"] = "Dual Berettas",
    ["famas"] = { name = "FAMAS", desc = "A cheap option for cash-strapped players, the FAMAS effectively fills the niche between more expensive rifles and the less-effective SMGs." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Highly accurate and armor-piercing, the pricy Five-Seven is a slow-loader that compensates with a generous 20-round magazine and forgiving recoil." },
    ["flashbang"] = { name = "Flashbang", desc = "The non-lethal flashbang grenade temporarily blinds anybody within its concussive blast, making it perfect for flushing out closed-in areas. Its loud explosion also temporarily masks the sound of footsteps." },
    ["g3sg1"] = { name = "G3SG1", desc = "The pricy G3SG1 lowers movement speed considerably but compensates with a higher rate of fire than other sniper rifles." },
    ["galilar"] = { name = "Galil AR", desc = "A less expensive option among the terrorist-exclusive assault rifles, the Galil AR is a serviceable weapon in medium to long-range combat." },
    ["glock18"] = { name = "Glock-18", desc = "The Glock 18 is a serviceable first-round pistol that works best against unarmored opponents and is capable of firing three-round bursts." },
    ["he_grenade"] = { name = "High Explosive Grenade", desc = "The high explosive fragmentation grenade administers high damage through a wide area, making it ideal for clearing out hostile rooms." },
    ["he_grenade_short"] = "HE Grenade",
    ["hegrenade"] = "High Explosive Grenade",
    ["knife"] = { name = "Knife", desc = "Quiet and always available, the knife has a fast, low-damage primary attack and a slow, high-damage secondary attack. A backstab will earn quiet players an instant kill." },
    ["knife_t"] = "Knife",
    ["knife_gg"] = "Gold Knife",
    ["knife_ghost"] = { name = "Spectral Shiv", desc = "Ghosts love ghost knives. When they get their hands on one, look out! They'll try stab you first chance they get. Too bad they are a ghost and ghost knives can't hurt people...." },
    ["m249"] = { name = "M249", desc = "A strong open-area LMG, the M249 is the perfect choice for players willing to trade a slow fire rate for increased accuracy and a high ammo capacity." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "With a smaller magazine than its unmuffled counterpart, the silenced M4A1 provides quieter shots with less recoil and better accuracy." },
    ["mac10"] = { name = "MAC-10", desc = "Essentially a box that bullets come out of, the MAC-10 SMG boasts a high rate of fire, with poor spread accuracy and high recoil as trade-offs." },
    ["p90"] = { name = "P90", desc = "Easily recognizable for its unique bullpup design, the P90 is a great weapon to shoot on the move due to its high-capacity magazine and low recoil." },
    ["smoke_grenade"] = { name = "Smoke Grenade", desc = "The smoke grenade creates a medium-area smoke screen. It can effectively hide your team from snipers, or even just create a useful distraction." },
    ["smokegrenade"] = "Smoke Grenade",
    ["ump45"] = { name = "UMP-45", desc = "The misunderstood middle child of the SMG family, the UMP45's small magazine is the only drawback to an otherwise versatile close-quarters automatic." },
    ["xm1014"] = { name = "XM1014", desc = "The XM1014 is a powerful fully automatic shotgun that justifies its heftier price tag with the ability to paint a room with lead fast." },
    ["c4"] = { name = "C4 Explosive", desc = "Stable and resistant to most physical shocks, this improvised plastic explosive has a detonation velocity of over 8,000 meters per second when ignited." },
    ["bizon"] = { name = "PP-Bizon", desc = "The Bizon SMG is low-damage, but offers a uniquely designed high-capacity drum magazine that reloads quickly." },
    ["mag7"] = { name = "MAG-7", desc = "The CT-exclusive Mag-7 delivers a devastating amount of damage at close range. Its rapid magazine-style reloads make it a great tactical choice." },
    ["negev"] = { name = "Negev", desc = "The Negev is a beast that can keep the enemy at bay with its pin-point supressive fire, provided you have the luxury of time to gain control over it." },
    ["sawedoff"] = { name = "Sawed-Off", desc = "The classic Sawed-Off deals very heavy close-range damage, but with its low accuracy, high spread and slow rate of fire, you'd better kill what you hit." },
    ["tec9"] = { name = "Tec-9", desc = "An ideal pistol for the Terrorist on the move, the Tec-9 is lethal in close quarters and features a high magazine capacity." },
    ["taser"] = { name = "Zeus x27", desc = "Perfect for close-range ambushes and enclosed area encounters, the single-shot x27 Zeus is capable of incapacitating an enemy in a single hit." },
    ["molotov"] = { name = "Molotov", desc = "The Molotov is a powerful and unpredictable area denial weapon that bursts into flames when thrown on the ground, injuring any player in its radius." },
    ["incgrenade"] = "Incendiary Grenade",
    ["incgrenade_short"] = "Incendiary",
    ["decoy"] = "Decoy Grenade",
    ["decoy_short"] = "Decoy",
    ["hkp2000"] = { name = "P2000", desc = "Accurate and controllable, the German-made P2000 is a serviceable first-round pistol that works best against unarmored opponents." },
    ["mp7"] = { name = "MP7", desc = "Versatile but expensive, the German-made MP7 SMG is the perfect choice for high-impact close-range combat." },
    ["mp5sd"] = { name = "MP5-SD", desc = "Often imitated but never equaled, the iconic MP5 is perhaps the most versatile and popular SMG in the world. This SD variant features an integrated silencer, making an already formidable weapon whisper-quiet." },
    ["mp9"] = { name = "MP9", desc = "Manufactured in Switzerland, the cutting-edge MP9 SMG is an ergonomic polymer weapon favored by private security firms." },
    ["nova"] = { name = "Nova", desc = "The Nova's rock-bottom price tag makes it a great ambush weapon for a cash-strapped team." },
    ["p250"] = { name = "P250", desc = "A low-recoil firearm with a high rate of fire, the P250 is a relatively inexpensive choice against armored opponents." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "The SCAR-20 is a semi-automatic sniper rifle that trades a high rate of fire and powerful long-distance damage for sluggish movement speed and big price tag." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "The SSG08 bolt-action is a low-damage but very cost-effective sniper rifle, making it a smart choice for early-round long-range marksmanship." },
    ["heavyassaultsuit"] = "Heavy Assault Suit",
    ["assaultsuit"] = "Kevlar & Helmet",
    ["assaultsuit_only_helmet"] = "Helmet",
    ["kevlar"] = "Kevlar Vest",
    ["defuser"] = "Defuse Kit",
    ["cutters"] = "Rescue Kit",
    ["revolver"] = { name = "R8 Revolver", desc = "The R8 Revolver delivers a highly accurate and powerful round at the expense of a lengthy trigger-pull. Firing rapidly by fanning the hammer may be the best option when point-blank stopping power is required." },
    ["usp_silencer"] = { name = "USP-S", desc = "A fan favorite from Counter-Strike Source, the Silenced USP Pistol has a detachable silencer that gives shots less recoil while suppressing attention-getting noise." },
    ["knifebayonet"] = { name = "Bayonet", desc = "Relatively unchanged in its design since World War II, the bayonet still retains a place in modern military strategy. Bayonet charges have continued to be effective as recently as the second Gulf War and the war in Afghanistan." },
    ["knifeflip"] = { name = "Flip Knife", desc = "Flip knives sport a Persian-style back-swept blade with an acute point.  While the point itself may be fragile, the overall design of the flip knife's design is surprisingly durable." },
    ["knifegut"] = { name = "Gut Knife", desc = "The most notable feature of a gut knife is the gut hook on the spine of the blade.  Originally popularized as an aid for field dressing game, the gut hook is also effective at  cutting through fibrous materials like rope, webbing, or safety belts with ease." },
    ["knifecss"] = { name = "Classic Knife", desc = "A classic of the Counter-Strike series, the edge of this knife is press-fit Stellite perfectly held in place due to its precise fit with the titanium on the blade's cheek and spine. The handle is fossilized mastodon ivory held in a carbon fibre pocket." },
    ["knifem9"] = { name = "M9 Bayonet", desc = "This is the M-9 bayonet.  Originally intended to be mounted on a rifle, it is also well suited to close-quarters combat." },
    ["knifekaram"] = { name = "Karambit", desc = "With its curved blade mimicking a tiger's claw, the karambit was developed as part of the southeast Asian martial discipline of silat. The knife is typically used with a reverse grip, with the finger ring on the index finger." },
    ["knifetactical"] = { name = "Huntsman Knife", desc = "A knife designed for modern tactical uses, the blade is well suited for a range of both combat and utilitarian needs.  The unique Tanto point allows for maximum penetration through even the toughest of surfaces." },
    ["knife_butterfly"] = { name = "Butterfly Knife", desc = "This is a custom-designed balisong, commonly known as a butterfly knife. The defining characteristic of this weapon is the fan-like opening of a freely pivoting blade, allowing rapid deployment or concealment. As a result, butterfly knives are outlawed in many countries." },
    ["partypopper"] = "Party Popper!",
    ["knife_falchion_advanced"] = { name = "Falchion Knife", desc = "A modern homage to a falchion sword, this clip point blade has a curved edge." },
    ["knife_push"] = { name = "Shadow Daggers", desc = "Designed for efficient brutality, using a push dagger is as simple as throwing a punch or two." },
    ["knife_survival_bowie"] = { name = "Bowie Knife", desc = "This full-tang sawback Bowie knife is designed for heavy use in brutal survival situations." },
    ["healthshot"] = "Medi-Shot",
    ["tagrenade"] = "Tactical Awareness Grenade",
    ["exploding_barrel"] = "Exploding Barrel",
    ["snowball"] = "Snowball",
    ["stompdamagekillstring"] = "crushed your skull",
    ["dangerzone"] = "Danger Zone",
    ["autosentry"] = "Automated Sentry",
    ["fists"] = "Bare Hands",
    ["tablet"] = "Tablet",
    ["breachcharge"] = "Breach Charge",
    ["bumpmine"] = "Bump Mine",
    ["axe"] = { name = "Axe", desc = "Heavy and always available, the axe has a sharp side and a dull side. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. How much wood would a woodchuck chuck?" },
    ["hammer"] = { name = "Hammer", desc = "The hammer is available for fixing things and breaking things. Swing it for low-damage primary attack or throw it for a high-damage secondary attack. If all you have is a hammer, everything looks like a nail." },
    ["spanner"] = { name = "Wrench", desc = "A wrench is typically used to apply torque when turning objects, but you can hit anything with it for low-damage primary attack or throw it for a high-damage secondary attack. Bringing a wrench to a firefight is a recipe for screwing up." },
    ["tripwirefire"] = "TrapFire",
    ["knife_cord"] = { name = "Paracord Knife", desc = "This fixed-blade survival knife is designed to withstand being used as both a weapon and a tool, such as for setting traps, hunting animals or cutting foliage. The handle is wrapped in a length of multi-purpose paracord." },
    ["knife_canis"] = { name = "Survival Knife", desc = "This multi-purpose tactical knife features a serrated edge for ripping through coarse material like bone or fiber, plus a sharp gutting hook. The composite material handle is bolted to the blade with hex nuts." },
    ["knife_ursus"] = { name = "Ursus Knife", desc = "This tanto-style survival knife features a faceted blade and full tang, complete with impact pommel. No fuss, no moving parts - just a reliable blade that's ready to work." },
    ["knife_gypsy_jackknife"] = { name = "Navaja Knife", desc = "This marble-enamel-handled flip knife conceals a small but viciously tapered blade." },
    ["knife_outdoor"] = { name = "Nomad Knife", desc = "This ergonomic tactical hunting lock-blade knife features composite handle inserts and a broad, sturdy blade, useful for cutting and prying apart material." },
    ["knife_widowmaker"] = { name = "Talon Knife", desc = "This ivory-handled karambit features brass rivets and saw-tooth ridges, so it cuts on the way in, and tears on the way out." },
    ["knife_stiletto"] = { name = "Stiletto Knife", desc = "Historically a focal point of contention and even regulation, this Italian-style stiletto switchblade knife features a spring-loaded blade that can be deployed almost instantly with the push of a release catch." },
    ["knife_skeleton"] = { name = "Skeleton Knife", desc = "This skeletonized-tang knife has been taped at the handle for improved grip. The hole allows a finger to be threaded through for stability and safety." },
    ["knife_kukri"] = { name = "Kukri Knife", desc = "Used in traditional rituals, such as weddings or stabbings." },
    ["firebomb"] = { name = "Fire Bomb", desc = "The Fire Bomb is a powerful experimental weapon that bursts into high-temperature flames when thrown on the ground, chemically burning any player in its wide spread radius." },
    ["diversion"] = { name = "Diversion Device", desc = "When thrown, the diversion device will highlight sectors on tablets, creating the illusion of additional enemies." },
    ["frag_grenade"] = { name = "Frag Grenade", desc = "The experimental fragmentation grenade can output extreme amounts of highly explosive damage in a wider area, making it ideal for both attacking and defensive strategies." },
    ["shield"] = "Riot Shield",
    ["zone_repulsor"] = { name = "Repulsor Device", desc = "Prototype Radial Emission Particulate Shielding Device" },
    ["glock_use"] = "• Deadly up close, just a nuisance at range\n• Consider in the first round of the half\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Accurate at range, spammable up close\n• Consider in the first round of the half\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Precise, silent, and (somewhat) deadly\n• Consider in the first round of the half\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Two rapid-fire pistols for the price of one\n• Consider in the first round of the half\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• A popular, if modest, damage upgrade\n• Consider in eco rounds\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Power, speed, and precision for a price\n• Consider in eco rounds\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• A burst of firepower to steal enemy weapons\n• Consider in eco rounds\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Highly mobile, effective at range and up close\n• Consider in eco rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Deals massive damage after a short delay\n• Consider in eco rounds\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• A lethal headshot at any range\n• Consider in eco rounds\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• A rechargeable one shot kill at short range\n• Attempt at your own risk\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• A hail of bullets to mow down unarmored enemies\n• Consider in the first three rounds of the half\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• A run and gun tool for breaching bombsites\n• Consider in the first three rounds of the half\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• A burst of damage to deny an enemy rush\n• Consider in the first three rounds of the half\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Easy to control for reliable mid-range damage\n• Consider in force buy rounds\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Nimble and stealthy for mid-range damage\n• Consider in force buy rounds\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Good armor penetration for mid-range fights\n• Consider in force buy rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• An endless bullet hose bested only by rifles\n• Consider in full buy rounds\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Cheap but effective against armored enemies\n• Consider in force buy rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Cheap but effective against armored enemies\n• Consider in force buy rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• The classic, accurate, and deadly workhorse\n• Consider in full buy rounds\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Good accuracy, with ammo to spare\n• Consider in full buy rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Precise, silent, tracer-free\n• Consider in full buy rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• An optional scope for exceptional accuracy\n• Consider in full buy rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• A lethal weapon made deadlier with a scope\n• Consider in full buy rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Devastating power for the confident sniper\n• Consider in full buy rounds\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• High risk/reward automatic sniper rifle\n• Consider only under special circumstances\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• A potent (if risky) tool to hold a position\n• Consider only under special circumstances\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Light and powerful long-distance damage dealer\n• Consider in force buy rounds\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Take the enemy by surprise, reload, repeat!\n• Consider in force buy rounds\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Versatile shotgun for close quarter combat\n• Consider in force buy rounds\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• High powered shotgun for close engagements\n• Consider in force buy rounds\n• Difficulty: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• A full-auto rapid-fire monster\n• Consider in force buy rounds\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• At least you won't have to reload...\n• Consider only under special circumstances\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Pin-point suppressive fire to buy some time\n• Consider in force buy rounds\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Deal damage or clear smoke grenades\n• Use with discretion\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Blinds/deafens nearby players\n• Throw prior to an attack\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Creates a large smoke cloud\n• Throw to cut off enemy line of sight\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Mimics a weapon firing sound\n• Throw early to confuse the enemy\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Clears out hiding spots with fire\n• Throw before attacking a bombsite\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Stifles enemy attacks with fire\n• Throw at the first sign of trouble\n• Difficulty: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Survive all but the most lethal bullets\n• Consider in full buy and force buy rounds\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Protects everything but your head\n• Consider in the first round of the half\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Cut your defusing time in half\n• Don't be a loser, buy a defuser!\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Pick up hostages in a fraction of the time\n• Consider when you have extra funds\n• Difficulty: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "A fully automatic variant of the CZ75, the CZ75-Auto is the ideal short-term choice for turning the tables and gaining your opponents weapon. But with very little ammo in the magazine, strong trigger discipline is required.",
    ["m4a4"] = "More accurate but less damaging than its AK-47 counterpart, the M4A4 is the full-auto assault rifle of choice for CTs.",
    ["sg553"] = "The terrorist-exclusive SG553 is a premium scoped alternative to the AK47 for effective long-range engagement.",
    ["decoy_grenade"] = "When thrown, the decoy grenade emulates the sound of the most powerful weapon you are carrying, creating the illusion of additional supporting forces.",
    ["incindiary_grenade"] = "When thrown, the incendiary grenade releases a high-temperature chemical reaction capable of burning anyone within its wide blast radius.",
    ["survival_taser"] = "Extremely short range weapon capable of killing in one shot. Can also be used to open weapon crates.",
    ["survival_healthshot"] = "Restores a portion of your health and provides a brief speed boost.",
    ["survival_vesthelm"] = "Provides resistance to damage.",
    ["survival_shield"] = "A ballistic riot shield which can block a large amount of damage before being destroyed.",
    ["survival_parachute"] = "Can be deployed when falling to prevent fall damage.",
    ["survival_exojump"] = "Significantly increases jump height.",
    ["survival_c4"] = "Plant anywhere in the map to cause a large explosion. Can be used to open safes.",
    ["survival_dronepilot"] = "Grants the ability to take control of drones. Use the tablet to select a drone to take over.",
    ["survival_exploremoney"] = "Grants extra money for each hex explored.",
    ["survival_wavemoney"] = "Grants extra money for each danger zone expansion wave survived.",
}
