csstring = { -- German
	["cat_pistols"] = "Pistolen",
	["cat_heavy"] = "Schwer",
	["cat_smg"] = "MPs",
	["cat_rifles"] = "Gewehre",
	["cat_grenades"] = "Granaten",
	["cat_gear"] = "Ausrüstung",

    ["ak47"] = { name = "AK-47", desc = "Als eines der beliebtesten Sturmgewehre der Welt ist das AK-47 sehr stark und zuverlässig. Mit kurzen, kontrollierten Feuerstößen ist diese Waffe besonders tödlich." },
    ["aug"] = { name = "AUG", desc = "Bekannt als mächtige und genaue Waffe kompensiert das mit einem Zielfernrohr ausgestattete AUG-Sturmgewehr seine lange Nachladezeit mit einem geringen Streuradius und einer hohen Feuerrate." },
    ["awp"] = { name = "AWP", desc = "Mit hohem Risiko und hohem Gewinn ist das AWP wegen seines unverkennbaren Schussgeräusches und seiner tödlichen Einzeltreffer berüchtigt." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Die genauso wirksame wie teure Desert Eagle ist eine Pistole mit Kultstatus, die zwar schwer zu beherrschen, aber auf weite Distanzen überraschend präzise ist." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Akimbo-Berettas", desc = "Das gleichzeitige Abfeuern zweier Berettas mit großen Magazinen verringert die Genauigkeit und erhöht die Nachladedauer. Wenn man es jedoch mal positiv betrachtet, so kommen Sie immerhin zum gleichzeitigen Abfeuern zweier Berettas mit großen Magazinen." },
    ["elite"] = "Akimbo-Berettas",
    ["famas"] = { name = "FAMAS", desc = "Als günstige Option für Spieler mit begrenztem Budget schließt das FAMAS die Lücke zwischen den teureren Gewehren und den weniger effektiven Maschinenpistolen." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Die sehr präzise und panzerbrechende Five-SeveN ist eine kostspielige Pistole mit langer Nachladedauer, welche dafür ein großzügiges 20-Patronen-Magazin und einen einfach zu handhabenden Rückschlag bietet." },
    ["flashbang"] = { name = "Blendgranate", desc = "Die ungefährliche Blendgranate blendet zeitweise jeden innerhalb ihres Explosionsradius. Dadurch eignet sie sich perfekt, um eingeschlossene Gebiete freizuräumen. Ihre laute Explosion überdeckt außerdem für eine gewisse Zeitspanne das Geräusch von Schritten." },
    ["g3sg1"] = { name = "G3SG1", desc = "Das teure G3SG1 verringert die Laufgeschwindigkeit stark, macht dies aber mit einer hohen Feurrate wieder wett, die andere Scharfschützengewehre in den Schatten stellt." },
    ["galilar"] = { name = "Galil AR", desc = "Als weniger teure Option unter den Sturmgewehren, die ausschließlich den Terroristen zur Verfügung stehen, gilt das Galil-Sturmgewehr als brauchbare Waffe beim Kampf auf mittlere bis lange Distanz." },
    ["glock18"] = { name = "Glock-18", desc = "Die Glock 18 ist eine brauchbare Pistole für die erste Runde, die am effektivsten gegen ungepanzerte Gegner eingesetzt werden kann und in der Lage ist, drei Kugeln gleichzeitig abzufeuern." },
    ["he_grenade"] = { name = "Splittergranate", desc = "Die hochexplosive Splittergranate sorgt für hohen Schaden auf großer Fläche, was sie ideal zum Freiräumen von feindlich besetzten Räumen macht." },
    ["he_grenade_short"] = "Splittergranate",
    ["hegrenade"] = "Splittergranate",
    ["knife"] = { name = "Messer", desc = "Das leise und stets verfügbare Messer hat einen schnellen, wenig Schaden anrichtenden Primärangriff und einen langsamen, hohen Schaden anrichtenden Sekundärangriff, welcher leisen Spielern bei einem Rückenstich einen sofortigen Kill einbringt." },
    ["knife_t"] = "Messer",
    ["knife_gg"] = "Goldenes Messer",
    ["knife_ghost"] = { name = "Geisterhaftes Klappmesser", desc = "Geister lieben Geistermesser. Wenn sie eins bekommen, sollten Sie aufpassen! Sie werden versuchen, Sie bei der ersten Gelegenheit zu erstechen. Zu schade, dass sie Geister sind und Geistermesser Menschen nicht verletzen können …" },
    ["m249"] = { name = "M249", desc = "Als solides Maschinengewehr für offenes Gelände ist das M249 die perfekte Wahl für Spieler, die gute Präzision und ein großes Magazin einer hohen Feuerrate vorziehen." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Mit einem kleineren Magazin ausgestattet als das nicht schallgedämpfte Gegenstück, liefert die schallgedämpfte M4A1 leisere Schüsse mit weniger Rückschlag und besserer Präzision." },
    ["mac10"] = { name = "MAC-10", desc = "Die MAC-10, im Grunde genommen nur eine Box, die Kugeln ausspuckt, bietet eine hohe Feuerrate in Kombination mit geringer Präzision und hohem Rückstoß." },
    ["p90"] = { name = "P90", desc = "Die P90, leicht erkennbar durch ihr einzigartiges Bullpup-Design, ist dank ihrem großen Magazin und dem geringen Rückstoß eine großartige Waffe für Schüsse aus der Bewegung." },
    ["smoke_grenade"] = { name = "Rauchgranate", desc = "Die Rauchgranate erzeugt eine mittelgroße Nebelwand. Sie kann Ihr Team effektiv vor Scharfschützen bewahren oder auch nur als Ablenkungsmanöver dienen." },
    ["smokegrenade"] = "Rauchgranate",
    ["ump45"] = { name = "UMP-45", desc = "Das verkannte Mittelkind der MP-Familie - Das kleine Magazin der UMP45 ist der einzige Nachteil einer ansonsten vielseitigen Automatikwaffe für Nahkampfeinsätze." },
    ["xm1014"] = { name = "XM1014", desc = "Die XM1014 ist eine schlagkräftige, vollautomatische Schrotflinte, die ihren höheren Preis mit der Fähigkeit rechtfertigt, einen Raum schnell mit Blei zu füllen." },
    ["c4"] = { name = "C4-Sprengstoff", desc = "Stabil und widerstandsfähig gegen die meisten physischen Stöße, hat dieser behelfsmäßige Plastiksprengstoff bei seiner Zündung eine Explosionsgeschwindigkeit von mehr als 8.000 Metern pro Sekunde." },
    ["bizon"] = { name = "PP-Bizon", desc = "Die Bizon-Maschinenpistole verursacht wenig Schaden, bietet aber ein einzigartig entworfenes Helixmagazin mit hoher Kapazität und kurzer Nachladedauer." },
    ["mag7"] = { name = "MAG-7", desc = "Die AT-exklusive MAG-7 richtet auf geringe Distanz verheerenden Schaden an. Ihre dank Magazinen kurze Nachladedauer macht sie zu einer großartigen taktischen Wahl." },
    ["negev"] = { name = "Negev", desc = "Die Negev ist ein Biest, das den Gegner mit zielgenauem, unterdrückenden Kugelhagel auf Abstand halten kann – vorausgesetzt Sie haben den Luxus der Zeit, um es zu kontrollieren." },
    ["sawedoff"] = { name = "Abgesägte Schrotflinte", desc = "Die klassische abgesägte Schrotflinte verursacht auf kurze Distanz verheerende Schäden, aber mit ihrer geringen Genauigkeit, ihrem großen Streuradius und ihrer langsamen Feuerrate sollten Sie auch besser töten, was Sie treffen." },
    ["tec9"] = { name = "Tec-9", desc = "Als ideale Pistole für den Terroristen unterwegs, ist die Tec-9 tödlich in kleinen Räumen und bietet ein großes Magazin." },
    ["taser"] = { name = "Zeus x27", desc = "Die Einzelschusswaffe x27 Zeus kann einen Gegner mit einem einzigen Treffer außer Gefecht setzen und ist perfekt für Überfälle aus kurzer Distanz und in geschlossenen Bereichen geeignet." },
    ["molotov"] = { name = "Molotow", desc = "Der Molotowcocktail ist eine wirksame und unberechenbare gebietsverteidigende Waffe, die in Flammen ausbricht, sobald sie auf den Boden geworfen wird, und alle Spieler in ihrem Radius verletzt." },
    ["incgrenade"] = "Brandgranate",
    ["incgrenade_short"] = "Brandgranate",
    ["decoy"] = "Ködergranate",
    ["decoy_short"] = "Ködergranate",
    ["hkp2000"] = { name = "P2000", desc = "Mit ihrer hohen Präzision und Kontrollierbarkeit ist die in Deutschland hergestellte P2000 eine brauchbare Pistole für die erste Runde, die im Einsatz gegen ungepanzerte Gegner am effektivsten ist." },
    ["mp7"] = { name = "MP7", desc = "Als vielseitige aber teure Maschinenpistole ist die in Deutschland hergestellte MP7 die perfekte Wahl für den intensiven Nahkampf." },
    ["mp5sd"] = { name = "MP5-SD", desc = "Die oft kopierte, aber nie erreichte, ikonische MP5 ist wahrscheinlich die vielseitigste und beliebteste MP der Welt. Diese SD-Veriante kommt mit einem integrierten Schalldämpfer und macht eine bereits beeindruckende Waffe flüsterleise." },
    ["mp9"] = { name = "MP9", desc = "Die in der Schweiz hergestellte, innovative Maschinenpistole MP9 ist eine ergonomische Polymer-Waffe, die von privaten Sicherheitsfirmen bevorzugt wird." },
    ["nova"] = { name = "Nova", desc = "Der niedrige Preis der Nova macht sie zu einer großartigen Hinterhaltswaffe für ein Team in Geldnot." },
    ["p250"] = { name = "P250", desc = "Als eine Waffe mit wenig Rückstoß und hoher Feuerrate erweist sich die P250 als eine relativ preiswerte Wahl gegen gepanzerte Gegner." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "Das SCAR-20 ist ein halbautomatisches Scharfschützengewehr, dessen hohe Feurrate und Durchschlagskraft auf lange Distanz mit eingeschränkter Beweglichkeit und hohen Kosten erkauft wird." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "Das SSG08 mit Kammerverschluss ist ein schwaches, aber sehr kosteneffektives Scharfschützengewehr. Dies macht es in den ersten Runden des Spiels zu einer guten Wahl für treffsichere Distanzschüsse." },
    ["heavyassaultsuit"] = "Schwere Rüstung",
    ["assaultsuit"] = "Kevlar + Helm",
    ["assaultsuit_only_helmet"] = "Helm",
    ["kevlar"] = "Kevlarweste",
    ["defuser"] = "Entschärfungskit",
    ["cutters"] = "Geiselrettungskit",
    ["revolver"] = { name = "R8-Revolver", desc = "Der R8-Revolver gibt einen äußerst präzisen und mächtigen Schuss ab, der auf Kosten eines langwierigen Abzugs geht. Ist hohe Mannstoppwirkung auf kurze Distanz gefordert, bietet sich ein schnelles Abfeuern mittels sogenanntem „Fanning“ an." },
    ["usp_silencer"] = { name = "USP-S", desc = "Die schallgedämpfte USP-Pistole, ein Fan-Favorit aus Counter-Strike: Source, hat einen abnehmbaren Schalldämpfer, der den Rückschlag bei Schüssen reduziert und außerdem aufsehenerregende Geräusche vermeidet." },
    ["knifebayonet"] = { name = "Bajonett", desc = "Seit seinem ersten Einsatz im Zweiten Weltkrieg ist das Design des Bajonetts weitgehend gleich geblieben und es hat seinen Platz in der modernen Militärstrategie behalten. Ihre Effektivität haben Bajonettangriffe in der jüngsten Vergangenheit, während des Golfkrieges und in Afghanistan, erneut unter Beweis gestellt." },
    ["knifeflip"] = { name = "Klappmesser", desc = "Klappmesser verfügen über eine nach persischer Art rückwärtig geschliffene Klinge mit einer scharfen Spitze. Während die Spitze selbst eher instabil sein mag, erweist sich das Design im Großen und Ganzen als erstaunlich widerstandsfähig." },
    ["knifegut"] = { name = "Aufbrechmesser", desc = "Das auffälligste Merkmal eines Aufbrechmessers ist der Haken an der Oberseite der Klinge. Seine Bekanntheit erlangte er als Hilfsmittel beim Ausnehmen von Wild, der Haken eignet sich aber ebenso gut zum Schneiden von Fasermaterialien wie Seilen, Geweben und Sicherheitsgurten." },
    ["knifecss"] = { name = "Klassisches Messer", desc = "Ein Klassiker der Counter-Strike-Serie! Die Kante dieses Messers wird durch die präzise Passform mit dem Titan auf der Wange und dem Rücken der Klinge perfekt gehalten. Der Griff ist aus versteinertem Mastodon-Elfenbein und wird in einer Kohlefasertasche gehalten." },
    ["knifem9"] = { name = "M9-Bajonett", desc = "Dies ist das M9-Bajonett. Auch wenn es ursprünglich entwickelt wurde, um an einem Gewehr befestigt zu werden, ist es ebenfalls sehr gut für den Nahkampf geeignet." },
    ["knifekaram"] = { name = "Karambit", desc = "Das mit seiner gebogenen Klinge an eine Tigerklaue erinnernde Karambit hat seinen Ursprung in der südasiatischen Kampfkunst Silat. Das Messer wird üblicherweise umgekehrt gehalten, wobei der Zeigefinger durch den Fingerring greift." },
    ["knifetactical"] = { name = "Jagdmesser", desc = "Ein für den modernen, taktischen Einsatz entwickeltes Messer. Die Klinge ist für viele Kampf- sowie gewöhnliche Zwecke bestens geeignet. Die einzigartige Tanto-Spitze erlaubt sogar das Durchdringen der widerstandsfähigsten Oberflächen." },
    ["knife_butterfly"] = { name = "Butterflymesser", desc = "Dies ist ein speziell angefertigtes Balisong, allgemein als Butterflymesser bekannt. Das definierende Merkmal dieser Waffe ist das fächerartige Aufklappen einer frei rotierenden Klinge, welches ein schnelles Hervorholen sowie Verstecken ermöglicht. Aufgrund dessen sind Butterflymesser in vielen Ländern gesetzlich verboten." },
    ["partypopper"] = "Partyknaller!",
    ["knife_falchion_advanced"] = { name = "Falchion-Messer", desc = "Als moderne Hommage an das Falchionschwert hat diese Clip-Point-Klinge eine gebogene Schneide." },
    ["knife_push"] = { name = "Schattendolche", desc = "Das für effiziente Brutalität entworfene Faustmesser zu benutzen ist genauso einfach wie ein oder zwei Schläge auszuteilen." },
    ["knife_survival_bowie"] = { name = "Bowiemesser", desc = "Dieses griffige Bowiemesser wurde für den Gebrauch in brutalen Überlebenskämpfen entworfen." },
    ["healthshot"] = "Heilungsspritze",
    ["tagrenade"] = "Taktische Aufklärungsgranate",
    ["exploding_barrel"] = "Explosives Fass",
    ["snowball"] = "Schneeball",
    ["stompdamagekillstring"] = "hat Ihren Schädel zertrümmert",
    ["dangerzone"] = "Gefahrenzone",
    ["autosentry"] = "Automatisiertes Geschütz",
    ["fists"] = "Blanke Hände",
    ["tablet"] = "Tablet",
    ["breachcharge"] = "Notfalltüröffnungskit",
    ["bumpmine"] = "Stoßmine",
    ["axe"] = { name = "Axt", desc = "Die Axt ist schwer, immer verfügbar und hat eine scharfe und eine stumpfe Seite. Schwingen Sie sie für einen Primärangriff mit geringem Schaden oder werfen Sie sie für einen Sekundärangriff mit hohem Schaden. Bösem Aste scharfe Axt." },
    ["hammer"] = { name = "Hammer", desc = "Der Hammer dient der Reparatur und der Zerstörung. Schwingen Sie ihn für einen Primärangriff mit geringem Schaden oder werfen Sie ihn für einen Sekundärangriff mit hohem Schaden. Wenn man nur einen Hammer hat, sieht alles aus wie ein Nagel." },
    ["spanner"] = { name = "Schraubenschlüssel", desc = "Ein Schraubenschlüssel wird in der Regel verwendet, um beim Drehen von Objekten ein Drehmoment auszuüben, aber man kann mit seinem Primärangriff alles schlagen, um geringen Schaden zuzufügen, oder ihn für einen Sekundärangriff mit hohem Schaden werfen. Wer mit einem Schraubenschlüssel in ein Feuergefecht zieht, hat also keine Schraube locker." },
    ["tripwirefire"] = "Feuerfalle",
    ["knife_cord"] = { name = "Fallschirm-Messer", desc = "Dieses Überlebensmesser mit feststehender Klinge kann sowohl als Waffe als auch als Werkzeug verwendet werden, so z. B. zum Fallenstellen, zur Jagd oder um sich durch Buschwerk zu kämpfen. Der Griff ist mit einer Vielzweck-Fallschirmleine umwickelt." },
    ["knife_canis"] = { name = "Survival-Messer", desc = "Dieses multifunktionale Sägemesser schneidet auch Knochen oder Fleischfasern und verfügt darüber hinaus über eine scharfe Aufbruchklinge. Der Griff aus Verbundmaterial ist mit Sechskantmuttern an der Klinge angeschraubt." },
    ["knife_ursus"] = { name = "Ursus-Messer", desc = "Dieses Überlebensmesser im Tantō-Stil hat eine facettierte und fein geschliffene Klinge sowie einen Schlagknauf. Kein Hokuspokus und keine beweglichen Teile – nur eine zuverlässige Klinge." },
    ["knife_gypsy_jackknife"] = { name = "Navaja-Messer", desc = "Dieses Klappmesser mit emailliertem Marmorgriff verbirgt eine kleine, aber bösartig zugespitzte Klinge." },
    ["knife_outdoor"] = { name = "Nomadenmesser", desc = "Dieses ergonomische taktische Jagdmesser verfügt über Griffeinsätze aus Verbundwerkstoff und eine breite, stabile und ausklappbare Klinge, die zum Schneiden und Zertrennen verschiedener Materialien geeignet ist." },
    ["knife_widowmaker"] = { name = "Talon-Messer", desc = "Dieses Karambit mit Elfenbeingriff hat Messingnieten und einen Säbelzahnrücken, sodass es beim Eindringen schneidet und beim Herausziehen reißt." },
    ["knife_stiletto"] = { name = "Stilett", desc = "Historisch gesehen ein Brennpunkt der Auseinandersetzung und sogar der Regulierung. Dieses Stilett-Springmesser im italienischen Stil hat eine gefederte Klinge, die durch Druck einer Ausklinknase augenblicklich ausklappt." },
    ["knife_skeleton"] = { name = "Skelettmesser", desc = "Dieses skelettierte Messer wurde am Griff gebunden, um die Griffigkeit zu verbessern. Das Loch ermöglicht es, einen Finger reinzustecken, um Stabilität und Sicherheit zu gewährleisten." },
    ["knife_kukri"] = { name = "Kukri-Messer", desc = "Wird bei traditionellen Ritualen wie Hochzeiten oder Messerstechereien verwendet." },
    ["firebomb"] = { name = "Brandbombe", desc = "Die Brandbombe ist eine leistungsstarke experimentelle Waffe, die in Hochtemperatur-Flammen ausbricht, wenn sie auf den Boden geworfen wird, und jeden Spieler in seinem weitläufigen Radius chemisch verbrennt." },
    ["diversion"] = { name = "Ablenkungsgerät", desc = "Wenn es geworfen wird, hebt das Ablenkungsgerät Sektoren auf Tablets hervor, um die Illusion zusätzlicher Gegner zu erzeugen." },
    ["frag_grenade"] = { name = "Splittergranate", desc = "Die experimentelle Splittergranate kann extreme Mengen an hochexplosivem Schaden in einem größeren Gebiet auslösen, was sie ideal für Angriffs- und Verteidigungsstrategien macht." },
    ["shield"] = "Taktischer Einsatzschild",
    ["zone_repulsor"] = { name = "Zonenabwehrgerät", desc = "Prototyp einer radialen Partikel-Abschirmvorrichtung" },
    ["glock_use"] = "• Tödlich aus der Nähe, lästig auf Distanz\n• Für die erste Runde einer Hälfte\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Präzise auf Entfernung, hohe Feuerrate im Nahkampf\n• Für die erste Runde einer Hälfte\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Präzise, schallgedämpft und (einigermaßen) tödlich\n• Für die erste Runde einer Hälfte\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Zwei Schnellfeuerpistolen zum Preis von einer\n• Für die erste Runde einer Hälfte\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Eine beliebte, wenn auch bescheidene Verbesserung des Schadens\n• Für Runden, in denen Sie sparen sollten\n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Leistung, Schnelligkeit und Präzision für einen gewissen Preis\n• Für Runden, in denen Sie sparen sollten\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Explosive Feuerkraft, um die Waffen des Gegners zu stehlen\n• Für Runden, in denen Sie sparen sollten\n• Handhabung: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Äußerst mobil, effektiv auf Distanz und aus der Nähe\n• Für Runden, in denen Sie sparen sollten\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Verursacht massiven Schaden nach einer kurzen Verzögerung\n• Für Runden, in denen Sie sparen sollten\n• Handhabung: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Ein tödlicher Kopfschuss bei jeder Reichweite\n• Für Runden, in denen Sie sparen sollten\n• Handhabung: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Ein tödlicher Einzelschuss auf kurze Reichweite\n• Nutzung auf eigene Gefahr\n• Handhabung: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Ein Kugelhagel, um ungepanzerte Gegner niederzumähen\n• Für die erste Runde einer Hälfte\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Ein Werkzeug zum Erstürmen von Bombenorten\n• Für die ersten drei Runden einer Hälfte\n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Explosiver Schaden, um einen gegnerischen Sturmangriff abzuwehren\n• Für die erste Runde einer Hälfte\n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Leicht zu kontrollieren für soliden Schaden auf mittlere Distanz\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Flink und verstohlen für Schaden auf mittlere Reichweite\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Gute panzerbrechende Eigenschaften für Kämpfe in mittlerer Reichweite\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Ein endloser Kugelhagel, der nur von Gewehren übertroffen wird\n• Für Runden, in denen Sie genug Geld haben\n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Billig, aber effektiv gegen gepanzerte Gegner\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Billig, aber effektiv gegen gepanzerte Gegner\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• Das klassische, präzise und tödliche Arbeitsgerät\n• Für Runden, in denen Sie genug Geld haben\n• Handhabung: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Gute Präzision mit reichlich Munition\n• Für Runden, in denen Sie genug Geld haben\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Präzise, schallgedämpft, ohne Tracer\n• Für Runden, in denen Sie genug Geld haben\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Mit einem optionales Zielfernrohr für höchste Präzision\n• Für Runden, in denen Sie genug Geld haben\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Eine tödliche Waffe mit noch tödlicherem Zielfernrohr\n• Für Runden, in denen Sie genug Geld haben\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Vernichtende Leistung für den selbstbewussten Scharfschützen\n• Für Runden, in denen Sie genug Geld haben\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Ein halbautomatisches Scharfschützengewehr, das zugleich risikoreich und lohnenswert ist\n• Für besondere Umstände\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Ein wirksames (wenn auch riskantes) Werkzeug, um eine Position zu halten\n• Für besondere Umstände\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Leichter und leistungsstarker Schadensausteiler auf große Distanz\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Gegner überraschen, nachladen, wiederholen\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Vielseitige Schrotflinte für den bewaffneten Nahkampf\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Leistungsstarke Schrotflinte für Begegnungen aus kürzester Nähe\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Ein halbautomatisches Schnellfeuermonster\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• Muss wenigstens nicht nachgeladen werden …\n• Für besondere Umstände\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Punktgenaues Unterdrückungsfeuer, um sich etwas Zeit zu verschaffen\n• Für Runden, die Sie gewinnen sollten\n• Handhabung: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Verursacht Schaden oder klärt Rauchgranaten\n• Nutzung nach eigenem Ermessen\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Macht Spieler in der Nähe blind und taub\n• Wird vor einem Angriff geworfen\n• Handhabung: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Erzeugt eine große Rauchwolke\n• Wird geworfen, um dem Gegner die Sicht zu nehmen\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Imitiert den Klang von Waffenfeuer\n• Wird frühzeitig geworfen, um den Gegner zu verwirren\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Räuchert Verstecke mit Feuer aus\n• Wird vor einem Angriff auf einen Bombenort geworfen\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Erstickt gegnerische Angriffe mit Feuer\n• Wird beim ersten Anzeichen von Schwierigkeiten geworfen\n• Handhabung: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Überlebt alles, außer den tödlichsten Kugeln\n• Für Runden, in denen Sie genug Geld haben und gewinnen sollten\n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Schützt alles außer Ihrem Kopf\n• Für die erste Runde einer Hälfte\n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Verkürzt die Entschärfungszeit um die Hälfte\n• Sei kein Verlierer, kauf’ ’nen Entschärfer! \n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Nehmen Sie Geiseln in einem Bruchteil der Zeit auf\n• Eine Erwägung wert, wenn Sie genug Geld haben\n• Handhabung: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "Als vollautomatische Variante der CZ75 ist die CZ75-Auto die ideale Übergangswaffe, bis sie einem überraschten Gegner dessen Waffe abgenommen haben. Aufgrund des geringen Munitionsvorrats ist jedoch eine hohe Disziplin am Abzug geboten.",
    ["m4a4"] = "Mit höherer Präzision aber geringerem Schaden als sein Gegenstück AK-47 ist das M4A4 das bevorzugte vollautomatische Sturmgewehr der Antiterroreinheit.",
    ["sg553"] = "Das den Terroristen vorbehaltene SG553 ist eine hochklassige und mit einem Zielfernrohr ausgestattete Alternative zum AK-47, wenn es um effektiven Kampf auf lange Distanz geht.",
    ["decoy_grenade"] = "Wenn sie geworfen wird, erzeugt die Ködergranate das Schussgeräusch der stärksten Waffe, die Sie bei sich tragen. Dadurch entsteht der Eindruck, Sie hätten Unterstützung dabei.",
    ["incindiary_grenade"] = "Wenn sie geworfen wird, löst die Brandgranate eine chemische Reaktion mit hoher Temperatur aus, die imstande ist jeden innerhalb ihres großen Detonationsradius zu verbrennen.",
    ["survival_taser"] = "Waffe mit extrem kurzer Reichweite, die mit einem Schuss töten kann. Kann auch zum Öffnen von Waffenkisten verwendet werden.",
    ["survival_healthshot"] = "Stellt einen Teil Ihrer Gesundheit wieder her und sorgt für einen kurzen Geschwindigkeitsschub.",
    ["survival_vesthelm"] = "Bietet Schutz vor Schaden.",
    ["survival_shield"] = "Ein taktischer Einsatzschild, der eine große Menge an Schaden blocken kann, bevor er zerstört wird.",
    ["survival_parachute"] = "Kann beim Fallen eingesetzt werden, um Fallschaden zu vermeiden.",
    ["survival_exojump"] = "Erhöht die Sprunghöhe deutlich.",
    ["survival_c4"] = "Legen Sie den C4-Sprengstoff irgendwo auf der Karte, um eine große Explosion zu verursachen. Kann zum Öffnen von Tresoren verwendet werden.",
    ["survival_dronepilot"] = "Gibt Ihnen die Fähigkeit, die Kontrolle über Drohnen zu übernehmen. Verwenden Sie Ihr Tablet, um eine Drohne auszuwählen und zu übernehmen.",
    ["survival_exploremoney"] = "Gibt Ihnen zusätzliches Geld für jeden erkundeten Sektor.",
    ["survival_wavemoney"] = "Gibt Ihnen zusätzliches Geld für jede überlebte Ausbreitung der Gefahrenzone.",
}
