csstring = { -- Brazilian Portuguese
	["cat_pistols"] = "Pistolas",
	["cat_heavy"] = "Pesadas",
	["cat_smg"] = "Sub metralhadoras",
	["cat_rifles"] = "Rifles",
	["cat_grenades"] = "Granadas",
	["cat_gear"] = "Diversos",

    ["ak47"] = { name = "AK-47", desc = "Poderoso e confiável, o AK-47 é um dos rifles de assalto mais populares do mundo. Ele é mais mortal em rajadas curtas e controladas." },
    ["aug"] = { name = "AUG", desc = "Poderoso e preciso, o rifle de assalto com lente de aproximação AUG compensa a sua recarga demorada com a sua precisão e rápido disparo." },
    ["awp"] = { name = "AWP", desc = "A infame AWP é conhecida por recompensar aqueles que arriscam, sendo famosa pelo funcionamento \"Um tiro, uma morte\"." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Tão cara quanto poderosa, a Desert Eagle é uma pistola icônica difícil de domar, mas surpreendentemente precisa a longa distância." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Berettas Duplas", desc = "Disparar duas Berettas ao mesmo tempo diminuirá a sua precisão e aumentará o tempo de recarga. Por outro lado, você estará disparando duas Berettas ao mesmo tempo." },
    ["elite"] = "Berettas Duplas",
    ["famas"] = { name = "FAMAS", desc = "Uma opção barata para jogadores com pouco dinheiro, o FAMAS preenche bem o nicho entre os rifles mais caros e as submetralhadoras menos eficientes." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Altamente precisa e perfurante, a Five-Seven é cara e lenta para recarregar, porém compensa com o seu pente de 20 balas e um coice generoso." },
    ["flashbang"] = { name = "Granada de Luz", desc = "A granada de luz não é letal, mas cega temporariamente qualquer um dentro da sua explosão de concussão, sendo perfeita para limpar áreas fechadas. O som alto da explosão também camufla o som de passos." },
    ["g3sg1"] = { name = "G3SG1", desc = "A G3SG1 é cara e diminui a velocidade do usuário consideravelmente, mas compensa com uma taxa de disparo maior do que os outros rifles de precisão." },
    ["galilar"] = { name = "Galil AR", desc = "Uma opção menos cara dentre os rifles de assalto exclusivos dos Terroristas, a Galil AR é uma arma útil em combates de média e longa distância." },
    ["glock18"] = { name = "Glock-18", desc = "A Glock-18 é uma boa pistola para começar a partida. É mais eficiente contra oponentes sem proteção e é capaz de disparar rajadas de três balas." },
    ["he_grenade"] = { name = "Granada Explosiva", desc = "A granada de fragmentação altamente explosiva causa um alto dano em uma área grande, sendo ideal para limpar salas hostis." },
    ["he_grenade_short"] = "Explosiva",
    ["hegrenade"] = "Granada Explosiva",
    ["knife"] = { name = "Faca", desc = "Silenciosa e sempre disponível, a faca possui dois tipos de ataque: o primário é rápido, mas causa pouco dano; o segundo é lento, porém causa muito dano. Uma facada nas costas recompensará jogadores sorrateiros com uma morte instantânea." },
    ["knife_t"] = "Faca",
    ["knife_gg"] = "Faca Dourada",
    ["knife_ghost"] = { name = "Lâmina Espectral", desc = "Fantasmas adoram facas fantasmas. Quando colocam as mãos em uma, cuidado — eles tentarão atacar na primeira oportunidade! É uma pena que sejam fantasmas e facas fantasmas não machuquem pessoas..." },
    ["m249"] = { name = "M249", desc = "Uma poderosa metralhadora leve para áreas abertas, a M249 é a escolha perfeita para jogadores que querem abrir mão da taxa de disparo por uma precisão melhor e um limite de munição maior." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Com menos balas no pente que o seu correspondente sem silenciador, o M4A1 silenciado tem disparos mais silenciosos com menor coice e melhor precisão." },
    ["mac10"] = { name = "MAC-10", desc = "Essencialmente uma caixa que lança balas, a submetralhadora MAC-10 possui uma alta taxa de disparo, que compensa a precisão ruim e o forte coice." },
    ["p90"] = { name = "P90", desc = "Facilmente reconhecida pelo seu design \"bullpup\", a P90 é uma ótima arma para atirar em movimento devido ao seu pente de alta capacidade e pequeno coice." },
    ["smoke_grenade"] = { name = "Granada de Fumaça", desc = "A granada de fumaça cria uma cortina de fumaça num raio de médio alcance, podendo esconder a sua equipe contra franco-atiradores ou simplesmente criar uma distração útil." },
    ["smokegrenade"] = "Granada de fumaça",
    ["ump45"] = { name = "UMP-45", desc = "Malcompreendida e filha do meio da família das submetralhadoras, o curto cartucho da UMP45 é o único inconveniente desta versátil arma automática de curta distância." },
    ["xm1014"] = { name = "XM1014", desc = "A XM1014 é uma escopeta automática poderosa que justifica o alto custo com a habilidade de limpar rapidamente qualquer área com as suas balas." },
    ["c4"] = { name = "Explosivo C4", desc = "Estável e resistente a impactos físicos, este explosivo plástico improvisado tem uma velocidade de detonação de mais de 8.000 metros por segundo ao ser ativado." },
    ["bizon"] = { name = "PP-Bizon", desc = "A Submetralhadora Bizon não causa muito dano, mas oferece um cartucho de alta capacidade exclusivo que permite um recarregamento rápido." },
    ["mag7"] = { name = "MAG-7", desc = "A Mag-7, exclusiva dos CTs, fornece uma quantidade devastadora de dano a curta distância. O seu recarregamento rápido a torna uma ótima escolha tática." },
    ["negev"] = { name = "Negev", desc = "A Negev é uma fera capaz de manter os inimigos a distância com os seus disparos supressivos, contanto que tenha à sua disposição o tempo para controlá-la." },
    ["sawedoff"] = { name = "Cano Curto", desc = "A clássica Cano Curto causa muitíssimo dano a curta distância, mas com uma precisão baixa, um desvio alto e uma taxa de disparo lenta, é melhor matar os seus alvos no primeiro tiro." },
    ["tec9"] = { name = "Tec-9", desc = "Uma pistola ideal para Terroristas que rotacionam pelo mapa, a Tec-9 é letal nos combates em ambientes confinados e possui um pente que porta bastante munição." },
    ["taser"] = { name = "Zeus x27", desc = "Perfeito para emboscadas de curto alcance e confrontos em espaços fechados, a Zeus x27 é capaz de incapacitar um inimigo com um único disparo." },
    ["molotov"] = { name = "Molotov", desc = "O Molotov é uma arma poderosa e imprevisível que cria uma barreira de chamas quando lançada, causando dano em qualquer jogador na área." },
    ["incgrenade"] = "Granada Incendiária",
    ["incgrenade_short"] = "Incendiária",
    ["decoy"] = "Granada de Distração",
    ["decoy_short"] = "Distração",
    ["hkp2000"] = { name = "P2000", desc = "Precisa e fácil de usar, a alemã P2000 é uma útil pistola de primeira rodada que funciona melhor em adversários desprotegidos." },
    ["mp7"] = { name = "MP7", desc = "Versátil, porém cara, a submetralhadora alemã MP7 é a escolha perfeita para combate de alto impacto a curta distância." },
    ["mp5sd"] = { name = "MP5-SD", desc = "Muito imitada mas nunca igualada, a icônica MP5 talvez seja a submetralhadora mais versátil e popular do mundo. Esta variante SD vem equipada com um silenciador integrado, deixando uma arma já formidável tão silenciosa quanto um sussurro." },
    ["mp9"] = { name = "MP9", desc = "Fabricada na Suíça, a submetralhadora de ponta MP9 é uma arma ergonômica de polímero optada por empresas de segurança privada." },
    ["nova"] = { name = "Nova", desc = "O preço baixíssimo da Nova a torna uma ótima arma para emboscadas para equipes que não podem esbanjar dinheiro." },
    ["p250"] = { name = "P250", desc = "Uma arma de fogo com alta taxa de disparo e pouco coice, a P250 é uma escolha relativamente barata contra adversários bem protegidos." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "O SCAR-20 é um rifle de precisão semiautomático que, em troca de uma velocidade de movimento menor e alto custo, fornece-lhe uma alta taxa de disparo e grande poder de dano a longa distância." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "O SSG08 é um rifle de precisão que não causa muito dano, mas é barato e tem grande poder de disparo, sendo ideal para confrontos a longa distância no início de rodadas." },
    ["heavyassaultsuit"] = "Proteção Pesada",
    ["assaultsuit"] = "Colete e Capacete",
    ["assaultsuit_only_helmet"] = "Capacete",
    ["kevlar"] = "Colete de Kevlar",
    ["defuser"] = "Kit de Desarme",
    ["cutters"] = "Kit de Resgate",
    ["revolver"] = { name = "Revólver R8", desc = "O Revólver R8 dispara balas precisas e poderosas em troca de um gatilho duro. Disparar rapidamente girando o cão pode ser a melhor opção quando for necessário um poder de parada à queima-roupa." },
    ["usp_silencer"] = { name = "USP-S", desc = "Uma arma favorita dos fãs de Counter-Strike: Source, esta versão da pistola USP tem um silenciador removível que reduz o som e o coice dos disparos." },
    ["knifebayonet"] = { name = "Baioneta", desc = "Com design relativamente inalterado desde a Segunda Guerra Mundial, a baioneta ainda tem um lugar em estratégias militares modernas. Investidas de baionetas continuam eficazes, como visto recentemente na segunda Guerra do Golfo e na guerra no Afeganistão." },
    ["knifeflip"] = { name = "Canivete", desc = "Os canivetes têm uma lâmina curva de estilo persa com uma ponta afiada. Apesar dessa ponta ser frágil, a estrutura geral do canivete inteira é surpreendentemente durável." },
    ["knifegut"] = { name = "Faca Gut Hook", desc = "O que mais chama a atenção em uma faca Gut Hook é o gancho no dorso da lâmina. Popularizada inicialmente para auxiliar em caças, a Gut Hook também é excelente para cortar materiais fibrosos como cordas, redes ou cintos de segurança com facilidade." },
    ["knifecss"] = { name = "Faca Clássica", desc = "Um clássico da série Counter-Strike, a lâmina desta faca é feita de estelite pressurizada, perfeitamente estabilizada em harmonia com o titânio do resto do corpo. A empunhadura é feita a partir de marfim fossilizado de mastodonte, envolto em fibra de carbono." },
    ["knifem9"] = { name = "Baioneta M9", desc = "Esta é a Baioneta M-9. Criada originalmente para ser acoplada em um rifle, ela também serve para combates corpo a corpo." },
    ["knifekaram"] = { name = "Karambit", desc = "Com a sua lâmina curva imitando uma garra de tigre, a Karambit foi criada como parte da tradição marcial de \"silat\" do Sudeste Asiático. Esta faca geralmente é usada com um cabo invertido, com o dedo indicador no aro." },
    ["knifetactical"] = { name = "Faca do Caçador", desc = "Uma faca projetada para operações táticas modernas, cuja lâmina é adequada tanto para combate como para fins utilitários. O gume distinto permite um nível máximo de penetração através da mais rígida das superfícies." },
    ["knife_butterfly"] = { name = "Canivete Borboleta", desc = "Este é um canivete borboleta. A maior característica deste tipo de arma é a forma como ela se abre, girando livremente em um movimento de rotação que permite um saque rápido. Como consequência, portar um canivete borboleta é proibido em muitos países." },
    ["partypopper"] = "Lança-confetes!",
    ["knife_falchion_advanced"] = { name = "Canivete Falchion", desc = "Uma homenagem à espada falchion, esta lâmina côncava possui uma ponta curvada." },
    ["knife_push"] = { name = "Adagas Sombrias", desc = "Projetadas para brutalidade eficaz, usar uma adaga é simples como dar um soco." },
    ["knife_survival_bowie"] = { name = "Faca Bowie", desc = "Esta faca Bowie, com uma lâmina de dorso serrilhado e perfeitamente fixada em seu cabo, foi projetada para uso intensivo em situações brutais de sobrevivência." },
    ["healthshot"] = "Injeção Médica",
    ["tagrenade"] = "Granada Tática",
    ["exploding_barrel"] = "Barril Explosivo",
    ["snowball"] = "Bola de neve",
    ["stompdamagekillstring"] = "esmagou o seu crânio",
    ["dangerzone"] = "Zona de Perigo",
    ["autosentry"] = "Sentinela Automática",
    ["fists"] = "Punhos",
    ["tablet"] = "Tablet",
    ["breachcharge"] = "Carga de Demolição",
    ["bumpmine"] = "Mina Repulsora",
    ["axe"] = { name = "Machado", desc = "Pesado e sempre em mãos, o machado tem um lado afiado e um lado maçante. Use o ataque primário para girá-lo e causar pouco dano, ou arremesse-o com o ataque secundário para causar bastante dano. Machado achado, negócio fechado!" },
    ["hammer"] = { name = "Martelo", desc = "O martelo pode tanto consertar coisas quanto quebrá-las. Use o ataque primário para girá-lo e causar pouco dano, ou arremesse-o com o ataque secundário para causar bastante dano. Se tudo o que você tem é um martelo, todas as coisas se parecem com um prego." },
    ["spanner"] = { name = "Chave Inglesa", desc = "Uma chave inglesa é tipicamente usada para aplicar torque ao girar objetos, mas você pode usá-la para atingir qualquer coisa com o ataque primário e causar pouco dano, ou arremessá-la com o ataque secundário para causar bastante dano. Trazer uma chave inglesa a um tiroteio é a receita para o fracasso." },
    ["tripwirefire"] = "Armadilha de fogo",
    ["knife_cord"] = { name = "Faca de Cordame", desc = "Esta faca de sobrevivência de lâmina fixa foi desenhada para poder ser usada como arma ou ferramenta para, por exemplo, armar armadilhas, caçar animais ou cortar folhagem. O cabo é enrolado com cordame multiuso." },
    ["knife_canis"] = { name = "Faca de Sobrevivência", desc = "Esta faca dobrável multiuso tem uma lâmina serrada para rasgar materiais grossos, como osso e fibra, além de uma ponta afiada em forma de gancho. O cabo de material entalhado é aferrolhado até a lâmina com porcas." },
    ["knife_ursus"] = { name = "Faca Ursus", desc = "Esta faca de sobrevivência estilo tantō possui uma lâmina facetada e de perfil integral, completa com empunhadura de impacto. Nenhum penduricalho ou peças móveis — apenas uma lâmina confiável pronta para o trabalho." },
    ["knife_gypsy_jackknife"] = { name = "Faca Navaja", desc = "Este canivete com punho de mármore esconde uma lâmina pequena, mas extremamente afiada." },
    ["knife_outdoor"] = { name = "Faca Nômade", desc = "Esta faca de caça dobrável e ergonômica tem uma lâmina com trava firme e larga, boa para cortar e abrir materiais, vem com cabo entalhado." },
    ["knife_widowmaker"] = { name = "Faca Talon", desc = "Esta karambit com punho de marfim vem com rebites de bronze e fio dentado, cortando na entrada e rasgando na saída." },
    ["knife_stiletto"] = { name = "Faca Stiletto", desc = "Historicamente alvo de disputas e até regulamentações, este stiletto italiano vem com uma lâmina a mola, que pode ser acionada quase que instantaneamente no pressionar de uma trava." },
    ["knife_skeleton"] = { name = "Faca Esqueleto", desc = "A empunhadura desta faca esqueletizada foi envolta em fita para possibilitar um melhor manuseio. O buraco no centro permite que a faca seja segurada com um dedo de uma forma estável e segura." },
    ["knife_kukri"] = { name = "Faca Kukri", desc = "Usada em rituais tradicionais, como casamentos e esfaqueamentos." },
    ["firebomb"] = { name = "Bomba Incendiária", desc = "A Bomba Incendiária é uma poderosa arma experimental que explode em chamas de alta temperatura quando jogada no chão, queimando qualquer jogador que esteja no seu amplo raio de alcance." },
    ["diversion"] = { name = "Dispositivo de Distração", desc = "Quando lançado, este dispositivo destacará seções vazias em tablets, criando a ilusão de mais inimigos." },
    ["frag_grenade"] = { name = "Granada de Fragmentação", desc = "Esta granada de fragmentação experimental pode causar um dano explosivo tremendo em uma grande área, sendo ideal para estratégias de ataque e defesa." },
    ["shield"] = { name = "Escudo Antimotim", desc = "Um dispositivo de proteção concebido para refletir ou absorver dano balístico e ajudar a proteger o portador contra projéteis de vários calibres." },
    ["zone_repulsor"] = { name = "Dispositivo Repulsor", desc = "Protótipo de dispositivo de proteção contra emissões de partículas radiais." },
    ["glock_use"] = "• Mortal de perto, nada além de um incômodo a distância\n• Boa opção na primeira rodada do tempo\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Precisa à distância, senta o dedo no gatilho de perto\n• Boa opção na primeira rodada do tempo\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Precisa, silenciosa e (um tanto) mortal\n• Boa opção na primeira rodada do tempo\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Duas pistolas de disparo rápido pelo preço de uma\n• Boa opção na primeira rodada do tempo\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Uma opção popular (e modesta), para causar mais dano\n• Boa opção em rodadas de economia\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Potência, velocidade e precisão têm o seu preço\n• Boa opção em rodadas de economia\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Uma rajada potente para roubar armas inimigas\n• Boa opção em rodadas de economia\n• Dificuldade: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Alta mobilidade e eficaz a qualquer distância\n• Boa opção em rodadas de economia\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Causa muito dano após um pequeno atraso\n• Boa opção em rodadas de economia\n• Dificuldade: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Um disparo na cabeça é letal a qualquer distância\n• Boa opção em rodadas de economia\n• Dificuldade: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Arma de curta distância com uma (única) carga letal\n• Tente por sua conta e risco\n• Dificuldade: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Uma chuva de balas para destruir inimigos sem a devida proteção\n• Boa opção nas três primeiras rodadas do tempo\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Uma ferramenta para correr atirando ao invadir alvos de explosão\n• Boa opção nas três primeiras rodadas do tempo\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Uma rajada de dano para conter uma invasão inimiga\n• Boa opção nas três primeiras rodadas do tempo\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Fácil de controlar para causar um bom dano a média distância\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Ágil e furtiva para causar dano a média distância\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Boa penetração de proteção para tiroteios a média distância\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Só rifles disparam balas tão bem quanto ela\n• Boa opção em rodadas de compra livre\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Barata, mas eficaz contra inimigos com proteção\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Barata, mas eficaz contra inimigos com proteção\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• A máquina clássica, precisa e letal\n• Boa opção em rodadas de compra livre\n• Dificuldade: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Boa precisão, com munição a gosto\n• Boa opção em rodadas de compra livre\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Precisa, silenciosa e sem deixar traços\n• Boa opção em rodadas de compra livre\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Uma luneta opcional para uma precisão excepcional\n• Boa opção em rodadas de compra livre\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Uma arma que já é letal, com a luneta então...\n• Boa opção em rodadas de compra livre\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Potência devastadora para o franco-atirador confiante\n• Boa opção em rodadas de compra livre\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Rifle de precisão automático para quem gosta de arriscar\n• Boa opção em circunstâncias especiais\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Uma ferramenta potente (e arriscada) para manter posição\n• Boa opção em circunstâncias especiais\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Leve e potente para causar dano a longa distância\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Pegue o inimigo de surpresa, recarregue e repita!\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Escopeta versátil para combate a curta distância\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Escopeta potente para embates a curta distância\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Um monstro automático de disparo rápido\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• Pelo menos, não precisa recarregar...\n• Boa opção em circunstâncias especiais\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Fogo de supressão altamente preciso para interromper avanços\n• Boa opção em rodadas de compra forçada\n• Dificuldade: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Cause dano ou abra espaço em fumaças\n• Use com moderação\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Cega e ensurdece jogadores próximos\n• Lance antes de atacar\n• Dificuldade: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Cria uma grande nuvem de fumaça\n• Lance para obstruir a linha de visão inimiga\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Imita o som de armas disparando\n• Lance cedo para confundir o inimigo\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Limpa áreas de esconderijo com fogo\n• Lance antes de atacar um alvo de explosão\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Interrompe ataques inimigos com fogo\n• Lance assim que perceber que o bicho vai pegar\n• Dificuldade: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Sobreviva a quase todas as balas\n• Boa opção em rodadas de compra livre e forçada\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Protege tudo, menos a cabeça\n• Boa opção na primeira rodada do tempo\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Corte o tempo de desarme pela metade\n• Não tem debate, leve o alicate!\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Pegue reféns em menos tempo\n• Boa opção quando tiver dinheiro sobrando\n• Dificuldade: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "Uma variante automática da CZ75, a CZ75-Auto é a escolha de curto prazo ideal para virar o jogo e levar a arma do seu adversário. Mas com pouca munição fornecida, é necessária sabedoria na hora de apertar o gatilho.",
    ["m4a4"] = "Mais preciso e menos poderoso que o AK-47, o seu correspondente, o M4A4 é o rifle de assalto automático dos CTs.",
    ["sg553"] = "Exclusiva dos Terroristas, a SG533 é uma arma de alto nível com lente de aproximação, sendo uma alternativa à AK-47 para combates a longa distância.",
    ["decoy_grenade"] = "Quando lançada, a granada de distração simula o som da arma mais poderosa que você carrega, criando a ilusão de forças de apoio adicionais.",
    ["incindiary_grenade"] = "Quando lançada, a granada incendiária libera substâncias químicas de alta temperatura capazes de queimar qualquer um dentro do raio de explosão.",
    ["survival_taser"] = "Arma de alcance extremamente curto, capaz de matar com um único disparo. Também pode ser usada para abrir caixas de armas.",
    ["survival_healthshot"] = "Restaura uma parte da sua vida e fornece breve impulso de velocidade.",
    ["survival_vesthelm"] = "Fornece resistência a dano.",
    ["survival_shield"] = "Um escudo antimotim que pode bloquear uma grande quantidade de dano antes de ser destruído.",
    ["survival_parachute"] = "Pode ser aberto ao cair para evitar dano por queda.",
    ["survival_exojump"] = "Aumenta bastante a altura dos seus pulos.",
    ["survival_c4"] = "Arme em qualquer lugar do mapa para causar uma grande explosão. Pode ser usada para abrir cofres.",
    ["survival_dronepilot"] = "Permite assumir o controle de drones. Use o tablet para selecionar um drone para controlar.",
    ["survival_exploremoney"] = "Concede dinheiro adicional por cada setor explorado.",
    ["survival_wavemoney"] = "Concede dinheiro adicional por cada onda de expansão da zona de perigo sobrevivida.",
}
