csstring = { -- Spanish
	["cat_pistols"] = "Pistolas",
	["cat_heavy"] = "Armas pesadas",
	["cat_smg"] = "Subfusiles",
	["cat_rifles"] = "Rifles",
	["cat_grenades"] = "Granadas",
	["cat_gear"] = "Equipamiento",

    ["ak47"] = { name = "AK-47", desc = "Potente y fiable, el AK-47 es uno de los rifles de asalto más famosos del mundo. Es sumamente letal en ráfagas cortas y controladas." },
    ["aug"] = { name = "AUG", desc = "Poderoso y preciso, el rifle de asalto con mira telescópica AUG compensa sus largos tiempos de recarga con su baja dispersión y una alta cadencia de fuego." },
    ["awp"] = { name = "AWP", desc = "Alto riesgo y alta recompensa, el infame AWP es reconocible por su característico sonido y su política de «un tiro, una muerte»." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Tan cara como potente, la Desert Eagle es una emblemática pistola difícil de dominar pero sorprendentemente precisa a larga distancia." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Berettas dobles", desc = "Disparar dos Berettas a la vez disminuirá la precisión y aumentará los tiempos de recarga. El lado positivo es que podrás disparar dos Berettas a la vez." },
    ["elite"] = "Berettas dobles",
    ["famas"] = { name = "FAMAS", desc = "Una opción económica para los jugadores con poco dinero, el FAMAS cubre con efectividad el vacío que hay entre el más caro de los rifles y el subfusil menos efectivo." },
    ["fiveseven"] = { name = "Five-seveN", desc = "Muy precisa y perforante, la cara Five-seveN es lenta de recargar, pero lo compensa con un generoso cargador de 20 balas y un bajo retroceso." },
    ["flashbang"] = { name = "Granada aturdidora", desc = "La granada aturdidora no es letal y ciega temporalmente a todos los que miren directamente al foco de su explosión, haciéndola perfecta para asaltar zonas poco fiables. Su ruidosa explosión también ensordece temporalmente, haciendo imposible oír el ruido de disparos o pasos." },
    ["g3sg1"] = { name = "G3SG1", desc = "El costoso G3SG1 reduce considerablemente la velocidad de movimiento, pero lo compensa con una cadencia de disparo superior a la de otros rifles de francotirador." },
    ["galilar"] = { name = "Galil AR", desc = "Una opción más barata entre los rifles de asalto exclusivos de los terroristas es el Galil AR, un arma útil en combate a media y larga distancia." },
    ["glock18"] = { name = "Glock-18", desc = "La Glock 18 es una práctica pistola de primera ronda que funciona mejor contra oponentes sin protección y cuenta con un modo ráfaga de tres balas." },
    ["he_grenade"] = { name = "Granada AE", desc = "Esta granada de fragmentación altamente explosiva causa una alta cantidad de daño en una amplia área a su alrededor, haciéndola ideal para despejar salas hostiles." },
    ["he_grenade_short"] = "Granada AE",
    ["hegrenade"] = "Granada AE",
    ["knife"] = { name = "Cuchillo", desc = "El cuchillo, silencioso y siempre disponible, tiene un ataque principal rápido y de daño reducido y un ataque secundario lento y de daño elevado. Una puñalada por la espalda con el ataque secundario permite asesinar de manera instantánea y discreta." },
    ["knife_t"] = "Cuchillo",
    ["knife_gg"] = "Cuchillo dorado",
    ["knife_ghost"] = { name = "Pincho espectral", desc = "A los fantasmas les encantan los cuchillos. ¡Ten cuidado si ves a alguno con uno en sus manos! Intentarán clavártelo por la espalda en cuanto puedan. Una pena que sean fantasmas y los cuchillos fantasma no puedan hacer daño..." },
    ["m249"] = { name = "M249", desc = "La M249, una potente ametralladora ligera de espacio abierto, es la elección perfecta para los jugadores dispuestos a sacrificar cadencia de disparo a cambio de mayor precisión y un cargador de gran capacidad." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "El M4A1 con silenciador tiene un cargador más pequeño que su homólogo no silenciado, pero proporciona disparos menos audibles con menor retroceso y mayor precisión." },
    ["mac10"] = { name = "MAC-10", desc = "Básicamente es una caja de la que salen balas, el subfusil MAC-10 cuenta con una gran cadencia de disparo, pero su precisión no es muy buena y su retroceso es muy elevado." },
    ["p90"] = { name = "P90", desc = "Fácil de reconocer por su diseño bullpup único, el P90 es un arma ideal para disparar en movimiento debido a su cargador de gran capacidad y su bajo retroceso." },
    ["smoke_grenade"] = { name = "Granada de humo", desc = "La granada de humo crea una cortina de humo de medio área. Es útil cuando quieres provocar distracciones al enemigo o simplemente esconderte de un francotirador." },
    ["smokegrenade"] = "Granada de humo",
    ["ump45"] = { name = "UMP-45", desc = "El UMP-45 es el hijo mediano incomprendido de la familia de los subfusiles. Su reducido cargador es el único inconveniente de esta versátil arma automática para distancias cortas." },
    ["xm1014"] = { name = "XM1014", desc = "La XM1014 es una poderosa escopeta automática que, aunque es muy cara, cuenta con la habilidad de rociar una sala de plomo rápidamente." },
    ["c4"] = { name = "Explosivo C4", desc = "Estable y resistente a la mayoría de los impactos físicos, este explosivo plástico improvisado tiene una velocidad de detonación de más de 8000 metros por segundo cuando se enciende." },
    ["bizon"] = { name = "PP-Bizon", desc = "El subfusil PP-Bizon no causa mucho daño, pero ofrece un cargador cilíndrico de alta capacidad y diseño único que se recarga rápidamente." },
    ["mag7"] = { name = "MAG-7", desc = "La Mag-7 exclusiva de los antiterroristas es un arma con una devastadora potencia de daño a corta distancia. Su cargador es fácil de recargar y ello lo hace una gran elección táctica." },
    ["negev"] = { name = "Negev", desc = "La Negev es una bestia que puede mantener a raya al enemigo con su preciso fuego de supresión, siempre y cuando dispongas del tiempo necesario para hacerte con su control." },
    ["sawedoff"] = { name = "Recortada", desc = "La clásica recortada hace mucho daño a corta distancia, pero dada su poca precisión, alta dispersión de las balas y baja cadencia de disparo, será mejor que si disparas a alguien no lo dejes con vida." },
    ["tec9"] = { name = "Tec-9", desc = "Como pistola ideal para el terrorista en movimiento, la Tec-9 es letal en espacios cerrados y cuenta con una generosa capacidad en el cargador." },
    ["taser"] = { name = "Zeus x27", desc = "Perfecta para emboscadas a corta distancia y combate en espacios cerrados, la Zeus x27 puede incapacitar a un enemigo de un solo disparo." },
    ["molotov"] = { name = "Molotov", desc = "El molotov es un arma poderosa, impredecible y bastante útil para cortar el paso a los enemigos. Cuando impacta contra el suelo se esparce cubriéndolo de llamas y causando quemaduras a los jugadores que pasan sobre él." },
    ["incgrenade"] = "Granada incendiaria",
    ["incgrenade_short"] = "Incendiaria",
    ["decoy"] = "Granada señuelo",
    ["decoy_short"] = "Señuelo",
    ["hkp2000"] = { name = "P2000", desc = "Precisa y controlable, la P2000 de fabricación alemana es una práctica pistola de primera ronda que funciona mejor contra oponentes sin protección." },
    ["mp7"] = { name = "MP7", desc = "Versátil pero caro, el subfusil alemán MP7 es la mejor elección para combates a corta distancia." },
    ["mp5sd"] = { name = "MP5-SD", desc = "A menudo imitado pero nunca igualado, el emblemático MP5 es quizá el subfusil más versátil y popular del mundo. Esta variante SD viene equipada con un silenciador integrado, lo que convierte a un arma ya de por sí formidable en silenciosa." },
    ["mp9"] = { name = "MP9", desc = "Fabricado en Suiza, el innovador subfusil MP9 es el arma ergonómica de polímero favorita de las empresas de seguridad privada." },
    ["nova"] = { name = "Nova", desc = "El bajísimo precio de la Nova la convierte en una escopeta excelente para los equipos con poco dinero." },
    ["p250"] = { name = "P250", desc = "Una pistola con poco retroceso y una gran cadencia de disparo, la P250 es una elección relativamente económica contra enemigos con protección." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "El SCAR-20 es un rifle de francotirador semiautomático que ofrece una alta cadencia de disparo y un potente daño a larga distancia a cambio de una velocidad de movimiento lenta y un precio elevado." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "El SSG08 de cerrojo es un rifle de francotirador que no causa mucho daño pero es bastante rentable, considerándose una sabia elección para los enfrentamientos a larga distancia durante las primeras rondas." },
    ["heavyassaultsuit"] = "Traje de asalto pesado",
    ["assaultsuit"] = "Kevlar y casco",
    ["assaultsuit_only_helmet"] = "Casco",
    ["kevlar"] = "Chaleco Kevlar",
    ["defuser"] = "Kit de desactivación",
    ["cutters"] = "Kit de rescate",
    ["revolver"] = { name = "Revólver R8", desc = "El revólver R8 ofrece una ronda de alta precisión y potencia a expensas de una pulsación de gatillo más larga. Disparar rápidamente 'abanicando' el percutor podría ser la mejor opción cuando se necesita poder de parada a quemarropa." },
    ["usp_silencer"] = { name = "USP-S", desc = "La favorita de los fans de Counter‑Strike: Source, la pistola USP con silenciador desmontable tiene menos retroceso y hace menos ruido para no llamar la atención." },
    ["knifebayonet"] = { name = "Bayoneta", desc = "Relativamente idéntica al diseño de la Segunda Guerra Mundial, la bayoneta aún conserva su lugar en la estrategia militar moderna. El uso de la bayoneta ha seguido siendo efectivo en conflictos actuales como la Guerra del Golfo y la de Afganistán." },
    ["knifeflip"] = { name = "Cuchillo plegable", desc = "Los cuchillos plegables tienen una hoja curvada de estilo persa con una punta afilada. Aunque la punta pueda ser frágil, el diseño general del cuchillo es sorprendentemente duradero." },
    ["knifegut"] = { name = "Cuchillo Destripador", desc = "La característica más notable de un cuchillo destripador es el gancho destripador que tiene al final de la hoja. Originalmente popularizado como una ayuda para los vendajes, el cuchillo destripador es también efectivo cortando materiales fibrosos como cuerdas, cinchas o cinturones de seguridad con bastante facilidad." },
    ["knifecss"] = { name = "Cuchillo clásico", desc = "Un clásico de la serie de Counter‑Strike, el filo de este cuchillo es de estelite y está encajado a presión firmemente en su sitio gracias a su ajuste preciso con el titanio del filo y del lomo de la hoja. El mango es de marfil de mastodonte fosilizado, envuelto en un revestimiento de fibra de carbono." },
    ["knifem9"] = { name = "Bayoneta M9", desc = "Esta es la bayoneta M-9. Pensada originalmente para ir acoplada a un rifle, también resulta muy adecuada para el combate en espacios cerrados." },
    ["knifekaram"] = { name = "Karambit", desc = "Con su hoja curvada emulando la garra de un tigre, el karambit fue desarrollado como parte de la disciplina marcial surasiática del silat. El cuchillo se usa normalmente con un agarre opuesto al de la hoja introduciendo el dedo índice en el aro." },
    ["knifetactical"] = { name = "Cuchillo del Cazador", desc = "Un cuchillo diseñado para usos tácticos modernos y cuya hoja está adaptada para el uso tanto de combate como de necesidades utilitarias. Ese estilo tantō exclusivo le proporciona una penetración máxima incluso a través de las superficies más gruesas." },
    ["knife_butterfly"] = { name = "Cuchillo Mariposa", desc = "Esto es una navaja de diseño personalizado, comúnmente conocida como cuchillo mariposa. La característica que define a esta arma es la apertura de abanico de la hoja que pivota libremente, que permite abrirla rápidamente o a escondidas. Debido a esto, las mariposas son ilegales en algunos países." },
    ["partypopper"] = "¡Confeti!",
    ["knife_falchion_advanced"] = { name = "Cuchillo Alfanje", desc = "Como homenaje moderno a una espada alfanje, esta hoja de punta cóncava tiene un filo curvado." },
    ["knife_push"] = { name = "Dagas Sombrías", desc = "Diseñada para proporcionar un brutalidad eficiente, usar una daga es tan simple como lanzar un puñetazo o dos." },
    ["knife_survival_bowie"] = { name = "Cuchillo Bowie", desc = "Este afilado cuchillo Bowie de espiga completa está diseñado para utilizarse en situaciones de supervivencia extremas." },
    ["healthshot"] = "Inyección medicinal",
    ["tagrenade"] = "Granada de reconocimiento táctico",
    ["exploding_barrel"] = "Barril explosivo",
    ["snowball"] = "Bola de nieve",
    ["stompdamagekillstring"] = "te ha aplastado el cráneo",
    ["dangerzone"] = "Danger Zone",
    ["autosentry"] = "Centinela automática",
    ["fists"] = "Puños",
    ["tablet"] = "Tableta",
    ["breachcharge"] = "Carga de demolición",
    ["bumpmine"] = "Eyector",
    ["axe"] = { name = "Hacha", desc = "El hacha, pesada y siempre disponible, tiene un lado afilado y otro romo. Blándela para realizar un ataque principal de daño reducido o lánzala para realizar un ataque secundario de daño elevado. ¿Cuántos robles roería un roedor...?" },
    ["hammer"] = { name = "Martillo", desc = "El martillo puede usarse para arreglar cosas y para romper cosas. Blándelo para realizar un ataque principal de daño reducido o lánzalo para realizar un ataque secundario de daño elevado. Si solo tienes un martillo, todo parece un clavo." },
    ["spanner"] = { name = "Llave inglesa", desc = "Una llave inglesa normalmente se utiliza para aplicar torsión al girar objetos, pero puedes golpear con ella lo que sea para realizar un ataque principal de daño reducido o lanzarla para realizar un ataque secundario de daño elevado. Llevar una llave inglesa a un tiroteo es una excelente manera de cagarla." },
    ["tripwirefire"] = "Fuego de cable trampa",
    ["knife_cord"] = { name = "Cuchillo encordado", desc = "Este cuchillo de supervivencia de hoja fija está diseñado para usarse bien como un arma bien como una herramienta, por ejemplo: para poner trampas, para cazar animales o para cortar ramas. El mango está envuelto en un cordón paracaidista multiuso." },
    ["knife_canis"] = { name = "Cuchillo de supervivencia", desc = "Este cuchillo táctico multiuso incluye un filo de sierra para desgarrar materiales toscos como hueso o fibra, además de un gancho afilado para eviscerar. El mango de material compuesto está sujeto a la hoja con tornillos hexagonales." },
    ["knife_ursus"] = { name = "Cuchillo ursus", desc = "Este cuchillo de supervivencia de estilo tantō cuenta con una hoja facetada y una espiga enteriza con talón percutor. Sin complicaciones, sin piezas móviles; solo una hoja fiable lista para hacer su trabajo." },
    ["knife_gypsy_jackknife"] = { name = "Navaja", desc = "Esta navaja con mango de mármol esmaltado esconde una pequeña pero increíblemente afilada cuchilla." },
    ["knife_outdoor"] = { name = "Cuchillo nómada", desc = "Esta navaja táctica ergonómica de hoja plegable incluye incrustaciones en un mango compuesto y una hoja ancha y sólida, útil para cortar y rebanar materiales." },
    ["knife_widowmaker"] = { name = "Cuchillo talón", desc = "Este karambit con mango de marfil posee remaches de latón y dientes de sierra, por lo que corta al entrar y desgarra al salir." },
    ["knife_stiletto"] = { name = "Estilete", desc = "Este delgado cuchillo de estilo italiano, foco de controversia e incluso regulación a lo largo de la historia, cuenta con una hoja accionada por resorte que se puede desplegar casi instantáneamente con tan solo pulsar un botón." },
    ["knife_skeleton"] = { name = "Cuchillo esqueletizado", desc = "Se ha encintado el puñal de este cuchillo afilado esqueletizado para mejorar su agarre. El agujero permite introducir un dedo para mayor estabilidad y seguridad." },
    ["knife_kukri"] = { name = "Cuchillo kukri", desc = "Utilizado en rituales tradicionales, como bodas y apuñalamientos." },
    ["firebomb"] = { name = "Bomba incendiaria", desc = "La granada incendiaria es una poderosa arma experimental que estalla en llamas de alta temperatura cuando se tira al suelo, quemando químicamente a cualquier jugador que se encuentre dentro de su amplio radio de propagación." },
    ["diversion"] = { name = "Dispositivo de distracción", desc = "Al lanzarlo, el dispositivo de distracción iluminará sectores en las tabletas y creará la ilusión de que hay enemigos adicionales." },
    ["frag_grenade"] = { name = "Granada de fragmentación", desc = "La granada de fragmentación experimental puede producir cantidades extremas de daño altamente explosivo en un área más amplia, por lo que es ideal tanto para estrategias ofensivas como defensivas." },
    ["shield"] = { name = "Escudo antidisturbios", desc = "Un dispositivo de protección diseñado para desviar o absorber el daño balístico y ayudar a proteger al usuario de las balas de varios calibres." },
    ["zone_repulsor"] = { name = "el dispositivo repulsor", desc = "Prototipo de Dispositivo de Protección contra Partículas de Emisión Radial" },
    ["glock_use"] = "• Letal de cerca y un fastidio a distancia.\n• Buena opción en la primera ronda de la mitad.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Precisión a distancia y disparos rápidos de cerca.\n• Buena opción en la primera ronda de la mitad.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Precisa, silenciosa y (algo) letal.\n• Buena opción en la primera ronda de la mitad.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Dos pistolas de disparo rápido por el precio de una.\n• Buena opción en la primera ronda de la mitad.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Una mejora del daño popular a la par que modesta.\n• Buena opción en rondas eco.\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Potencia, velocidad y precisión por un módico precio.\n• Buena opción en rondas eco.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Potencia de fuego explosiva para robar armas a los enemigos.\n• Buena opción en rondas eco.\n• Dificultad: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Dinámica y efectiva a distancia y de cerca.\n• Buena opción en rondas eco.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Tras una breve pausa, causa muchísimo daño.\n• Buena opción en rondas eco.\n• Dificultad: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Disparos mortales a la cabeza a cualquier distancia.\n• Buena opción en rondas eco.\n• Dificultad: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Muerte asegurada con un solo disparo a corta distancia.\n• Inténtalo bajo tu propia responsabilidad.\n• Dificultad: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Una lluvia de balas para masacrar enemigos sin protección.\n• Buena opción en las tres primeras rondas de la mitad.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Útil para disparar mientras corres y atravesar emplazamientos de bomba.\n• Buena opción en las tres primeras rondas de la mitad.\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Explosión de daño para denegar los asaltos del enemigo.\n• Buena opción en las tres primeras rondas de la mitad.\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Fácil de controlar y fiable para causar daño a media distancia.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Agilidad y sigilo para causar daño a media distancia.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Buena penetración del blindaje para luchar a media distancia.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Un chorro de balas sin fin superable solamente con un rifle.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Barato pero eficaz contra enemigos con protección.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Barato pero eficaz contra enemigos con protección.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• La clásica bestia, precisa y mortal.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Buena precisión y munición de sobra.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Preciso, silencioso y sin rastro.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Una mira optativa para una precisión excepcional.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Un arma letal aún más peligrosa con una mira.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Potencia devastadora para los francotiradores seguros de sí mismos.\n• Buena opción en rondas de compra completa.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Rifle automático de francotirador, tan arriesgado como fiable.\n• Buena opción solamente en circunstancias especiales.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Una potente herramienta (aunque arriesgada) para defender una posición.\n• Buena opción solamente en circunstancias especiales.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Ligero y potente para causar daño a larga distancia.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Sorprende al enemigo una y otra vez.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Escopeta versátil para el combate en espacios cerrados.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Escopeta potente para el combate en espacios cerrados.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Un monstruo de disparo rápido completamente automático.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• Al menos no tendrás que recargar...\n• Buena opción solamente en circunstancias especiales.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Frena al enemigo con disparos incesantes para ganar tiempo.\n• Buena opción en rondas de compra forzada.\n• Dificultad: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Causa daño o despeja granadas de humo.\n• Utilízala con cuidado.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Ciega y ensordece a los jugadores cercanos.\n• Lánzala antes de un ataque.\n• Dificultad: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Crea una nube de humo enorme.\n• Lánzala para bloquear la línea de visión del enemigo.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Imita el sonido de un disparo.\n• Lánzala pronto para desconcertar al enemigo.\n• Dificultad <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Despeja escondites con fuego.\n• Lánzalo antes de atacar emplazamientos de bomba.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Suprime los ataques del enemigo con fuego.\n• Lánzala en cuanto estés en peligro.\n• Dificultad: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Sobrevive a todas las balas, excepto las más letales.\n• Buena opción en las rondas de compra completa y forzada.\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Protección total, menos en la cabeza.\n• Buena opción en la primera ronda de la mitad.\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Desactiva bombas en la mitad de tiempo.\n• No seas un fracasado. ¡Sé un experto de la desactivación!\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Tarda menos tiempo en llevarte a los rehenes\n• Buena opción cuando tienes dinero extra\n• Dificultad: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "La CZ75-Auto, variante totalmente automática de la CZ75, es la opción ideal a corto plazo para darle la vuelta a la tortilla y apropiarte del arma de tu oponente. Aunque con tan poca munición en el cargador, requiere una excelente disciplina de gatillo.",
    ["m4a4"] = "Más precisa pero menos potente que su equivalente, el AK-47, la M4A4 es el rifle de asalto automático disponible para los antiterroristas.",
    ["sg553"] = "El SG553 exclusivo de los terroristas es una alternativa superior al AK-47 por su mayor efectividad en largas distancias.",
    ["decoy_grenade"] = "Al lanzarla, la granada señuelo emula el sonido del arma más poderosa que lleves en ese momento, provocando una ilusión que hará pensar al enemigo que hay fuerzas de apoyo adicionales.",
    ["incindiary_grenade"] = "Al lanzarla, la granada incendiaria libera una reacción química a alta temperatura que causará quemaduras a cualquiera que pase sobre el área de la explosión.",
    ["survival_taser"] = "Un arma de muy corto alcance capaz de matar de un solo disparo. También puede utilizarse para abrir cajas de armas.",
    ["survival_healthshot"] = "Restaura una parte de tu salud y proporciona un breve aumento de velocidad.",
    ["survival_vesthelm"] = "Proporciona resistencia al daño.",
    ["survival_shield"] = "Un escudo balístico antidisturbios que puede bloquear una gran cantidad de daño antes de ser destruido.",
    ["survival_parachute"] = "Puede desplegarse para prevenir daño por caída.",
    ["survival_exojump"] = "Aumenta significativamente la altura del salto.",
    ["survival_c4"] = "Colócalo en cualquier lugar del mapa para provocar una gran explosión. Puede utilizarse para abrir cajas fuertes.",
    ["survival_dronepilot"] = "Concede la capacidad de controlar los drones. Utiliza la tableta para seleccionar el dron que vas a pilotar.",
    ["survival_exploremoney"] = "Otorga dinero adicional por cada hexágono explorado.",
    ["survival_wavemoney"] = "Otorga dinero adicional por cada oleada de Danger Zone superada.",
}
