csstring = { -- Finnish
	["cat_pistols"] = "Pistoolit",
	["cat_heavy"] = "Raskaat",
	["cat_smg"] = "Konepistoolit",
	["cat_rifles"] = "Kiväärit",
	["cat_grenades"] = "Kranaatit",
	["cat_gear"] = "Varusteet",

    ["ak47"] = { name = "AK-47", desc = "Voimakas ja aina yhtä luotettava AK-47 on eräs maailman suosituimpia rynnäkkökivääreitä. Se on tappavimmillaan pieniä, hallittuja tulipurskeita ammuttaessa." },
    ["aug"] = { name = "AUG", desc = "AUG on tehokas ja tarkka kiikarirynnäkkökivääri, joka kompensoi pitkiä latausaikojaan tappavalla tarkkuudellaan ja suurella tulinopeudellaan." },
    ["awp"] = { name = "AWP", desc = "Pahamaineinen AWP on riskaabeli mutta hyödyllinen valinta. Sen tunnistaa äänestä ja siitä, että jokainen osuma on taattu tappo." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Desert Eagle on kallis ja tehokas, taitoa vaativa ja äärimmäisen suosittu pistooli, joka on pitkällä matkalla yllättävän tarkka." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Tupla-Berettat", desc = "Kahdella isolippaisella Berettalla yhtä aikaa ampuminen alentaa tarkkuutta ja hidastaa lataamista. Mutta toisaalta saa ampua kahdella isolippaisella Berettalla yhtä aikaa." },
    ["elite"] = "Tupla-Berettat",
    ["famas"] = { name = "FAMAS", desc = "FAMAS on penninvenyttäjän halpa vaihtoehto, joka osuu sopivasti kalliimpien kiväärien ja vähemmän tehokkaiden konepistoolien väliin." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Tarkka ja panssarin läpäisevä Five-SeveN on kallis, hitaasti lataava pistooli, joka tarjoaa vastapainona 20 panoksen lippaan ja pehmeän rekyylin." },
    ["flashbang"] = { name = "Valokranaatti", desc = "Valokranaatti ei tapa, mutta sokaisee hetkellisesti jokaisen iskukantaman alueella olevan, ja on siksi täydellinen vihollisen savustamiseen ulos ahtaista paikoista. Sen kova räjähdys peittää hetkellisesti myös askelten äänet." },
    ["g3sg1"] = { name = "G3SG1", desc = "Hintava G3SG1 hidastaa matkantekoasi huomattavasti, mutta ampuu paljon nopeammin kuin muut kiikarikiväärit." },
    ["galilar"] = { name = "Galil AR", desc = "Galil AR on terroristien rynnäkkökiväärien joukossa se halvempi vaihtoehto ja oiva ratkaisu keskipitkän ja pitkän matkan taisteluihin." },
    ["glock18"] = { name = "Glock-18", desc = "Glock 18 on hyödyllinen ensimmäisen kierroksen pistooli, joka pystyy ampumaan kolmen ammuksen sarjoja ja tehoaa parhaiten vihollisiin, joilla ei ole Kevlar-liiviä." },
    ["he_grenade"] = { name = "HE-kranaatti", desc = "Voimakas sirpalekranaatti kylvää tuhoa laajalle alueelle, ja on täydellinen suljettujen tilojen tyhjentämiseen vihollisista." },
    ["he_grenade_short"] = "HE-kranaatti",
    ["hegrenade"] = "HE-kranaatti",
    ["knife"] = { name = "Veitsi", desc = "Taisteluveitsi on hiljainen ja aina saatavilla. Sen tavallinen hyökkäys on nopea mutta heikko, vaihtoehtoinen hyökkäys tappavampi. Hiljaiset pelaajat saavat selkäänpuukottamalla välittömän tapon." },
    ["knife_t"] = "Veitsi",
    ["knife_gg"] = "Kultaveitsi",
    ["knife_ghost"] = { name = "Aaveveitsi", desc = "Kummitukset rakastavat kummitusveitsiä. Ole valppaana, kun ne saavat käsiinsä sellaisen! Ne yrittävät puukottaa ensimmäisen tilaisuuden tultua. Harmi kyllä, ne ovat kummituksia, eikä kummitusveitsetkään pysty vahingoittamaan ihmisiä...." },
    ["m249"] = { name = "M249", desc = "Tehokas ja avoimiin tiloihin soveltuva M249-konekivääri on täydellinen pelaajille, jotka haluavat lisää tarkkuutta ja suuremman ammusmäärän tulitusnopeuden kustannuksella." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Äänenvaimentimella varustettu M4A1 on pienilippaisempi ja hiljaisempi vaihtoehto, joka takaa tarkat laukaukset." },
    ["mac10"] = { name = "MAC-10", desc = "MAC-10 on käytännössä laatikko, joka syytää luoteja kuin tykinsuusta, mutta tarkkuudessa ja rekyylissä olisi toivomisen varaa." },
    ["p90"] = { name = "P90", desc = "P90 on helppo tunnistaa ainutlaatuisesta bullpup-mallistaan. Se sopii ison lippaan ja vähäisen rekyylin ansiosta liikkeessä ampumiseen." },
    ["smoke_grenade"] = { name = "Savukranaatti", desc = "Savukranaatti tuottaa keskikokoisen savuverhon. Sen avulla voit suojella tiimiäsi tehokkaasti tarkka-ampujilta, tai vaikka tehdä harhautuksia." },
    ["smokegrenade"] = "Savukranaatti",
    ["ump45"] = { name = "UMP-45", desc = "UMP45 on konepistoolien keskivertoa. Sen pieni lipas on aseen ainoa huono puoli, muuten se on hyvin monipuolinen automaattiase lähitaisteluihin." },
    ["xm1014"] = { name = "XM1014", desc = "XM1014 on tehokas täysautomaattihaulikko, jonka kallista hintalappua kompensoi sen tulinopeus." },
    ["c4"] = { name = "C4-räjähde", desc = "Tämä improvisoitu muoviräjähde on vakaa ja kestää useimmat fyysiset rasitukset, ja sytytettäessä sen räjähdysnopeus on yli 8 000 m/s." },
    ["bizon"] = { name = "PP-Bizon", desc = "Bizon-konepistooli ei tarjoa suurta tulivoimaa, mutta siinä on ainutlaatuinen, tilava rumpulipas, joka lataa nopeasti." },
    ["mag7"] = { name = "MAG-7", desc = "Erikoisjoukkojen Mag-7 takaa tappavan annoksen vahinkoa lähikantamalta. Nopea lipaslataus tekee siitä mahtavan taktisen vaihtoehdon." },
    ["negev"] = { name = "Negev", desc = "Negev pitää viholliset loitolla tarkalla tulituksellaan, kunhan sinulla on tarpeeksi aikaa saada se hallintaan." },
    ["sawedoff"] = { name = "Katkaistu haulikko", desc = "Klassinen katkaistu haulikko tekee hurjan määrän vahinkoa lähietäisyydeltä, mutta kun ase on epätarkka, ampuu hitaasti ja levittää haulit ympäriinsä, niin ensimmäisen osuman on paras tappaa." },
    ["tec9"] = { name = "Tec-9", desc = "Ihanteellinen pistooli liikkuvalle terroristille. Tec-9 tappaa lähitaistelussa ja tarjoaa suuren lippaan." },
    ["taser"] = { name = "Zeus x27", desc = "Zeus x27 on täydellinen lähikantaman väijytyksiin ja suljettujen tilojen taisteluihin, sillä se voi lamauttaa vihollisen yhdellä osumalla." },
    ["molotov"] = { name = "Polttopullo", desc = "Molotov on tehokas ja arvaamaton ase, joka leimahtaa liekkeihin osuessaan maahan ja vahingoittaa sen lähellä olevia pelaajia." },
    ["incgrenade"] = "Palopommi",
    ["incgrenade_short"] = "Palopommi",
    ["decoy"] = "Harhautuskranaatti",
    ["decoy_short"] = "Harhautus",
    ["hkp2000"] = { name = "P2000", desc = "Tarkka ja hallittava saksalaisvalmisteinen P2000 on hyödyllinen ensimmäisen erän pistooli, joka toimii parhaiten suojattomia vihollisia vastaan." },
    ["mp7"] = { name = "MP7", desc = "MP7 on monipuolinen ja kallis saksalainen konepistooli, joka on täydellinen lähitaistelutilanteissa." },
    ["mp5sd"] = { name = "MP5-SD", desc = "MP5 on ikoninen konepistooli, jota on yritetty turhaan jäljitellä. Se on ehkä maailman monikäyttöisin ja suosituin konepistooli. Tästä versiosta löytyy integroitu äänenvaimennin, joka tekee mahtavasta aseesta hiirenhiljaisen." },
    ["mp9"] = { name = "MP9", desc = "Sveitsiläinen MP9 on ergonominen polymeerikonepistooli, joka on varsinkin yksityisten vartiointifirmojen suosiossa." },
    ["nova"] = { name = "Nova", desc = "Nova on erittäin halpa väijytysase niille, joilla on matti kukkarossa." },
    ["p250"] = { name = "P250", desc = "P250 on hyvin vähän potkaiseva ja nopeasti ampuva käsiase, joka on halpa ratkaisu panssaroituja vihollisia vastaan." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "SCAR-20 on puoliautomaattinen kiikarikivääri, joka tulittaa nopeasti ja tehokkaasti pitkällä matkalla, mutta hidastaa liikettä ja maksaa hunajaa." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "SSG08-pulttilukkokivääri tekee vähäistä vahinkoa halpaan hintaan, joten se sopii hyvin alkuerien pitkän matkan tarkkuusammuntaan." },
    ["heavyassaultsuit"] = "Raskas rynnäkköpuku",
    ["assaultsuit"] = "Kevlar ja kypärä",
    ["assaultsuit_only_helmet"] = "Kypärä",
    ["kevlar"] = "Kevlar-liivi",
    ["defuser"] = "Pomminpurkupakkaus",
    ["cutters"] = "Pelastuspakkaus",
    ["revolver"] = { name = "R8-revolveri", desc = "R8-revolveri on varsin tarkka voimanpesä, mutta liipaisinveto hidas. Kun lähitaistelussa tarvitaan raakaa pysäytysvoimaa, nopea tulitus iskurvasaraa läpsimällä on paras vaihtoehto." },
    ["usp_silencer"] = { name = "USP-S", desc = "Vaimennettu USP-pistooli on pelaajien suosikki Counter-Strike: Sourcesta. Siihen kuuluu irrotettava äänenvaimennin, joka vähentää rekyyliä sekä huomiota herättävää ääntä." },
    ["knifebayonet"] = { name = "Pistin", desc = "Pistin ei ole juuri muuttunut sitten toisen maailmansodan, mutta sillä on silti paikkansa nykypäivän taistelutaktiikoissa. Pistinrynnäköt ovat pysyneet tehokkaina viime aikoinakin, kuten Persianlahden ja Afganistanin sodissa." },
    ["knifeflip"] = { name = "Taittoveitsi", desc = "Taittoveitsissä on persialaistyylinen kaareva terä, jossa on terävä kärki. Vaikka kärki itsessään saattaa olla särkyvä, taittoveitsi on yllättävän kestävä sen muotoilun vuoksi." },
    ["knifegut"] = { name = "Metsästysveitsi", desc = "Metsästysveitsen huomattavin ominaisuus on sen koukku terän selkäpuolella. Alun perin se yleistyi metsästyssaaliiden käsittelyn apuvälineenä, mutta leikkaa helposti myös narua, verkkoa tai turvavyön." },
    ["knifecss"] = { name = "Klassinen veitsi", desc = "Counter-Strike-sarjan klassikko. Puukon laita on puristettua stelliittiä, joka istuu täydellisesti muun terän titaaniin. Puukon kahva on fossilisoitunutta mastodontin luuta hiilikuitutupessa." },
    ["knifem9"] = { name = "M9-pistin", desc = "M9-pistin suunniteltiin alun perin kiinnitettäväksi kivääriin, mutta toimii hyvin myös lähikontaktissa." },
    ["knifekaram"] = { name = "Karambit", desc = "Karambit, jonka kaareva terä muistuttaa tiikerin kynttä, kehitettiin osana Kaakkois-Aasian silat-kamppailulajeja. Veistä pidetään yleensä terä alaspäin etusormen ollessa veitsen kahvassa olevassa sormiaukossa." },
    ["knifetactical"] = { name = "Metsämiehen veitsi", desc = "Moderneihin, taktisiin käyttötarkoituksiin suunniteltu veitsi, jonka terä sopii mainiosti käytettäväksi sekä taistelussa että työkaluna. Ainutlaatuinen Tanto-terä läpäisee kovimmatkin pinnat tehokkaasti." },
    ["knife_butterfly"] = { name = "Perhosveitsi", desc = "Tämä on mittatilauksena tehty balisong, joka tunnetaan yleisesti perhosveitsenä. Tämän aseen erityispiirteenä on sen vapaasti kääntyvän terän viuhkamainen avautuminen, joka sallii sen nopean käyttöönoton tai kätkemisen. Tämän seurauksena perhosveitset ovat laittomia monissa maissa." },
    ["partypopper"] = "Paukkuserpentiini!",
    ["knife_falchion_advanced"] = { name = "Falchion-veitsi", desc = "Nykyaikaisena kunnianosoituksena falchion-miekalle tässä terässä on kurvikas kärki." },
    ["knife_push"] = { name = "Varjotikarit", desc = "Tehokas mutta brutaali nyrkkipuukko yhtä yksinkertainen kuin nyrkinisku naamaan." },
    ["knife_survival_bowie"] = { name = "Bowie-puukko", desc = "Tämä täysruotorakenteinen, hammastettu Bowie-puukko on suunniteltu kovaan käyttöön brutaaleissa selviytymistilanteissa." },
    ["healthshot"] = "Lääkepiikki",
    ["tagrenade"] = "Taktinen tiedustelukranaatti",
    ["exploding_barrel"] = "Räjähtävä tynnyri",
    ["snowball"] = "Lumipallo",
    ["stompdamagekillstring"] = "murskasi kallosi",
    ["dangerzone"] = "Vaaravyöhyke",
    ["autosentry"] = "Automatisoitu vartiotykki",
    ["fists"] = "Nyrkit",
    ["tablet"] = "Tabletti",
    ["breachcharge"] = "Murtopanos",
    ["bumpmine"] = "Pomppumiina",
    ["axe"] = { name = "Kirves", desc = "Raskas ja aina saatavilla. Kirveessä on terävä ja tylsä puoli. Heilauta sitä päähyökkäyaseena ja tee vähän vahinkoa tai tee kakkoshyökkäys heittämällä ja tekemällä paljon vahinkoa. Tämän aseen kanssa et jää puun ja kuoren väliin!" },
    ["hammer"] = { name = "Vasara", desc = "Vasara on oiva ase asioiden korjaamiseen tai rikkomiseen. Heilauta sitä päähyökkäysaseena ja tee vähän vahinkoa tai tee kakkoshyökkäys heittämällä ja tekemällä paljon vahinkoa. Jos käytössä on vain vasara, kaikki näyttää nauloilta." },
    ["spanner"] = { name = "Jakoavain", desc = "Jakoavain antaa yleensä esimerkiksi muttereiden kiristykseen vääntövoimaa, mutta päähyökkäysaseena sillä voi lyödä ja tehdä vähän vahinkoa tai sillä voi tehdä kakkoshyökkäyksen ja paljon vahinkoa. Jakoavain on kuin vahinko: sen voi laittaa kiertämään." },
    ["tripwirefire"] = "Ansalanka",
    ["knife_cord"] = { name = "Paracord-kahvainen kenttäpuukko", desc = "Tämä selviytymisveitsi on suunniteltu sekä aseeksi että työkaluksi, ja sillä voi asettaa ansoja, metsästää eläimiä ja raivata lehvistöä. Veitsen kahvaan on kiedottu monikäyttöinen paracord-naru." },
    ["knife_canis"] = { name = "Selviytymisveitsi", desc = "Tässä monikäyttöisessä taktisessa puukkossa on terävä koukku sekä sahalaitainen reuna, jonka ansioista sillä voi repiä jämäkämpääkin materiaalia, kuten luita tai kuituja. Sen komposiittikahva on kiinnitetty terään tukevasti kuusiomuttereilla." },
    ["knife_ursus"] = { name = "Karhuveitsi", desc = "Tässä tantō-tyylisessä selviytymisveitsessä on viistetty terä ja täysruoto, jotka on viimeistelty iskuponsilla. Ei hössötystä eikä liikkuvia osia - ainoastaan luotettava veitsi, joka on valmis töihin." },
    ["knife_gypsy_jackknife"] = { name = "Linkkuveitsi", desc = "Marmorikiillekahvaisessa taittoveitsessä on pieni mutta vaarallinen ja kapea terä." },
    ["knife_outdoor"] = { name = "Nomad-puukko", desc = "Tämä ergonominen metsästykseen tarkoitettu kääntöveitsi koostuu komposiittikahvasta sekä leveästä ja tukevasta terästä. Hyödyllinen leikkelyyn ja materiaalin repimiseen." },
    ["knife_widowmaker"] = { name = "Kynsiveitsi", desc = "Tässä norsunluukahvaisessa karambit-veitsessä on messinkiniitit ja sahanteräselkä, minkä vuoksi se leikkaa mennessä ja repii tullessa." },
    ["knife_stiletto"] = { name = "Stiletti", desc = "Historiassa eripuran ja säännöstelyn keskipisteenä olleessa italialaistyyppisessä stilettiveitsessä on jousitettu terä, jonka saa otettua esiin lähes välittömästi nappia painamalla." },
    ["knife_skeleton"] = { name = "Skeleton-puukko", desc = "Skeleton-puukon kahva on teipattu, jotta siitä saa paremman otteen. Reikään voi pujottaa sormen, jolloin ote on vakaampi ja turvallisempi." },
    ["knife_kukri"] = { name = "Kukri-veitsi", desc = "Käytetään perinteisissä rituaaleissa, kuten häissä tai puukotuksissa." },
    ["firebomb"] = { name = "Polttopullo", desc = "Palopommi on voimakas kokeellinen ase. Heitettäessä se syttyy palamaan, vapauttaa suuren määrän lämpöä ja polttaa sen laajalla räjähdysalueella olevia." },
    ["diversion"] = { name = "Harhautuslaite", desc = "Heitetty harhautuslaite korostaa tabletilla sektoreita, mikä luo harhan useammasta vihollisesta." },
    ["frag_grenade"] = { name = "Sirpalekranaatti", desc = "Kokeellinen sirpalekranaatti voi aiheuttaa valtavan räjähdysvahingon laajalla alueella. Nämä ominaisuudet tekevät siitä ihanteellisen sekä hyökkäys- että puolustusstrategioille." },
    ["shield"] = { name = "Mellakkakilpi", desc = "Suojavaruste, joka on suunniteltu vaimentamaan ja kääntämään ballistinen vahinko pois kohteesta sekä auttamaan suojaamaan kantajaansa ammussateelta." },
    ["zone_repulsor"] = { name = "Repulsorilaite", desc = "Pienhiukkassäteilyn suojalaitteen prototyyppi" },
    ["glock_use"] = "• Tehokas lähietäisyydeltä, hyödytön kaukotaistelussa\n• Sopii puoliskon ensimmäiseen erään\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Tarkka kaukoetäisyydeltä, räiskintäominaisuus lähitaistelussa\n• Sopii puoliskon ensimmäiseen erään\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Tarkka, hiljainen ja jokseenkin tappava\n• Sopii puoliskon ensimmäiseen erään\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Kaksi sarjatulipistoolia yhden hinnalla\n• Sopii puoliskon ensimmäiseen erään\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Suosittu vaikkakin vaatimaton vahinkolisä\n• Sopii rahansäästöeriin\n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Voimallla, vauhdilla ja tarkkuudella on hintansa \n• Sopii rahansäästöeriin \n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Tulivoiman ryöppy riisuu viholliset aseista\n• Sopii rahansäästöeriin\n• Vaikeustaso: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Helposti kannettava, tehokas sekä läheltä että kaukaa\n• Sopii rahansäästöeriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Aiheuttaa massiivista vahinkoa pienellä viiveellä\n• Sopii rahansäästöeriin\n• Vaikeustaso: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Pääosumat tappavat läheltä tai kaukaa\n• Sopii rahansäästöeriin\n• Vaikeustaso: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Kertakäyttöinen yhdellä osumalla tappava lähiase\n• Kokeile omalla vastuulla\n• Vaikeustaso: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Luotisade lahtaa panssaria vailla olevat viholliset hetkessä\n• Sopii puoliskon kolmeen ensimmäiseen erään\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Pommialueiden rynnäköihin soveltuva ase\n• Sopii puoliskon kolmeen ensimmäiseen erään\n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Tulinopeus ja -voima hidastavat vihollisten hyökkäystä\n• Sopii puoliskon kolmeen ensimmäiseen erään \n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Helppokäyttöinen ja luotettava keskietäisyydeltä\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Helppokäyttöinen ja matalaprofiilinen keskipitkällä kantamalla\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Hyvä panssarinläpäisykyky keskietäisyydellä\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Loputon luotisade, jonka peittoavat vain kiväärit\n• Sopii täysostoeriin\n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Halpa, mutta tehokas läpäisemään vihollisten panssareja\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Halpa, mutta tehokas läpäisemään vihollisten panssareja\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• Tarkka ja tappava klassikko\n• Sopii täysostoeriin\n• Vaikeustaso: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Hyvä tarkkuus ja reilusti ammuksia\n• Sopii täysostoeriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Tarkka, hiljainen eikä jätä valojuovia\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Erityisen tarkka valinnaisen kiikaritähtäimen kera\n• Sopii täysostoseriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Tappava ase, joka on entistä vaarallisempi kiikaritähtäimen kera\n• Sopii täysostoeriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Järisyttävän tehokas kokeneen tarkka-ampujan käsissä\n• Sopii täysostoeriin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Automaattinen tarkkuuskivääri, jonka hyöty-laatusuhde riippuu tilanteesta\n• Sopii vain erikoistilanteisiin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Vahva mutta riskaabeli työkalu tuliaseman turvaamiseen\n• Sopii vain erikoistilanteisiin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Kevyt ja vahva ase, jolla ammutaan kaukaa\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Yllätä vihollinen, lataa ase ja toista sama kuvio!\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Monikäyttöinen haulikko lähitaisteluihin\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Erittäin tehokas haulikko lähitaisteluihin\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Nopea ja tappava konetuliase\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• Tätä ei sentään tarvitse ladata\n• Sopii vain erikoistilanteisiin\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Äärimmäisen tarkka, sopii taustatuleen ja vihollisen hidastamiseen\n• Sopii ostopakkoeriin\n• Vaikeustaso: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Tee vahinkoa tai hankkiudu eroon savukranaattien savupilvistä\n• Käytä varoen\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Sokaisee ja kuurouttaa lähellä olevat pelaajat\n• Heitä ennen hyökkäystä\n• Vaikeustaso: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Luo suuren savupilven\n• Heitä sabotoidaksesi vihollisten näkökenttää\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Imitoi ampumisääniä\n• Heitä aikaisessa vaiheessa hämätäksesi vihollisia\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Häätää viholliset ulos piiloistaan tulella\n• Heitä ennen pommialueelle hyökkäämistä\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Hidastaa vihollisten hyökkäystä sytyttämällä alueen tuleen\n• Heitä heti, kun olet pulassa\n• Vaikeustaso: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Pysäyttää useimmat luodit\n• Sopii täysosto- ja ostopakkoeriin \n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Suojaa koko vartaloa päätä lukuun ottamatta\n• Sopii puoliskon ensimmäiseen erään\n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Pura pommi kaksi kertaa nopeammin\n• Osta pomminpurkupakkaus ja säästy posauksilta!\n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Kanna panttivangit turvaan vauhdilla\n• Sopii tilanteisiin, joissa rahaa on yllin kyllin\n• Vaikeustaso: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "CZ75-Auto on CZ75:n täysin automaattinen versio ja oiva, väliaikainen valinta tappiotilanteesta nousemiseen ja vihollisten aseiden varastamiseen. Pienen lipaskokonsa takia se vaatii käyttäjältään hyvää liipasinkuria.",
    ["m4a4"] = "M4A4 on erikoisjoukkojen tarkempi, mutta heikompi vastine terroristien AK-47-rynnäkkökiväärille.",
    ["sg553"] = "Terroristien yksinoikeutettu SG553 on kiikarilla varustettu vaihtoehto AK-47-rynnäkkökiväärille pitkän matkan taisteluihin.",
    ["decoy_grenade"] = "Heitettäessä harhautuskranaatti toistaa tehokkaimman kantamasi aseen ääntä, luoden illuusion apujoukoista.",
    ["incindiary_grenade"] = "Heitettäessä palopommin kemiallinen reaktio vapauttaa suuren määrän lämpöä, joka polttaa jokaista sen suurella räjädysalueella olevaa.",
    ["survival_taser"] = "Erittäin lyhyen kantaman ase, jolla voi tappaa yhdellä laukauksella. Voidaan käyttää myös aselaatikoiden avaamiseen.",
    ["survival_healthshot"] = "Palauttaa osan terveydestäsi ja tarjoaa lyhytkestoisen nopeuslisän.",
    ["survival_vesthelm"] = "Antaa vahingonvastustusta.",
    ["survival_shield"] = "Mellakkakilpi, joka torjuu paljon vahinkoa ennen tuhoutumistaan.",
    ["survival_parachute"] = "Estää vahingoittumasta putoamisen yhteydessä.",
    ["survival_exojump"] = "Lisää huomattavasti hypyn korkeutta.",
    ["survival_c4"] = "Aseta mihin tahansa kartalla aiheuttamaan suuri räjähdys. Voidaan käyttää tallelokeroiden avaamiseen.",
    ["survival_dronepilot"] = "Voit hallita lennokkeja tabletillasi. Valitse tabletilla hallintaan otettava lennokki.",
    ["survival_exploremoney"] = "Antaa lisärahaa jokaisesta tutkitusta sektorista.",
    ["survival_wavemoney"] = "Myöntää lisää rahaa jokaisesta selvitystä Vaaravyöhykkeen räjähdysaallosta.",
}
