csstring = { -- Italian
	["cat_pistols"] = "Pistole",
	["cat_heavy"] = "Armi pesanti",
	["cat_smg"] = "Mitra",
	["cat_rifles"] = "Fucili",
	["cat_grenades"] = "Granate",
	["cat_gear"] = "Attrezzatura",

    ["ak47"] = { name = "AK-47", desc = "Potente ed affidabile, l'AK-47 è uno dei fucili d'assalto più popolari del mondo. È più letale in raffiche di fuoco brevi e controllate." },
    ["aug"] = { name = "AUG", desc = "Potente e preciso, l'AUG, dotato di mirino di precisione, compensa i suoi lunghi tempi di ricarica con una dispersione ridotta ed un'alta cadenza di tiro." },
    ["awp"] = { name = "AWP", desc = "Il famigerato AWP, rischioso da usare ma molto utile, è riconoscibile per il suo tratto distintivo: un colpo, un morto." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Tanto costosa quanto potente, la Desert Eagle è una pistola famosa che è difficile da padroneggiare ma incredibilmente precisa a lunga gittata." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Doppia Beretta", desc = "Sparare contemporaneamente due Beretta con caricatori maggiorati ridurrà la precisione e aumenterà i tempi di ricarica. Dal lato positivo, potrai sparare contemporaneamente con due Beretta dotate di caricatori maggiorati." },
    ["elite"] = "Doppia Beretta",
    ["famas"] = { name = "FAMAS", desc = "Una scelta economica per i giocatori rimasti a tasche vuote, il FAMAS colma lo spazio che si trova tra i fucili più costosi e i mitra meno efficaci." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Estremamente precisa e utile contro i giubbotti antiproiettile, la costosa Five-Seven è un'arma lenta da ricaricare, compensata da un caricatore da 20 colpi e da un rinculo modesto." },
    ["flashbang"] = { name = "Granata flashbang", desc = "Questa granata flashbang non letale acceca chiunque rimanga esposto alla luce dell'esplosione, l'ideale per stanare i nemici in ambienti chiusi. Inoltre, il suo suono assordante maschera temporaneamente il rumore dei passi." },
    ["g3sg1"] = { name = "G3SG1", desc = "Il costoso G3SG1 riduce la velocità di movimento considerevolmente ma compensa con una cadenza di tiro più alta rispetto a ogni altro fucile di precisione." },
    ["galilar"] = { name = "Galil AR", desc = "Una scelta meno costosa tra i fucili esclusivi ai Terroristi, il Galil AR è un'arma utile nel combattimento a distanza medio-lunga." },
    ["glock18"] = { name = "Glock-18", desc = "La Glock 18 è un'utile pistola per il primo round che si dimostra più efficace contro avversari senza giubbotto antiproiettile ed è capace di sparare in raffiche da 3 colpi." },
    ["he_grenade"] = { name = "Granata ad alto esplosivo", desc = "Questa granata a frammentazione ad alto potenziale esplosivo infligge danni pesanti in un'ampia area, l'ideale per ripulire una stanza piena di forze ostili." },
    ["he_grenade_short"] = "Granata AE",
    ["hegrenade"] = "Granata ad alto esplosivo",
    ["knife"] = { name = "Coltello", desc = "Silenzioso e sempre disponibile, il coltello ha un attacco primario rapido a danno contenuto, e uno secondario lento a danno elevato. Una pugnalata alle spalle ricompenserà i giocatori furtivi con un'uccisione istantanea." },
    ["knife_t"] = "Coltello",
    ["knife_gg"] = "Coltello dorato",
    ["knife_ghost"] = { name = "Lama spettrale", desc = "I fantasmi amano i coltelli. Quando ne hanno uno per le mani, fai attenzione! Cercheranno di pugnalarti appena ne avranno l'occasione. Peccato che siano fantasmi, e che i coltelli fantasma non possano ferire le persone..." },
    ["m249"] = { name = "M249", desc = "Una potente mitragliatrice da campo aperto, l'M249 è la scelta perfetta per i giocatori che desiderano rinunciare ad un'alta cadenza di tiro per una precisione maggiore e una grande capacità di munizioni." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Meno costoso e dotato di un caricatore di capacità inferiore rispetto alla sua versione normale, l'M4A1 silenziato garantisce colpi più difficili da udire, un rinculo ridotto ed una maggior precisione." },
    ["mac10"] = { name = "MAC-10", desc = "Fondamentalmente, una scatoletta da cui escono fuori i proiettili, il MAC-10 fa vanto di una cadenza di tiro rapida, a discapito di una dispersione dei colpi poco precisa e di un alto rinculo." },
    ["p90"] = { name = "P90", desc = "Facilmente riconoscibile per la sua configurazione bullpup, la P90 è un'arma ottima per sparare in movimento grazie al caricatore ad alta capacità e al basso rinculo." },
    ["smoke_grenade"] = { name = "Granata fumogena", desc = "La granata fumogena crea una cortina di fumo in un'area contenuta. Può occultare la tua squadra in maniera efficace dai cecchini, o può tornare utile come diversivo." },
    ["smokegrenade"] = "Granata fumogena",
    ["ump45"] = { name = "UMP-45", desc = "Figlio incompreso di mezzo nella famiglia dei mitra, l'UMP45 è dotato di un caricatore piccolo, unico neo di un'arma automatica altrimenti versatile che eccelle in scontri ravvicinati." },
    ["xm1014"] = { name = "XM1014", desc = "L'XM1014 è un potente fucile a pompa automatico che giustifica il suo prezzo un po' alto con la capacità di riverniciare una stanza di piombo in pochi istanti." },
    ["c4"] = { name = "Esplosivo C4", desc = "Stabile e resistente alla maggior parte degli shock fisici, questo esplosivo plastico improvvisato ha una velocità di detonazione di oltre 8000 metri al secondo quando viene innescato." },
    ["bizon"] = { name = "PP-Bizon", desc = "Il mitra Bizon ha una limitata potenza di fuoco, ma offre un caricatore a tamburo ad alta capacità espressamente progettato che si ricarica rapidamente." },
    ["mag7"] = { name = "MAG-7", desc = "Il Mag-7, esclusivo per gli AT, è in grado di infliggere una notevole quantità di danni a distanza ravvicinata. Il suo caratteristico caricatore rapido lo rende una scelta tattica molto interessante." },
    ["negev"] = { name = "Negev", desc = "Il Negev è un'arma molto potente, in grado di tenere il nemico a distanza grazie al suo fuoco di soppressione, sempre che tu ti possa permettere il tempo per riuscire a controllarlo." },
    ["sawedoff"] = { name = "Fucile a canne mozze", desc = "Il classico fucile a canne mozze infligge gravissimi danni a distanza ravvicinata, ma con la sua bassa precisione, la sua rosa ampia e i suoi lunghi tempi tra un colpo e il successivo, ti converrà mirare bene e assicurarti di uccidere." },
    ["tec9"] = { name = "Tec-9", desc = "Ideale per le sparatorie in corsa, questa pistola per i Terroristi è letale negli scontri ravvicinati e dispone di un caricatore molto capiente." },
    ["taser"] = { name = "Zeus x27", desc = "Perfetto per le imboscate a corta distanza e per gli scontri ravvicinati, lo Zeus x27 è in grado di rendere inoffensivo un nemico in un solo colpo." },
    ["molotov"] = { name = "Molotov", desc = "La molotov è un'arma potente e imprevedibile adatta a negare l'accesso ad un'area, che scoppia in un tappeto di fiamme quando viene scagliata a terra, ferendo qualunque giocatore si trovi nel suo raggio d'azione." },
    ["incgrenade"] = "Granata incendiaria",
    ["incgrenade_short"] = "Incendiaria",
    ["decoy"] = "Granata diversiva",
    ["decoy_short"] = "Diversiva",
    ["hkp2000"] = { name = "P2000", desc = "Precisa e controllabile, la P2000, di fabbricazione tedesca, è un'utile pistola per il primo round che si dimostra efficace contro gli avversari senza giubbotto antiproiettile." },
    ["mp7"] = { name = "MP7", desc = "Versatile ma costoso, l'MP7 di fabbricazione tedesca è un mitra perfetto per il combattimento a distanza ravvicinata ad alto impatto." },
    ["mp5sd"] = { name = "MP5-SD", desc = "Spesso imitato, ma mai eguagliato, l'emblematico MP5 è forse il mitra più versatile e popolare del mondo. La variante SD di quest'arma già formidabile presenta un silenziatore integrato, che la rende silenziosa come un sussurro." },
    ["mp9"] = { name = "MP9", desc = "Fabbricato in Svizzera, l'innovativo mitra MP9 è un'arma ergonomica in polimeri prediletta dalle aziende di sicurezza private." },
    ["nova"] = { name = "Nova", desc = "Il misero prezzo del Nova lo rende un'arma ottima per le imboscate per una squadra rimasta al verde." },
    ["p250"] = { name = "P250", desc = "La P250, una pistola a basso rinculo ed alta cadenza di tiro, è una scelta relativamente poco costosa contro avversari dotati di giubbotto antiproiettile." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "Lo SCAR-20 è un fucile di precisione semiautomatico che offre un'alta cadenza di tiro e una grande potenza di fuoco a lunga gittata al prezzo di un ingombro notevole e di un costo impressionante." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "L'SSG08 a otturatore girevole-scorrevole è un fucile di precisione a bassa potenza di fuoco ma molto efficace per il suo prezzo, che lo rende una scelta appetibile per il tiro a lunga distanza nei primi round." },
    ["heavyassaultsuit"] = "Armatura pesante",
    ["assaultsuit"] = "Giubbotto antiproiettile ed elmetto",
    ["assaultsuit_only_helmet"] = "Elmetto",
    ["kevlar"] = "Giubbotto antiproiettile",
    ["defuser"] = "Kit di disinnesco",
    ["cutters"] = "Kit di salvataggio",
    ["revolver"] = { name = "Revolver R8", desc = "Il Revolver R8 spara un colpo molto preciso e potente a discapito della lentezza del grilletto. Quando è necessaria la potenza di fuoco a bruciapelo, la migliore opzione potrebbe essere quella di sparare rapidamente sventolando il cane della pistola." },
    ["usp_silencer"] = { name = "USP-S", desc = "Un'arma amata dai fan di Counter-Strike: Source, la pistola silenziata USP è dotata di un silenziatore smontabile che fornisce un rinculo minore e contemporaneamente evita che il rumore dello sparo attiri troppo l'attenzione." },
    ["knifebayonet"] = { name = "Baionetta", desc = "Pressoché invariata rispetto alla sua versione della seconda guerra mondiale, la baionetta conserva ancora un ruolo nelle strategie militari moderne. Le cariche di baionetta hanno mantenuto la loro efficacia anche più recentemente, nella guerra del Golfo e nella guerra in Afghanistan." },
    ["knifeflip"] = { name = "Coltello ricurvo", desc = "Il coltello ricurvo sfoggia una lama persiana ricurva a punta acuminata. Sebbene la punta in sé sia fragile, la struttura generale del coltello ricurvo è incredibilmente resistente." },
    ["knifegut"] = { name = "Coltello da sventramento", desc = "La caratteristica più saliente di un coltello da sventramento è l'uncino sul dorso della lama. In origine pensato per agevolare la rimozione delle viscere nelle battute di caccia, l'uncino si dimostra particolarmente efficace anche per tagliare materiali fibrosi come corde, cinghie o cinture di sicurezza." },
    ["knifecss"] = { name = "Coltello classico", desc = "Un classico della serie di Counter-Strike: la lama è realizzata meticolosamente in Stellite e titanio. Il manico è realizzato in avorio di mastodonte fossilizzato e rinforzato in fibra di carbonio." },
    ["knifem9"] = { name = "Baionetta M9", desc = "Questa è la baionetta M-9. Originariamente pensata per essere montata sul fucile, rimane comunque ben adatta agli scontri ravvicinati." },
    ["knifekaram"] = { name = "Karambit", desc = "Con la sua lama ricurva a mo' di artiglio di tigre, il karambit fu sviluppato come parte integrante della disciplina silat di arti marziali asiatiche di Sud-Est. Il coltello è tipicamente impugnato a rovescio, facendo passare l'indice nell'apposito anello." },
    ["knifetactical"] = { name = "Coltello da cacciatore", desc = "Un coltello realizzato per usi tattici moderni, la lama è utilizzabile sia per il combattimento che per scopi generici. La caratteristica lama a punta Tanto permette la massima penetrazione anche nelle superfici più resistenti." },
    ["knife_butterfly"] = { name = "Coltello a farfalla", desc = "Questo è un balisong di fattura personalizzata, conosciuto comunemente con il nome di coltello a farfalla. La caratteristica distintiva di quest'arma è il sistema di apertura a ventaglio della lama a perno libero, che le consente di venire estratta o celata molto rapidamente. Per questo motivo, i coltelli a farfalla sono vietati in quasi tutto il mondo." },
    ["partypopper"] = "Petardi da festa!",
    ["knife_falchion_advanced"] = { name = "Coltello falchion", desc = "Un omaggio all'antico falchion in chiave moderna, questa lama uncinata ha il filo curvo." },
    ["knife_push"] = { name = "Fendi ombra", desc = "Progettati per una meticolosa brutalità, utilizzare questi pugnali è semplice come tirare un pugno o due." },
    ["knife_survival_bowie"] = { name = "Coltello Bowie", desc = "Questo affilato coltello Bowie dalla lama parzialmente nascosta è stato progettato per un utilizzo intensivo in situazioni brutali di sopravvivenza." },
    ["healthshot"] = "Iniezione medica",
    ["tagrenade"] = "Granata di rilevamento tattica",
    ["exploding_barrel"] = "Barile esplosivo",
    ["snowball"] = "Palla di neve",
    ["stompdamagekillstring"] = "ti ha sfondato il cranio",
    ["dangerzone"] = "Zona di pericolo",
    ["autosentry"] = "Torretta automatica",
    ["fists"] = "Mani nude",
    ["tablet"] = "Tablet",
    ["breachcharge"] = "Carica esplosiva",
    ["bumpmine"] = "Mina da salto",
    ["axe"] = { name = "Ascia", desc = "Pesante e sempre disponibile, l'ascia ha una faccia affilata e una smussata. Falla roteare per sferrare un attacco primario a danno contenuto oppure lanciala per sferrare un attacco secondario a danno elevato. Quanta legna è capace di tagliare una marmotta?" },
    ["hammer"] = { name = "Martello", desc = "Il martello serve per riparare cose e per rompere cose. Fallo roteare per sferrare un attacco primario a danno contenuto oppure lancialo per sferrare un attacco secondario a danno elevato. Se tutto ciò che hai è un martello, tutto quanto ti sembrerà un chiodo." },
    ["spanner"] = { name = "Chiave inglese", desc = "Anche se viene generalmente utilizzata per stringere dadi e bulloni, con una chiave inglese puoi sferrare un attacco primario colpendo qualunque cosa e infliggendo un danno contenuto, oppure lanciarla in un attacco secondario a danno elevato. Utilizzare una chiave inglese in uno scontro a fuoco significa mettersi in guai seri." },
    ["tripwirefire"] = "Trappola di fuoco",
    ["knife_cord"] = { name = "Coltello Paracord", desc = "Questo coltello da sopravvivenza a lama fissa è progettato per essere utilizzato come arma o come utensile, ad esempio per preparare trappole, cacciare animali o tagliare rami. Il manico è rivestito da un cavo da paracadute multiuso." },
    ["knife_canis"] = { name = "Coltello da sopravvivenza", desc = "Questo coltello tattico multiuso è dotato di un bordo seghettato per tagliare materiali ruvidi come ossa o fibre, oltre a un gancio affilato per eviscerare. Il manico in materiale composito è fissato alla lama con viti esagonali." },
    ["knife_ursus"] = { name = "Coltello Ursus", desc = "Questo coltello da sopravvivenza in pieno stile tantō è dotato di una lama piatta e un codolo pieno con tanto di impugnatura da impatto. Niente fronzoli, niente parti mobili, solo una lama affidabile pronta all'uso." },
    ["knife_gypsy_jackknife"] = { name = "Coltello Navaja", desc = "Questo coltello ricurvo con manico smaltato in marmo nasconde una lama piccola ma affilata per uccidere." },
    ["knife_outdoor"] = { name = "Coltello Nomade", desc = "Questo coltello tattico da caccia a lama pieghevole include inserti in materiale composito sull'impugnatura ergonomica e una lama larga e robusta, utile per tagliare e affettare materiali." },
    ["knife_widowmaker"] = { name = "Coltello Talon", desc = "Questo karambit con il manico di avorio è caratterizzato da rivetti di ottone ed estremità dentate, in modo tale da tagliare quando entra dentro e lacerare quando esce fuori." },
    ["knife_stiletto"] = { name = "Stiletto", desc = "Da sempre al centro di dibattiti e regolamentazioni, questo coltello a serramanico dal design a stiletto in stile italiano è dotato di una lama caricata a molla che può essere rilasciata in modo quasi istantaneo rilasciando la sicura." },
    ["knife_skeleton"] = { name = "Coltello Scheletro", desc = "Su questo coltello a tema scheletrico è stato applicato del nastro per una presa più ferma. Il buco permette di inserire un dito per avere più sicurezza e stabilità." },
    ["knife_kukri"] = { name = "Coltello Kukri", desc = "Utilizzato nei rituali tradizionali, come matrimoni o accoltellamenti." },
    ["firebomb"] = { name = "Molotov", desc = "La bomba molotov è una potente arma sperimentale che sparge fiamme ad alta temperatura una volta lanciata al suolo, bruciando qualsiasi giocatore che si trovi nel suo raggio di diffusione." },
    ["diversion"] = { name = "Dispositivo di diversione", desc = "Quando viene lanciato, il dispositivo di diversione evidenzierà dei settori sui tablet, creando l'illusione che ci siano altri nemici nelle vicinanze." },
    ["frag_grenade"] = { name = "Granata a frammentazione", desc = "La granata a frammentazione sperimentale può infliggere enormi quantità di danni esplosivi in un'area molto vasta, rendendola ideale sia per strategie di attacco che di difesa." },
    ["shield"] = { name = "Scudo antisommossa", desc = "Un dispositivo protettivo progettato per deviare o assorbire danni balistici e aiutare a proteggere chi lo indossa da proiettili di vario calibro." },
    ["zone_repulsor"] = { name = "Dispositivo di repulsione", desc = "Prototipo di dispositivo protettivo a emissioni di particolato radiali" },
    ["glock_use"] = "• Letale negli scontri ravvicinati, rappresenta solo un ingombro dalla distanza.\n• Considerala nel primo round.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Precisa da lontano, valida per sparare alla rinfusa da vicino.\n• Considerala nel primo round.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Precisa, silenziosa e (abbastanza) letale.\n• Considerala nel primo round.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Due pistole dal fuoco rapido al prezzo di una!\n• Considerale nel primo round.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Un'opzione popolare, seppur modesta, per infliggere qualche danno in più.\n• Considerala nei round di economia.\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Potenza, velocità e precisione hanno un prezzo.\n• Considerala nei round di economia.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Una raffica di fuoco per poter rubare le armi degli avversari.\n• Considerala nei round di economia.\n• Difficoltà: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Mobilità elevata ed efficacia a qualunque distanza.\n• Considerala nei round di economia.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Infligge danni enormi, ma ha un breve ritardo prima di fare fuoco.\n• Consideralo nei round di economia.\n• Difficoltà: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Colpi alla testa letali da qualunque distanza.\n• Consideralo nei round di economia.\n• Difficoltà: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Un singolo colpo letale dalla distanza ravvicinata.\n• Provaci a tuo rischio e pericolo.\n• Difficoltà: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Una selva di proiettili con cui investire nemici senza giubbotto antiproiettile.\n• Consideralo nei primi tre round.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• L'arma \"corri e spara\" ideale per irrompere nei Siti della bomba.\n• Considerala nei primi tre round.\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Una scarica di danni per interrompere un'invasione nemica.\n• Consideralo nei primi tre round.\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Facile da controllare e buoni danni dalla media distanza.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Agile e discreto per danni dalla media distanza.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Buona penetrazione dei giubbotti negli scontri a media distanza.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Una scarica infinita di proiettili, superata solo dai fucili.\n• Consideralo nei round di acquisto libero.\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Economico ma efficace contro i nemici dotati di giubbotti antiproiettile.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Economico ma efficace contro i nemici dotati di giubbotti antiproiettile.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• La macchina da guerra classica: accurato e preciso.\n• Consideralo nei round di acquisto libero.\n• Difficoltà: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Una buona precisione e una buona quantità di munizioni.\n• Consideralo nei round di acquisto libero.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Preciso, silenzioso e in grado di disorientare.\n• Consideralo nei round di acquisto libero.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Una mira telescopica per una precisione eccezionale.\n• Consideralo nei round di acquisto libero.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Un'arma letale, resa ancora più pericolosa grazie al mirino.\n• Considerala nei round di acquisto libero.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Potenza devastante per il tiratore scelto che sa quello che fa.\n• Consideralo nei round di acquisto libero.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Fucile di precisione automatico dall'elevato tasso di rischio/ricompensa.\n• Consideralo solo in circostanze speciali.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Un'arma potente (seppur rischiosa) per mantenere una posizione.\n• Considerala solo in circostanze speciali.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Arma leggera e potente che infligge danni significativi da lunghe distanze.\n• Considerala nei round di acquisto obbligato.\n• Difficoltà: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Cogli di sorpresa il nemico, ricarica e ripeti!\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Un fucile a pompa versatile per gli scontri ravvicinati.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Un fucile a pompa estremamente potente per i combattimenti ravvicinati.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Un mostro totalmente automatico con cadenza di fuoco elevata.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• Almeno non avrai bisogno di ricaricare...\n• Consideralo solo in circostanze speciali.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Fuoco di soppressione preciso per guadagnare un po' di tempo.\n• Consideralo nei round di acquisto obbligato.\n• Difficoltà: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Granata che infligge danni o spazza via il fumo.\n• Usala con moderazione.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Acceca/stordisce i nemici nei paraggi.\n• Lanciala prima di un attacco.\n• Difficoltà: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Crea una grande nube di fumo.\n• Lanciala per ostruire la linea visiva del nemico.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Imita il rumore di armi che fanno fuoco.\n• Usala presto per confondere il nemico.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Libera i nascondigli grazie al fuoco.\n• Lanciala prima di attaccare un Sito della bomba.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Sopprime gli attacchi nemici con il fuoco.\n• Lanciala al primo segnale di pericolo.\n• Difficoltà: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Ti permette di sopravvivere a tutti i proiettili, tranne quelli più letali.\n• Consideralo nei round di acquisto obbligato e libero.\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Protegge tutto, tranne la tua testa.\n• Consideralo nel primo round.\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Dimezza il tempo necessario per il disinnesco della bomba.\n• Che errore gigantesco non comprare un kit di disinnesco!\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Recupera gli ostaggi in una frazione del tempo.\n• Consideralo se hai denaro da spendere.\n• Difficoltà: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "La CZ75-Auto, una variante completamente automatica della CZ75, è un'altra scelta economica contro gli avversari provvisti di giubbotto antiproiettile. Dato che ha poche munizioni, dovrai far valere al meglio ogni colpo.",
    ["m4a4"] = "Più preciso ma dotato di una potenza di fuoco inferiore rispetto al corrispettivo AK-47, l'M4A4 è il fucile d'assalto d'ordinanza completamente automatico per gli AT.",
    ["sg553"] = "L'SG553, esclusivo per i Terroristi, è una versione maggiorata dell'AK-47 dotata di un mirino di precisione, efficace negli scontri a lungo raggio.",
    ["decoy_grenade"] = "Quando viene lanciata, la granata diversiva simula il suono dell'arma più potente che hai addosso, creando così l'illusione della presenza di forze alleate aggiuntive.",
    ["incindiary_grenade"] = "Quando viene lanciata, la granata incendiaria rilascia una reazione chimica fortemente esotermica capace di ustionare chiunque si trovi nel raggio dell'esplosione.",
    ["survival_taser"] = "Un'arma a raggio estremamente ridotto in grado di uccidere con un solo colpo. Si può usare anche per aprire le casse di armi.",
    ["survival_healthshot"] = "Ripristina una parte della tua salute e fornisce un potenziamento della velocità temporaneo.",
    ["survival_vesthelm"] = "Fornisce resistenza ai danni.",
    ["survival_shield"] = "Uno scudo balistico antisommossa in grado di bloccare una grande quantità di danni prima di venire distrutto.",
    ["survival_parachute"] = "Può essere aperto quando si cade per evitare i danni da caduta.",
    ["survival_exojump"] = "Aumenta significativamente l'altezza dei salti.",
    ["survival_c4"] = "Piazzalo ovunque nella mappa per provocare una forte esplosione. Utilizzabile per aprire le casseforti.",
    ["survival_dronepilot"] = "Fornisce l'abilità di prendere il controllo dei droni. Usa il tablet per selezionare il drone di cui vuoi impossessarti.",
    ["survival_exploremoney"] = "Guadagna soldi extra per ogni esagono esplorato.",
    ["survival_wavemoney"] = "Guadagna soldi extra per ogni ondata di espansione della Zona di pericolo superata.",
}
