csstring = { -- Czech
	["cat_pistols"] = "Pistole",
	["cat_heavy"] = "Těžké",
	["cat_smg"] = "Samopaly",
	["cat_rifles"] = "Pušky",
	["cat_grenades"] = "Granáty",
	["cat_gear"] = "Vybavení",

    ["ak47"] = { name = "AK-47", desc = "Silná a spolehlivá útočná puška AK-47 je jednou z nejpopulárnějších zbraní na světě. Největší poškození uděluje v krátkých, kontrolovaných dávkách." },
    ["aug"] = { name = "AUG", desc = "AUG je silná a přesná útočná puška s možností přiblížení, která kompenzuje svoji dlouhou dobu přebíjení malým rozptylem a vysokou rychlostí střelby." },
    ["awp"] = { name = "AWP", desc = "Odstřelovací puška AWP je vysoce riskantní a vysoce účinná zbraň, která je nechvalně známá svým charakteristickým zvukem a také faktem, že jedna rána z ní znamená jednoho mrtvého v řadách nepřátel." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Ikonická pistole Desert Eagle je drahá a zpočátku těžko ovladatelná zbraň. Avšak těm, kteří si ji osvojí, nabídne překvapivě přesnou a silnou střelbu na velkou vzdálenost." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Dual Berettas", desc = "Střelba ze dvou pistolí značky Beretta s velkými zásobníky sníží tvoji přesnost a prodlouží dobu přebíjení. Na druhou stranu budeš střílet ze dvou pistolí s velkými zásobníky." },
    ["elite"] = "Dual Berettas",
    ["famas"] = { name = "FAMAS", desc = "FAMAS je zbraň vhodná pro hráče, kteří mají hlouběji do kapsy, a efektivně vyplňuje mezeru mezi dražšími puškami a horšími samopaly." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Five-Seven je dražší, avšak vysoce přesná pistole, která pomalé přebíjení kompenzuje zásobníkem s 20 průraznými střelami a shovívavým zpětným rázem." },
    ["flashbang"] = { name = "Oslepující granát", desc = "Oslepující granát, který neuděluje poškození, ale dočasně svým výbuchem oslepí ostatní hráče. To z něj činí vhodný prostředek na obsazování místností střežených protivníky. Jeho hlasitá exploze také dokáže překrýt zvuky chůze." },
    ["g3sg1"] = { name = "G3SG1", desc = "Drahá odstřelovací puška G3SG1 citelně zpomaluje pohyb, což však kompenzuje vyšší rychlosti střelby." },
    ["galilar"] = { name = "Galil AR", desc = "Galil AR, zástupce levnějších útočných pušek exkluzivních pro Teroristy, je zbraň vhodná pro boj na střední i větší vzdálenost." },
    ["glock18"] = { name = "Glock-18", desc = "Glock 18 je pistole vhodná pro první kolo. Nejúčinnější je proti neobrněným protivníkům a je schopná střílet v dávkách po třech." },
    ["he_grenade"] = { name = "Výbušný granát", desc = "Vysoce výbušný tříštivý granát oplývající vysokým poškozením uděleným na značné ploše je vhodný k vyčištění místnosti od protivníků." },
    ["he_grenade_short"] = "Granát",
    ["hegrenade"] = "Výbušný granát",
    ["knife"] = { name = "Nůž", desc = "Nůž, tichý a vždy dostupný společník, má rychlý a slabý primární útok a pomalý a silný sekundární útok. Pokud nepřítele bodneš do zad, zabiješ ho jedním zásahem." },
    ["knife_t"] = "Nůž",
    ["knife_gg"] = "Zlatý nůž",
    ["knife_ghost"] = { name = "Nůž ze záhrobí", desc = "Věděl jsi, že i duchové mají rádi hezké nože? Naštěstí pro nás živé je však mají pouze pro okrasu a ze záhrobí nás nemohou zapíchnout." },
    ["m249"] = { name = "M249", desc = "M249, lehký kulomet vhodný pro otevřené prostory, je perfektní volbou pro hráče ochotné vyměnit pomalou rychlost střelby za zvýšenou přesnost a větší počet nábojů." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Tato varianta útočné pušky M4A1 s tlumičem umožňuje tišší střelbu a díky menšímu zpětnému rázu dosahuje vyšší přesnosti než její hlasitější verze, ovšem za cenu menšího zásobníku." },
    ["mac10"] = { name = "MAC-10", desc = "Samopal MAC-10, doslova krabice, ze které lítají kulky, se může pochlubit vysokou rychlostí střelby, kterou však kazí nízká přesnost a silný zpětný ráz." },
    ["p90"] = { name = "P90", desc = "P90, zbraň s nezaměnitelným designem, je výborná pro střelbu od boku díky své vysoké kapacitě zásobníku a slabému zpětnému rázu." },
    ["smoke_grenade"] = { name = "Dýmovnice", desc = "Dýmovnice vytváří středně rozlehlou kouřovou clonu, která může účinně skrýt tvůj tým proti odstřelovačům nebo posloužit jako rozptýlení." },
    ["smokegrenade"] = "Dýmovnice",
    ["ump45"] = { name = "UMP-45", desc = "UMP45, nepochopené prostřední dítě z rodiny samopalů, je univerzální automatická zbraň, jejíž jedinou nevýhodou je malý zásobník." },
    ["xm1014"] = { name = "XM1014", desc = "XM1014 je silná, plně automatická brokovnice, která svoji vyšší cenu kompenzuje schopností rychle vymalovat pokoj horkým olovem." },
    ["c4"] = { name = "Výbušnina C4", desc = "Stabilní improvizovaná plastická trhavina odolná proti většině fyzických zásahů, která disponuje detonační rychlostí přes 8 000 metrů za sekundu." },
    ["bizon"] = { name = "PP-Bizon", desc = "Samopal Bizon je sice slabý, ale zato nabízí unikátně navržený, vysokokapacitní bubnový zásobník, který lze velmi rychle přebíjet." },
    ["mag7"] = { name = "MAG-7", desc = "Mag-7, brokovnice exkluzivní pro CT, udílí devastující poškození na krátkou vzdálenost a oplývá rychlým přebíjením, díky čemuž se jedná o vhodnou zbraň pro přestřelky v menších místnostech." },
    ["negev"] = { name = "Negev", desc = "Kulomet Negev je monstrum, pomocí jehož přesné střelby můžeš podstatně navýšit rozsah svého osobního prostoru. Tedy pokud máš dost času to monstrum zkrotit." },
    ["sawedoff"] = { name = "Upilovaná brokovnice", desc = "Klasická upilovaná brokovnice uděluje velké poškození na krátkou vzdálenost, avšak její malá přesnost, velký rozptyl a pomalá rychlost střelby z ní činí zbraň vhodnou převážně pro ty, kteří jí dokáží využít k zabití jednou ranou." },
    ["tec9"] = { name = "Tec-9", desc = "Tec-9 je ideální pistolí pro Teroristu, který neposedí. Je smrtící na blízko a má vysoký počet nábojů v zásobníku." },
    ["taser"] = { name = "Zeus x27", desc = "Zeus x27 je pouze na jedno použití, ale při překvapení nepřítele nebo při boji v uzavřených prostorech je i jedna rána z něj smrtelná." },
    ["molotov"] = { name = "Molotov", desc = "Molotov je účinná a nepředvídatelná zbraň vhodná pro odříznutí cesty. Po dopadu na zem začne okolí dopadu hořet a každý, kdo do plamenů vstoupí, utrží poškození." },
    ["incgrenade"] = "Zápalný granát",
    ["incgrenade_short"] = "Zápalný",
    ["decoy"] = "Návnada",
    ["decoy_short"] = "Návnada",
    ["hkp2000"] = { name = "P2000", desc = "Přesná a lehce ovladatelná německá pistole P2000 je vhodná pro první kolo a proti neobrněným protivníkům." },
    ["mp7"] = { name = "MP7", desc = "Samopal MP7 německé výroby je univerzální, ale drahý pomocník pro boj na kratší vzdálenost." },
    ["mp5sd"] = { name = "MP5-SD", desc = "Ačkoli se ho ostatní pokoušeli napodobit, kvalit ikonického a nesmírně populárního samopalu MP5 nikdy nedosáhli. Ve verzi SD navíc tenhle krasavec nabízí také tlumič, který z něj činí smrtící a zároveň tichou volbu." },
    ["mp9"] = { name = "MP9", desc = "Špičkový samopal MP9 švýcarské výroby je ergonomická, polymerová zbraň oblíbená zejména mezi soukromými bezpečnostními firmami." },
    ["nova"] = { name = "Nova", desc = "Brokovnice Nova je díky své velmi nízké ceně vhodnou zbraní pro chudé hráče, kteří i přes stav svého konta chtějí přepadávat nepřátele s brokovnicí v ruce." },
    ["p250"] = { name = "P250", desc = "P250 je relativně levná pistole s malým zpětným rázem a vysokou rychlostí střelby, která se hodí i proti obrněným protivníkům." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "SCAR-20 je polo-automatická odstřelovací puška, která svému majiteli za vysokou cenu a sníženou rychlost pohybu nabídne vysokou rychlost střelby a možnost udělit poškození i z velké vzdálenosti." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "SSG08 je opakovací odstřelovací puška, jejíž nízká cena odpovídá její síle, díky které je zbraň vhodná převážné pro odstřelování v prvních kolech." },
    ["heavyassaultsuit"] = "Těžká vesta",
    ["assaultsuit"] = "Kevlar a helma",
    ["assaultsuit_only_helmet"] = "Helma",
    ["kevlar"] = "Kevlarová vesta",
    ["defuser"] = "Souprava pro zneškodňování bomb",
    ["cutters"] = "Souprava pro záchranu rukojmích",
    ["revolver"] = { name = "Revolver R8", desc = "Střelba z revolveru R8 je velmi přesná a účinná, ovšem promáčknutí spouště chvíli trvá. Na krátkou vzdálenost je proto lepší použít rychlejší, ale méně přesné fofrování." },
    ["usp_silencer"] = { name = "USP-S", desc = "Pistole USP, oblíbená zbraň hráčů hry Counter-Strike: Source, disponuje odnímatelným tlumičem, který zmírňuje zpětný ráz a tlumí výstřely." },
    ["knifebayonet"] = { name = "Bajonet", desc = "Ačkoli se jeho design od dob 2. světové války nijak zásadně nezměnil, zůstává bajonet i nadále ve standardní vojenské výbavě. Jeho užitečnost se ukázala například ve druhé válce v Perském zálivu a ve válce v Afghánistánu." },
    ["knifeflip"] = { name = "Skládací nůž", desc = "Skládací nůž disponuje mírně zakroucenou čepelí v perském stylu. Ačkoli je jeho špička křehká, zbytek je překvapivě odolný." },
    ["knifegut"] = { name = "Rozparovací nůž", desc = "Nejvýraznější částí rozparovacího nože je jeho párák na páteři čepele. Ačkoli byl původně používán převážné ke stahování zvířat z kůže, lze jej využít i při přeřezávání různých vláknitých materiálů, jakými jsou například lana, popruhy a bezpečnostní pásy." },
    ["knifecss"] = { name = "Klasický nůž", desc = "Ostří tohoto klasického nože ze série her Counter-Strike tvoří lisovaný stellit upevněný v čepeli z titanu. Rukojeť byla vyrobena ze zkamenělé slonoviny mastodonta a potažena karbonovými vlákny." },
    ["knifem9"] = { name = "Bajonet M9", desc = "Toto je bajonet M-9. Původně byl určený k tomu, aby byl přimontovaný k pušce, avšak ukázal se být vhodný i jako samostatná zbraň pro kontaktní boj." },
    ["knifekaram"] = { name = "Karambit", desc = "Karambit, nůž se zahnutou čepelí připomínající tygří dráp, byl původně vyroben pro jihovýchodní asijské bojové umění silat. Tento nůž je obvykle používán s reverzní rukojetí a s prstenním kroužkem nasazeným na ukazováčku." },
    ["knifetactical"] = { name = "Lovecký nůž", desc = "Moderní nůž s čepelí vhodnou jak pro boj zblízka, tak pro všestranné využití. Díky speciální špičce „Tantó“ se nezalekne ani nejpevnějšího materiálu." },
    ["knife_butterfly"] = { name = "Motýlek", desc = "Toto je speciálně navržený skládací nůž, běžně známý jako „motýlek“. Jeho charakteristickým znakem je to, že se otevírá podobně jako vějíře, avšak na rozdíl od nich v sobě neskrývá látku, ale otočnou čepel, kterou lze díky zmíněnému otevíracímu mechanismu rychle připravit k akci nebo naopak rychle ukrýt. Důsledkem toho je zakázaný v mnoha zemích světa." },
    ["partypopper"] = "Zábavní pyrotechnika!",
    ["knife_falchion_advanced"] = { name = "Falchion", desc = "Zakřivená čepel tohoto nože dává najevo, že se jedná o moderní poctu osvědčeným šavlím." },
    ["knife_push"] = { name = "Pěstní dýky", desc = "Pěstní dýky vypadají složitě, ale ve skutečnosti je jejich použití nesmírně jednoduché. Představ si údery pěstí, ale účinnější." },
    ["knife_survival_bowie"] = { name = "Nůž Bowie", desc = "Špičkový nůž typu Bowie disponující pilovou horní čepelí, se kterým se v klidu můžeš postavit celé armádě." },
    ["healthshot"] = "Adrenalin",
    ["tagrenade"] = "Taktický granát",
    ["exploding_barrel"] = "Výbušný barel",
    ["snowball"] = "Sněhová koule",
    ["stompdamagekillstring"] = "ti rozdrtil lebku",
    ["dangerzone"] = "Zóna smrti",
    ["autosentry"] = "Automatická střílna",
    ["fists"] = "Pěsti",
    ["tablet"] = "Tablet",
    ["breachcharge"] = "Dálkově ovládaná výbušnina",
    ["bumpmine"] = "Odrážecí mina",
    ["axe"] = { name = "Sekyra", desc = "Jedna strana ostrá, druhá tupá. To není hádanka, ale rychlý popis těžké příruční sekery, kterou můžeš máchnout a provést tak slabý primární útok nebo ji vrhnout pro silný sekundární útok. Probuď svého vnitřního dřevorubce!" },
    ["hammer"] = { name = "Kladivo", desc = "Běžná kladiva zvládají věci opravovat i ničit. Tohle jenom ničí – máchnutím lze provést slabý primární útok a odhozením pak silný sekundární útok. Vítej v demoliční četě." },
    ["spanner"] = { name = "Hasák", desc = "Hasák je užitečný nástroj pro každého a hodí se jak pro slabé primární útoky, tak pro odhazování a silné sekundární útoky. Navzdory svému jménu však nic nehasí, naopak přikládá pod oheň násilí." },
    ["tripwirefire"] = "Ohnivá past",
    ["knife_cord"] = { name = "Výsadkářský nůž", desc = "Nůž s pevnou čepelí použitelný nejen jako zbraň, ale také jako nástroj při kladení pastí, lovení zvěře nebo prosekávání se porostem. Rukojeť je navíc omotána nylonovým lanem ještě navyšujícím všestrannost nože." },
    ["knife_canis"] = { name = "Záchranářský nůž", desc = "Víceúčelový vojenský nůž s vroubkovaným ostřím, které nezastaví ani kosti nebo pevná vlákna. Využití jistě najde také ostrý párák. Kompozitní rukojeť je k čepeli přišroubovaná šestihrannými maticemi." },
    ["knife_ursus"] = { name = "Nůž Ursus", desc = "Všestranný nůž se zbroušenou pevnou čepelí a nárazuvzdornou rukojetí. Žádné pohyblivé části ani jiné zbytečnosti, prostě spolehlivý nůž vždy připravený do akce." },
    ["knife_gypsy_jackknife"] = { name = "Nůž Navaja", desc = "Skládací nůž s mramorovou rukojetí a malou, nicméně velmi ostrou čepelí." },
    ["knife_outdoor"] = { name = "Outdoorový nůž", desc = "Ergonomický skládací nůž pyšnící se kompozitní rukojetí a širokou čepelí, kterou ocení každý zálesák." },
    ["knife_widowmaker"] = { name = "Talon", desc = "Karambit se slonovinovou rukojetí, mosaznými nýty a pilovým hřbetem, který pronikne dovnitř a cestu ven si rozpáře." },
    ["knife_stiletto"] = { name = "Vystřelovací nůž", desc = "Dlouhodobě velmi oblíbený vystřelovací nůž italského typu „Stiletto“, který lze díky pružinovému mechanismu vytáhnout takřka okamžitě, stačí stisknout uvolňovací západku." },
    ["knife_skeleton"] = { name = "Skeletový nůž", desc = "Vysoce stylový skeletonizovaný nůž s rukojetí omotanou lepicí páskou zajišťující lepší úchyt. Dírou v čepeli lze prostrčit prst a výrazně tak snížit riziko vyklouznutí nože z ruky." },
    ["knife_kukri"] = { name = "Nůž Kukri", desc = "Legendární zbraň používaná při tradičních rituálech jako jsou svatby nebo popravy." },
    ["firebomb"] = { name = "Ohnivý granát", desc = "Ohnivý granát je mocná experimentální zbraň, která po dopadu vyvolá chemickou reakci o vysoké teplotě a začne spalovat své okolí." },
    ["diversion"] = { name = "Matoucí granát", desc = "Matoucí granát po odhození zvýrazní daný sektor na nepřátelských tabletech, čímž vytvoří iluzi přítomnosti nepřátel." },
    ["frag_grenade"] = { name = "Tříštivý granát", desc = "Experimentální tříštivý granát schopný udělit vysoké poškození ve velké oblasti kolem místa výbuchu. Ideální pro ofenzivu i defenzivu." },
    ["shield"] = { name = "Zásahový štít", desc = "Ochranná pomůcka schopná odrazit nebo absorbovat balistické útoky a ochránit nositele před zbraněmi různých kalibrů." },
    ["zone_repulsor"] = { name = "Repulzní zařízení", desc = "Prototyp zařízení stínícího emisní částice." },
    ["glock_use"] = "• Na blízko smrtící, na dálku ne moc účinná pistole\n• Dobrá volba pro první kolo poloviny\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Na dálku přesná a na blízko dostatečně rychlá pistole\n• Dobrá volba pro první kolo poloviny\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Přesná, tichá a (relativně) smrtící pistole\n• Dobrá volba pro první kolo poloviny\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Dvě rychlopalné pistole za cenu jedné\n• Dobrá volba pro první kolo poloviny\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Populární, byť ne moc znatelné navýšení palebné síly\n• Dobrá volba pro kola s minimálním nákupem\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Silná, rychlá a přesná pistole s mírně vyšší cenovkou\n• Dobrá volba pro kola s minimálním nákupem\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Plně automatická pomoc s odzbrojením nepřátel\n• Dobrá volba pro kola s minimálním nákupem\n• Náročnost: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Vysoce mobilní pistole účinná na blízko i na dálku\n• Dobrá volba pro kola s minimálním nákupem\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Revolver s masivním poškozením, ale opožděnou střelbou\n• Dobrá volba pro kola s minimálním nákupem\n• Náročnost: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Kanón rozdávající smrtící headshoty nedbaje vzdálenosti\n• Dobrá volba pro kola s minimálním nákupem\n• Náročnost: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Jednorázový taser smrtící na blízko\n• Používání je na vlastní nebezpečí\n• Náročnost: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Vysokokapacitní samopal pro kosení neobrněných nepřátel\n• Dobrá volba pro první tři kola poloviny\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Nástroj pro neohrožené dobývání nepřátelských pozic\n• Dobrá volba pro první tři kola poloviny\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Překvapivě přesný samopal pro zastavení nepřátelského postupu\n• Dobrá volba pro první tři kola poloviny\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Spolehlivý samopal na středně velkou vzdálenost\n• Dobrá volba pro kola s vynuceným nákupem\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Hbitý a tichý samopal se středním dosahem\n• Dobrá volba pro kola s vynuceným nákupem\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Samopal na střední vzdálenosti s dobrou průrazností\n• Dobrá volba pro kola s vynuceným nákupem \n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Takřka bezedný samopal, který překonají už jen pušky\n• Dobrá volba pro kola s kompletním nákupem\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Levná puška účinná proti obrněným nepřátelům\n• Dobrá volba pro kola s vynuceným nákupem \n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Puška s nízkou cenovkou, ale slušnou průrazností\n• Dobrá volba pro kola s vynuceným nákupem \n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• Světoznámý dříč oplývající silou a přesností\n• Dobrá volba pro kola s kompletním nákupem\n• Náročnost: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Přesná puška s dostatečně velkým zásobníkem\n• Dobrá volba pro kola s kompletním nákupem \n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Precizní a tichá puška, jejíž kulky nezanechávají stopy\n• Dobrá volba pro kola s kompletním nákupem \n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Puška s možností přiblížení (pro ještě větší přesnost)\n• Dobrá volba pro kola s kompletním nákupem \n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Smrtící zbraň dále vylepšená možností přiblížení\n• Dobrá volba pro kola s kompletním nákupem \n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Devastující puška pro sebevědomého odstřelovače\n• Dobrá volba pro kola s kompletním nákupem\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Automatická odstřelovací puška s vysokým poměrem rizika/odměny\n• Zbraň vhodná pouze pro speciální příležitosti\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Silná (byť riskantní) puška pro udržení pozice\n• Zbraň vhodná pouze pro speciální příležitosti\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Lehká a účinná odstřelovací puška na velké vzdálenosti\n• Dobrá volba pro kola s vynuceným nákupem\n• Náročnost: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Brokovnice ideální pro překvapivé výpady\n• Dobrá volba pro kola s vynuceným nákupem\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Všestranná brokovnice pro boj na krátkou vzdálenost\n• Dobrá volba pro kola s vynuceným nákupem\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Vysoce účinná brokovnice pro blízká setkání s nepřáteli\n• Dobrá volba pro kola s vynuceným nákupem\n• Náročnost: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Plně automatické monstrum s brutální kadencí\n• Dobrá volba pro kola s vynuceným nákupem\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• Lehký kulomet, který se běžně přebíjí až v záhrobí\n• Zbraň vhodná pouze pro speciální příležitosti\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Maximálně přesný kulomet schopný potlačovací palby\n• Dobrá volba pro kola s vynuceným nákupem\n• Náročnost: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Granát pro udílení poškození a přesouvání oblaků dýmu\n• Používej s rozvahou\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Granát oslepující a ohlušující všechny poblíž místa výbuchu\n• Doporučujeme hodit před zahájením útoku\n• Náročnost: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Granát vytvářející na místě výbuchu velký oblak dýmu\n• Lze použít k zamezení dohledu nepřátel\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Granát napodobující zvuky střelby\n• Doporučujeme hodit na začátku kola pro zmatení nepřátel\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Prostý nástroj vyhánějící nepřátele ohněm z úkrytů\n• Doporučujeme hodit před zahájením útoku\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Granát schopný rozpoutat nekontrolovatelné inferno\n• Doporučujeme hodit při prvním náznaku problémů\n• Náročnost: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Výbava zajišťující přežití skoro v každé situaci\n• Dobrá volba pro kola s vynuceným i kompletním nákupem\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Ochrana všeho kromě tvojí hlavy\n• Dobrá volba pro první kolo poloviny\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Souprava o polovinu zkracující dobu pro zneškodnění bomby\n• Nepovinně povinná výbava pro každého CT\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Souprava výrazně urychlující zvedání rukojmích\n• Dobrá volba, když máš peníze navíc\n• Náročnost: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "Tato plně automatická varianta české pistole CZ75 je vhodná jako dočasná zbraň pro zvrácení průběhu boje a získání protivníkovy zbraně. Má však velmi malý zásobník, takže je třeba pečlivě zvážit každý výstřel.",
    ["m4a4"] = "M4A4, přesnější, avšak slabší protějšek AK-47, je plně automatická útočná puška exkluzivní pro CT.",
    ["sg553"] = "SG553 je puška s možností přiblížení exkluzivní pro Teroristy, která je vhodná pro boj na větší vzdálenost.",
    ["decoy_grenade"] = "Návnada po odhození napodobuje zvuk nejsilnější zbraně, kterou neseš, čímž vytváří iluzi blížících se nepřátel.",
    ["incindiary_grenade"] = "Po dopadu vyvolá zápalný granát chemickou reakci o vysoké teplotě, která je schopná zapálit každého hráče nacházejícího se v oblasti výbuchu granátu.",
    ["survival_taser"] = "Zbraň na extrémně krátkou vzdálenost, která je však schopná zabít na jednu ránu. Lze použít také k otevření bedny.",
    ["survival_healthshot"] = "Po použití obnoví část tvého zdraví a také dočasně navýší rychlost pohybu.",
    ["survival_vesthelm"] = "Poskytuje odolnost vůči poškození.",
    ["survival_shield"] = "Balistický zásahový štít, který je schopný zablokovat velké množství poškození.",
    ["survival_parachute"] = "Lze otevřít ve vzduchu a vyhnout se tak poškození pádem.",
    ["survival_exojump"] = "Umožňují podstatně vyšší skoky.",
    ["survival_c4"] = "Lze nechat vybuchnout kdekoli na mapě nebo použít k otevření sejfu.",
    ["survival_dronepilot"] = "Umožňuje ti převzít kontrolu nad vybranými drony.",
    ["survival_exploremoney"] = "Poskytuje bonusové peníze za prozkoumávání sektorů.",
    ["survival_wavemoney"] = "Poskytuje bonusové peníze za přežívání navzdory rozpínající se zóně smrti.",
}
