csstring = { -- French
	["cat_pistols"] = "Pistolets",
	["cat_heavy"] = "Lourdes",
	["cat_smg"] = "PMs",
	["cat_rifles"] = "Fusils",
	["cat_grenades"] = "Grenades",
	["cat_gear"] = "Packs d'équipement",

    ["ak47"] = { name = "AK-47", desc = "Puissant et fiable, l'AK-47 est l'un des fusils d'assaut les plus célèbres au monde. Cette arme est beaucoup plus meurtrière en tirant de courtes rafales contrôlées." },
    ["aug"] = { name = "AUG", desc = "Puissant et précis, le fusil d'assaut à lunette AUG compense ses longs temps de recharge par une faible dispersion et une cadence de tir élevée." },
    ["awp"] = { name = "AWP", desc = "« La fortune sourit aux audacieux », voici la devise de cette arme tristement célèbre qu'est l'AWP. Reconnaissable au son caractéristique qu'il produit, un seul tir suffit." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Aussi puissant que couteux, le Desert Eagle est un pistolet emblématique difficile à maitriser, mais étonnamment précis à longue distance." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Dual Berettas", desc = "Tirer avec deux Berettas à grand chargeur diminuera la précision et augmentera le temps de rechargement. Mais bon, vous aurez quand même la chance de tirer avec deux Berettas à grand chargeur." },
    ["elite"] = "Dual Berettas",
    ["famas"] = { name = "FAMAS", desc = "Une option bon marché pour les joueurs à court d'argent, le FAMAS remplit efficacement son rôle entre les fusils plus coûteux et le manque d'efficacité des pistolets mitrailleurs." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Très précis et perforant, le Five-Seven est un pistolet assez onéreux se rechargeant lentement, mais qui a en contrepartie un généreux chargeur de 20 cartouches et un recul correct." },
    ["flashbang"] = { name = "GSS", desc = "La GSS est une grenade incapacitante qui aveugle temporairement quiconque se trouve dans son onde de choc, la rendant idéale pour débusquer les adversaires dans les espaces clos. Son explosion bruyante masque temporairement les bruits de pas." },
    ["g3sg1"] = { name = "G3SG1", desc = "Le G3SG1 est assez onéreux et réduit considérablement la vitesse de déplacement, mais il compense ce problème par une cadence de tir bien plus élevée que les autres fusils de précision." },
    ["galilar"] = { name = "Galil AR", desc = "Une des options les moins coûteuses parmi les fusils d'assaut exclusifs aux terroristes, le Galil AR est une bonne arme en combat à moyenne et longue portée." },
    ["glock18"] = { name = "Glock-18", desc = "Le Glock 18 est un bon pistolet de première manche, très efficace contre des adversaires sans protection et qui peut tirer des rafales de trois coups." },
    ["he_grenade"] = { name = "Grenade explosive", desc = "La grenade à fragmentation hautement explosive inflige d'importants dégâts sur une vaste zone, la rendant idéale pour le nettoyage de zones hostiles." },
    ["he_grenade_short"] = "Explosive",
    ["hegrenade"] = "Grenade explosive",
    ["knife"] = { name = "Couteau", desc = "Silencieux et toujours prêt à l'emploi, le couteau permet d'infliger rapidement de faibles dégâts avec l'attaque principale ou d'infliger lentement de lourds dégâts avec l'attaque secondaire. Une attaque dans le dos provoquera une mort instantanée." },
    ["knife_t"] = "Couteau",
    ["knife_gg"] = "Couteau d'or",
    ["knife_ghost"] = { name = "Couteau spectral", desc = "Les fantômes adorent les couteaux spectraux. S'ils en ont un en main, méfiez-vous ! Ils essayeront de vous poignarder à la moindre occasion. Le plus dommage dans l'histoire, c'est que ce sont des fantômes et les fantômes, même avec des couteaux, ça ne fait de mal à personne…" },
    ["m249"] = { name = "M249", desc = "Une puissante mitrailleuse légère de zones ouvertes, la M249 est le choix parfait pour les joueurs souhaitant avoir une cadence de tir un peu plus faible au profit d'une précision accrue et d'une grande capacité de munitions." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Possédant un plus petit chargeur que son homologue assourdissant, la M4A1 possède un silencieux qui permet de diminuer le recul et d'augmenter la précision tout en réduisant le bruit des tirs." },
    ["mac10"] = { name = "MAC-10", desc = "Avec sa courte silhouette parallélépipédique, le pistolet mitrailleur MAC-10 se targue d'une cadence de tir élevée mais dispose en contrepartie d'une faible précision et d'un puissant recul." },
    ["p90"] = { name = "P90", desc = "Facilement reconnaissable par son architecture « bullpup », le P90 est une excellente arme pour tirer tout en se déplaçant grâce à son chargeur grande capacité et son faible recul." },
    ["smoke_grenade"] = { name = "Grenade fumigène", desc = "La grenade fumigène crée un écran de fumée de taille moyenne. Elle peut cacher de manière efficace votre équipe contre les snipers ou tout simplement créer diversion." },
    ["smokegrenade"] = "Grenade fumigène",
    ["ump45"] = { name = "UMP-45", desc = "L'UMP45, cadet incompris de la famille des pistolets mitrailleurs, est une arme automatique versatile en combat rapproché, malgré son petit chargeur." },
    ["xm1014"] = { name = "XM1014", desc = "Le XM1014 est un puissant fusil à pompe semi-automatique qui justifie son prix assez élevé par sa capacité à recouvrir rapidement une pièce de plombs." },
    ["c4"] = { name = "C4", desc = "Stable et résistant à la plupart des chocs physiques, cet explosif improvisé a une vitesse de détonation de plus de 8 000 mètres par seconde." },
    ["bizon"] = { name = "PP-Bizon", desc = "Le pistolet mitrailleur Bizon inflige de faible dégâts, mais offre un chargeur hélicoïdal haute capacité de conception unique qui permet de recharger rapidement." },
    ["mag7"] = { name = "MAG-7", desc = "Le Mag-7, exclusif aux antiterroristes, inflige des dégâts dévastateurs à courte portée. Ses chargeurs amovibles lui permettant de recharger rapidement en font un excellent choix tactique." },
    ["negev"] = { name = "Negev", desc = "La Negev est une arme puissante pouvant tenir les adversaires à distance grâce à son feu suppressif, pourvu que vous arriviez à la manier." },
    ["sawedoff"] = { name = "Sawed-Off", desc = "Le classique Sawed-Off inflige de très lourds dégâts à courte portée, mais en raison de son manque de précision, de sa forte dispersion et de sa faible cadence de tir, vous feriez mieux de ne pas louper vos cibles." },
    ["tec9"] = { name = "Tec-9", desc = "Un pistolet idéal pour les Terroristes sur le mouvement, le Tec-9 est mortel en combat rapproché et dispose d'un chargeur grande capacité." },
    ["taser"] = { name = "Zeus x27", desc = "Parfait pour les embuscades rapprochées ou en espace clos, le Zeus x27 est capable de neutraliser une unité ennemie en un seul tir." },
    ["molotov"] = { name = "Molotov", desc = "Le cocktail Molotov est une puissante et imprévisible arme de déni de zone qui s'enflamme lorsqu'elle se brise au sol, blessant quiconque se trouve dans son rayon." },
    ["incgrenade"] = "Grenade incendiaire",
    ["incgrenade_short"] = "Incendiaire",
    ["decoy"] = "Grenade leurre",
    ["decoy_short"] = "Leurre",
    ["hkp2000"] = { name = "P2000", desc = "Précis et facile à prendre en main, le P2000 de fabrication allemande est un bon pistolet de première manche qui est très efficace contre des adversaires sans protection." },
    ["mp7"] = { name = "MP7", desc = "Polyvalent mais coûteux, le pistolet mitrailleur MP7 de fabrication allemande est le choix parfait pour infliger d'important dégâts en combat rapproché." },
    ["mp5sd"] = { name = "MP5SD", desc = "Souvent copié, mais jamais égalé, l'emblématique MP5 est sans doute le pistolet-mitrailleur le plus polyvalent et populaire au monde. Cette variante SD est équipée d'un silencieux, ce qui rend cette arme déjà formidable extrêmement discrète." },
    ["mp9"] = { name = "MP9", desc = "Fabriqué en Suisse, le pistolet mitrailleur MP9 est une arme ergonomique en polymère appréciée des entreprises de sécurité privée." },
    ["nova"] = { name = "Nova", desc = "Le prix extrêmement bas du Nova en fait une excellente arme d'embuscade pour une équipe à court d'argent." },
    ["p250"] = { name = "P250", desc = "Une arme à faible recul et à cadence de tir élevée, le P250 est un choix relativement peu coûteux contre des adversaires portant des protections." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "Le SCAR-20 est un fusil de précision semi-automatique qui possède une cadence de tir élevée et inflige d'importants dégâts à longue distance en contrepartie d'une vitesse de déplacement plus lente et d'un prix assez élevé." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "Le SSG08 à verrou inflige de faibles dégâts, mais est un excellent fusil de précision en matière de cout-efficacité, ce qui en fait un choix judicieux en début de partie pour les spécialistes du tir embusqué." },
    ["heavyassaultsuit"] = "Armure lourde",
    ["assaultsuit"] = "Gilet de Kevlar + casque",
    ["assaultsuit_only_helmet"] = "Casque",
    ["kevlar"] = "Gilet en Kevlar",
    ["defuser"] = "Kit de désamorçage",
    ["cutters"] = "Kit de secours",
    ["revolver"] = { name = "Révolver R8", desc = "Le révolver R8 offre une précision et une puissance de tir considérables, aux dépens d'une gâchette très résistante. À bout portant, préférez marteler le chien pour bénéficier d'une vitesse de tir élevée au détriment de la précision." },
    ["usp_silencer"] = { name = "USP-S", desc = "Une des armes les plus plébiscitées dans Counter-Strike: Source, le pistolet USP possède un silencieux amovible qui diminue le recul et le bruit afin de gagner en discrétion." },
    ["knifebayonet"] = { name = "Baïonnette", desc = "Relativement inchangée dans sa conception depuis la Seconde Guerre mondiale, la baïonnette conserve toujours sa place dans la stratégie militaire moderne. Les charges à la baïonnette ont continué à être très efficaces comme lors de la guerre du Golfe et d'Afghanistan." },
    ["knifeflip"] = { name = "Couteau pliant", desc = "Les couteaux pliants ont une lame style persan avec une pointe acérée. Alors que la pointe peut être fragile, la conception globale de ce type de couteau est étonnamment très solide." },
    ["knifegut"] = { name = "Couteau à éviscérer", desc = "La principale caractéristique d'un couteau à éviscérer est le crochet placé sur le dos de la lame. Popularisé à l'origine comme une aide pour dépecer le gibier, le crochet est aussi efficace pour découper avec facilité les matériaux fibreux comme des cordes, sangles ou ceintures de sécurité." },
    ["knifecss"] = { name = "Couteau classique", desc = "Un grand classique de la série Counter-Strike. La lame en stellite de ce couteau a été fabriquée méticuleusement avec du titane. Sa poignée est faite d'ivoire de mastodonte renforcé par de la fibre de carbone." },
    ["knifem9"] = { name = "Baïonnette M9", desc = "Il s'agit de la baïonnette M-9. Initialement destinée à être montée sur un fusil, elle est aussi bien adaptée pour les combats rapprochés." },
    ["knifekaram"] = { name = "Karambit", desc = "Avec sa lame incurvée imitant une griffe de tigre, le karambit a été développé pour le Pencak silat : un art martial d'Asie du Sud. Le couteau est généralement pris en main de manière inversée, l'index dans l'anneau." },
    ["knifetactical"] = { name = "Couteau de chasse", desc = "Un couteau conçu à des fins de tactiques modernes, la lame convient tout aussi bien pour le combat que pour des besoins utilitaires. L'extrémité Tantō permet une pénétration maximale même à travers la plus dure des surfaces." },
    ["knife_butterfly"] = { name = "Couteau papillon", desc = "Il s'agit d'un couteau pliable conçu sur mesure, communément appelé couteau papillon. La principale caractéristique de cette arme est l'ouverture en éventail d'une lame à pivotement libre, permettant le déploiement ou la dissimulation rapide. C'est une des raisons principales de son interdiction dans de nombreux pays." },
    ["partypopper"] = "Lancer de confettis !",
    ["knife_falchion_advanced"] = { name = "Couteau fauchon", desc = "Un hommage moderne d'une épée fauchon, cette lame pointue dispose d'un bord incurvé." },
    ["knife_push"] = { name = "Dagues sombres", desc = "Brutalité et efficacité : utiliser une dague est aussi facile que de mettre un coup de poing." },
    ["knife_survival_bowie"] = { name = "Couteau Bowie", desc = "Ce couteau Bowie est conçu pour une utilisation intensive dans des situations brutales de survie." },
    ["healthshot"] = "Seringue médicale",
    ["tagrenade"] = "Grenade tactique de repérage",
    ["exploding_barrel"] = "Baril explosif",
    ["snowball"] = "Boule de neige",
    ["stompdamagekillstring"] = "a écrasé votre crâne",
    ["dangerzone"] = "Zone de danger",
    ["autosentry"] = "Sentinelle automatique",
    ["fists"] = "Mains nues",
    ["tablet"] = "Tablette",
    ["breachcharge"] = "Charge explosive",
    ["bumpmine"] = "Mine propulsive",
    ["axe"] = { name = "Hache", desc = "Lourde et toujours à portée, la hache a un côté tranchant et un côté émoussé. Attaque principale : infligez de faibles dégâts au corps à corps. Attaque secondaire : lancez la hache dans une direction et infligez de lourds dégâts. Qui hache un chou cache un chat." },
    ["hammer"] = { name = "Marteau", desc = "Le marteau est un outil ambivalent : il répare autant qu'il casse. Attaque principale : infligez de faibles dégâts au corps à corps. Attaque secondaire : lancez le marteau dans une direction et infligez de lourds dégâts. Pour qui dispose d'un marteau, tous les problèmes sont des clous." },
    ["spanner"] = { name = "Clé à molette", desc = "La clé à molette est généralement utilisée pour entrainer un mouvement de rotation à un objet. Attaque principale : infligez de faibles dégâts au corps à corps. Attaque secondaire : lancez la clé à molette dans une direction et infligez de lourds dégâts. Avec un tel outil, vous allez pouvoir serrer la vis à vos adversaires." },
    ["tripwirefire"] = "Nid-à-feu",
    ["knife_cord"] = { name = "Couteau en paracorde", desc = "Ce couteau de survie à lame fixe est conçu pour être utilisé à la fois comme arme et comme outil, notamment pour tendre des pièges, chasser des animaux ou débroussailler du terrain. Le manche est enveloppé dans du paracorde à usages multiples." },
    ["knife_canis"] = { name = "Couteau de survie", desc = "Ce couteau de survie multi-usage est composé d'un crochet tranchant pour le dépeçage et d'une lame crantée pour découper des matériaux denses, comme les os ou la fibre synthétique. Des vis hexagonales maintiennent la lame au manche en composite." },
    ["knife_ursus"] = { name = "Ursus", desc = "Ce couteau de survie, digne d'un tantō, possède une lame à facettes et une soie entière, complétée par un pommeau à impact. Zéro prise de tête et pas de partie mobile. Cette lame fiable est prête à être utilisée telle quelle." },
    ["knife_gypsy_jackknife"] = { name = "Navaja", desc = "Ce couteau à rabat en marbre émaillé dissimule une lame, petite mais très effilée." },
    ["knife_outdoor"] = { name = "Couteau de nomade", desc = "Ce couteau de chasse et de survie pliant est composé d'un manche ergonomique, d'inserts en composite ainsi que d'une lame large et robuste. Ce couteau permet de découper toutes sortes de matières." },
    ["knife_widowmaker"] = { name = "Canif", desc = "Ce karambit au pommeau d'ivoire dispose de rivets en laiton et de fines dents de scie. Parfait pour couper à l'aller et déchiqueter au retour." },
    ["knife_stiletto"] = { name = "Stylet", desc = "Anciennement au cœur de controverses et de divergences, ce stylet italien dispose d'une lame à ressort qui peut être déployée quasiment instantanément grâce à sa poignée." },
    ["knife_skeleton"] = { name = "Couteau squelettique", desc = "Ce couteau à l'aspect squelettique a été recouvert d'adhésif sur la poignée pour une meilleure prise en main. Le trou permet de glisser un doigt pour la stabilité et la sécurité." },
    ["knife_kukri"] = { name = "Couteau Kukri", desc = "Utilisé dans les rituels traditionnels, lors des mariages et des exécutions au couteau." },
    ["firebomb"] = { name = "Bombe incendiaire", desc = "La grenade incendiaire est une arme expérimentale puissante qui éclate en formant des flammes à haute température quand elle est lancée au sol, causant des brûlures chimiques à tous les joueurs situés dans son large rayon d'action." },
    ["diversion"] = { name = "Leurre", desc = "Lorsqu'un leurre est lancé, il ajoute des zones en surbrillance sur les tablettes pour créer l'illusion qu'il y a davantage d'unités ennemies." },
    ["frag_grenade"] = { name = "Grenade à fragmentation", desc = "La grenade à fragmentation expérimentale peut causer des dégâts extrêmes sur une zone importante ; elle est donc idéale autant dans les stratégies offensives que défensives." },
    ["shield"] = { name = "Bouclier antiémeute", desc = "Un dispositif de protection conçu pour dévier ou absorber les dommages balistiques et aider à protéger la personne qui le porte de projectiles de différents calibres." },
    ["zone_repulsor"] = { name = "Répulsif", desc = "Prototype de dispositif de protection contre les émissions de particules radiales" },
    ["glock_use"] = "• Mortel à bout portant, mais peu efficace à distance\n• À privilégier lors de la première manche de la mi-temps\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Précis à longue portée, et mortel à courte portée grâce à sa gâchette facile à actionner\n • À privilégier lors de la première manche de la mi-temps\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Précis, silencieux et (un tantinet) mortel\n• À privilégier lors de la première manche de la mi-temps\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Deux pistolets à tir rapide pour le prix d'un\n• À privilégier lors de la première manche de la mi-temps\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Un pistolet peu cher et populaire à la puissance de feu redoutable\n• À privilégier lors des manches éco\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Puissance, vitesse et précision pour un prix unique\n• À privilégier lors des manches éco\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Une puissance de feu vous permettant de dérober les armes ennemies\n• À privilégier lors des manches éco\n• Difficulté : <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Offre une haute précision en mouvement et une efficacité redoutable de loin comme de près\n• À privilégier lors des manches éco\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Inflige d'importants dégâts après un court délai\n• À privilégier lors de manches éco\n• Difficulté : <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Un tir en pleine tête mortel à n'importe quelle distance\n• À privilégier lors des manches éco\n• Difficulté : <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Arme à utilisation unique qui tue sur le coup à courte distance\n• À vos risques et périls\n• Difficulté : <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Lance des rafales de balles qui pulvérisent toute unité ennemie dépourvue d'armure\n• À privilégier lors des trois premières manches de la mi-temps\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Conçue pour tirer et courir en même temps, cette arme permet de se frayer un chemin sur les sites de bombe\n• À privilégier lors des trois premières manches de la mi-temps\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Une explosion de dégâts pour prévenir toute avancée ennemie\n• À privilégier lors des trois premières manches de la mi-temps\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Arme facile à contrôler et qui inflige de bons dégâts à portée intermédiaire\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Arme maniable et discrète qui inflige des dégâts à portée intermédiaire\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Forte puissance de pénétration, efficace à moyenne distance\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Un jet de balles permanent surpassé uniquement par les fusils\n• À privilégier pour les manches en achat complet (« full buy » en anglais)\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Peu cher et efficace contre les unités ennemies équipées d'une protection\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Peu cher et efficace contre les unités ennemies équipées d'une protection\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• Classique, précis et mortel, une bête de somme martiale\n• À privilégier pour les manches en achat complet (« full buy » en anglais)\n• Difficulté : <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Bonne précision, et pas mal de munitions\n• À privilégier pour les manches en achat complet (« full buy » en anglais)\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Précis, silencieux, sans balles traçantes\n• À privilégier pour les manches en achat complet (« full buy » en anglais)\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Sa lunette en option lui offre une précision exceptionnelle\n• À privilégier pour les manches en achat complet (« full buy » en anglais)\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Arme meurtrière équipée d'une lunette\n• À privilégier pour les manches en achat complet (« full buy » en anglais)\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Offre une puissance dévastatrice à qui sait bien viser\n• À privilégier pour les manches en achat complet (« full buy » en anglais)\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Fusil de précision semi-automatique pour les adeptes du quitte ou double\n• À considérer uniquement pour les occasions spéciales\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Arme puissante (mais pas sans risques) utilisée pour tenir une position \n• À privilégier uniquement pour les occasions spéciales\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Arme légère et puissante à longue portée\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Surprenez votre adversaire, rechargez et recommencez !\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Fusil à pompe versatile pour les combats rapprochés\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Fusil à pompe très puissant pour les combats au corps-à-corps\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Monstre semi-automatique à tir rapide\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• Au moins, vous n'aurez pas besoin de recharger…\n• À privilégier uniquement pour les occasions spéciales\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Cette arme aux tirs précis tient les unités ennemies à distance et peut vous faire gagner un peu de temps\n• À privilégier pour les manches en achat forcé (« force buy » en anglais)\n• Difficulté : <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Inflige des dégâts et dissipe les fumigènes\n• À utiliser avec discernement\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Aveugle et assourdit les personnes alentours\n• À jeter avant de lancer une attaque\n• Difficulté : <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Crée un épais nuage de fumée\n• À jeter afin de bloquer la ligne de mire ennemie\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Imite le son de tirs\n• À jeter tôt dans la bataille pour déconcerter les forces ennemies\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Débusque par le feu toute personne cachée\n• À jeter avant d'attaquer un site de bombe\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Met un terme aux attaques ennemies par le feu\n• À jeter dès que ça sent le roussi\n• Difficulté : <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Protège contre tout, sauf les balles les plus meurtrières\n• À privilégier pour les manches en achat forcé ou complet (« force/full buy » en anglais)\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Protège tout le corps, sauf la tête\n• À privilégier dès la première manche\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Réduit de moitié le temps de désamorçage\n• Vous connaissez l'adage, malheur à qui n'achète pas un kit de désamorçage !\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Secourez les otages en un rien de temps\n• À considérer quand vous avez de l'argent en trop\n• Difficulté : <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "Une variante automatique du CZ75, le CZ75-Auto est le choix idéal de courte durée pour récupérer l'arme de vos adversaires. Cependant à cause du peu de munitions fournies par le chargeur, une discipline stricte sur la gâchette est recommandée.",
    ["m4a4"] = "Plus précise mais moins puissante que l'AK-47, la M4A4 est le fusil d'assaut automatique de prédilection des antiterroristes.",
    ["sg553"] = "Le fusil d'assaut à lunette SG553, exclusif aux terroristes, est une bonne alternative à l'AK-47 pour les combats à longue distance.",
    ["decoy_grenade"] = "Lorsque lancée, la grenade leurre imite le son de la plus puissante des armes que vous portez, créant l'illusion de forces d'appui supplémentaires.",
    ["incindiary_grenade"] = "Lorsque lancée, la grenade incendiaire produit une réaction chimique haute température capable de brûler quiconque se trouvant dans son rayon d'action.",
    ["survival_taser"] = "Une arme d'une portée extrêmement faible capable de tuer en un coup. Peut également être utilisée pour ouvrir les caisses d'armes.",
    ["survival_healthshot"] = "Restaure une partie de votre santé et augmente brièvement votre vitesse de déplacement.",
    ["survival_vesthelm"] = "Augmente votre résistance aux dégâts.",
    ["survival_shield"] = "Un bouclier antiémeute pouvant bloquer une grande quantité de dégâts avant d’être détruit.",
    ["survival_parachute"] = "Peut être déployé lorsque vous tombez pour éviter les dégâts de chute.",
    ["survival_exojump"] = "Augmente considérablement la hauteur de saut.",
    ["survival_c4"] = "Posez cette bombe n'importe où sur la carte pour provoquer une violente explosion. Peut être utilisée pour ouvrir les coffres-forts.",
    ["survival_dronepilot"] = "Vous permet de contrôler les drones. Utilisez la tablette pour sélectionner un drone à contrôler.",
    ["survival_exploremoney"] = "Vous donne de l'argent supplémentaire pour chaque espace exploré.",
    ["survival_wavemoney"] = "Vous rapporte de l'argent supplémentaire à chaque fois que vous survivez à une vague d'extension de la zone de danger.",
}
