csstring = { -- Vietnamese
	["cat_pistols"] = "Súng ngắn",
	["cat_heavy"] = "Hạng nặng",
	["cat_smg"] = "Súng tiểu liên",
	["cat_rifles"] = "Súng trường",
	["cat_grenades"] = "Lựu đạn",
	["cat_gear"] = "Dụng cụ",

    ["ak47"] = { name = "AK-47", desc = "Mạnh mẽ và đáng tin cậy, AK-47 là một trong những khẩu súng trường tấn công nổi tiếng nhất thế giới. Cực kì nguy hiểm nhất là khi được bắn thành những loạt đạn ngắn, có kiểm soát." },
    ["aug"] = { name = "AUG", desc = "Mạnh mẽ và chính xác, súng trường tấn công có lắp ống ngắm AUG bù cho thời gian nạp đạn lâu bằng độ tỏa thấp và tốc độ bắn cao." },
    ["awp"] = { name = "AWP", desc = "Được ăn cả ngã về không, AWP khét tiếng được nhận dạng bởi âm thanh dễ nhận biết và quy tắc một phát, một mạng của nó." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Tiền nào của ấy, Desert Eagle là khẩu súng ngắn độc đáo khó thuần thục nhưng chuẩn xác không ngờ ở tầm xa." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Dual Berettas", desc = "Dùng hai khẩu Beretta ổ đạn lớn một lúc làm giảm độ chính xác và tăng thời gian nạp đạn. Nhưng tin vui là, bạn được cầm những hai khẩu Beretta ổ đạn lớn một lúc." },
    ["elite"] = "Dual Berettas",
    ["famas"] = { name = "FAMAS", desc = "Lựa chọn rẻ cho người chơi bị kẹt tiền, FAMAS bù vào chỗ trống giữa súng trường đắt hơn và tiểu liên không hiệu quả bằng." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Độ chính xác cao và xuyên giáp tốt, khẩu Five-Seven đắt tiền tuy nạp đạn chậm nhưng bù lại có ổ đạn 20 viên dồi dào và độ giật dễ kiểm soát." },
    ["flashbang"] = { name = "Lựu đạn choáng", desc = "Lựu đạn choáng không gây sát thương nhưng làm mù tạm thời bất cứ ai ở trong tầm chấn động của nó, khiến nó rất lý tưởng cho việc gây hỗn loạn các khu vực kín. Tiếng nổ lớn cũng tạm thời giúp ngụy trang tiếng bước chân." },
    ["g3sg1"] = { name = "G3SG1", desc = "Khẩu G3SG1 đắt tiền làm giảm đáng kể vận tốc nhưng bù lại là tốc độ bắn nhanh hơn các khẩu súng bắn tỉa khác." },
    ["galilar"] = { name = "Galil AR", desc = "Lựa chọn rẻ hơn trong chỗ súng trường tấn công dành riêng của khủng bố, Galil AR là vũ khí hữu dụng ở tầm giao chiến từ trung tới xa." },
    ["glock18"] = { name = "Glock-18", desc = "Glock 18 là khẩu súng ngắn ván đầu tiên hoạt động tốt nhất khi dùng lên kẻ địch không có giáp, và sở hữu chế độ bắn chùm ba viên." },
    ["he_grenade"] = { name = "Lựu đạn nổ", desc = "Lựu đạn văng mảnh nổ mạnh tung ra sát thương lớn trên diện tích rộng, khiến nó lý tưởng cho việc làm dọn căn phòng chứa địch." },
    ["he_grenade_short"] = "Lựu đạn nổ",
    ["hegrenade"] = "Lựu đạn nổ",
    ["knife"] = { name = "Dao", desc = "Âm thầm và luôn ngay cạnh, dao có đòn tấn công chính nhanh, ít sát thương và đòn phụ chậm, sát thương cao. Một phát vào lưng thưởng cho người chơi kín đáo một mạng giết ngay lập tức." },
    ["knife_t"] = "Dao",
    ["knife_gg"] = "Dao mạ vàng",
    ["knife_ghost"] = { name = "Spectral Shiv", desc = "Ma nào thì dao nấy. Khi chúng trang bị vũ khí này, cẩn thận nhé! Chúng sẽ đâm bạn bất cứ lúc nào có thể. Đáng tiếc rằng chúng chỉ là ma, và dao ma thì không thể làm đau người thường..." },
    ["m249"] = { name = "M249", desc = "Một khẩu súng máy hạng nhẹ mạnh mẽ dùng ở không gian trống, M249 là lựa chọn thích hợp cho người chơi sẵn sàng nhận tốc độ bắn chậm đổi lấy độ chính xác và dung lượng đạn." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Dù có băng đạn nhỏ hơn người song sinh, khẩu M4A1-S bù lại điểm yếu bằng việc làm giảm tiếng ồn và độ giật, cũng như tăng độ chính xác." },
    ["mac10"] = { name = "MAC-10", desc = "Nói cho gọn là một cái hộp phun ra đạn, khẩu tiểu liên MAC-10 phô diễn tốc độ bắn cao, với độ chính xác tỏa ra kém và giật cao để bù lại." },
    ["p90"] = { name = "P90", desc = "Dễ dàng nhận ra nhờ thiết kế bullpup độc đáo, khẩu P90 là sự lựa chọn rất tốt nếu muốn khai hỏa trong khi di chuyển, nhờ ổ đạn sức chứa lớn cùng độ giật thấp." },
    ["smoke_grenade"] = { name = "Lựu đạn khói", desc = "Lựu đạn khói tạo một làn khói diện vừa. Làm ẩn đi hiệu quả đội bạn khỏi kẻ bắn tỉa, hoặc đơn giản là gây đánh lạc hướng." },
    ["smokegrenade"] = "Lựu đạn khói",
    ["ump45"] = { name = "UMP-45", desc = "Đứa con giữa bị hiểu lầm của nhà tiểu liên, ổ đạn nhỏ của UMP45 là bất lợi duy nhất trên khẩu súng thuộc dòng tự động tầm gần đa năng." },
    ["xm1014"] = { name = "XM1014", desc = "XM1014 là khẩu súng săn hoàn toàn tự động đầy uy lực, biện luận cho cái bảng giá của mình với khả năng phun kín chì khắp một căn phòng nhanh chóng." },
    ["c4"] = { name = "Bom C4", desc = "Ổn định và chống được hầu hết các kích thích vật lý, chất nổ dẻo này có vận tốc phát nổ lên tới hơn 8000 mét một giây khi kích hoạt." },
    ["bizon"] = { name = "PP-Bizon", desc = "Khẩu tiểu liên Bizon sát thương thấp, nhưng đem đến ổ đạn hình trống sức chứa lớn với thiết kế độc đáo cho phép nạp đạn nhanh." },
    ["mag7"] = { name = "MAG-7", desc = "Khẩu Mag-7 dành riêng cho CT tung ra sát thương tàn phá ở tầm gần. Kiểu nạp đạn bằng ổ nhanh khiến nó thành lựa chọn chiến thuật tốt." },
    ["negev"] = { name = "Negev", desc = "Negev là một con thú vật có thể giữ chân kẻ địch làn đạn đàn áp tuyệt đối, ấy là nếu bạn có đủ thời gian để cố kiểm soát nó." },
    ["sawedoff"] = { name = "Súng nòng ngắn", desc = "Khẩu Sawed-Off kinh điển gây sát thương nặng ở tầm gần, nhưng vì độ chính xác kém, tỏa nhiều và bắn chậm, tốt hơn là bạn nên bắn chết với phát đầu tiên." },
    ["tec9"] = { name = "Tec-9", desc = "Một khẩu súng ngắn lý tưởng dành cho những tên khủng bố hay di chuyển, Tec-9 là một vũ khí chết người ở cự ly gần, sở hữu ổ đạn có sức chứa lớn." },
    ["taser"] = { name = "Zeus x27", desc = "Dùng để mai phục tầm gần và đối mặt không gian hẹp thì tuyệt hảo, khẩu Zeus x27 một lần bắn nhưng đủ làm tê liệt đối phương ngay lập tức." },
    ["molotov"] = { name = "Bom xăng", desc = "Bom xăng là vũ khí cản đường uy lực và khó lường, tóe ra lửa khi ném xuống đất, làm bị thương bất cứ người chơi nào trong phạm vi của nó." },
    ["incgrenade"] = "Bom cháy",
    ["incgrenade_short"] = "Lựu đạn cháy",
    ["decoy"] = "Lựu đạn mồi",
    ["decoy_short"] = "Lựu đạn mồi",
    ["hkp2000"] = { name = "P2000", desc = "Chính xác và dễ kiểm soát, P2000 đến từ Đức là khẩu súng ngắn ván đầu tiên hữu dụng, hiệu suất tốt nhất khi dùng lên kẻ địch không có giáp." },
    ["mp7"] = { name = "MP7", desc = "Đa năng nhưng đắt tiền, khẩu tiểu liên MP7 đến từ Đức là lựa chọn tuyệt vời để giao chiến khoảng gần tác động mạnh." },
    ["mp5sd"] = { name = "MP5-SD", desc = "Thường bị nhái nhưng không bao giờ có kẻ ngang tầm, MP5 lẫy lừng có lẽ là khẩu súng tiểu liên nổi tiếng và linh hoạt nhất thế giới. Phiên bản SD bao gồm một ống giảm thanh gắn cố định hoàn toàn, giúp hệ thống vũ khí vốn đã ghê gớm giờ lại tĩnh lặng đến chết người." },
    ["mp9"] = { name = "MP9", desc = "Được sản xuất tại Thụy Sĩ, khẩu tiểu liên hiện đại MP9 là vũ khí polime vừa tay được các công ty an ninh tư nhân ưa dùng." },
    ["nova"] = { name = "Nova", desc = "Mức giá kịch sàn của Nova khiến nó thành vũ khí mai phục tốt cho một đội đang kẹt tiền." },
    ["p250"] = { name = "P250", desc = "Một khẩu súng với tốc độ bắn cao và độ giật thấp, P250 là lựa chọn tương đối rẻ để đánh lại kẻ địch mang giáp." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "Khẩu SCAR-20 súng bắn tỉa bán tự động đổi tốc độ bắn cao và sát thương tầm xa mạnh với di chuyển chậm chạp và bảng giá cao." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "Khẩu kéo thoi SSG08 là súng bắn tỉa sát thương ít nhưng giá hợp lý, khiến nó trở thành lựa chọn thông minh cho việc ngắm bắn tầm xa những ván đầu." },
    ["heavyassaultsuit"] = "Giáp hạng nặng",
    ["assaultsuit"] = "Giáp & Mũ",
    ["assaultsuit_only_helmet"] = "Mũ bảo hiểm",
    ["kevlar"] = "Giáp Kevlar",
    ["defuser"] = "Bộ gỡ bom",
    ["cutters"] = "Bộ dụng cụ",
    ["revolver"] = { name = "Súng lục R8", desc = "Khẩu súng lục R8 tung ra phát bắn cực kì chính xác và mạnh đổi lại là thời gian bóp cò lâu. Xả đạn liên tục bằng cách giữ cho tay ở búa cò súng là phương án tốt nhất khi cần hạ gục ngay lập tức mục tiêu ở thẳng mặt." },
    ["usp_silencer"] = { name = "USP-S", desc = "Là món vũ khí được fan yêu thích từ thời Counter-Strike Source, khẩu súng ngắn USP giảm thanh có bộ giảm thanh có thể tháo rời, khiến phát bắn giật ít hơn và triệt tiêu tiếng ồn gây chú ý." },
    ["knifebayonet"] = { name = "Bayonet", desc = "Tương đối nguyên vẹn về thiết kế kể từ Thế Chiến II, bayonet vẫn giữ cho mình vị trí trong chiến thuật quân đội hiện đại. Những phát đâm của Bayonet vẫn mang lại hiệu quả, gần đây nhất là ở chiến tranh vùng Vịnh lần hai và ở Afghanistan." },
    ["knifeflip"] = { name = "Dao bấm", desc = "Dòng dao bấm diện lưỡi dao nghiêng ra sau kiểu Ba Tư với mũi dao sắc bén. Dù bản thân phần mũi đó khá mỏng mảnh, toàn thể thiết kế của dao bấm lại bền đến đáng ngạc nhiên." },
    ["knifegut"] = { name = "Dao móc", desc = "Đặc tính nổi trội nhất của dao móc là phần móc ở sống dao. Vốn được phổ biến để hỗ trợ cho việc lột da thú săn được, móc cũng cắt qua những vật liệu vải sợi như dây thừng, vải nỉ, hoặc dây an toàn một cách dễ dàng." },
    ["knifecss"] = { name = "Classic Knife", desc = "Vũ khí cổ điển của loạt sê-ri Counter-Strike, lưỡi dao đã được ép phẳng với vật liệu Stellite, được giữ hoàn hảo tại chỗ thông qua khớp nhấn làm bằng Titan ở mặt lưỡi và mặt sau. Tay cầm làm bằng hóa thạch ngà voi răng mấu, và được phủ bao quanh bởi sợi carbon." },
    ["knifem9"] = { name = "M9 Bayonet", desc = "Đây là M-9 bayonet. Vốn được dùng để gắn lên súng trường, nhưng cũng thích hợp cho giao chiến phạm vi gần." },
    ["knifekaram"] = { name = "Karambit", desc = "Với lưỡi dao cong bắt chước vuốt hổ, karambit được tạo ra là một phần của môn võ thuật đông nam Á Silat. Con dao thường được cầm ngược lại, luồn ngón trỏ vào vòng ngón." },
    ["knifetactical"] = { name = "Dao Huntsman", desc = "Một con dao được thiết kế với mục đích chiến thuật hiện đại, lưỡi dao thích hợp kể từ việc giao chiến cho tới nhu cần thực dụng. Mũi dao kiểu Tanto cho phép sức xuyên thủng tối đa qua cả những bề mặt chắc nhất." },
    ["knife_butterfly"] = { name = "Dao bướm", desc = "Đây là một cây balisong thiết kế tùy chỉnh, thường được biết với cái tên dao bướm. Tính chất đặc trưng của vũ khí này là cách mở giống chiếc quạt với lưỡi dao xoay tự do, cho phép lấy ra và giấu đi nhanh chóng. Và vì thế, dao bướm bị cấm tại nhiều nước." },
    ["partypopper"] = "Chúc mừng sinh nhật!",
    ["knife_falchion_advanced"] = { name = "Dao Falchion", desc = "Là lời tỏ lòng kính trọng thời hiện đại cho dòng kiếm falchion, chiếc dao \"đầu cụt\" này có lưỡi cong." },
    ["knife_push"] = { name = "Dao găm chữ T", desc = "Được thiết kế để sát hại nhanh gọn, sử dụng dao găm đẩy đơn giản như việc tung một hai cú đấm." },
    ["knife_survival_bowie"] = { name = "Dao Bowie", desc = "Con dao Bowie cán liền thân, lưỡi răng cưa này được thiết kế để chịu công việc nặng trong hoàn cảnh sinh tồn khắc nghiệt." },
    ["healthshot"] = "Medi-Shot",
    ["tagrenade"] = "Lựu đạn do thám",
    ["exploding_barrel"] = "Thùng dễ nổ",
    ["snowball"] = "Bóng tuyết",
    ["stompdamagekillstring"] = "đè đầu của bạn",
    ["dangerzone"] = "Vùng nguy hiểm",
    ["autosentry"] = "Ụ súng tự động",
    ["fists"] = "Tay không",
    ["tablet"] = "Máy tính bảng",
    ["breachcharge"] = "Khối thuốc phá",
    ["bumpmine"] = "Mìn nhảy",
    ["axe"] = { name = "Rìu", desc = "Tuy nặng nề nhưng luôn kề bên, rìu có một mặt sắc và một mặt cùn. Vung rìu để gây đòn tấn công chính gây sát thương thấp, hoặc ném đi để gây đòn phụ sát thương cao. Xin hỏi tiều phu đây cây rìu vàng này có phải của con?" },
    ["hammer"] = { name = "Búa", desc = "Cây búa là công cụ đắc lực để sửa chữa và phá tan vạn vật. Vung búa để gây đòn tấn công chính sát thương thấp, hoặc ném đi để gây đòn tấn công sát thương cao. Phe địch có đao to? Ta đây có búa lớn." },
    ["spanner"] = { name = "Mỏ lết", desc = "Cờ lê giúp ta nhớ lại môn vật lý ở trường về ứng dụng mô-men để xoay vật thể, nhưng vật lý chợ đời dạy ta cách vung lên làm cách tấn công chính với sát thương thấp, hoặc ném để gây sát thương cao. Với cờ lê trong tay, đừng có mà xoắn với anh đây." },
    ["tripwirefire"] = "Bẫy lửa",
    ["knife_cord"] = { name = "Dao Paracord", desc = "Với thiết kế lưỡi cố định, dao sinh tồn được tạo nên để có thể chịu được tốt khi sử dụng làm vũ khí hay công cụ, như là đặt bẫy, săn thú hay cắt lá. Tay cầm của dao được bọc bằng một đoạn dây dù đa năng." },
    ["knife_canis"] = { name = "Dao sinh tồn", desc = "Con dao chiến thuật đa năng này có cạnh răng cưa để cắt xuyên qua vật liệu thô như xương hay thớ gỗ, cùng với đó là một lưỡi móc sắc cạnh. Tay cầm bằng vật liệu tổng hợp được bắt vào lưỡi dao với ốc hình lục giác." },
    ["knife_ursus"] = { name = "Dao Ursus", desc = "Con dao dã chiến phong cách tanto này có lưỡi được mài với cán liền một khối với dao, kèm theo chuôi nhọn. Không ồn ào, không bộ phận rời - chỉ đơn giản là một lưỡi dao đáng tin cậy để hành sự." },
    ["knife_gypsy_jackknife"] = { name = "Dao Navaja", desc = "Con dao cán đá cẩm thạch tráng men này giấu một lưỡi dao hình nón nhỏ, nhưng hiểm." },
    ["knife_outdoor"] = { name = "Dao Nomad", desc = "Con dao gập chiến thuật này có khóa lưỡi được thiết kế công thái học, với tay cầm bằng vật liệu tổng hợp cùng lưỡi dao to bản và chắc chắn. Cực kì hữu dụng khi cắt xẻ vật liệu." },
    ["knife_widowmaker"] = { name = "Dao Talon", desc = "Dao karambit này có cán ngà, đinh tán đồng thau và lằn răng lưỡi cưa, để khi chém thì đâm ngập cả lưỡi, khi rút thì xé toạc thịt da." },
    ["knife_stiletto"] = { name = "Dao Stiletto", desc = "Về mặt lịch sử, đây là thứ vũ khí nằm trên làn ranh của quy định và hạn chế, con dao bấm stiletto kiểu ý này có một lưỡi dao lò xo xuất kích tức thì ngay khi tháo chốt." },
    ["knife_skeleton"] = { name = "Dao Skeleton", desc = "Chiếc dao được lột vỏ và bọc lại phần tay cầm để cải thiện độ bám. Lỗ trên dao cho phép ngón tay có thể xuyên qua để nâng cao khả năng an toàn và ổn định của dao." },
    ["knife_kukri"] = { name = "Dao Kukri", desc = "Sử dụng trong các nghi lễ truyền thống, như đám cưới hay đâm chém." },
    ["firebomb"] = { name = "Bom lửa", desc = "Khi ném, bom lửa (mặc dù còn trong giải đoạn thử nghiệm) tạo ra lửa nhiệt độ cao trên mặt đất, gây phỏng hóa học lên bất cứ người chơi nào ở trong tầm tỏa rộng của nó." },
    ["diversion"] = { name = "Thiết bị đánh lạc hướng", desc = "Khi ném, thiết bị đánh lạc hướng sẽ làm khu vực trên máy tính bảng phát sáng, gây lầm tưởng rằng ở đó có kẻ địch." },
    ["frag_grenade"] = { name = "Lựu đạn nổ", desc = "Lựu đạn nổ (tuy còn trong giai đoạn thí nghiệm) này có thể bung một lượng sát thương nổ cực cao lên khu vực rộng, khiến nó lý tưởng trong chiến lược tấn công lẫn phòng thủ." },
    ["shield"] = { name = "Khiên chống bạo động", desc = "Thiết bị bảo vệ được thiết kế để dội hoặc hấp thu sát thương đạn đạo và bảo vệ người cầm khỏi nhiều cỡ đạn khác nhau." },
    ["zone_repulsor"] = { name = "Thiết bị lá chắn", desc = "Nguyên mẫu lá chắn chống hạt phát xạ" },
    ["glock_use"] = "• Chết chóc ở tầm gần, muỗi cắn ở tầm xa\n• Cân nhắc dùng ở ván đầu mỗi hiệp\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Chuẩn xác ở nhiều cự ly, xả được đạn tầm gần\n• Cân nhắc dùng ở ván đầu mỗi hiệp\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Chính xác, thầm lặng và (tương đối) nguy hiểm\n• Cân nhắc dùng ở ván đầu mỗi hiệp\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Mua một tặng hai, cặp súng lục xả nhanh loạt đạn\n• Cân nhắc dùng ở ván đầu mỗi hiệp\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Đình đám nhưng nâng cấp sát thương chỉ kha khá\n• Cân nhắc dùng trong các ván tiết kiệm (eco)\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Mạnh mẽ, nhanh nhẹn, và chuẩn xác chỉ trong một giá\n• Cân nhắc dùng trong các ván tiết kiệm (eco)\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Dồn hỏa lực, diệt kẻ địch, để lấy vũ khí của chúng\n• Cân nhắc dùng trong các ván tiết kiệm (eco)\n• Độ khó: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Cực kỳ cơ động, hiệu quả từ xa đến gần\n• Cân nhắc dùng trong các ván tiết kiệm (eco)\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Lên đạn chậm, nhưng gây sát thương khủng\n• Cân nhắc dùng trong các ván tiết kiệm (eco)\n• Độ khó: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Xuyên táo chết người ở bất kỳ cự ly nào\n• Cân nhắc dùng trong các ván tiết kiệm (eco)\n• Độ khó: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Chỉ một phát, hạ một kẻ địch, nhưng tầm cực ngắn\n• Thử chết ráng chịu\n• Độ khó: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Rải mưa đạn để triệt hạ kẻ địch không mặc giáp\n• Cân nhắc dùng trong ba ván đầu mỗi hiệp\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Công cụ vừa chạy vừa bắn để tấn công khu đặt bom\n• Cân nhắc dùng trong ba ván đầu mỗi hiệp\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Bung sát thương để ngăn kẻ địch đẩy vào\n• Cân nhắc dùng trong ba ván đầu mỗi hiệp\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Dễ bắn, sát thương đáng tin cậy ở cự ly tầm trung\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Nhanh nhẹn và lén lút, tương đối hiệu quả ở tầm trung\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Xuyên giáp tốt cho giao tranh cự ly tầm trung\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Vòi phun đạn chỉ bị khuất phục bởi súng trường \n• Cân nhắc ở những ván mua đủ (full buy)\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Rẻ nhưng hiệu quả với kẻ địch mặc giáp\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Rẻ nhưng hiệu quả với kẻ địch mặc giáp\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• Kinh điển, chính xác, một mãnh thú chết người\n• Cân nhắc ở những ván mua đủ (full buy)\n• Độ khó: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• Độ chính xác tốt, đạn dược đầy đủ\n• Cân nhắc ở những ván mua đủ (full buy)\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Chính xác, tĩnh lặng, khỏi dò đường đạn\n• Cân nhắc ở những ván mua đủ (full buy)\n• Độ khó:★★★</font>",
    ["aug_use"] = "• Thêm một ống ngắm để chính xác ngoại hạng\n• Cân nhắc ở những ván mua đủ (full buy)\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Một vũ khí nguy hiểm nay lại nguy hiểm hơn với ống ngắm\n• Cân nhắc ở những ván mua đủ (full buy)\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Sức tàn phá kinh hoàng cho xạ thủ tự tin\n• Cân nhắc ở những ván mua đủ (full buy)\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Súng bắn tỉa tự động, liều lĩnh có thưởng\n• Cân nhắc chỉ dùng trong trường hợp đặc biệt\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Công cụ mạnh mẽ (và rủi ro) để giữ vị trí\n• Cân nhắc chỉ dùng trong trường hợp đặc biệt\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Nhẹ và gây sát thương cao với cự ly dài\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Bắt bài kẻ địch, nạp đạn, lặp lại!\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Shotgun đa dụng cho giao tranh cận chiến\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Shotgun sát thương cao cho giao tranh gần\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Một con quái vật bắn nhanh hoàn toàn tự động\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• Ít ra bạn chả cần phải nạp đạn...\n• Cân nhắc chỉ dùng trong trường hợp đặc biệt\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Hỏa lực áp chế để câu giờ\n• Cân nhắc ở những ván mua cố (force buy)\n• Độ khó: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Gây sát thương hoặc đẩy mờ lựu đạn khói\n• Cân nhắc trước khi dùng\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Làm mù và điếc người chơi lân cận\n• Ném trước khi tấn công\n• Độ khó: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Tạo một đám khói lớn\n• Ném để cắt tầm nhìn kẻ địch\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Bắt chước tiếng súng khai hỏa\n• Ném sớm để đánh lạc hướng kẻ địch\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Dọn dẹp chỗ nấp bằng lửa\n• Ném trước khi tấn công khu đặt bom\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Chặn đứng đợt công kích của đối phương bằng lửa\n• Ném ngay khi thấy dấu hiệu nguy hiểm\n• Độ khó: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Chỉ chịu thua trước những phát đạn hiểm hóc nhất\n• Cân nhắc trong ván mua đủ (full buy) và mua cố (force buy)\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Bảo vệ gần như mọi nơi trừ đầu\n• Cân nhắc dùng ở ván đầu mỗi hiệp\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Giảm một nửa thời gian gỡ bom\n• Đừng ki bo quá, mua gỡ bom đi!\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Đặt con tin lên trong tíc tắc\n• Cân nhắc khi bạn có dư tiền\n• Độ khó: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "Là dòng biến thể hoàn toàn tự động của khẩu CZ75, CZ75-Auto là lựa chọn tạm thời lý tưởng để lật ngược tình thế và giật lấy súng của kẻ địch. Nhưng với ổ đạn chẳng mấy viên, cần có rèn luyện kỷ luật cò súng.",
    ["m4a4"] = "Chính xác nhưng sát thương ít hơn tương đương của nó là AK-47, M4A4 là khẩu súng trường tấn công hoàn toàn tự động được CT sử dụng.",
    ["sg553"] = "Khẩu SG553 dành riêng cho bên khủng bố lựa chọn thay thế có ống ngắm cho AK47 hiệu quả ở giao chiến tầm xa.",
    ["decoy_grenade"] = "Khi được ném, lựu đạn mồi làm giả âm thanh của vũ khí mạnh nhất bạn mang trên người, gây đánh lừa rằng mình có lực lượng hỗ trợ thêm.",
    ["incindiary_grenade"] = "Khi ném, lựu đạn lửa tạo ra phản ứng hóa học nhiệt độ cao đủ để nướng chín bất cứ ai ở trong tầm tỏa rộng của nó.",
    ["survival_taser"] = "Một vũ khí tầm cực ngắn có khả năng giết trong một phát. Cũng có thể dùng để mở hòm vũ khí.",
    ["survival_healthshot"] = "Hồi một lượng máu của bạn và tạm thời tăng tốc độ di chuyển.",
    ["survival_vesthelm"] = "Tăng khả năng kháng sát thương.",
    ["survival_shield"] = "Khiên chống bạo động có thể chặn được một lượng lớn sát thương trước khi bị phá hủy.",
    ["survival_parachute"] = "Có thể dùng khi đang rơi để tránh sát thương khi tiếp đất.",
    ["survival_exojump"] = "Cho phép nhảy cao hơn đáng kể.",
    ["survival_c4"] = "Đặt ở bất kỳ đâu trên bàn đổ để gây ra một vụ nổ lớn. Có thể dùng để mở két.",
    ["survival_dronepilot"] = "Cho khả năng điều khiển drone. Dùng máy tính bảng để chọn một drone bạn muốn điều khiển.",
    ["survival_exploremoney"] = "Thêm tiền thưởng cho mỗi ô lục giác khám phá được.",
    ["survival_wavemoney"] = "Thêm tiền thưởng với mỗi lần sống sót trước đợt nã pháo của vùng nguy hiểm.",
}
