csstring = { -- Danish
	["cat_pistols"] = "Pistoler",
	["cat_heavy"] = "Tunge",
	["cat_smg"] = "SMG'er",
	["cat_rifles"] = "Rifler",
	["cat_grenades"] = "Granater",
	["cat_gear"] = "Udstyr",

    ["ak47"] = { name = "AK-47", desc = "AK-47, kraftfuld og pålidelig, er en af de mest populære kamprifler i verden. Den er mest dødelig i korte, kontrollerede salver af skud." },
    ["aug"] = { name = "AUG", desc = "Den kraftfulde og nøjagtige AUG-kampriffel med kikkertsigte kompenserer for dens lange genladningstider med en lille spredning og en høj skudhastighed." },
    ["awp"] = { name = "AWP", desc = "Den berygtede AWP, med stor risiko og stor gevinst, er genkendelig med dens signaturrapport og ét skud, ét drab-politik." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Desert Eagle, så dyr som den er kraftfuld, er en ikonisk pistol, der er svær at mestre men overraskende præcis på lang afstand." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Dual Berettas", desc = "At affyre to stormagasin-Berettaer på samme tid gør præcisionen mindre og forøger ladetider. På den lyse side får du lov til at affyre to stormagasin-Berettaer på samme tid." },
    ["elite"] = "Dual Berettas",
    ["famas"] = { name = "FAMAS", desc = "Som en billig mulighed for pengemanglende spillere fylder FAMAS effektivt nichen mellem dyrere rifler og de mindre effektive maskinpistoler." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Den meget præcise og panserbrydende, men dyre, Five-Seven er en langsom lader, der kompenserer med et gavmildt 20-skudsmagasin og tilgivende rekyl." },
    ["flashbang"] = { name = "Flashbang", desc = "Den ikke-dødelige flashbang-granat blænder midlertidigt enhver i dens chokeksplosion, hvilket gør den perfekt til at rømme lukkede områder. Dens højlydte eksplosion dækker også midlertidigt over lyden af fodtrin." },
    ["g3sg1"] = { name = "G3SG1", desc = "Den dyre G3SG1 gør din bevægelseshastighed betydeligt lavere men kompenserer med en højere skudhastighed end andre snigskytterifler." },
    ["galilar"] = { name = "Galil AR", desc = "Som en mindre dyr mulighed blandt de terrorist-eksklusive kamprifler er Galil AR et brugbart våben i mellem- til langsigtet kamp." },
    ["glock18"] = { name = "Glock-18", desc = "Glock 18 er en brugbar pistol til første runde, der virker bedst mod upansrede modstandere og er i stand til at affyre tre-skudssalver." },
    ["he_grenade"] = { name = "Højeksplosiv granat", desc = "Den højeksplosive fragmentationsgranat uddeler høj skade i et stort område, hvilket gør den ideel til at rydde fjendtlige rum." },
    ["he_grenade_short"] = "HE-granat",
    ["hegrenade"] = "Højeksplosiv granat",
    ["knife"] = { name = "Kniv", desc = "Stille og altid til rådighed. Kniven har et hurtigt, lavt-skadende primært angreb og et langsomt, højt-skadende sekundært angreb. Et rygstik giver en stille spiller et øjeblikkeligt drab." },
    ["knife_t"] = "Kniv",
    ["knife_gg"] = "Guldkniv",
    ["knife_ghost"] = { name = "Spøgelseskniv", desc = "Spøgelser elsker spøgelsesknive. Så pas på, når de får fingrene i en! De forsøger at stikke dig, når de kan se deres snit til det. Synd, at de er spøgelser, og spøgelsesknive ikke kan skade folk..." },
    ["m249"] = { name = "M249", desc = "M249, et LMG, der er stærkt i åbne områder, er det perfekte valg for spillere, der er villige til at overkomme en langsom skudhastighed for forøget nøjagtighed og høj ammunitionskapacitet." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Med et mindre magasin end sit udæmpede modstykke, giver den lydløse M4A1 støjsvage skud med mindre rekyl og bedre præcision." },
    ["mac10"] = { name = "MAC-10", desc = "MAC-10-maskinpistolen, der egentlig bare er en kasse, som kugler kommer ud af, har en hurtig skudhastighed men med dårlig præcision og høj rekyl til afvejning." },
    ["p90"] = { name = "P90", desc = "P90, der nemt kan genkendes med sit unikke bullpup-design, er et godt våben til at skyde, mens man er i bevægelse, pga. dens højkapacitetsmagasin og lave rekyl." },
    ["smoke_grenade"] = { name = "Røggranat", desc = "Røggranaten skaber et mellemstort område med røgslør. Den kan effektivt skjule dit hold fra snigskytter eller blot skabe en nyttig distrahering." },
    ["smokegrenade"] = "Røggranat",
    ["ump45"] = { name = "UMP-45", desc = "UMP45, maskinpistol-familiens misforståede mellembarn, har én ulempe som er dens lille magasin, men den er derudover et fleksibelt automatvåben til nærkamp." },
    ["xm1014"] = { name = "XM1014", desc = "XM1014 er et kraftfuldt, fuldautomatisk haglgevær, som retfærdiggør sin heftige pris med evnen til hurtigt at fylde et rum med bly." },
    ["c4"] = { name = "C4-sprængstof", desc = "Dette improviserede plastiksprængstof, stabilt og resistent mod de fleste fysiske stød, har en eksplosionshastighed på over 8.000 meter i sekundet, når det antændes." },
    ["bizon"] = { name = "PP-Bizon", desc = "Bizon-maskinpistolen gør lav skade men tilbyder et unikt designet højkapacitet-tromlemagasin, der genlader hurtigt." },
    ["mag7"] = { name = "MAG-7", desc = "Den CT-eksklusive Mag-7 leverer en katastrofal mængde skade ved kort afstand. Dens hurtige magasin-stil-genladninger gør den til et godt taktisk valg." },
    ["negev"] = { name = "Negev", desc = "Negev er et monster af et våben, der kan holde fjenderne på afstand med sin præcise dækningsild, forudsat at du har nok tid til at få styr på den." },
    ["sawedoff"] = { name = "Sawed-off", desc = "Den klassiske Sawed-off gør meget kraftig skade på korte afstande, men med dens lave præcision, store spredning og langsomme skudhastighed må du hellere dræbe, hvad du rammer." },
    ["tec9"] = { name = "Tec-9", desc = "Tec-9, en ideel pistol for terroristen på farten, er dødelig i nærkamp og har en høj magasinkapacitet." },
    ["taser"] = { name = "Zeus x27", desc = "Perfekt til baghold ved korte afstande og træfninger i indelukkede områder. Etskudsvåbnet Zeus x27 kan lamme en fjende på én enkelt træffer." },
    ["molotov"] = { name = "Molotov", desc = "Molotovcocktailen er et kraftigt og uforudsigeligt område-nægtende våben, der bryder i flammer, når den kastes på jorden, hvilket skader enhver spiller i dens radius." },
    ["incgrenade"] = "Brandgranat",
    ["incgrenade_short"] = "Ildsættende",
    ["decoy"] = "Lokkegranat",
    ["decoy_short"] = "Lokkegranat",
    ["hkp2000"] = { name = "P2000", desc = "Den tysklavede P2000, præcis og kontrollerbar, er en brugbar pistol til første runde, der virker bedst mod upansrede modstandere." },
    ["mp7"] = { name = "MP7", desc = "Den tysklavede MP7-maskinpistol, fleksibel men dyr, er det perfekte valg til kamp på korte afstande med stor virkning." },
    ["mp5sd"] = { name = "MP5-SD", desc = "Ofte imiteret, men aldrig set lignende: Den ikoniske MP5 er måske den mest alsidige og populære maskinpistol i verden. Denne SD-variant er udstyret med en integreret lyddæmper, som gør et allerede formidabelt våben stille som hvisken." },
    ["mp9"] = { name = "MP9", desc = "Den banebrydende MP9-maskinpistol, der fremstilles i Schweiz, er et våben af ergonomisk polymer, som mange private sikkerhedsfirmaer foretrækker." },
    ["nova"] = { name = "Nova", desc = "Novas bundpris gør den til et godt bagholdsangrebsvåben for et pengemanglende hold." },
    ["p250"] = { name = "P250", desc = "P250, et lavrekyl-skydevåben med høj skudhastighed, er et relativt billigt valg mod pansrede fjender." },
    ["cz75"] = "CZ75-Auto",
    ["scar20"] = { name = "SCAR-20", desc = "SCAR-20 er en halvautomatisk snigskytteriffel, der med en høj skudhastighed og kraftig lang-afstandsskade dog har langsom bevægelseshastighed og høj pris." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "SSG08 bolt-action er en lav-skade men meget omkostningseffektiv snigskytteriffel, hvilket gør den et klogt valg til lang-afstandsskydefærdigheder i de tidlige runder." },
    ["heavyassaultsuit"] = "Tungangrebsdragt",
    ["assaultsuit"] = "Kevlar og hjelm",
    ["assaultsuit_only_helmet"] = "Hjelm",
    ["kevlar"] = "Kevlarvest",
    ["defuser"] = "Demonteringssæt",
    ["cutters"] = "Redningssæt",
    ["revolver"] = { name = "R8-revolver", desc = "R8-revolveren leverer en meget nøjagtig og kraftfuld kugle men er længe om at udføre trykket på aftrækkeren. At skyde hurtigt, ved at slå på slagstiften, kan være den bedste mulighed, når stoppende kraft på klos hold er krævet." },
    ["usp_silencer"] = { name = "USP-S", desc = "En af fanfavoritterne fra Counter-Strike: Source – den lyddæmpede USP-pistol har en aftagelig lyddæmper, der giver skud mindre rekyl, mens den dæmper opmærksomhedstiltrækkende støj." },
    ["knifebayonet"] = { name = "Bajonet", desc = "Bajonetten, der er relativt uændret i sit design siden Anden Verdenskrig, har stadig sin plads i moderne militærstrategier. Bajonetangreb har fortsat været effektive så nyligt som i den anden Golfkrig og krigen i Afghanistan." },
    ["knifeflip"] = { name = "Foldekniv", desc = "Foldeknive er prydet med en persiskstilet tilbagefejende klinge med en skarp spids. Mens spidsen i sig selv måske er skrøbeligt, er foldeknivens overordnede design overraskende holdbart." },
    ["knifegut"] = { name = "Jagtkniv", desc = "Den mest fremtrædende af jagtknivens funktioner er tarmkrogen på klingens ryg. Selvom den originalt blev populariseret til at hjælpe med at fjerne dyreindvolde under jagt, er tarmkrogen også effektiv til at skære gennem fiberholdigt materiale som reb, stropper eller sikkerhedsbælter med lethed." },
    ["knifecss"] = { name = "Klassisk kniv", desc = "Denne kniv er en klassiker i Counter-Strike-serien. Bladet er af stellit, som holdes perfekt på plads med prespasningen med titanen på knivbladets ryg og side. Håndtaget er lavet af fossileret mastodontelfenben, som sidder i en kulfiberlomme." },
    ["knifem9"] = { name = "M9-bajonet", desc = "Dette er M9-bajonetten. Originalt beregnet til at montere på en riffel, men den er også velegnet til nærkamp." },
    ["knifekaram"] = { name = "Karambit", desc = "Med dens kurvede klinge, der efterligner en tigers klo, blev karambitten udviklet som del af den sydøstasiatiske kampsport silat. Kniven bruges typisk med et omvendt greb med fingerringen på pegefingeren." },
    ["knifetactical"] = { name = "Huntsman-kniv", desc = "En kniv designet til moderne taktisk brug, hvor klingen er velegnet til et sortiment af både kamp- og nyttebehov. Det unikke Tanto-punkt tillader maksimal penetration gennem selv de stærkeste overflader." },
    ["knife_butterfly"] = { name = "Butterfly-kniv", desc = "Dette er en specialdesignet balisong, almindeligvis kendt som en butterfly-kniv. De definerende karakteristikker af dette våben er den blæser-lignende åbning af den fritdrejende klinge, hvilket tillader hurtig udfoldning eller skjulning. Som et resultat er butterfly-knive ulovlige i mange lande." },
    ["partypopper"] = "Konfettikanon!",
    ["knife_falchion_advanced"] = { name = "Falchion-kniv", desc = "Denne slagpunktsklinge, der er en moderne hyldest til et falchion-sværd, har en kurvet kant." },
    ["knife_push"] = { name = "Shadow-daggerter", desc = "Designet til effektiv brutalitet, at bruge en skubbedaggert er så simpelt som at slå en gang eller to." },
    ["knife_survival_bowie"] = { name = "Bowie-kniv", desc = "Denne savtakkede, fuld-angel Bowie-kniv er designet til hård brug i brutale overlevelsessituationer." },
    ["healthshot"] = "Medicinsprøjte",
    ["tagrenade"] = "Taktisk afsløringsgranat",
    ["exploding_barrel"] = "Eksploderende tønde",
    ["snowball"] = "Snebold",
    ["stompdamagekillstring"] = "knuste dit kranie",
    ["dangerzone"] = "Danger Zone",
    ["autosentry"] = "Automatiseret sentry",
    ["fists"] = "Bare næver",
    ["tablet"] = "Tablet",
    ["breachcharge"] = "Sprængladning",
    ["bumpmine"] = "Hoppemine",
    ["axe"] = { name = "Økse", desc = "Denne økse er tung og altid ved hånden. Den har en skarp side og en sløv side. Sving den for at gøre mindre skade ved primære angreb, eller kast den for at gøre stor skade ved sekundære angreb. Goddag mand, økseskaft!" },
    ["hammer"] = { name = "Hammer", desc = "Hammeren er til rådighed til at reparere og ødelægge ting. Sving den for et primærangreb med lav skade, eller kast den for et sekundært angreb med høj skade. Hvis du kun har en hammer, ligner alting et søm." },
    ["spanner"] = { name = "Skruenøgle", desc = "En skruenøgle bruges typisk til at påføre moment, når du drejer genstande, men du kan ramme hvad som helst med den som et primærangreb med lav skade eller kaste den som et sekundært angreb med høj skade. At medbringe en skruenøgle i en ildkamp er en opskrift på at dumme sig." },
    ["tripwirefire"] = "Ildfælde",
    ["knife_cord"] = { name = "Paracordkniv", desc = "Denne overlevelseskniv har et fikseret knivblad og er designet til at kunne tåle brug som både et våben og værktøj til at opsætte fælder, jagte dyr eller klippe buske. Skaftet er pakket ind i universel faldskærmssnor." },
    ["knife_canis"] = { name = "Overlevelseskniv", desc = "Denne taktiske universalkniv har en savtakket æg, som kan skære igennem hårdt materiale som knogler eller fiber samt en skarp krog. Skaftet er lavet af kompositmateriale og er skruet fast med sekskantede skruer." },
    ["knife_ursus"] = { name = "Ursus-kniv", desc = "Denne overlevelseskniv i tanto-stil har en facetteret, fuldtangs knivklinge, fuldført med sværknop. Ingen problemer, ingen bevægelige dele – bare et pålideligt blad, der er klar til brug." },
    ["knife_gypsy_jackknife"] = { name = "Navaja-kniv", desc = "Denne springkniv med et greb i marmoremalje skjuler en lille, men ondt tilspidset klinge." },
    ["knife_outdoor"] = { name = "Nomadekniv", desc = "Denne ergonomiske, taktiske jagtkniv har et bredt og solidt knivblad, som kan låses. Den er god til at skære og lirke materiale fra hinanden. Skaftet er lavet af kompositmateriale." },
    ["knife_widowmaker"] = { name = "Talon-kniv", desc = "Denne karambitformede kniv med elfenbensgreb har messingnitter og savkanter, så den skærer på vejen ind og river, når den trækkes ud." },
    ["knife_stiletto"] = { name = "Stiletto-kniv", desc = "Denne italienske stiletto-springkniv har historisk set været omdrejningspunkt for kontrovers og lovgivning. Den har en fjedermekanisme, der kan skubbe kniven ud på et øjeblik." },
    ["knife_skeleton"] = { name = "Skeletkniv", desc = "Denne skelettangkniv er blevet tapet ved håndtaget for at forbedre grebet. Hullet gør det muligt at føre en finger igennem for at sikre stabilitet og sikkerhed." },
    ["knife_kukri"] = { name = "Kukrikniv", desc = "Bruges i traditionelle ceremonier, såsom bryllupper og knivoverfald." },
    ["firebomb"] = { name = "Ildbombe", desc = "En ildbombe er et kraftfuldt eksperimentelt våben, som frigiver en kemisk reaktion ved høj temperatur, der kan brænde enhver inden for dens store radius." },
    ["diversion"] = { name = "Afledningsapparat", desc = "Når et afledningsapparat kastes, aktiveres sektorer på tablets og giver illusionen af yderligere fjender." },
    ["frag_grenade"] = { name = "Fragmentationsgranat", desc = "Den eksperimentelle fragmentationsgranat kan yde ekstrem eksplosiv skade på et større område, hvilket gør den ideel til både angreb og forsvar." },
    ["shield"] = { name = "Beskyttelsesskjold", desc = "Beskyttelsesudstyr til at afværge eller absorbere ballistisk skade og hjælpe med at beskytte brugeren mod projektiler i forskellige kalibre." },
    ["zone_repulsor"] = { name = "Afskærmningsenhed", desc = "Prototype af en radial afskærmningsenhed mod partikeludslip" },
    ["glock_use"] = "• Farlig tæt på, men blot en irritation over afstand\n• Overvej den i halvlegens første runde\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Nøjagtig på afstand og kan affyrres hurtigt tæt på\n• Overvej den i halvlegens første runde\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• Præcis, tavs og (nogenlunde) dødbringende\n• Overvej den i halvlegens første runde\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• To hurtigtskydende pistoler for én pistols pris\n• Overvej dem i halvlegens første runde\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• En populær, omend beskeden, skadeopgradering\n• Overvej den i økorunder\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Slagkraftig, hurtig og præcis til sin pris \n• Overvej den i økorunder\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• En salve af ildkraft til at stjæle fjendens våben\n• Overvej i økorunder\n• Sværhedsgrad: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Meget mobil, effektiv på afstand og i nærkamp\n• Overvej i økorunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Gør massiv skade efter en kort forsinkelse\n• Overvej den i økorunder\n• Sværhedsgrad: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Engangsbrug med kort afstand og garanteret drab\n• Forsøg på eget ansvar\n• Sværhedsgrad: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• En kugleregn for at meje upansrede modstandere ned\n• Overvej den i de første tre runder af halvlegen\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Løb og skyd dig vej frem til bombelokaliteterne\n• Overvej den i de første tre runder af halvlegen\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• En skaderegn for at stoppe en fjendtlig invasion\n• Overvej den i de første tre runder af halvlegen\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Nem at styre for pålidelig skade på mellemafstand\n• Overvej den i tvangskøbsrunder\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Et adræt og stille våben til middel afstand\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• God rustningspenetration på middel afstand\n• Overvej i fulde købsrunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• En endeløs kugleslange, kun overgået af rifler\n• Overvej i fulde købsrunder\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Billig, men effektiv mod pansrede fjender\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Billig, men effektiv mod pansrede fjender\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• Den klassiske, præcise og dødbringende arbejdshest\n• Overvej i fulde købsrunder\n• Sværhedsgrad: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• God nøjagtighed, med ammunition til overs\n• Overvej i fulde købsrunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• Præcis, lydløs og sporfri\n• Overvej i fulde købsrunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Et valgfrit kikkertsigte for ekstraordinær nøjagtighed\n• Overvej i fulde købsrunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Et dødbringende våben, gjort farligere med kikkertsigte\n• Overvej i fulde købsrunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Ødelæggende kraft til den selvsikre snigskytte\n• Overvej i fulde købsrunder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Automatisk snigskytteriffel med høj risiko og høj belønning\n• Overvej den kun under særlige omstændigheder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Et kraftfuldt (om end risikabelt) værktøj til at forsvare en position\n• Overvej den kun under særlige omstændigheder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Et let og kraftfuldt våben til lange afstande\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Overrask fjenden, genlad og gentag!\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Alsidigt haglgevær til tætte kampe\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Kraftigt haglgevær til tætte kampe\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Et hurtigtskydende fuldautomatisk monster\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• I det mindste behøver du ikke at genlade...\n• Overvej kun under særlige omstændigheder\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Præcis ild til at undertrykke og købe tid\n• Overvej i tvangskøbsrunder\n• Sværhedsgrad: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Gør skade eller rydder røggranater\n• Anvend med omtanke\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Blænder/døver spillere i nærheden\n• Kast før et angreb\n• Sværhedsgrad: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Skaber en stor røgsky\n• Kast for at afskære fjendens synsfelt\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Efterligner affyringslyden fra et våben\n• Kast tidligt for at forvirre fjenden\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Rydder skjulesteder med ild\n• Kast før angreb på en bombelokalitet\n • Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Undertrykker fjendtlige angreb med ild\n• Kast ved det første tegn på problemer\n• Sværhedsgrad: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• Overlev alle kugler, bortset fra de mest dødbringende\n• Overvej i fulde købs- og tvangskøbsrunder\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Beskytter alting undtagen dit hoved\n• Overvej den i halvlegens første runde\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Sænk demonteringstiden til det halve\n• Lad ikke de andre vinde, brug de ekstra penge!\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Saml gidsler op på en brøkdel af tiden\n• Overvej, når du har ekstra midler\n• Sværhedsgrad: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "Som en fuld-automatisk variant til CZ75'eren er CZ75-Auto'en endnu et ideelt, kortsigtet valg for at vende situationen og få fat i din fjendes våben. Men med meget lidt ammunition i magasinet, kræves en stærk aftrækkerdisciplin.",
    ["m4a4"] = "M4A4, mere præcis men mindre skadende end sit AK-47-modstykke, er den mest populære fuldautomatiske riffel for CT'ere.",
    ["sg553"] = "Den terrorist-eksklusive SG553 er et luksusalternativ til AK-47 med sigte til effektiv lang-afstandssammenstød.",
    ["decoy_grenade"] = "Når den smides, efterligner lokkegranaten lyden af det kraftigste våben, du bærer, og skaber illusionen af flere støttende styrker.",
    ["incindiary_grenade"] = "Når den kastes frigiver brandgranaten en kemisk reaktion ved høj temperatur, der kan brænde enhver inden for dens store eksplosionsradius.",
    ["survival_taser"] = "Et våben med ekstremt kort rækkevidde, der kan dræbe med ét skud. Kan også bruges til at åbne våbenkasser.",
    ["survival_healthshot"] = "Gendanner en del af dit helbred og giver et kortvarigt hastighedsboost.",
    ["survival_vesthelm"] = "Giver modstandsdygtighed over for skader.",
    ["survival_shield"] = "Et beskyttelsesskjold, som kan blokere en stor mængde skade, før det ødelægges.",
    ["survival_parachute"] = "Kan udløses i fald for at forhindre faldskade.",
    ["survival_exojump"] = "Øger hoppehøjden betydeligt.",
    ["survival_c4"] = "Placer et vilkårligt sted på banen for at skabe en stor eksplosion. Kan bruges til at åbne pengeskabe.",
    ["survival_dronepilot"] = "Gør dig i stand til at styre droner. Brug tabletten til at vælge en drone, du vil overtage.",
    ["survival_exploremoney"] = "Giver ekstra penge for hver udforskede heksagon.",
    ["survival_wavemoney"] = "Giver ekstra penge for hver bølge af farezoneudvidelsen, du overlever.",
    ["deagle_use"] = "• A lethal headshot at any range\n• Consider in eco rounds\n• Difficulty: <color=191,64,64>★★★★</color>\n\n",
}
