csstring = { -- Turkish
	["cat_pistols"] = "Tabancalar",
	["cat_heavy"] = "Ağir sİlahlar",
	["cat_smg"] = "Hafİf makİnelİler",
	["cat_rifles"] = "Tüfekler",
	["cat_grenades"] = "El bombalari",
	["cat_gear"] = "Teçhİzat",

    ["ak47"] = { name = "AK-47", desc = "Güçlü ve güvenilir, AK-47 dünyanın en popüler saldırı tüfeklerinden biridir. Kontrollü atış gücü ile yakın mesafede ölümcüldür." },
    ["aug"] = { name = "AUG", desc = "Güçlü ve isabetli olan dürbünlü AUG silahının şarjörünü doldurmak uzun sürer, ama mermileri fazla dağıtmaması ve yüksek bir atış hızına sahip olması bunu telafi eder." },
    ["awp"] = { name = "AWP", desc = "Büyük risk ve büyük ödül. Ünlü AWP silahı, bir atışta bir leş sözü ile de hatırlanabilir." },
    ["deserteagle"] = { name = "Desert Eagle", desc = "Güçlü olduğu kadar pahalı ve artık ikonlaşmış bir tabanca olan Desert Eagle ustalaşması zor bir silahtır. Ayrıca şaşırtıcı bir şekilde uzak mesafelerde de isabetlidir." },
    ["deagle"] = "Desert Eagle",
    ["elites"] = { name = "Çift Beretta", desc = "İki büyük şarjöre sahip olan Çift Beretta ile ateş ettiğinizde isabet oranınız azalacak ve şarjörü doldurmanız uzun sürecektir. Ama işin iyi tarafına bakacak olursak, iki tane büyük şarjörü olan Çift Beretta ile ateş etmiş olacaksınız." },
    ["elite"] = "Çift Beretta",
    ["famas"] = { name = "FAMAS", desc = "Nakitte sıkıntı çeken oyuncular için ucuz bir seçenek olan FAMAS, daha pahalı tüfekler ve daha az etkili hafif makineliler arasındaki boşluğu etkin biçimde dolduruyor." },
    ["fiveseven"] = { name = "Five-SeveN", desc = "Yüksek isabet oranı ve zırh delme kabiliyetine sahip pahalı bir tabanca olan Five-SeveN şarjörü yavaş doldurur, ama 20 mermilik cömert şarjörü ve geri tepme oranı bunu telafi eder." },
    ["flashbang"] = { name = "Flaş Bombası", desc = "Öldürücü olmayan flaş bombası, sarsıntılı patlamanın içerisindeki birini geçici olarak kör eder ve kapalı alanlara baskını mükemmel hale getirir. Ayrıca yüksek sesle patlaması da ayak seslerini maskeler." },
    ["g3sg1"] = { name = "G3SG1", desc = "Pahalı bir silah olan G3SG1 hareket hızını ciddi derecede azaltır ama diğer dürbünlü tüfeklere göre daha yüksek bir atış hızına sahip olması bunu telafi eder." },
    ["galilar"] = { name = "Galil AR", desc = "Terörist saldırı tüfekleri arasında daha ucuz bir seçenek, Galil AR orta ve uzak mesafe çatışmada kullanışlı bir silahtır." },
    ["glock18"] = { name = "Glock-18", desc = "Glock-18 zırhsız düşmanlara karşı kullanışlı bir ilk raunt tabancasıdır ve üçlü atış yapabilir." },
    ["he_grenade"] = { name = "El Bombası", desc = "El bombası geniş bir alan boyunca yüksek hasar verir ve düşman odalarını boşaltmak için ideal hale getirir." },
    ["he_grenade_short"] = "El Bombası",
    ["hegrenade"] = "El Bombası",
    ["knife"] = { name = "Bıçak", desc = "Sessiz ve her zaman erişilebilir, bıçağın ilk vuruşu hızlı ve düşük hasarlıdır, ikinci vuruşu yavaş fakat daha yüksek hasarlıdır. Arkadan bıçaklama ise sessiz oyunculara ani öldürüşü sağlar." },
    ["knife_t"] = "Bıçak",
    ["knife_gg"] = "Altın Bıçak",
    ["knife_ghost"] = { name = "Hayalet Kaması", desc = "Hayaletler hayalet bıçaklarını severler. Eğer ellerine geçerlerse dikkatli olun! Buldukları ilk fırsatta sizi bıçaklamaya çalışacaklar. Onların hayalet olmaları ve hayalet bıçaklarının insanlara zarar verememesi kötü tabii..." },
    ["m249"] = { name = "M249", desc = "Güçlü bir açık alan ağır silahı olan M249, artırılmış isabet ve yüksek cephane kapasitesi için yavaş atış hızını göze alan oyuncular için mükemmel seçimdir." },
    ["m4a1"] = "M4A4",
    ["m4_silencer"] = "M4A1-S",
    ["m4a1_silencer"] = { name = "M4A1-S", desc = "Susturuculu M4A1, susturucu çıkarılmış haline nazaran daha küçük bir şarjör haznesine sahip olmakla beraber daha az geri tepme ve daha iyi kesinlik ile daha sessiz atışlar sağlar." },
    ["mac10"] = { name = "MAC-10", desc = "Basitçe içinden mermiler çıkan bir kutu olan MAC-10 hafif makinelisi, yüksek bir atış hızına sahiptir ancak fazla geri teper ve isabet oranı düşüktür." },
    ["p90"] = { name = "P90", desc = "Benzersiz bullpup tasarımı sayesinde kolayca hatırlanabilen, yüksek kapasiteli şarjörüyle ve düşük geri tepmesiyle P90, hareket halindeyken vurmak için mükemmel bir silahtır." },
    ["smoke_grenade"] = { name = "Sis Bombası", desc = "Sis bombası orta boyutlu bir duman perdesi oluşturur. Bu, takımınızı keskin nişancılardan gizlemek, veya yararlı bir oyalama oluşturmak konusunda etkili olabilir." },
    ["smokegrenade"] = "Sis Bombası",
    ["ump45"] = { name = "UMP-45", desc = "Hafif makineli ailesinin değeri anlaşılamamış ortanca çocuğu. Yakın mesafede oldukça etkili ve tam otomatik bir silah olan UMP-45'in tek dezavantajı küçük şarjör kapasitesidir." },
    ["xm1014"] = { name = "XM1014", desc = "XM1014, pahalı fiyat etiketini bir odayı anında kurşunla doldurabilme kabiliyetiyle telafi eden güçlü ve tam otomatik bir pompalı tüfektir." },
    ["c4"] = { name = "C4 Patlayıcı", desc = "Çoğu fiziksel sarsıntıya karşı sağlam ve dirençli olan bu el yapımı plastik patlayıcı, ateşlendiğinde saniyede 8.000 metreden fazla bir patlama hızına sahiptir." },
    ["bizon"] = { name = "PP-Bizon", desc = "Bizon hafif makinelisi düşük hasar verir, ama seri değiştirilebilmesi için özel tasarlanmış yüksek kapasiteli bir şarjör sunar." },
    ["mag7"] = { name = "MAG-7", desc = "AT'ye özel Mag-7 yakın mesafede yok edici etkiye sahiptir. Hızlı şarjör değiştirmesi onu mükemmel bir taktiksel seçenek hâline getirir." },
    ["negev"] = { name = "Negev", desc = "Eğer kontrol altında tutabilecek zaman lüksüne sahipseniz Negev, oldukça isabetli bastırma ateşi ile düşmanları uzakta tutabilecek bir canavardır." },
    ["sawedoff"] = { name = "Sawed-Off", desc = "Klasik bir silah olan Sawed-Off yakın mesafelerde çok ağır hasar verir. Ama düşük isabet oranı, mermileri fazla dağıtması ve düşük atış hızından dolayı vurduğunuzu öldürseniz iyi olur." },
    ["tec9"] = { name = "Tec-9", desc = "Hareket halindeki Teröristler için ideal bir tabanca olan Tec-9, yakın mesafeli çatışmalarda ölümcüldür ve yüksek kapasiteli bir şarjör sunar." },
    ["taser"] = { name = "Zeus x27", desc = "Yakın mesafe pusuları ve kapalı alan çatışmaları için mükemmel olan tek atışlık Zeus x27, düşmanı tek vuruşta etkisiz hâle getirme kapasitesine sahiptir." },
    ["molotov"] = { name = "Molotof", desc = "Molotof oldukça güçlü ve bir bölgeye attığınızda orada beklenmedik bir alan engellemesi oluşturabilen bir silahtır. Düştüğü yer yanmaya başlar ve o alan içinde bulunan oyuncular zarar görür." },
    ["incgrenade"] = "Yanıcı Bomba",
    ["incgrenade_short"] = "Yanıcı",
    ["decoy"] = "Yanıltıcı Bomba",
    ["decoy_short"] = "Yanıltıcı",
    ["hkp2000"] = { name = "P2000", desc = "İsabetli ve kontrol edilebilir, Alman yapımı P2000 zırhsız düşmanlara karşı en iyi ilk raunt tabancasıdır." },
    ["mp7"] = { name = "MP7", desc = "Çok yönlü fakat pahalı. Alman yapımı MP7 hafif makinelisi yakın çatışmalarda etkili olmak için mükemmel bir seçimdir." },
    ["mp5sd"] = { name = "MP5-SD", desc = "Çok sık taklit edilen ancak eşi benzeri olmayan MP5, dünyadaki hafif makineli silahlar arasından belki de en çok yönlü ve popüler olanlardan biridir. Ölümcül MP5'ın bu SD versiyonu sahip olduğu entegre susturucusu sayesinde fısıltı sessizliğinde çalışır." },
    ["mp9"] = { name = "MP9", desc = "İsviçre'de üretilmiş son teknoloji ürünü olan MP9 hafif makinelisi, özel güvenlik firmaları tarafından tercih edilen ergonomik polimer bir silahtır." },
    ["nova"] = { name = "Nova", desc = "Nova'nın ucuz fiyatı, onu nakit sıkıntısı çeken takımlar için müthiş bir pusu silahı haline getirir." },
    ["p250"] = { name = "P250", desc = "Düşük bir geri tepme oranına sahip ve seri ateş edebilme kabiliyeti olan P250 tabancası, zırhlı rakiplerinize karşı diğer silahlara göre biraz daha ucuz bir seçimdir." },
    ["cz75"] = "CZ75-Otomatik",
    ["scar20"] = { name = "SCAR-20", desc = "SCAR-20, yüksek atış hızı ve güçlü uzun mesafe hasarı için, ağır hareket hızı ve büyük fiyat etiketine katlanılan yarı otomatik bir keskin nişancı tüfeğidir." },
    ["sg556"] = "SG 553",
    ["ssg08"] = { name = "SSG 08", desc = "SSG 08'in az hasar veren ancak fiyatına göre çok etkili bir keskin nişancı silahı olması, ilk rauntlarda onu uzun menzilli nişancılık için akıllı bir tercih haline getirmektedir." },
    ["heavyassaultsuit"] = "Ağır Saldırı Zırhı",
    ["assaultsuit"] = "Çelik Yelek ve Kask",
    ["assaultsuit_only_helmet"] = "Kask",
    ["kevlar"] = "Çelik Yelek",
    ["defuser"] = "İmha Teçhizatı",
    ["cutters"] = "Kurtarma Teçhizatı",
    ["revolver"] = { name = "R8 Revolver", desc = "R8 Revolver, uzun bir tetik çekişi pahasına oldukça isabetli ve güçlü bir mermi sağlar. Çok kısa mesafeden durdurucu güç gerektiğinde belki de en iyi seçenek, horozu hızlıca ateşlemektir." },
    ["usp_silencer"] = { name = "USP-S", desc = "Counter-Strike: Source hayranlarının favorilerinden biri olan USP-S tabancası, silahın geri tepme oranını azaltırken aynı zamanda sesini de bastıran ve takıp çıkarılabilen bir susturucuya sahiptir." },
    ["knifebayonet"] = { name = "Bayonet", desc = "İkinci Dünya Savaşı'ndan bu yana tasarımı çok fazla değişmeyen Bayonet'in modern askeri stratejide hâlâ yeri bulunmaktadır. Bayonet hücumları, son dönemlerdeki Afganistan Savaşı ve İkinci Körfez Savaşı'nda görüldüğü üzere etkili olmaya devam etmektedir." },
    ["knifeflip"] = { name = "Sustalı Bıçak", desc = "Sustalı Bıçak; Pers tarzı arka tarafı kavisli, sivri bir ucu olan gösterişli bir bıçaktır. Sivri noktanın kendisi kırılgan durumda iken, bıçağın genel tasarımı şaşırtıcı derecede dayanıklıdır." },
    ["knifegut"] = { name = "Kancalı Bıçak", desc = "Kancalı Bıçağın en göze çarpan özelliği arka kısmındaki kancadır. Orijinal olarak, savaş alanlarında yapılan pansumanlarda kullanılan bir alet olarak popülerleşmiştir. Bıçaktaki kanca ayrıca ip, kayış ya da emniyet kemeri gibi lifli materyalleri de kolayca kesebilir." },
    ["knifecss"] = { name = "Klasik Bıçak", desc = "Counter-Strike serisinin bir klasiği olan bu bıçağın köşeleri, bıçağın yanaklarında ve sırtında bulunan titanyum sayesinde keskin ve kusursuz bir şekilde yerine oturtulmuştur. Kabzası, fosilleşmiş mastadon dişi ve karbon fiber ile birlikte tutturulmuştur." },
    ["knifem9"] = { name = "M9 Bayonet", desc = "Bu, M9 Bayonet. Asıl olarak bir tüfeğe takılmak için tasarlanmıştır, ayrıca yakın mesafeli çatışmalar için de çok uygundur." },
    ["knifekaram"] = { name = "Karambit", desc = "Kıvrık bıçağıyla bir kaplanın pençesini andıran Karambit, güneydoğu Asya silat dövüş disiplininin bir parçası olarak geliştirilmiştir. Bıçak genelde, üzerindeki halkadan işaret parmağı geçirilerek ters bir kavrayış ile kullanılır." },
    ["knifetactical"] = { name = "Avcı Bıçağı", desc = "Modern taktiksel kullanımlar için dizayn edilmiş bu bıçak, yakın mücadele ve faydalı kullanım gibi alanların her ikisi için de uygundur. Eşsiz Tanto noktası en sert yüzeylerde bile maksimum delmeyi sağlar." },
    ["knife_butterfly"] = { name = "Kelebek Bıçak", desc = "Bu özel dizayn edilmiş bir balisong bıçağı, halk arasında kelebek olarak da bilinir. Daha çok elde çevrilmesiyle tanınır. Hızlıca gizlenebilmesi ve çıkarılabilmesi artı yönlerindendir. Çoğu ülkede kelebek bıçaklar yasaklanmıştır." },
    ["partypopper"] = "Parti Patlatıcı!",
    ["knife_falchion_advanced"] = { name = "Pala Bıçağı", desc = "Palaya modern bir saygı gösterisi olan bu ucu eğik bıçağın kenarları da kavislidir." },
    ["knife_push"] = { name = "Gölge Hançerler", desc = "Etkili darbeler için tasarlanan bu hançerleri kullanmak, bir iki yumruk atmak kadar kolaydır." },
    ["knife_survival_bowie"] = { name = "Bowie Bıçağı", desc = "Arkası testereli bu Eğri Av Bıçağı, ciddi hayatta kalma mücadelelerinde kullanmak üzere tasarlanmıştır." },
    ["healthshot"] = "Sağlık Aşısı",
    ["tagrenade"] = "Taktiksel Farkındalık Bombası",
    ["exploding_barrel"] = "Patlayan Varil",
    ["snowball"] = "Kartopu",
    ["stompdamagekillstring"] = "kafatasını parçaladı",
    ["dangerzone"] = "Tehlikeli Bölge",
    ["autosentry"] = "Otomatik Taret",
    ["fists"] = "Yumruklar",
    ["tablet"] = "Tablet",
    ["breachcharge"] = "Yıkım Bombası",
    ["bumpmine"] = "Fırlatma Mayınları",
    ["axe"] = { name = "Balta", desc = "Ağır ve her zaman kullanılabilen baltanın keskin ve kör bir tarafı vardır. Düşük hasarlı birincil saldırı için savur veya yüksek hasarlı ikincil saldırı için fırlat. Bir balta diğer bir baltaya gel beraber baltalayım demiş." },
    ["hammer"] = { name = "Çekiç", desc = "Çekiç, bir şeyleri onarmak veya kırmak için kullanılabilir. Düşük hasarlı birincil saldırı için savur veya yüksek hasarlı ikincil saldırı için fırlat. Elinde sadece çekiç varsa her şey çivi olur." },
    ["spanner"] = { name = "İngiliz Anahtarı", desc = "İngilliz anahtarı genellikle bir şeyleri sıkarken tork uygulamak için kullanılır, ancak herhangi bir şeye vurarak düşük hasarlı birincil saldırısını veya fırlatarak yüksek hasarlı ikincil saldırısını kullanabilirsin. Yalnız, nasıl ki silahlı çatışmaya bıçakla gitmiyorsan, İngiliz anahtarıyla da gitmemelisin." },
    ["tripwirefire"] = "Ateş Tuzağı",
    ["knife_cord"] = { name = "Paraşüt Kordonu Saplı Bıçak", desc = "Bu sabit hayatta kalma bıçağı tuzak kurulumu, hayvan avı ya da ot kesme gibi durumlar ortaya çıktığında hem silah hem de bir araç olarak kullanılması için tasarlanmıştır. Bıçağın sapı boydan boya çok amaçlı paraşüt kordonuyla sarılıdır." },
    ["knife_canis"] = { name = "Hayatta Kalma Bıçağı", desc = "Bu çok amaçlı taktisel bıçakta kemik ya da lif gibi kalın malzemelerin içinden doğrudan geçmesine olanak tanıyan testere dişli bir bıçak ve bu bıçağın ucunda da deşme kancası yer alıyor. Kompozit bir malzemeden imal edilen sapı, bıçağa altıgen somunlar kullanılarak cıvatalarla tutturulmuştur." },
    ["knife_ursus"] = { name = "Ursus Bıçağı", desc = "Bu tanto tipi hayatta kalma bıçağında çok boyutlu bir bıçak ağzına, hafif eğimli bir baş kısmına ve darbe emici kabzaya sahiptir. Hareket eden parçası yoktur. Tam anlamıyla işe koyulabileceğin dört dörtlük güvenilir bir bıçaktır." },
    ["knife_gypsy_jackknife"] = { name = "Navaja Bıçağı", desc = "Mermer emayeli kabzaya sahip bu açılır bıçakta küçük ama vahşi şekilde efektif konik uçlu bir bıçak saklıdır." },
    ["knife_outdoor"] = { name = "Göçebe Bıçağı", desc = "Açılır ve kilit mekanizmasına sahip olan bu ergonomik taktiksel avcı bıçağı, ayrıca kompozit saplara ve bir şeyleri kesmek ya da kanırtmak için kullanılabilecek güçlü bir bıçağa sahiptir." },
    ["knife_widowmaker"] = { name = "Talon Bıçağı", desc = "Fildişi kabzalı bu karambitte pirinç cıvatalar kullanılmıştır, saplarken rahat bir şekilde girebilmesi ve çıkarken de parçalayabilmesi için testere ağzına sahip bir kısmı vardır." },
    ["knife_stiletto"] = { name = "Stiletto Bıçak", desc = "Geçmişten bu yana tartışmalara, hatta düzenlemelere konu olmuş İtalyan tarzı bu stiletto bıçağın normalde gizli duran bıçak kısmı yaylı mekanizması sayesinde tek bir dokunuşla anında ortaya çıkartılabilir." },
    ["knife_skeleton"] = { name = "İskelet Bıçak", desc = "Bu iskelete benzetilen bıçağın kabzası daha iyi bir kavrama için bantla kaplanmış. Kabzasındaki deliğe parmak sokularak daha güvenilir ve kararlı bir kullanım tecrübesi sağlıyor." },
    ["knife_kukri"] = { name = "Kukri Bıçağı", desc = "Düğünler ve bıçaklama gibi geleneksel ritüellerde kullanılır." },
    ["firebomb"] = { name = "Yangın Bombası", desc = "Güçlü deneysel yangın bombası, yere atıldığı zaman oldukça yüksek ısıda yanan alevler saçarak geniş etki alanında yer alan oyuncuları kimyasal olarak yakmaya başlar." },
    ["diversion"] = { name = "Dikkat Dağıtma Aygıtı", desc = "Dikkat dağıtma aygıtı atıldığı zaman sektörleri yakarak daha fazla düşman varmış gibi bir izlenim yaratır." },
    ["frag_grenade"] = { name = "El Bombası", desc = "Deneysel parça tesirli bomba, geniş bölgelere muazzam seviyede patlayıcı hasarı verdiği için hem saldırı hem de savunma stratejileri için idealdir." },
    ["shield"] = { name = "Polis Kalkanı", desc = "Balistik hasarı emmek veya savuşturmak ve taşıyıcısını farklı kalibredeki mermilerden korumaya yardımcı olmak üzere tasarlanmış bir korunma eşyası." },
    ["zone_repulsor"] = { name = "İtme Aygıtı", desc = "Prototip Radyal Emisyon Parçacıklara Karşı Koruyucu Kalkan Aygıtı" },
    ["glock_use"] = "• Yakın mesafede ölümcül, uzak mesafelerde etkisi az.\n• Yarının ilk raundunda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["hkp2000_use"] = "• Uzak mesafelerde isabetli, yakın mesafede tarama yapılabilir.\n• Yarının ilk raundunda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["usp_silencer_use"] = "• İsabetli, sessiz ve (bir miktar) ölümcül.\n• Yarının ilk raundunda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["elite_use"] = "• Hızlıca ateşlenebilen, tek fiyatına çift tabanca.\n• Yarının ilk raundunda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["p250_use"] = "• Ateş gücünü mütevazı artıran popüler bir tabanca.\n• Az para harcanacak rauntlarda alınabilir.\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["fiveseven_use"] = "• Güçlü, hızlı, isabetli ancak biraz pahalı.\n• Az para harcanacak rauntlarda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["cz75a_use"] = "• Düşman silahlarını çalmada kullanılabilecek ani ateş gücüne sahiptir.\n• Az para harcanacak rauntlarda alınabilir.\n• Zorluk: <color=191,64,64>★★★★</color>\n\n",
    ["tec9_use"] = "• Yüksek hareket kabiliyetine sahiptir; uzaktan ve yakından etkilidir.\n• Az para harcanacak rauntlarda alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["revolver_use"] = "• Kısa bir gecikmeden sonra çok fazla hasar verir.\n• Az para harcanacak rauntlarda alınabilir.\n• Zorluk: <color=191,64,64>★★★★</color>\n\n",
    ["deagle_use"] = "• Kafadan vuruşlar her mesafede ölümcüldür.\n• Az para harcanacak rauntlarda alınabilir.\n• Zorluk: <color=191,64,64>★★★★</color>\n\n",
    ["taser_use"] = "• Kısa mesafede tek atışla öldürür, tek kullanımlıktır.\n• Risk ve ödül oranı yüksektir.\n• Zorluk: <color=191,64,64>★★★★</color>\n\n",
    ["bizon_use"] = "• Mermi yağdırarak zırhsız düşmanları biçebilirsin.\n• Yarının ilk üç raundunda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["mac10_use"] = "• Bombalama alanlarına koşarak ve ateş ederek girmede kullanılır.\n• Yarının ilk üç raundunda alınabilir.\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["mp9_use"] = "• Düşman taarruzunu ani yüksek hasarla engellemek için kullanılabilir.\n• Yarının ilk üç raundunda alınabilir.\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["mp7_use"] = "• Orta mesafeden hasar vermek için kontrolü kolaydır.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["mp5sd_use"] = "• Orta mesafeden hasar vermek için kullanışlı ve sessizdir.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["ump45_use"] = "• Orta mesafe çatışmalarında zırh delmesi iyidir.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["p90_use"] = "• Sadece tüfeklerin alt edebildiği sonsuz mermi yağmuru sunar.\n• Tam satın alım rauntlarında alınabilir.\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["galilar_use"] = "• Ucuz ama zırhlı düşmanlara karşı etkilidir.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["famas_use"] = "• Ucuz ama zırhlı düşmanlara karşı etkilidir.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["ak47_use"] = "• Klasik, isabetli ve ölümcül.\n• Tam satın alım rauntlarında alınabilir.\n• Zorluk: <color=191,64,64>★★★★</color>\n\n",
    ["m4a1_use"] = "• İsabet oranı iyidir ve mermisi boldur.\n• Tam satın alım rauntlarında alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["m4a1_silencer_use"] = "• İsabetli ve sessizdir, izli mermi içermez.\n• Tam satın alım rauntlarında alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["aug_use"] = "• Üstün isabetlilik için opsiyonel dürbünü vardır.\n• Tam satın alım rauntlarında alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["sg556_use"] = "• Dürbünle daha ölümcül hâle gelen ölümcül silah.\n• Tam satın alım rauntlarında alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["awp_use"] = "• Kendinden emin keskin nişancıda ölüm saçar.\n• Tam satın alım rauntlarında alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["g3sg1_use"] = "• Riski ve ödülü yüksek otomatik keskin nişancı tüfeği.\n• Özel durumlarda alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["scar20_use"] = "• Pozisyon savunmada kullanılabilecek güçlü (riskli) bir araç.\n• Özel durumlarda alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["ssg08_use"] = "• Uzun mesafeden hasar verebilen hafif ve güçlü bir silah.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,64,64>★★★★</color>\n\n",
    ["mag7_use"] = "• Düşmanı gafil avla, şarjörü değiştir ve tekrarla!\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["nova_use"] = "• Yakın mesafe çatışmaları için kullanışlı bir pompalı.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["sawedoff_use"] = "• Yakın mesafeler için yüksek güçlü pompalı.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,191,64>★★</color>\n\n",
    ["xm1014_use"] = "• Tam otomatik ve mermi kusan bir canavar.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["m249_use"] = "• En azından şarjör değiştirmeyeceksin...\n• Özel durumlarda alınabilir.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["negev_use"] = "• Düşman ilerlemesini durdurabilecek yüksek isabetli baskılama ateşi sağlar.\n• Bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=191,64,64>★★★★</color>\n\n",
    ["hegrenade_use"] = "• Hasar ver veya sis bombalarını temizle.\n• Gerekli olduğunda kullan.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["flashbang_use"] = "• Yakındaki oyuncuları kör/sağır eder.\n• Saldırmadan önce at.\n• Zorluk: <color=191,64,64>★★★★</color>\n\n",
    ["smokegrenade_use"] = "• Büyük bir sis bulutu oluşturur.\n• Düşman görüşünü engellemek için at.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["decoy_use"] = "• Silah ateşi sesini taklit eder.\n• Düşmanın kafasını karıştırmak için önceden at.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["molotov_use"] = "• Saklanma yerlerini ateşle kaplar.\n• Bombalama alanına girmeden önce at.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["incgrenade_use"] = "• Düşman saldırılarını ateşle keser.\n• Tehlike anında at.\n• Zorluk: <color=191,146,64>★★★</color>\n\n",
    ["assaultsuit_use"] = "• En ölümcülleri hariç, mermilere karşı seni korur.\n• Tam alış yaptığın ve bir şey almaya mecbur olduğun rauntlarda alınabilir.\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["kevlar_use"] = "• Kafan dışında her yerini korur.\n• Yarının ilk raundunda alınabilir.\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["defuser_use"] = "• Bomba imha süreni yarıya düşürür.\n• İmha teçhizatı raunt kazandırır!\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["cutters_use"] = "• Bununla, rehineleri sırtına çok daha hızlı alırsın.\n• Fazla paran varsa alınabilir\n• Zorluk: <color=64,191,64>★</color>\n\n",
    ["cz75a"] = "CZ75'in tam otomatik bir türü olan CZ75-Otomatik, rakibinin silahını alarak durumu kendi lehine çevirmek için kısa vadeli ideal bir seçenektir. Fakat çok az bir cephaneye sahip olduğu için, güçlü bir tetik disiplini gerektirir.",
    ["m4a4"] = "Muadili AK-47'den daha isabetli fakat daha az zarar veren bir silah olan olan M4A4, AT'ler için tam otomatik taarruz tüfeği seçeneğidir.",
    ["sg553"] = "Sadece teröristlere özel bir silah olan SG 553, etkili uzak mesafe çatışmaları için AK-47'nin dürbünlü bir alternatifidir.",
    ["decoy_grenade"] = "Yanıltıcı bomba, fırlatıldığında taşıdığınız en güçlü silahın sesini taklit ederek, ilave destek kuvvetlerinin bir yanılsamasını oluşturur.",
    ["incindiary_grenade"] = "Yanıcı bomba, fırlatıldığında patlama çapında olan herkesi yakabilme özelliği olan yüksek sıcaklıktaki bir kimyasal tepkime başlatır.",
    ["survival_taser"] = "Oldukça kısa menzile sahip ancak tek atışta öldürebilen bir silah. Silah kutularını açmak için de kullanılabilir.",
    ["survival_healthshot"] = "Sağlığının bir kısmını yeniler ve kısa süreli bir hız artırımı sağlar.",
    ["survival_vesthelm"] = "Hasara karşı direnç sağlar.",
    ["survival_shield"] = "Parçalanmadan önce hatırı sayılır miktarda hasarı engelleyebilecek bir polis kalkanı.",
    ["survival_parachute"] = "Düşerken hasar almamak için açılabilir.",
    ["survival_exojump"] = "Zıplama yüksekliğini hatırı sayılır bir ölçüde artırır.",
    ["survival_c4"] = "Büyük bir patlamaya neden olmak için haritada istediğin yere kur. Kasaları açmak için kullanılabilir.",
    ["survival_dronepilot"] = "İHA'ların kontrolünü ele geçirebilmek özelliği sağlar. Ele geçirilecek İHA'yı seçmek için tableti kullan.",
    ["survival_exploremoney"] = "Keşfedilen her bölge için fazladan para kazandırır.",
    ["survival_wavemoney"] = "Sağ kalınan her Tehlikeli Bölge genişleme dalgası için fazladan para kazandırır.",
}
